/-
Copyright (c) 2026 Paul Lezeau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Lezeau
-/
module

public import Mathlib.Algebra.Homology.HomologicalComplexAbelian
public import Mathlib.Algebra.Category.Grp.Abelian
public import Mathlib.AlgebraicTopology.SingularHomology.Basic
public import Mathlib.AlgebraicTopology.SimplicialSet.SubcomplexColimits
public import Mathlib.CategoryTheory.Abelian.CommSq
public import Mathlib.CategoryTheory.Limits.Preserves.SigmaConst
public import Mathlib.Topology.Category.TopCat.Opens

/-!
# Singular chains generated by a binary open cover

For an open subset `U` of `X`, this file defines the subcomplex of the singular simplicial set of
`X` generated by simplices factoring through `U`. The meet and join of the two subcomplexes from
`U` and `V` form a pushout square. Integral simplicial chains preserve this pushout, giving a
short exact sequence of chain complexes.

This is the algebraic part of singular Mayer--Vietoris that is already supported by Mathlib. The
remaining excision step is to prove that, when `U ⊔ V = ⊤`, the inclusion from the join of
these subcomplexes into the full singular complex is a quasi-isomorphism.
-/

@[expose] public section

noncomputable section

open AlgebraicTopology CategoryTheory Limits Simplicial TopologicalSpace

namespace SphereSixComplex.BinaryOpenCover

/-! ## Singular subcomplexes associated to open subsets -/

/-- Integral chains of a simplicial set. -/
public noncomputable abbrev integralSimplicialChains :
    SSet ⥤ ChainComplex AddCommGrpCat ℕ :=
  (SSet.chainComplexFunctor AddCommGrpCat).obj (AddCommGrpCat.of ℤ)

/-- The subcomplex of `Simp(X)` consisting of simplices which factor through `U`. -/
public noncomputable def singularOpenSubcomplex {X : TopCat} (U : Opens X) :
    (TopCat.toSSet.obj X).Subcomplex :=
  SSet.Subcomplex.range (TopCat.toSSet.map (Opens.inclusion' U))

/-- The singular set of an open subset maps onto its image subcomplex in `Simp(X)`. -/
public noncomputable def singularOpenCorestriction {X : TopCat} (U : Opens X) :
    TopCat.toSSet.obj ((Opens.toTopCat X).obj U) ⟶ singularOpenSubcomplex U :=
  SSet.Subcomplex.toRange (TopCat.toSSet.map (Opens.inclusion' U))

@[reassoc (attr := simp)]
public theorem singularOpenCorestriction_comp_inclusion {X : TopCat} (U : Opens X) :
    singularOpenCorestriction U ≫ (singularOpenSubcomplex U).ι =
      TopCat.toSSet.map (Opens.inclusion' U) :=
  SSet.Subcomplex.toRange_ι _

/-- Inclusion of open subsets induces inclusion of their singular image subcomplexes. -/
public theorem singularOpenSubcomplex_mono {X : TopCat} {U V : Opens X} (h : U ≤ V) :
    singularOpenSubcomplex U ≤ singularOpenSubcomplex V := by
  let i := (Opens.toTopCat X).map (homOfLE h)
  have hi : i ≫ Opens.inclusion' V = Opens.inclusion' U := by
    ext x
    rfl
  rw [singularOpenSubcomplex, singularOpenSubcomplex, ← hi, Functor.map_comp]
  exact Subfunctor.range_comp_le _ _

/-- The subcomplex from `U ⊓ V` maps into the meet of the two image subcomplexes. -/
public theorem singularOpenSubcomplex_inf_le {X : TopCat} (U V : Opens X) :
    singularOpenSubcomplex (U ⊓ V) ≤
      singularOpenSubcomplex U ⊓ singularOpenSubcomplex V :=
  le_inf
    (singularOpenSubcomplex_mono (inf_le_left : U ⊓ V ≤ U))
    (singularOpenSubcomplex_mono (inf_le_right : U ⊓ V ≤ V))

/-- A singular simplex lies in both open-image subcomplexes exactly when it factors through the
open intersection. -/
public theorem singularOpenSubcomplex_inf {X : TopCat} (U V : Opens X) :
    singularOpenSubcomplex (U ⊓ V) =
      singularOpenSubcomplex U ⊓ singularOpenSubcomplex V := by
  apply le_antisymm (singularOpenSubcomplex_inf_le U V)
  intro n x hx
  change
    (∃ a, (TopCat.toSSet.map (Opens.inclusion' U)).app n a = x) ∧
    (∃ b, (TopCat.toSSet.map (Opens.inclusion' V)).app n b = x) at hx
  rcases hx with ⟨⟨a, ha⟩, ⟨b, hb⟩⟩
  change ∃ c, (TopCat.toSSet.map (Opens.inclusion' (U ⊓ V))).app n c = x
  let aMap := ((Opens.toTopCat X).obj U).toSSetObjEquiv n a
  let bMap := ((Opens.toTopCat X).obj V).toSSetObjEquiv n b
  let xMap := X.toSSetObjEquiv n x
  have ha_apply (z) : xMap z = (aMap z).1 := by
    have h := congrArg (fun s ↦ X.toSSetObjEquiv n s z) ha
    exact h.symm
  have hb_apply (z) : xMap z = (bMap z).1 := by
    have h := congrArg (fun s ↦ X.toSSetObjEquiv n s z) hb
    exact h.symm
  let cMap : C(stdSimplex ℝ (Fin (n.unop.len + 1)), (Opens.toTopCat X).obj (U ⊓ V)) :=
    ⟨fun z ↦ ⟨xMap z, ⟨ha_apply z ▸ (aMap z).2, hb_apply z ▸ (bMap z).2⟩⟩,
      continuous_induced_rng.2 xMap.continuous⟩
  refine ⟨((Opens.toTopCat X).obj (U ⊓ V)).toSSetObjEquiv n |>.symm cMap, ?_⟩
  apply (X.toSSetObjEquiv n).injective
  ext z
  rfl

/-! ## The meet--join short exact sequence -/

/-- The intersection of the two singular image subcomplexes. -/
public noncomputable abbrev coverIntersection {X : TopCat} (U V : Opens X) :=
  singularOpenSubcomplex U ⊓ singularOpenSubcomplex V

/-- The canonical comparison from simplices in `U ⊓ V` to the lattice intersection. -/
public noncomputable def openIntersectionComparison {X : TopCat} (U V : Opens X) :
    (singularOpenSubcomplex (U ⊓ V)).toSSet ⟶ (coverIntersection U V).toSSet :=
  SSet.Subcomplex.homOfLE (singularOpenSubcomplex_inf_le U V)

public noncomputable instance openIntersectionComparison_isIso {X : TopCat}
    (U V : Opens X) : IsIso (openIntersectionComparison U V) := by
  let h := singularOpenSubcomplex_inf U V
  change IsIso ((SSet.Subcomplex.eqToIso h).hom)
  infer_instance

/-- The subcomplex generated by singular simplices lying in either member of the cover. -/
public noncomputable abbrev coverUnion {X : TopCat} (U V : Opens X) :=
  singularOpenSubcomplex U ⊔ singularOpenSubcomplex V

/-- Meet and join give a bicartesian square in the lattice of singular subcomplexes. -/
public def coverSubcomplexBicartSq {X : TopCat} (U V : Opens X) :
    SSet.Subcomplex.BicartSq (coverIntersection U V)
      (singularOpenSubcomplex U) (singularOpenSubcomplex V) (coverUnion U V) where
  sup_eq := rfl
  inf_eq := rfl

/-- The meet--join square is a pushout square of simplicial sets. -/
public noncomputable def coverSubcomplexIsPushout {X : TopCat} (U V : Opens X) :
    IsPushout
      (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₁₂)
      (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₁₃)
      (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₂₄)
      (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₃₄) :=
  (coverSubcomplexBicartSq U V).isPushout

/-- Integral simplicial chains preserve pushout diagrams. -/
public noncomputable instance integralSimplicialChains_preservesPushouts :
    PreservesColimitsOfShape WalkingSpan integralSimplicialChains := by
  apply HomologicalComplex.preservesColimitsOfShape_of_eval
  intro n
  change PreservesColimitsOfShape WalkingSpan
    ((evaluation _ _).obj (Opposite.op (SimplexCategory.mk n)) ⋙
      sigmaConst.obj (AddCommGrpCat.of ℤ))
  infer_instance

/-- Integral simplicial chains preserve monomorphisms of simplicial sets. -/
public instance integralSimplicialChains_preservesMonomorphisms :
    integralSimplicialChains.PreservesMonomorphisms where
  preserves f _ := by
    dsimp [integralSimplicialChains, SSet.chainComplexFunctor]
    apply +allowSynthFailures Functor.map_mono

/-- Applying integral chains to the meet--join square again gives a pushout. -/
public noncomputable def coverChainIsPushout {X : TopCat} (U V : Opens X) :=
  (coverSubcomplexIsPushout U V).map integralSimplicialChains

/-- The alternating intersection-to-pieces map followed by the sum-to-union map. -/
public noncomputable def coverChainShortComplex {X : TopCat} (U V : Opens X) :
    ShortComplex (ChainComplex AddCommGrpCat ℕ) :=
  (coverChainIsPushout U V).shortComplex

/-- Integral chains induced by the comparison from the actual open intersection. -/
public noncomputable def openIntersectionChainComparison {X : TopCat}
    (U V : Opens X) :
    integralSimplicialChains.obj (singularOpenSubcomplex (U ⊓ V)) ⟶
      integralSimplicialChains.obj (coverIntersection U V) :=
  integralSimplicialChains.map (openIntersectionComparison U V)

public noncomputable instance openIntersectionChainComparison_isIso {X : TopCat}
    (U V : Opens X) : IsIso (openIntersectionChainComparison U V) := by
  dsimp [openIntersectionChainComparison]
  infer_instance

public noncomputable instance openIntersectionHomologyComparison_isIso {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    IsIso (HomologicalComplex.homologyMap (openIntersectionChainComparison U V) n) := by
  change IsIso
    ((HomologicalComplex.homologyFunctor AddCommGrpCat _ n).map
      (openIntersectionChainComparison U V))
  infer_instance

/-- The two canonical chain maps compose to zero. -/
public theorem coverChain_comp_eq_zero {X : TopCat} (U V : Opens X) :
    (coverChainShortComplex U V).f ≫ (coverChainShortComplex U V).g = 0 :=
  (coverChainShortComplex U V).zero

/-- The chain-level meet--join sequence is exact. -/
public theorem coverChainShortComplex_exact {X : TopCat} (U V : Opens X) :
    (coverChainShortComplex U V).Exact :=
  (coverChainIsPushout U V).exact_shortComplex

/-- In fact the chain-level meet--join sequence is short exact. -/
public theorem coverChainShortComplex_shortExact {X : TopCat} (U V : Opens X) :
    (coverChainShortComplex U V).ShortExact := by
  letI : Mono (integralSimplicialChains.map
      (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₁₂)) := by
    infer_instance
  letI : Mono (coverChainShortComplex U V).f := by
    change Mono (biprod.lift
      (integralSimplicialChains.map
        (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₁₂))
      (-integralSimplicialChains.map
        (SSet.Subcomplex.homOfLE (coverSubcomplexBicartSq U V).le₁₃)))
    exact mono_of_mono_fac (biprod.lift_fst _ _)
  apply ShortComplex.ShortExact.mk'
  · exact coverChainShortComplex_exact U V
  · infer_instance
  · exact (coverChainIsPushout U V).epi_shortComplex_g

/-- The map from chains generated by the cover to the full integral singular chain complex. -/
public noncomputable def coverChainInclusion {X : TopCat} (U V : Opens X) :
    integralSimplicialChains.obj (coverUnion U V) ⟶
      integralSimplicialChains.obj (TopCat.toSSet.obj X) :=
  integralSimplicialChains.map (coverUnion U V).ι

end SphereSixComplex.BinaryOpenCover
