name = "sphere-six-complex"
version = "0.1.0"
defaultTargets = ["SphereSixComplex", "Challenge", "Solution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"

[[lean_lib]]
name = "SphereSixComplex"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
