/-
Copyright (c) 2026 Paul Lezeau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Lezeau
-/
module

public import SphereSixComplex.Topology.BinaryOpenCoverCorestriction
public import SphereSixComplex.Topology.BinaryOpenCoverExcision
public import Mathlib.Algebra.Homology.HomologySequence
public import Mathlib.Algebra.Homology.ShortComplex.Ab

/-!
# Mayer--Vietoris from binary open-cover chains

The subcomplexes generated by a binary cover form a short exact sequence of integral chain
complexes. Mathlib's homology-sequence API therefore supplies its complete long exact sequence.
This file records that deduction and the formal transport from generated-cover homology to the
ordinary homology of the open pieces and ambient space.

The union isomorphism in `OpenCoverHomologyComparison` is the genuine subdivision/excision
assertion. The intersection and biproduct isomorphisms package corestriction-to-range and
homology-of-biproduct identifications. Naturality is kept explicit rather than hidden in an
assumed Mayer--Vietoris theorem.
-/

@[expose] public section

noncomputable section

open AlgebraicTopology CategoryTheory Limits TopologicalSpace

namespace SphereSixComplex.BinaryOpenCover

/-! ## Exact triples -/

/-- Three objects and two maps, exact at the middle object. -/
public structure HomologyExactTriple (A B C : AddCommGrpCat) where
  left : A ⟶ B
  right : B ⟶ C
  zero : left ≫ right = 0
  isExact : (ShortComplex.mk left right zero).Exact

/-- Transport an exact triple across objectwise isomorphisms and commuting squares. -/
public noncomputable def HomologyExactTriple.transportIso
    {A B C A' B' C' : AddCommGrpCat} (S : HomologyExactTriple A B C)
    (f : A' ⟶ B') (g : B' ⟶ C')
    (eA : A ≅ A') (eB : B ≅ B') (eC : C ≅ C')
    (hf : eA.hom ≫ f = S.left ≫ eB.hom)
    (hg : eB.hom ≫ g = S.right ≫ eC.hom) :
    HomologyExactTriple A' B' C' := by
  have hzero : f ≫ g = 0 := by
    rw [← cancel_epi eA.hom]
    calc
      eA.hom ≫ f ≫ g = (eA.hom ≫ f) ≫ g :=
        (Category.assoc _ _ _).symm
      _ = (S.left ≫ eB.hom) ≫ g := by rw [hf]
      _ = S.left ≫ eB.hom ≫ g := Category.assoc _ _ _
      _ = S.left ≫ S.right ≫ eC.hom := by rw [hg]
      _ = (S.left ≫ S.right) ≫ eC.hom :=
        (Category.assoc _ _ _).symm
      _ = 0 := by rw [S.zero, zero_comp]
      _ = eA.hom ≫ 0 := by rw [comp_zero]
  refine
    { left := f
      right := g
      zero := hzero
      isExact := ?_ }
  exact ShortComplex.exact_of_iso
    (ShortComplex.isoMk eA eB eC hf hg) S.isExact

/-! ## The long exact sequence of the generated chain cover -/

public noncomputable abbrev generatedIntersectionHomology {X : TopCat}
    (U V : Opens X) (n : ℕ) : AddCommGrpCat :=
  (coverChainShortComplex U V).X₁.homology n

public noncomputable abbrev generatedBiprodHomology {X : TopCat}
    (U V : Opens X) (n : ℕ) : AddCommGrpCat :=
  (coverChainShortComplex U V).X₂.homology n

public noncomputable abbrev generatedUnionHomology {X : TopCat}
    (U V : Opens X) (n : ℕ) : AddCommGrpCat :=
  (coverChainShortComplex U V).X₃.homology n

/-- The map on homology induced by the alternating intersection-to-pieces chain map. -/
public noncomputable def generatedToBiprod {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    generatedIntersectionHomology U V n ⟶ generatedBiprodHomology U V n :=
  HomologicalComplex.homologyMap (coverChainShortComplex U V).f n

/-- The map on homology induced by the sum of the two piece inclusions. -/
public noncomputable def generatedFromBiprod {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    generatedBiprodHomology U V n ⟶ generatedUnionHomology U V n :=
  HomologicalComplex.homologyMap (coverChainShortComplex U V).g n

/-- The connecting morphism supplied by the chain-level short exact sequence. -/
public noncomputable def generatedBoundary {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    generatedUnionHomology U V (n + 1) ⟶ generatedIntersectionHomology U V n :=
  (coverChainShortComplex_shortExact U V).δ (n + 1) n rfl

/-- Exactness at the intersection term of the generated-cover sequence. -/
public noncomputable def generatedExactAtIntersection {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    HomologyExactTriple (generatedUnionHomology U V (n + 1))
      (generatedIntersectionHomology U V n) (generatedBiprodHomology U V n) where
  left := generatedBoundary U V n
  right := generatedToBiprod U V n
  zero := (coverChainShortComplex_shortExact U V).δ_comp (n + 1) n rfl
  isExact := (coverChainShortComplex_shortExact U V).homology_exact₁ (n + 1) n rfl

/-- Exactness at the biproduct term of the generated-cover sequence. -/
public noncomputable def generatedExactAtBiprod {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    HomologyExactTriple (generatedIntersectionHomology U V n)
      (generatedBiprodHomology U V n) (generatedUnionHomology U V n) where
  left := generatedToBiprod U V n
  right := generatedFromBiprod U V n
  zero := by
    rw [generatedToBiprod, generatedFromBiprod,
      ← HomologicalComplex.homologyMap_comp, (coverChainShortComplex U V).zero,
      HomologicalComplex.homologyMap_zero]
  isExact := (coverChainShortComplex_shortExact U V).homology_exact₂ n

/-- Exactness at the union term of the generated-cover sequence. -/
public noncomputable def generatedExactAtUnion {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    HomologyExactTriple (generatedBiprodHomology U V (n + 1))
      (generatedUnionHomology U V (n + 1)) (generatedIntersectionHomology U V n) where
  left := generatedFromBiprod U V (n + 1)
  right := generatedBoundary U V n
  zero := (coverChainShortComplex_shortExact U V).comp_δ (n + 1) n rfl
  isExact := (coverChainShortComplex_shortExact U V).homology_exact₃ (n + 1) n rfl

/-! ## Ordinary open-cover terms -/

/-- Integral singular homology as a functor on topological spaces. -/
public noncomputable abbrev integralHomologyFunctor (n : ℕ) :
    TopCat ⥤ AddCommGrpCat :=
  (singularHomologyFunctor AddCommGrpCat n).obj (AddCommGrpCat.of ℤ)

/-- The alternating map from intersection homology to the biproduct of piece homologies. -/
public noncomputable def integralMVToBiprod {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj (U ⊓ V)) ⟶
      (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj U) ⊞
        (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj V) :=
  biprod.lift
    ((integralHomologyFunctor n).map
      ((Opens.toTopCat X).map (Opens.infLELeft U V)))
    (-((integralHomologyFunctor n).map
      ((Opens.toTopCat X).map (Opens.infLERight U V))))

/-- The sum of the two inclusion maps from the pieces to the ambient space. -/
public noncomputable def integralMVFromBiprod {X : TopCat}
    (U V : Opens X) (n : ℕ) :
    (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj U) ⊞
        (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj V) ⟶
      (integralHomologyFunctor n).obj X :=
  biprod.desc
    ((integralHomologyFunctor n).map (Opens.inclusion' U))
    ((integralHomologyFunctor n).map (Opens.inclusion' V))

/-- Exact data in the integral singular Mayer--Vietoris sequence of a binary open cover. -/
public structure IntegralMayerVietorisData {X : TopCat}
    (U V : Opens X) (_hcover : U ⊔ V = ⊤) where
  boundary (n : ℕ) :
    (integralHomologyFunctor (n + 1)).obj X ⟶
      (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj (U ⊓ V))
  exact_at_intersection (n : ℕ) :
    Function.Exact (fun x ↦ boundary n x) (fun x ↦ integralMVToBiprod U V n x)
  exact_at_biprod (n : ℕ) :
    Function.Exact (fun x ↦ integralMVToBiprod U V n x)
      (fun x ↦ integralMVFromBiprod U V n x)
  exact_at_union (n : ℕ) :
    Function.Exact (fun x ↦ integralMVFromBiprod U V (n + 1) x)
      (fun x ↦ boundary n x)

/-- Comparison data between generated-cover homology and the actual open-cover terms. -/
public structure OpenCoverHomologyComparison {X : TopCat} (U V : Opens X) where
  intersectionIso (n : ℕ) :
    generatedIntersectionHomology U V n ≅
      (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj (U ⊓ V))
  biprodIso (n : ℕ) :
    generatedBiprodHomology U V n ≅
      (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj U) ⊞
        (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj V)
  unionIso (n : ℕ) :
    generatedUnionHomology U V n ≅ (integralHomologyFunctor n).obj X
  toBiprod_comm (n : ℕ) :
    (intersectionIso n).hom ≫ integralMVToBiprod U V n =
      generatedToBiprod U V n ≫ (biprodIso n).hom
  fromBiprod_comm (n : ℕ) :
    (biprodIso n).hom ≫ integralMVFromBiprod U V n =
      generatedFromBiprod U V n ≫ (unionIso n).hom

/-- The actual connecting map obtained by conjugating the generated connecting map. -/
public noncomputable def OpenCoverHomologyComparison.boundary {X : TopCat}
    {U V : Opens X} (h : OpenCoverHomologyComparison U V) (n : ℕ) :
    (integralHomologyFunctor (n + 1)).obj X ⟶
      (integralHomologyFunctor n).obj ((Opens.toTopCat X).obj (U ⊓ V)) :=
  (h.unionIso (n + 1)).inv ≫ generatedBoundary U V n ≫
    (h.intersectionIso n).hom

@[reassoc]
public theorem OpenCoverHomologyComparison.unionIso_hom_comp_boundary {X : TopCat}
    {U V : Opens X} (h : OpenCoverHomologyComparison U V) (n : ℕ) :
    (h.unionIso (n + 1)).hom ≫ h.boundary n =
      generatedBoundary U V n ≫ (h.intersectionIso n).hom := by
  simp [OpenCoverHomologyComparison.boundary]

/-- The three singular Mayer--Vietoris exactness assertions follow from a generated-chain
comparison. -/
public noncomputable def OpenCoverHomologyComparison.toIntegralMayerVietorisData
    {X : TopCat} {U V : Opens X} (h : OpenCoverHomologyComparison U V)
    (hcover : U ⊔ V = ⊤) : IntegralMayerVietorisData U V hcover where
  boundary := h.boundary
  exact_at_intersection n := by
    let T := HomologyExactTriple.transportIso (generatedExactAtIntersection U V n)
      (h.boundary n) (integralMVToBiprod U V n) (h.unionIso (n + 1))
      (h.intersectionIso n) (h.biprodIso n) (h.unionIso_hom_comp_boundary n)
      (h.toBiprod_comm n)
    exact (ShortComplex.ab_exact_iff_function_exact _).1 T.isExact
  exact_at_biprod n := by
    let T := HomologyExactTriple.transportIso (generatedExactAtBiprod U V n)
      (integralMVToBiprod U V n) (integralMVFromBiprod U V n)
      (h.intersectionIso n) (h.biprodIso n) (h.unionIso n)
      (h.toBiprod_comm n) (h.fromBiprod_comm n)
    exact (ShortComplex.ab_exact_iff_function_exact _).1 T.isExact
  exact_at_union n := by
    let T := HomologyExactTriple.transportIso (generatedExactAtUnion U V n)
      (integralMVFromBiprod U V (n + 1)) (h.boundary n) (h.biprodIso (n + 1))
      (h.unionIso (n + 1)) (h.intersectionIso n) (h.fromBiprod_comm (n + 1))
      (h.unionIso_hom_comp_boundary n)
    exact (ShortComplex.ab_exact_iff_function_exact _).1 T.isExact

/-! ## Precise excision boundaries -/

/-- Subdivision makes the generated-cover inclusion a homology isomorphism in every degree. -/
public def IntegralGeneratedCoverExcisionStatement : Prop :=
  ∀ (X : TopCat) (U V : Opens X), U ⊔ V = ⊤ → ∀ n : ℕ,
    IsIso (HomologicalComplex.homologyMap (coverChainInclusion U V) n)

/-- A subdivision certificate supplies generated-cover excision. -/
public theorem integralGeneratedCoverExcisionStatement_of_subdivision
    (h : BinaryOpenCoverSubdivisionStatement) :
    IntegralGeneratedCoverExcisionStatement := by
  intro X U V hcover n
  obtain ⟨D⟩ := h X U V hcover
  exact D.isIso_homologyMap n

/-- The range-intersection comparison is an isomorphism in every degree. -/
public def IntegralOpenIntersectionComparisonStatement : Prop :=
  ∀ (X : TopCat) (U V : Opens X) (n : ℕ),
    IsIso (HomologicalComplex.homologyMap (openIntersectionChainComparison U V) n)

/-- The open-intersection comparison is independent of subdivision. -/
public theorem integralOpenIntersectionComparisonStatement :
    IntegralOpenIntersectionComparisonStatement := by
  intro X U V n
  infer_instance

/-- The complete comparison needed to recover ordinary singular Mayer--Vietoris. -/
public def IntegralOpenCoverComparisonStatement : Prop :=
  ∀ (X : TopCat) (U V : Opens X), U ⊔ V = ⊤ →
    Nonempty (OpenCoverHomologyComparison U V)

/-- A comparison theorem supplies ordinary singular Mayer--Vietoris data. -/
public theorem integralMayerVietorisData_of_comparison
    (h : IntegralOpenCoverComparisonStatement) {X : TopCat}
    (U V : Opens X) (hcover : U ⊔ V = ⊤) :
    Nonempty (IntegralMayerVietorisData U V hcover) := by
  obtain ⟨comparison⟩ := h X U V hcover
  exact ⟨comparison.toIntegralMayerVietorisData hcover⟩

end SphereSixComplex.BinaryOpenCover
