/-
Copyright (c) 2026 Paul Lezeau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Lezeau
-/
module

public import SphereSixComplex.Topology.BinaryOpenCoverChains
public import Mathlib.Algebra.Category.Grp.EpiMono
public import Mathlib.Algebra.Category.Grp.Zero
public import Mathlib.Algebra.Homology.HomologySequenceLemmas

/-!
# The subdivision-to-excision bridge for singular chains

This file isolates the exact chain-level content of the classical subdivision proof of excision.
For a binary open cover, a chain is *small* when it comes from the subcomplex generated by
singular simplices contained in one member of the cover. An abstract chain subdivision consists
of a chain endomorphism together with its prism homotopy to the identity.

The main result is `CoverSubdivisionData.coverChainInclusion_quasiIso`. It says that the
generated-cover inclusion is a quasi-isomorphism once subdivision descends to its cokernel and
every ambient chain becomes small after a chain-dependent number of iterations. Allowing the
number of iterations to depend on the chain is essential: a binary open cover does not generally
have one subdivision exponent which works for all singular simplices at once.

The proof is fully algebraic. Local nilpotence of subdivision on quotient chains implies that the
quotient complex is acyclic, because every subdivision iterate induces the identity on homology.
The long exact sequence of the cokernel then makes the cover inclusion a quasi-isomorphism.
-/

@[expose] public section

noncomputable section

open AlgebraicTopology CategoryTheory Limits TopologicalSpace

namespace SphereSixComplex.BinaryOpenCover

/-! ## Small chains for a binary cover -/

/-- The full integral singular chain complex of a topological space. -/
public noncomputable abbrev singularChains (X : TopCat) :
    ChainComplex AddCommGrpCat ℕ :=
  integralSimplicialChains.obj (TopCat.toSSet.obj X)

/-- The integral chains generated by simplices lying in either member of a binary cover. -/
public noncomputable abbrev generatedCoverChains {X : TopCat} (U V : Opens X) :
    ChainComplex AddCommGrpCat ℕ :=
  integralSimplicialChains.obj (coverUnion U V)

/-- A singular chain is small for `U, V` when it comes from the generated cover complex. -/
public def IsCoverSmallChain {X : TopCat} (U V : Opens X) (n : ℕ)
    (c : (singularChains X).X n) : Prop :=
  ∃ a : (generatedCoverChains U V).X n, (coverChainInclusion U V).f n a = c

public theorem isCoverSmallChain_zero {X : TopCat} (U V : Opens X) (n : ℕ) :
    IsCoverSmallChain U V n 0 :=
  ⟨0, by simp⟩

public theorem IsCoverSmallChain.add {X : TopCat} {U V : Opens X} {n : ℕ}
    {c c' : (singularChains X).X n} (hc : IsCoverSmallChain U V n c)
    (hc' : IsCoverSmallChain U V n c') : IsCoverSmallChain U V n (c + c') := by
  obtain ⟨a, rfl⟩ := hc
  obtain ⟨a', rfl⟩ := hc'
  exact ⟨a + a', by simp⟩

public theorem IsCoverSmallChain.neg {X : TopCat} {U V : Opens X} {n : ℕ}
    {c : (singularChains X).X n} (hc : IsCoverSmallChain U V n c) :
    IsCoverSmallChain U V n (-c) := by
  obtain ⟨a, rfl⟩ := hc
  exact ⟨-a, by simp⟩

/-! ## Iterating a chain endomorphism -/

/-- The `k`-fold composite of a chain endomorphism, with the zeroth iterate equal to identity. -/
public def chainMapIterate {K : ChainComplex AddCommGrpCat ℕ} (f : K ⟶ K) :
    ℕ → (K ⟶ K)
  | 0 => 𝟙 K
  | k + 1 => f ≫ chainMapIterate f k

@[simp]
public theorem chainMapIterate_zero {K : ChainComplex AddCommGrpCat ℕ} (f : K ⟶ K) :
    chainMapIterate f 0 = 𝟙 K :=
  rfl

@[simp]
public theorem chainMapIterate_succ {K : ChainComplex AddCommGrpCat ℕ} (f : K ⟶ K)
    (k : ℕ) : chainMapIterate f (k + 1) = f ≫ chainMapIterate f k :=
  rfl

/-- Iterates commute with a map whenever the original endomorphisms do. -/
public theorem chainMapIterate_comp {K L : ChainComplex AddCommGrpCat ℕ}
    (f : K ⟶ K) (g : L ⟶ L) (p : K ⟶ L) (h : f ≫ p = p ≫ g) :
    ∀ k : ℕ, chainMapIterate f k ≫ p = p ≫ chainMapIterate g k
  | 0 => by simp
  | k + 1 => by
      simp only [chainMapIterate_succ, Category.assoc]
      rw [chainMapIterate_comp f g p h k, ← Category.assoc, h, Category.assoc]

/-! ## Abstract subdivision and local nilpotence -/

/-- A chain subdivision operator together with its prism homotopy to the identity. -/
public structure ChainSubdivision (K : ChainComplex AddCommGrpCat ℕ) where
  map : K ⟶ K
  homotopyToIdentity : Homotopy map (𝟙 K)

namespace ChainSubdivision

/-- Every iterate of a subdivision operator is chain homotopic to the identity. -/
public def iterateHomotopy {K : ChainComplex AddCommGrpCat ℕ} (S : ChainSubdivision K) :
    ∀ k : ℕ, Homotopy (chainMapIterate S.map k) (𝟙 K)
  | 0 => Homotopy.refl _
  | k + 1 =>
      (S.homotopyToIdentity.compRightId (chainMapIterate S.map k)).trans
        (iterateHomotopy S k)

/-- Every subdivision iterate acts as the identity on homology. -/
public theorem homologyMap_iterate {K : ChainComplex AddCommGrpCat ℕ}
    (S : ChainSubdivision K) (n k : ℕ) :
    HomologicalComplex.homologyMap (chainMapIterate S.map k) n = 𝟙 (K.homology n) := by
  simpa using (S.iterateHomotopy k).homologyMap_eq n

/-- Pointwise local nilpotence of subdivision on chains.

The exponent may depend on the degree and on the individual chain. -/
public def LocallyNilpotentOnChains {K : ChainComplex AddCommGrpCat ℕ}
    (S : ChainSubdivision K) : Prop :=
  ∀ n : ℕ, ∀ c : K.X n, ∃ k : ℕ, (chainMapIterate S.map k).f n c = 0

/-- A subdivision homotopic to identity and locally nilpotent on chains makes the complex
acyclic. -/
public theorem acyclic_of_locallyNilpotentOnChains {K : ChainComplex AddCommGrpCat ℕ}
    (S : ChainSubdivision K) (h : LocallyNilpotentOnChains S) : K.Acyclic := by
  intro n
  rw [HomologicalComplex.exactAt_iff_isZero_homology,
    AddCommGrpCat.isZero_iff_subsingleton]
  constructor
  intro x y
  have vanishes (x : K.homology n) : x = 0 := by
    have hsurjective : Function.Surjective (K.homologyπ n) :=
      (AddCommGrpCat.epi_iff_surjective _).mp inferInstance
    obtain ⟨z, rfl⟩ := hsurjective x
    obtain ⟨k, hk⟩ := h n ((K.iCycles n) z)
    have hz : HomologicalComplex.cyclesMap (chainMapIterate S.map k) n z = 0 := by
      apply (AddCommGrpCat.mono_iff_injective _).mp
        (inferInstance : Mono (K.iCycles n))
      calc
        (K.iCycles n) (HomologicalComplex.cyclesMap (chainMapIterate S.map k) n z) =
            (chainMapIterate S.map k).f n ((K.iCycles n) z) := by
          simpa only [ConcreteCategory.comp_apply] using congrArg (fun q ↦ q z)
            (HomologicalComplex.cyclesMap_i (chainMapIterate S.map k) n)
        _ = 0 := hk
        _ = (K.iCycles n) 0 := by simp
    have hx : HomologicalComplex.homologyMap (chainMapIterate S.map k) n
        ((K.homologyπ n) z) = 0 := by
      calc
        HomologicalComplex.homologyMap (chainMapIterate S.map k) n
              ((K.homologyπ n) z) =
            (K.homologyπ n)
              (HomologicalComplex.cyclesMap (chainMapIterate S.map k) n z) := by
          simpa only [ConcreteCategory.comp_apply] using congrArg (fun q ↦ q z)
            (HomologicalComplex.homologyπ_naturality
              (chainMapIterate S.map k) n)
        _ = 0 := by rw [hz]; simp
    rw [S.homologyMap_iterate n k] at hx
    simpa using hx
  exact (vanishes x).trans (vanishes y).symm

end ChainSubdivision

/-! ## The quotient by cover-small chains -/

public noncomputable instance coverChainInclusion_mono {X : TopCat} (U V : Opens X) :
    Mono (coverChainInclusion U V) := by
  dsimp [coverChainInclusion]
  infer_instance

/-- The quotient of all singular chains by the chains generated by the binary cover. -/
public noncomputable def coverChainQuotient {X : TopCat} (U V : Opens X) :
    ChainComplex AddCommGrpCat ℕ :=
  cokernel (coverChainInclusion U V)

/-- The quotient projection from all singular chains. -/
public noncomputable def coverChainQuotientProjection {X : TopCat} (U V : Opens X) :
    singularChains X ⟶ coverChainQuotient U V :=
  cokernel.π (coverChainInclusion U V)

public noncomputable instance coverChainQuotientProjection_epi {X : TopCat}
    (U V : Opens X) : Epi (coverChainQuotientProjection U V) := by
  dsimp [coverChainQuotientProjection]
  constructor
  intro Z g h w
  exact coequalizer.hom_ext w

@[reassoc (attr := simp)]
public theorem coverChainInclusion_comp_quotientProjection {X : TopCat}
    (U V : Opens X) :
    coverChainInclusion U V ≫ coverChainQuotientProjection U V = 0 :=
  cokernel.condition (coverChainInclusion U V)

/-- A cover-small chain vanishes after passing to the quotient complex. -/
public theorem quotientProjection_apply_eq_zero_of_isCoverSmallChain {X : TopCat}
    {U V : Opens X} {n : ℕ} {c : (singularChains X).X n}
    (hc : IsCoverSmallChain U V n c) :
    (coverChainQuotientProjection U V).f n c = 0 := by
  obtain ⟨a, rfl⟩ := hc
  have h := congrArg (fun q ↦ q.f n a)
    (coverChainInclusion_comp_quotientProjection U V)
  simpa only [HomologicalComplex.comp_f, HomologicalComplex.zero_f,
    ConcreteCategory.comp_apply, AddCommGrpCat.hom_zero,
    AddMonoidHom.zero_apply, map_zero] using h

/-- The canonical short exact sequence consisting of the cover inclusion and its cokernel. -/
public noncomputable def coverChainCokernelSequence {X : TopCat} (U V : Opens X) :
    ShortComplex (ChainComplex AddCommGrpCat ℕ) :=
  ShortComplex.mk (coverChainInclusion U V) (coverChainQuotientProjection U V)
    (coverChainInclusion_comp_quotientProjection U V)

/-- The cover inclusion followed by its quotient projection is a short exact sequence. -/
public theorem coverChainCokernelSequence_shortExact {X : TopCat} (U V : Opens X) :
    (coverChainCokernelSequence U V).ShortExact := by
  apply ShortComplex.ShortExact.mk'
  · exact ShortComplex.exact_cokernel (coverChainInclusion U V)
  · change Mono (coverChainInclusion U V)
    infer_instance
  · change Epi (coverChainQuotientProjection U V)
    infer_instance

/-! ## A precise subdivision certificate for binary-cover excision -/

/-- Data supplied by the classical barycentric subdivision argument for a binary open cover.

`ambient` is the barycentric subdivision operator and prism homotopy on singular chains.
`quotient` is the induced operator and descended homotopy on the quotient by cover-small chains.
The commutative square records descent. `eventuallySmall` is the chainwise Lebesgue-number
argument; importantly, its exponent is allowed to depend on the chain. -/
public structure CoverSubdivisionData {X : TopCat} (U V : Opens X) where
  isCover : U ⊔ V = ⊤
  ambient : ChainSubdivision (singularChains X)
  quotient : ChainSubdivision (coverChainQuotient U V)
  projection_comm :
    ambient.map ≫ coverChainQuotientProjection U V =
      coverChainQuotientProjection U V ≫ quotient.map
  eventuallySmall :
    ∀ n : ℕ, ∀ c : (singularChains X).X n,
      ∃ k : ℕ, IsCoverSmallChain U V n ((chainMapIterate ambient.map k).f n c)

namespace CoverSubdivisionData

/-- The quotient projection commutes with every subdivision iterate. -/
public theorem iterate_projection {X : TopCat} {U V : Opens X}
    (D : CoverSubdivisionData U V) (k : ℕ) :
    chainMapIterate D.ambient.map k ≫ coverChainQuotientProjection U V =
      coverChainQuotientProjection U V ≫ chainMapIterate D.quotient.map k :=
  chainMapIterate_comp D.ambient.map D.quotient.map
    (coverChainQuotientProjection U V) D.projection_comm k

/-- Eventual smallness upstairs becomes pointwise local nilpotence on quotient chains. -/
public theorem quotient_locallyNilpotentOnChains {X : TopCat} {U V : Opens X}
    (D : CoverSubdivisionData U V) : D.quotient.LocallyNilpotentOnChains := by
  intro n x
  have hsurjective : Function.Surjective ((coverChainQuotientProjection U V).f n) :=
    (AddCommGrpCat.epi_iff_surjective _).mp inferInstance
  obtain ⟨c, rfl⟩ := hsurjective x
  obtain ⟨k, hk⟩ := D.eventuallySmall n c
  refine ⟨k, ?_⟩
  calc
    (chainMapIterate D.quotient.map k).f n
          ((coverChainQuotientProjection U V).f n c) =
        (coverChainQuotientProjection U V).f n
          ((chainMapIterate D.ambient.map k).f n c) := by
      simpa only [HomologicalComplex.comp_f, ConcreteCategory.comp_apply] using
        congrArg (fun q ↦ q.f n c) (D.iterate_projection k).symm
    _ = 0 := quotientProjection_apply_eq_zero_of_isCoverSmallChain hk

/-- The quotient by cover-small chains is acyclic. -/
public theorem quotient_acyclic {X : TopCat} {U V : Opens X}
    (D : CoverSubdivisionData U V) : (coverChainQuotient U V).Acyclic :=
  D.quotient.acyclic_of_locallyNilpotentOnChains D.quotient_locallyNilpotentOnChains

end CoverSubdivisionData

/-! ## Quasi-isomorphism and homology-isomorphism endpoints -/

/-- Acyclicity of the quotient makes the generated-cover inclusion a quasi-isomorphism. -/
public theorem coverChainInclusion_quasiIso_of_quotient_acyclic {X : TopCat}
    {U V : Opens X} (h : (coverChainQuotient U V).Acyclic) :
    QuasiIso (coverChainInclusion U V) := by
  have hS := coverChainCokernelSequence_shortExact U V
  rw [quasiIso_iff]
  intro n
  rw [quasiIsoAt_iff_isIso_homologyMap]
  letI : Mono (HomologicalComplex.homologyMap (coverChainInclusion U V) n) := by
    change Mono (HomologicalComplex.homologyMap
      (coverChainCokernelSequence U V).f n)
    exact (hS.homology_exact₁ (n + 1) n rfl).mono_g
      ((h (n + 1)).isZero_homology.eq_of_src _ _)
  letI : Epi (HomologicalComplex.homologyMap (coverChainInclusion U V) n) := by
    change Epi (HomologicalComplex.homologyMap
      (coverChainCokernelSequence U V).f n)
    exact (hS.homology_exact₂ n).epi_f
      ((h n).isZero_homology.eq_of_tgt _ _)
  exact Balanced.isIso_of_mono_of_epi _

/-- Quasi-isomorphism of the cover inclusion is equivalent to acyclicity of its quotient. -/
public theorem coverChainInclusion_quasiIso_iff_quotient_acyclic {X : TopCat}
    {U V : Opens X} :
    QuasiIso (coverChainInclusion U V) ↔ (coverChainQuotient U V).Acyclic := by
  constructor
  · intro h
    exact (coverChainCokernelSequence_shortExact U V).acyclic_X₃ h
  · exact coverChainInclusion_quasiIso_of_quotient_acyclic

/-- Barycentric subdivision data proves the generated-cover inclusion is a quasi-isomorphism. -/
public theorem CoverSubdivisionData.coverChainInclusion_quasiIso {X : TopCat}
    {U V : Opens X} (D : CoverSubdivisionData U V) :
    QuasiIso (coverChainInclusion U V) :=
  coverChainInclusion_quasiIso_of_quotient_acyclic D.quotient_acyclic

/-- Degreewise homology isomorphism obtained from the subdivision certificate. -/
public theorem CoverSubdivisionData.isIso_homologyMap {X : TopCat} {U V : Opens X}
    (D : CoverSubdivisionData U V) (n : ℕ) :
    IsIso (HomologicalComplex.homologyMap (coverChainInclusion U V) n) := by
  letI : QuasiIso (coverChainInclusion U V) := D.coverChainInclusion_quasiIso
  infer_instance

/-- Exact source-level boundary left by Mathlib for binary open-cover excision. -/
public def BinaryOpenCoverSubdivisionStatement : Prop :=
  ∀ (X : TopCat) (U V : Opens X), U ⊔ V = ⊤ → Nonempty (CoverSubdivisionData U V)

end SphereSixComplex.BinaryOpenCover
