module

public import SphereSixComplex.Topology.MayerVietoris
public import Mathlib.Topology.CWComplex.Classical.Finite

/-!
# Classical cellular homology

This module isolates the objectwise content of the classical integral cellular-homology theorem.
Mathlib provides CW complexes and singular homology, but not their cellular comparison.
-/

@[expose] public section

noncomputable section

open CategoryTheory

namespace SphereSixComplex

/-- The objectwise content of integral cellular homology for one CW complex: a chain complex
freely generated by the cells whose homology agrees degreewise with integral singular homology. -/
public structure IntegralCWCellularHomologyModel
    (Y : Type) [TopologicalSpace Y] [Topology.CWComplex (Set.univ : Set Y)] where
  chainComplex : ChainComplex AddCommGrpCat ℕ
  cellBasis : ∀ n,
    (Topology.CWComplex.cell (Set.univ : Set Y) n →₀ ℤ) ≃+ chainComplex.X n
  homologyEquiv : ∀ n,
    chainComplex.homology n ≃+ IntegralSingularHomology n Y

namespace EstablishedCellularHomology

/-- For a Hausdorff CW complex, the integral cellular chain complex is free on its cells and its
homology is isomorphic to integral singular homology.

The explicit Hausdorff hypothesis is required because Mathlib's `CWComplex` class does not include
it.  This is the objectwise integral form of the cellular-homology theorem; no choice of a direct
chain map to singular chains, and no unsupported naturality data, is included.

Reference: [Hat02, Theorem 2.35]. -/
public axiom integralCWCellularHomologyModel
    (Y : Type) [TopologicalSpace Y] [T2Space Y]
    [Topology.CWComplex (Set.univ : Set Y)] :
    IntegralCWCellularHomologyModel Y

end EstablishedCellularHomology

end SphereSixComplex

end

end
