module

public import SphereSixComplex.Topology.PaperCuspCentralFiberCWModel

/-!
# Cellular algebra of the cusp toric fibre

The source CW decomposition has two vertices, three edges joining them, four two-cells, two
three-cells, and one four-cell.  Its only nonzero cellular differential is the incidence map from
the three oriented edges to the two vertices.  This module proves the resulting integral algebra;
it does not identify these groups with the homology of the actual cusp fibre.
-/

@[expose] public section

noncomputable section

namespace SphereSixComplex

/-- The cellular incidence map of three parallel oriented edges from the first vertex to the
second. -/
public def cuspToricCellularBoundaryOne : (Fin 3 → ℤ) →+ (Fin 2 → ℤ) where
  toFun x := ![-(x 0 + x 1 + x 2), x 0 + x 1 + x 2]
  map_zero' := by
    funext i
    fin_cases i <;> simp
  map_add' x y := by
    funext i
    fin_cases i <;> simp <;> ring

public theorem cuspToricCellularBoundaryOne_eq_zero_iff (x : Fin 3 → ℤ) :
    cuspToricCellularBoundaryOne x = 0 ↔ x 0 + x 1 + x 2 = 0 := by
  constructor
  · intro h
    have h1 := congrFun h (1 : Fin 2)
    simpa [cuspToricCellularBoundaryOne] using h1
  · intro h
    funext i
    fin_cases i <;> simp [cuspToricCellularBoundaryOne] <;> omega

/-- The kernel of the edge-incidence map is freely generated by two edge differences. -/
public def cuspToricCellularDegreeOneEquiv :
    AddMonoidHom.ker cuspToricCellularBoundaryOne ≃+ (Fin 2 → ℤ) where
  toFun x := ![x.1 0, x.1 1]
  invFun y :=
    ⟨![y 0, y 1, -y 0 - y 1],
      cuspToricCellularBoundaryOne_eq_zero_iff _ |>.2 (by simp)⟩
  map_add' x y := by
    funext i
    fin_cases i <;> simp
  left_inv x := by
    apply Subtype.ext
    have hx := cuspToricCellularBoundaryOne_eq_zero_iff x.1 |>.1 x.2
    funext i
    fin_cases i <;> simp
    omega
  right_inv y := by
    funext i
    fin_cases i <;> simp

/-- With zero differential out of the four two-cells, cellular degree two is free of rank four. -/
public def cuspToricCellularDegreeTwoEquiv : (Fin 4 → ℤ) ≃+ (Fin 4 → ℤ) :=
  AddEquiv.refl _

/-- With zero differential out of the two three-cells, cellular degree three is free of rank two. -/
public def cuspToricCellularDegreeThreeEquiv : (Fin 2 → ℤ) ≃+ (Fin 2 → ℤ) :=
  AddEquiv.refl _

/-- The unique four-cell generates cellular degree four. -/
public def cuspToricCellularDegreeFourEquiv : (Fin 1 → ℤ) ≃+ ℤ where
  toFun x := x 0
  invFun z := ![z]
  map_add' _ _ := rfl
  left_inv x := by
    funext i
    fin_cases i
    rfl
  right_inv _ := rfl

end SphereSixComplex
