module

public import SphereSixComplex.Topology.EstablishedAffineVanKampen
public import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# Unwrapped affine filling covers

This module packages the standard universal-cover construction for cyclic affine and toric
fillings.  In each case the filling deck group is defined as the quotient of the boundary deck
group by the normal closure of the meridians that bound in the filling.  Consequently the deck
map, its surjectivity, and its kernel are formal consequences of the quotient construction.
-/

@[expose] public section

noncomputable section

open Set Topology
open scoped ContinuousMap

namespace SphereSixComplex

/-! ## Cyclic affine collars -/

/-- Algebraic deck data for an unwrapped cyclic affine collar.

The boundary deck group is generated by translations and one angular meridian.  Going around the
meridian acts on the translation lattice by `monodromy`.  In the filling, the `m`-th power of the
meridian becomes translation by `twist`. -/
public structure UnwrappedCyclicAffineBoundaryDeckData
    (m : ℕ) (Λ G : Type*) [NeZero m] [AddCommGroup Λ] [Group G] where
  translation : Λ →+ Additive G
  translation_injective : Function.Injective translation
  meridian : G
  monodromy : Multiplicative (AddAut Λ)
  conjugate : ∀ a,
    meridian * Additive.toMul (translation a) * meridian⁻¹ =
      Additive.toMul (translation (monodromy.toAdd a))
  generators_generate : Subgroup.closure
    (Set.range (fun a ↦ Additive.toMul (translation a)) ∪ {meridian}) = ⊤
  twist : Λ
  monodromy_pow : monodromy ^ m = 1
  twist_fixed : monodromy.toAdd twist = twist

namespace UnwrappedCyclicAffineBoundaryDeckData

variable {m : ℕ} {Λ G : Type*} [NeZero m] [AddCommGroup Λ] [Group G]

/-- The boundary deck transformation that bounds after attaching the cyclic filling. -/
public def fillingRelation (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) : G :=
  D.meridian ^ m * (Additive.toMul (D.translation D.twist))⁻¹

/-- The normal subgroup killed by the cyclic filling. -/
public def fillingKernel (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) : Subgroup G :=
  Subgroup.normalClosure {D.fillingRelation}

/-- The cyclic filling kernel is normal. -/
public instance fillingKernel_normal (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    D.fillingKernel.Normal := by
  rw [fillingKernel]
  infer_instance

/-- The deck group of the cyclic filling. -/
public abbrev FillingDeck (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :=
  G ⧸ D.fillingKernel

/-- The canonical quotient from the unwrapped boundary deck group to the filling deck group. -/
public def fillingDeckMap (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    G →* D.FillingDeck :=
  QuotientGroup.mk' D.fillingKernel

/-- The cyclic filling deck map is onto. -/
public theorem fillingDeckMap_surjective
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    Function.Surjective D.fillingDeckMap :=
  QuotientGroup.mk'_surjective D.fillingKernel

/-- The cyclic filling deck map kills exactly the normal closure of its affine meridian. -/
public theorem fillingDeckMap_kernel
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    D.fillingDeckMap.ker = Subgroup.normalClosure {D.fillingRelation} := by
  exact QuotientGroup.ker_mk' (N := D.fillingKernel)

/-- The affine meridian relation is trivial in the filling deck group. -/
@[simp]
public theorem fillingDeckMap_fillingRelation
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    D.fillingDeckMap D.fillingRelation = 1 := by
  change D.fillingRelation ∈ D.fillingDeckMap.ker
  rw [D.fillingDeckMap_kernel]
  exact Subgroup.subset_normalClosure (Set.mem_singleton D.fillingRelation)

end UnwrappedCyclicAffineBoundaryDeckData

/-- A simply connected unwrapped cover square for a cyclic affine filling.

The filling deck group and the equivariance homomorphism are the canonical quotient determined by
the affine meridian relation; they are not additional inputs. -/
public structure UnwrappedCyclicAffineFillingCover
    (m : ℕ) (Λ G E E' B N : Type*)
    [NeZero m] [AddCommGroup Λ] [Group G]
    [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B] [TopologicalSpace N]
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G)
    [MulAction G E] [MulAction D.FillingDeck E'] where
  boundaryProjection : C(E, B)
  fillingProjection : C(E', N)
  boundaryQuotient : IsQuotientCoveringMap boundaryProjection G
  fillingQuotient : IsQuotientCoveringMap fillingProjection D.FillingDeck
  boundarySimplyConnected : SimplyConnectedSpace E
  fillingSimplyConnected : SimplyConnectedSpace E'
  lift : C(E, E')
  baseMap : C(B, N)
  commutes : ∀ z, baseMap (boundaryProjection z) = fillingProjection (lift z)
  equivariant : ∀ g z, lift (g • z) = D.fillingDeckMap g • lift z
  base : E

namespace UnwrappedCyclicAffineFillingCover

variable {m : ℕ} {Λ G E E' B N : Type*}
variable [NeZero m] [AddCommGroup Λ] [Group G]
variable [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B]
variable [TopologicalSpace N]
variable {D : UnwrappedCyclicAffineBoundaryDeckData m Λ G}
variable [MulAction G E] [MulAction D.FillingDeck E']

/-- The equivariant quotient-cover map carried by an unwrapped cyclic filling cover. -/
public def coverMap (U : UnwrappedCyclicAffineFillingCover m Λ G E E' B N D) :
    QuotientCoverMapData (G := G) (H := D.FillingDeck)
      U.boundaryProjection U.fillingProjection where
  deckMap := D.fillingDeckMap
  lift := U.lift
  baseMap := U.baseMap
  commutes := U.commutes
  equivariant := U.equivariant

/-- Forget the canonical quotient construction and retain the regular-cover model expected by the
fundamental-group filling theorem. -/
public def toCyclicAffineFillingCoverModel
    (U : UnwrappedCyclicAffineFillingCover m Λ G E E' B N D) :
    CyclicAffineFillingCoverModel m Λ G D.FillingDeck E E' B N where
  boundaryProjection := U.boundaryProjection
  fillingProjection := U.fillingProjection
  boundaryQuotient := U.boundaryQuotient
  fillingQuotient := U.fillingQuotient
  boundarySimplyConnected := U.boundarySimplyConnected
  fillingSimplyConnected := U.fillingSimplyConnected
  coverMap := U.coverMap
  base := U.base
  deckTranslation := D.translation
  deckMeridian := D.meridian
  monodromy := D.monodromy
  twist := D.twist
  monodromy_pow := D.monodromy_pow
  twist_fixed := D.twist_fixed
  deckMap_surjective := D.fillingDeckMap_surjective
  deckMap_kernel := D.fillingDeckMap_kernel

/-- The standard cyclic filling computation applied to an unwrapped affine cover square. -/
public noncomputable def fundamentalGroupData
    (U : UnwrappedCyclicAffineFillingCover m Λ G E E' B N D) :
    CyclicAffineFillingPiOneData U.toCyclicAffineFillingCoverModel :=
  establishedCyclicAffineFillingPiOne U.toCyclicAffineFillingCoverModel

end UnwrappedCyclicAffineFillingCover

/-! ## Toric cusp collars -/

/-- Algebraic deck data for an unwrapped toric cusp collar.

The filling kills the angular meridian and every translation in the image of `vanishing`. -/
public structure UnwrappedToricBoundaryDeckData
    (Λ K G : Type*) [AddCommGroup Λ] [AddCommGroup K] [Group G] where
  translation : Λ →+ Additive G
  translation_injective : Function.Injective translation
  meridian : G
  vanishing : K →+ Λ
  generators_generate : Subgroup.closure
    (Set.range (fun a ↦ Additive.toMul (translation a)) ∪ {meridian}) = ⊤

namespace UnwrappedToricBoundaryDeckData

variable {Λ K G : Type*} [AddCommGroup Λ] [AddCommGroup K] [Group G]

/-- The boundary deck transformations that bound after the toric filling. -/
public def fillingRelations (D : UnwrappedToricBoundaryDeckData Λ K G) : Set G :=
  Set.range (fun k ↦ Additive.toMul (D.translation (D.vanishing k))) ∪ {D.meridian}

/-- The normal subgroup killed by the toric filling. -/
public def fillingKernel (D : UnwrappedToricBoundaryDeckData Λ K G) : Subgroup G :=
  Subgroup.normalClosure D.fillingRelations

/-- The toric filling kernel is normal. -/
public instance fillingKernel_normal (D : UnwrappedToricBoundaryDeckData Λ K G) :
    D.fillingKernel.Normal := by
  rw [fillingKernel]
  infer_instance

/-- The deck group of the toric filling. -/
public abbrev FillingDeck (D : UnwrappedToricBoundaryDeckData Λ K G) :=
  G ⧸ D.fillingKernel

/-- The canonical quotient from the unwrapped cusp deck group to the toric filling deck group. -/
public def fillingDeckMap (D : UnwrappedToricBoundaryDeckData Λ K G) : G →* D.FillingDeck :=
  QuotientGroup.mk' D.fillingKernel

/-- The toric filling deck map is onto. -/
public theorem fillingDeckMap_surjective (D : UnwrappedToricBoundaryDeckData Λ K G) :
    Function.Surjective D.fillingDeckMap :=
  QuotientGroup.mk'_surjective D.fillingKernel

/-- The toric filling deck map kills exactly the normal closure of the vanishing translations and
the angular meridian. -/
public theorem fillingDeckMap_kernel (D : UnwrappedToricBoundaryDeckData Λ K G) :
    D.fillingDeckMap.ker =
      Subgroup.normalClosure
        (Set.range (fun k ↦ Additive.toMul (D.translation (D.vanishing k))) ∪
          {D.meridian}) := by
  exact QuotientGroup.ker_mk' (N := D.fillingKernel)

/-- Every specified vanishing translation is trivial in the toric filling deck group. -/
@[simp]
public theorem fillingDeckMap_vanishing
    (D : UnwrappedToricBoundaryDeckData Λ K G) (k : K) :
    D.fillingDeckMap (Additive.toMul (D.translation (D.vanishing k))) = 1 := by
  change Additive.toMul (D.translation (D.vanishing k)) ∈ D.fillingDeckMap.ker
  rw [D.fillingDeckMap_kernel]
  apply Subgroup.subset_normalClosure
  exact Or.inl ⟨k, rfl⟩

/-- The cusp meridian is trivial in the toric filling deck group. -/
@[simp]
public theorem fillingDeckMap_meridian (D : UnwrappedToricBoundaryDeckData Λ K G) :
    D.fillingDeckMap D.meridian = 1 := by
  change D.meridian ∈ D.fillingDeckMap.ker
  rw [D.fillingDeckMap_kernel]
  apply Subgroup.subset_normalClosure
  exact Or.inr (Set.mem_singleton D.meridian)

end UnwrappedToricBoundaryDeckData

/-- A simply connected unwrapped cover square for a toric cusp filling. -/
public structure UnwrappedToricFillingCover
    (Λ K G E E' B N : Type*)
    [AddCommGroup Λ] [AddCommGroup K] [Group G]
    [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B] [TopologicalSpace N]
    (D : UnwrappedToricBoundaryDeckData Λ K G)
    [MulAction G E] [MulAction D.FillingDeck E'] where
  boundaryProjection : C(E, B)
  fillingProjection : C(E', N)
  boundaryQuotient : IsQuotientCoveringMap boundaryProjection G
  fillingQuotient : IsQuotientCoveringMap fillingProjection D.FillingDeck
  boundarySimplyConnected : SimplyConnectedSpace E
  fillingSimplyConnected : SimplyConnectedSpace E'
  lift : C(E, E')
  baseMap : C(B, N)
  commutes : ∀ z, baseMap (boundaryProjection z) = fillingProjection (lift z)
  equivariant : ∀ g z, lift (g • z) = D.fillingDeckMap g • lift z
  base : E

namespace UnwrappedToricFillingCover

variable {Λ K G E E' B N : Type*}
variable [AddCommGroup Λ] [AddCommGroup K] [Group G]
variable [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B]
variable [TopologicalSpace N]
variable {D : UnwrappedToricBoundaryDeckData Λ K G}
variable [MulAction G E] [MulAction D.FillingDeck E']

/-- The equivariant quotient-cover map carried by an unwrapped toric filling cover. -/
public def coverMap (U : UnwrappedToricFillingCover Λ K G E E' B N D) :
    QuotientCoverMapData (G := G) (H := D.FillingDeck)
      U.boundaryProjection U.fillingProjection where
  deckMap := D.fillingDeckMap
  lift := U.lift
  baseMap := U.baseMap
  commutes := U.commutes
  equivariant := U.equivariant

/-- Forget the canonical quotient construction and retain the regular-cover model expected by the
fundamental-group filling theorem. -/
public def toToricFillingCoverModel
    (U : UnwrappedToricFillingCover Λ K G E E' B N D) :
    ToricFillingCoverModel Λ K G D.FillingDeck E E' B N where
  boundaryProjection := U.boundaryProjection
  fillingProjection := U.fillingProjection
  boundaryQuotient := U.boundaryQuotient
  fillingQuotient := U.fillingQuotient
  boundarySimplyConnected := U.boundarySimplyConnected
  fillingSimplyConnected := U.fillingSimplyConnected
  coverMap := U.coverMap
  base := U.base
  deckTranslation := D.translation
  deckMeridian := D.meridian
  vanishing := D.vanishing
  deckMap_surjective := D.fillingDeckMap_surjective
  deckMap_kernel := D.fillingDeckMap_kernel

/-- The standard toric filling computation applied to an unwrapped cusp cover square. -/
public noncomputable def fundamentalGroupData
    (U : UnwrappedToricFillingCover Λ K G E E' B N D) :
    ToricFillingPiOneData U.toToricFillingCoverModel :=
  establishedToricFillingPiOne U.toToricFillingCoverModel

end UnwrappedToricFillingCover

end SphereSixComplex

end
