module

public import SphereSixComplex.Topology.EstablishedAffineVanKampen
public import Mathlib.GroupTheory.QuotientGroup.Defs
public import Mathlib.GroupTheory.SemidirectProduct

/-!
# Unwrapped affine filling covers

This module packages the standard universal-cover construction for cyclic affine and toric
fillings.  In each case the filling deck group is defined as the quotient of the boundary deck
group by the normal closure of the meridians that bound in the filling.  Consequently the deck
map, its surjectivity, and its kernel are formal consequences of the quotient construction.
-/

@[expose] public section

noncomputable section

open Set Topology
open scoped ContinuousMap

namespace SphereSixComplex

/-! ## Cyclic affine collars -/

/-- Algebraic deck data for an unwrapped cyclic affine collar.

The boundary deck group is generated by translations and one angular meridian.  Going around the
meridian acts on the translation lattice by `monodromy`.  In the filling, the `m`-th power of the
meridian becomes translation by `twist`. -/
public structure UnwrappedCyclicAffineBoundaryDeckData
    (m : ℕ) (Λ G : Type*) [NeZero m] [AddCommGroup Λ] [Group G] where
  translation : Λ →+ Additive G
  translation_injective : Function.Injective translation
  meridian : G
  monodromy : Multiplicative (AddAut Λ)
  conjugate : ∀ a,
    meridian * Additive.toMul (translation a) * meridian⁻¹ =
      Additive.toMul (translation (monodromy.toAdd a))
  generators_generate : Subgroup.closure
    (Set.range (fun a ↦ Additive.toMul (translation a)) ∪ {meridian}) = ⊤
  twist : Λ
  monodromy_pow : monodromy ^ m = 1
  twist_fixed : monodromy.toAdd twist = twist

namespace UnwrappedCyclicAffineBoundaryDeckData

variable {m : ℕ} {Λ G : Type*} [NeZero m] [AddCommGroup Λ] [Group G]

/-- The boundary deck transformation that bounds after attaching the cyclic filling. -/
public def fillingRelation (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) : G :=
  D.meridian ^ m * (Additive.toMul (D.translation D.twist))⁻¹

/-- The normal subgroup killed by the cyclic filling. -/
public def fillingKernel (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) : Subgroup G :=
  Subgroup.normalClosure {D.fillingRelation}

/-- The cyclic filling kernel is normal. -/
public instance fillingKernel_normal (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    D.fillingKernel.Normal := by
  rw [fillingKernel]
  infer_instance

/-- The deck group of the cyclic filling. -/
public abbrev FillingDeck (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :=
  G ⧸ D.fillingKernel

/-- The canonical quotient from the unwrapped boundary deck group to the filling deck group. -/
public def fillingDeckMap (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    G →* D.FillingDeck :=
  QuotientGroup.mk' D.fillingKernel

/-- The cyclic filling deck map is onto. -/
public theorem fillingDeckMap_surjective
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    Function.Surjective D.fillingDeckMap :=
  QuotientGroup.mk'_surjective D.fillingKernel

/-- The cyclic filling deck map kills exactly the normal closure of its affine meridian. -/
public theorem fillingDeckMap_kernel
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    D.fillingDeckMap.ker = Subgroup.normalClosure {D.fillingRelation} := by
  exact QuotientGroup.ker_mk' (N := D.fillingKernel)

/-- The affine meridian relation is trivial in the filling deck group. -/
@[simp]
public theorem fillingDeckMap_fillingRelation
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G) :
    D.fillingDeckMap D.fillingRelation = 1 := by
  change D.fillingRelation ∈ D.fillingDeckMap.ker
  rw [D.fillingDeckMap_kernel]
  exact Subgroup.subset_normalClosure (Set.mem_singleton D.fillingRelation)

end UnwrappedCyclicAffineBoundaryDeckData

/-! ### The canonical semidirect boundary deck group -/

/-- Integral powers of an additive automorphism, as an additive homomorphism. -/
public def integerPowersAddAut {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :
    ℤ →+ AddAut Λ where
  toFun n := n • φ
  map_zero' := zero_zsmul φ
  map_add' n k := add_zsmul φ n k

/-- The action of the unwrapped angular deck group on the translation lattice. -/
public def integerAffineMonodromy {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :
    Multiplicative ℤ →* MulAut (Multiplicative Λ) :=
  (MulAutMultiplicative Λ).symm.toMonoidHom.comp (integerPowersAddAut φ).toMultiplicative

/-- The canonical unwrapped cyclic-affine boundary deck group. -/
public abbrev CanonicalCyclicAffineBoundaryDeck
    {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :=
  Multiplicative Λ ⋊[integerAffineMonodromy φ] Multiplicative ℤ

/-- The canonical translation embedding in an unwrapped cyclic-affine boundary deck group. -/
public def canonicalCyclicAffineTranslation
    {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :
    Λ →+ Additive (CanonicalCyclicAffineBoundaryDeck φ) where
  toFun a := Additive.ofMul
    (SemidirectProduct.inl (φ := integerAffineMonodromy φ) (Multiplicative.ofAdd a))
  map_zero' := by
    apply Additive.toMul.injective
    exact (SemidirectProduct.inl (φ := integerAffineMonodromy φ)).map_one
  map_add' a b := by
    apply Additive.toMul.injective
    exact (SemidirectProduct.inl (φ := integerAffineMonodromy φ)).map_mul
      (Multiplicative.ofAdd a) (Multiplicative.ofAdd b)

/-- The positive angular meridian in the canonical unwrapped cyclic-affine deck group. -/
public def canonicalCyclicAffineMeridian
    {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :
    CanonicalCyclicAffineBoundaryDeck φ :=
  SemidirectProduct.inr (Multiplicative.ofAdd 1)

/-- Canonical cyclic-affine translations embed faithfully. -/
public theorem canonicalCyclicAffineTranslation_injective
    {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :
    Function.Injective (canonicalCyclicAffineTranslation φ) := by
  intro a b h
  have h' := congrArg SemidirectProduct.left (congrArg Additive.toMul h)
  change Multiplicative.ofAdd a = Multiplicative.ofAdd b at h'
  exact Multiplicative.ofAdd.injective h'

/-- Conjugation by the positive angular meridian is the chosen affine monodromy. -/
public theorem canonicalCyclicAffine_conjugate
    {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) (a : Λ) :
    canonicalCyclicAffineMeridian φ *
          Additive.toMul (canonicalCyclicAffineTranslation φ a) *
        (canonicalCyclicAffineMeridian φ)⁻¹ =
      Additive.toMul (canonicalCyclicAffineTranslation φ (φ a)) := by
  symm
  change SemidirectProduct.inl
      (φ := integerAffineMonodromy φ) (Multiplicative.ofAdd (φ a)) =
    SemidirectProduct.inr (Multiplicative.ofAdd 1) *
      SemidirectProduct.inl (Multiplicative.ofAdd a) *
        (SemidirectProduct.inr (Multiplicative.ofAdd 1))⁻¹
  convert SemidirectProduct.inl_aut
    (φ := integerAffineMonodromy φ) (Multiplicative.ofAdd 1)
      (Multiplicative.ofAdd a) using 1
  · rfl
  · rw [map_inv]

/-- Translations and the positive meridian generate the canonical unwrapped cyclic-affine deck
group. -/
public theorem canonicalCyclicAffine_generators_generate
    {Λ : Type*} [AddCommGroup Λ] (φ : AddAut Λ) :
    Subgroup.closure
      (Set.range (fun a ↦ Additive.toMul (canonicalCyclicAffineTranslation φ a)) ∪
        {canonicalCyclicAffineMeridian φ}) = ⊤ := by
  apply top_unique
  intro d _
  have hleft :
      SemidirectProduct.inl (φ := integerAffineMonodromy φ) d.left ∈
        Subgroup.closure
          (Set.range (fun a ↦ Additive.toMul (canonicalCyclicAffineTranslation φ a)) ∪
            {canonicalCyclicAffineMeridian φ}) :=
    Subgroup.subset_closure (Or.inl ⟨d.left.toAdd, rfl⟩)
  have hmeridian :
      canonicalCyclicAffineMeridian φ ∈
        Subgroup.closure
          (Set.range (fun a ↦ Additive.toMul (canonicalCyclicAffineTranslation φ a)) ∪
            {canonicalCyclicAffineMeridian φ}) :=
    Subgroup.subset_closure
      (Or.inr (Set.mem_singleton (canonicalCyclicAffineMeridian φ)))
  have hright :
      SemidirectProduct.inr d.right ∈
        Subgroup.closure
          (Set.range (fun a ↦ Additive.toMul (canonicalCyclicAffineTranslation φ a)) ∪
            {canonicalCyclicAffineMeridian φ}) := by
    rw [show SemidirectProduct.inr d.right =
        (canonicalCyclicAffineMeridian φ) ^ d.right.toAdd by
      change SemidirectProduct.inr d.right =
        (SemidirectProduct.inr (Multiplicative.ofAdd 1)) ^ d.right.toAdd
      rw [← map_zpow]
      congr 1
      apply Multiplicative.toAdd.injective
      simp]
    exact Subgroup.zpow_mem _ hmeridian d.right.toAdd
  rw [← SemidirectProduct.inl_left_mul_inr_right d]
  exact Subgroup.mul_mem _ hleft hright

/-- Canonical algebraic data for an unwrapped cyclic-affine collar. -/
public def canonicalCyclicAffineBoundaryDeckData
    {m : ℕ} {Λ : Type*} [NeZero m] [AddCommGroup Λ]
    (φ : AddAut Λ) (twist : Λ)
    (hφ : (Multiplicative.ofAdd φ) ^ m = 1) (htwist : φ twist = twist) :
    UnwrappedCyclicAffineBoundaryDeckData m Λ
      (CanonicalCyclicAffineBoundaryDeck φ) where
  translation := canonicalCyclicAffineTranslation φ
  translation_injective := canonicalCyclicAffineTranslation_injective φ
  meridian := canonicalCyclicAffineMeridian φ
  monodromy := Multiplicative.ofAdd φ
  conjugate := canonicalCyclicAffine_conjugate φ
  generators_generate := canonicalCyclicAffine_generators_generate φ
  twist := twist
  monodromy_pow := hφ
  twist_fixed := htwist

/-- A simply connected unwrapped cover square for a cyclic affine filling.

The filling deck group and the equivariance homomorphism are the canonical quotient determined by
the affine meridian relation; they are not additional inputs. -/
public structure UnwrappedCyclicAffineFillingCover
    (m : ℕ) (Λ G E E' B N : Type*)
    [NeZero m] [AddCommGroup Λ] [Group G]
    [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B] [TopologicalSpace N]
    (D : UnwrappedCyclicAffineBoundaryDeckData m Λ G)
    [MulAction G E] [MulAction D.FillingDeck E'] where
  boundaryProjection : C(E, B)
  fillingProjection : C(E', N)
  boundaryQuotient : IsQuotientCoveringMap boundaryProjection G
  fillingQuotient : IsQuotientCoveringMap fillingProjection D.FillingDeck
  boundarySimplyConnected : SimplyConnectedSpace E
  fillingSimplyConnected : SimplyConnectedSpace E'
  lift : C(E, E')
  baseMap : C(B, N)
  commutes : ∀ z, baseMap (boundaryProjection z) = fillingProjection (lift z)
  equivariant : ∀ g z, lift (g • z) = D.fillingDeckMap g • lift z
  base : E

namespace UnwrappedCyclicAffineFillingCover

variable {m : ℕ} {Λ G E E' B N : Type*}
variable [NeZero m] [AddCommGroup Λ] [Group G]
variable [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B]
variable [TopologicalSpace N]
variable {D : UnwrappedCyclicAffineBoundaryDeckData m Λ G}
variable [MulAction G E] [MulAction D.FillingDeck E']

/-- The equivariant quotient-cover map carried by an unwrapped cyclic filling cover. -/
public def coverMap (U : UnwrappedCyclicAffineFillingCover m Λ G E E' B N D) :
    QuotientCoverMapData (G := G) (H := D.FillingDeck)
      U.boundaryProjection U.fillingProjection where
  deckMap := D.fillingDeckMap
  lift := U.lift
  baseMap := U.baseMap
  commutes := U.commutes
  equivariant := U.equivariant

/-- Forget the canonical quotient construction and retain the regular-cover model expected by the
fundamental-group filling theorem. -/
public def toCyclicAffineFillingCoverModel
    (U : UnwrappedCyclicAffineFillingCover m Λ G E E' B N D) :
    CyclicAffineFillingCoverModel m Λ G D.FillingDeck E E' B N where
  boundaryProjection := U.boundaryProjection
  fillingProjection := U.fillingProjection
  boundaryQuotient := U.boundaryQuotient
  fillingQuotient := U.fillingQuotient
  boundarySimplyConnected := U.boundarySimplyConnected
  fillingSimplyConnected := U.fillingSimplyConnected
  coverMap := U.coverMap
  base := U.base
  deckTranslation := D.translation
  deckMeridian := D.meridian
  monodromy := D.monodromy
  deck_conjugate := D.conjugate
  twist := D.twist
  monodromy_pow := D.monodromy_pow
  twist_fixed := D.twist_fixed
  deckMap_surjective := D.fillingDeckMap_surjective
  deckMap_kernel := D.fillingDeckMap_kernel

/-- The standard cyclic filling computation applied to an unwrapped affine cover square. -/
public noncomputable def fundamentalGroupData
    (U : UnwrappedCyclicAffineFillingCover m Λ G E E' B N D) :
    CyclicAffineFillingPiOneData U.toCyclicAffineFillingCoverModel :=
  establishedCyclicAffineFillingPiOne U.toCyclicAffineFillingCoverModel

end UnwrappedCyclicAffineFillingCover

/-! ## Toric cusp collars -/

/-- Algebraic deck data for an unwrapped toric cusp collar.

The filling kills the angular meridian and every translation in the image of `vanishing`. -/
public structure UnwrappedToricBoundaryDeckData
    (Λ K G : Type*) [AddCommGroup Λ] [AddCommGroup K] [Group G] where
  translation : Λ →+ Additive G
  translation_injective : Function.Injective translation
  meridian : G
  vanishing : K →+ Λ
  generators_generate : Subgroup.closure
    (Set.range (fun a ↦ Additive.toMul (translation a)) ∪ {meridian}) = ⊤

namespace UnwrappedToricBoundaryDeckData

variable {Λ K G : Type*} [AddCommGroup Λ] [AddCommGroup K] [Group G]

/-- The boundary deck transformations that bound after the toric filling. -/
public def fillingRelations (D : UnwrappedToricBoundaryDeckData Λ K G) : Set G :=
  Set.range (fun k ↦ Additive.toMul (D.translation (D.vanishing k))) ∪ {D.meridian}

/-- The normal subgroup killed by the toric filling. -/
public def fillingKernel (D : UnwrappedToricBoundaryDeckData Λ K G) : Subgroup G :=
  Subgroup.normalClosure D.fillingRelations

/-- The toric filling kernel is normal. -/
public instance fillingKernel_normal (D : UnwrappedToricBoundaryDeckData Λ K G) :
    D.fillingKernel.Normal := by
  rw [fillingKernel]
  infer_instance

/-- The deck group of the toric filling. -/
public abbrev FillingDeck (D : UnwrappedToricBoundaryDeckData Λ K G) :=
  G ⧸ D.fillingKernel

/-- The canonical quotient from the unwrapped cusp deck group to the toric filling deck group. -/
public def fillingDeckMap (D : UnwrappedToricBoundaryDeckData Λ K G) : G →* D.FillingDeck :=
  QuotientGroup.mk' D.fillingKernel

/-- The toric filling deck map is onto. -/
public theorem fillingDeckMap_surjective (D : UnwrappedToricBoundaryDeckData Λ K G) :
    Function.Surjective D.fillingDeckMap :=
  QuotientGroup.mk'_surjective D.fillingKernel

/-- The toric filling deck map kills exactly the normal closure of the vanishing translations and
the angular meridian. -/
public theorem fillingDeckMap_kernel (D : UnwrappedToricBoundaryDeckData Λ K G) :
    D.fillingDeckMap.ker =
      Subgroup.normalClosure
        (Set.range (fun k ↦ Additive.toMul (D.translation (D.vanishing k))) ∪
          {D.meridian}) := by
  exact QuotientGroup.ker_mk' (N := D.fillingKernel)

/-- Every specified vanishing translation is trivial in the toric filling deck group. -/
@[simp]
public theorem fillingDeckMap_vanishing
    (D : UnwrappedToricBoundaryDeckData Λ K G) (k : K) :
    D.fillingDeckMap (Additive.toMul (D.translation (D.vanishing k))) = 1 := by
  change Additive.toMul (D.translation (D.vanishing k)) ∈ D.fillingDeckMap.ker
  rw [D.fillingDeckMap_kernel]
  apply Subgroup.subset_normalClosure
  exact Or.inl ⟨k, rfl⟩

/-- The cusp meridian is trivial in the toric filling deck group. -/
@[simp]
public theorem fillingDeckMap_meridian (D : UnwrappedToricBoundaryDeckData Λ K G) :
    D.fillingDeckMap D.meridian = 1 := by
  change D.meridian ∈ D.fillingDeckMap.ker
  rw [D.fillingDeckMap_kernel]
  apply Subgroup.subset_normalClosure
  exact Or.inr (Set.mem_singleton D.meridian)

end UnwrappedToricBoundaryDeckData

/-! ### The canonical toric boundary deck group -/

/-- The canonical deck group of an unwrapped toric cusp boundary. -/
public abbrev CanonicalToricBoundaryDeck (Λ : Type*) [AddCommGroup Λ] :=
  Multiplicative Λ × Multiplicative ℤ

/-- The canonical translation embedding in an unwrapped toric boundary deck group. -/
public def canonicalToricTranslation {Λ : Type*} [AddCommGroup Λ] :
    Λ →+ Additive (CanonicalToricBoundaryDeck Λ) where
  toFun a := Additive.ofMul (Multiplicative.ofAdd a, 1)
  map_zero' := by
    apply Additive.toMul.injective
    ext <;> simp
  map_add' a b := by
    apply Additive.toMul.injective
    ext <;> simp

/-- The positive angular meridian in the canonical unwrapped toric boundary deck group. -/
public def canonicalToricMeridian {Λ : Type*} [AddCommGroup Λ] :
    CanonicalToricBoundaryDeck Λ :=
  (1, Multiplicative.ofAdd 1)

/-- Canonical toric translations embed faithfully. -/
public theorem canonicalToricTranslation_injective
    {Λ : Type*} [AddCommGroup Λ] :
    Function.Injective (canonicalToricTranslation (Λ := Λ)) := by
  intro a b h
  have h' := congrArg Prod.fst (congrArg Additive.toMul h)
  change Multiplicative.ofAdd a = Multiplicative.ofAdd b at h'
  exact Multiplicative.ofAdd.injective h'

/-- The angular meridian commutes with every toric translation. -/
public theorem canonicalToricMeridian_commutes
    {Λ : Type*} [AddCommGroup Λ] (a : Λ) :
    Commute (canonicalToricMeridian (Λ := Λ))
      (Additive.toMul (canonicalToricTranslation a)) := by
  simp [canonicalToricMeridian, canonicalToricTranslation, Commute]

/-- Translations and the positive meridian generate the canonical unwrapped toric deck group. -/
public theorem canonicalToric_generators_generate
    {Λ : Type*} [AddCommGroup Λ] :
    Subgroup.closure
      (Set.range (fun a ↦ Additive.toMul (canonicalToricTranslation a)) ∪
        {canonicalToricMeridian (Λ := Λ)}) = ⊤ := by
  apply top_unique
  intro d _
  have hleft :
      (d.1, 1) ∈
        Subgroup.closure
          (Set.range (fun a ↦ Additive.toMul (canonicalToricTranslation a)) ∪
            {canonicalToricMeridian (Λ := Λ)}) :=
    Subgroup.subset_closure (Or.inl ⟨d.1.toAdd, rfl⟩)
  have hmeridian :
      canonicalToricMeridian (Λ := Λ) ∈
        Subgroup.closure
          (Set.range (fun a ↦ Additive.toMul (canonicalToricTranslation a)) ∪
            {canonicalToricMeridian (Λ := Λ)}) :=
    Subgroup.subset_closure
      (Or.inr (Set.mem_singleton (canonicalToricMeridian (Λ := Λ))))
  have hright :
      (1, d.2) ∈
        Subgroup.closure
          (Set.range (fun a ↦ Additive.toMul (canonicalToricTranslation a)) ∪
            {canonicalToricMeridian (Λ := Λ)}) := by
    rw [show (1, d.2) = (canonicalToricMeridian (Λ := Λ)) ^ d.2.toAdd by
      change (1, d.2) =
        ((1, Multiplicative.ofAdd 1) : CanonicalToricBoundaryDeck Λ) ^ d.2.toAdd
      ext
      · simp
      · apply Multiplicative.toAdd.injective
        simp]
    exact Subgroup.zpow_mem _ hmeridian d.2.toAdd
  rw [show d = (d.1, 1) * (1, d.2) by ext <;> simp]
  exact Subgroup.mul_mem _ hleft hright

/-- Canonical algebraic data for an unwrapped toric cusp collar. -/
public def canonicalToricBoundaryDeckData
    {Λ K : Type*} [AddCommGroup Λ] [AddCommGroup K] (vanishing : K →+ Λ) :
    UnwrappedToricBoundaryDeckData Λ K (CanonicalToricBoundaryDeck Λ) where
  translation := canonicalToricTranslation
  translation_injective := canonicalToricTranslation_injective
  meridian := canonicalToricMeridian
  vanishing := vanishing
  generators_generate := canonicalToric_generators_generate

/-- A simply connected unwrapped cover square for a toric cusp filling. -/
public structure UnwrappedToricFillingCover
    (Λ K G E E' B N : Type*)
    [AddCommGroup Λ] [AddCommGroup K] [Group G]
    [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B] [TopologicalSpace N]
    (D : UnwrappedToricBoundaryDeckData Λ K G)
    [MulAction G E] [MulAction D.FillingDeck E'] where
  boundaryProjection : C(E, B)
  fillingProjection : C(E', N)
  boundaryQuotient : IsQuotientCoveringMap boundaryProjection G
  fillingQuotient : IsQuotientCoveringMap fillingProjection D.FillingDeck
  boundarySimplyConnected : SimplyConnectedSpace E
  fillingSimplyConnected : SimplyConnectedSpace E'
  lift : C(E, E')
  baseMap : C(B, N)
  commutes : ∀ z, baseMap (boundaryProjection z) = fillingProjection (lift z)
  equivariant : ∀ g z, lift (g • z) = D.fillingDeckMap g • lift z
  base : E

namespace UnwrappedToricFillingCover

variable {Λ K G E E' B N : Type*}
variable [AddCommGroup Λ] [AddCommGroup K] [Group G]
variable [TopologicalSpace E] [TopologicalSpace E'] [TopologicalSpace B]
variable [TopologicalSpace N]
variable {D : UnwrappedToricBoundaryDeckData Λ K G}
variable [MulAction G E] [MulAction D.FillingDeck E']

/-- The equivariant quotient-cover map carried by an unwrapped toric filling cover. -/
public def coverMap (U : UnwrappedToricFillingCover Λ K G E E' B N D) :
    QuotientCoverMapData (G := G) (H := D.FillingDeck)
      U.boundaryProjection U.fillingProjection where
  deckMap := D.fillingDeckMap
  lift := U.lift
  baseMap := U.baseMap
  commutes := U.commutes
  equivariant := U.equivariant

/-- Forget the canonical quotient construction and retain the regular-cover model expected by the
fundamental-group filling theorem. -/
public def toToricFillingCoverModel
    (U : UnwrappedToricFillingCover Λ K G E E' B N D) :
    ToricFillingCoverModel Λ K G D.FillingDeck E E' B N where
  boundaryProjection := U.boundaryProjection
  fillingProjection := U.fillingProjection
  boundaryQuotient := U.boundaryQuotient
  fillingQuotient := U.fillingQuotient
  boundarySimplyConnected := U.boundarySimplyConnected
  fillingSimplyConnected := U.fillingSimplyConnected
  coverMap := U.coverMap
  base := U.base
  deckTranslation := D.translation
  deckMeridian := D.meridian
  vanishing := D.vanishing
  deckMap_surjective := D.fillingDeckMap_surjective
  deckMap_kernel := D.fillingDeckMap_kernel

/-- The standard toric filling computation applied to an unwrapped cusp cover square. -/
public noncomputable def fundamentalGroupData
    (U : UnwrappedToricFillingCover Λ K G E E' B N D) :
    ToricFillingPiOneData U.toToricFillingCoverModel :=
  establishedToricFillingPiOne U.toToricFillingCoverModel

end UnwrappedToricFillingCover

end SphereSixComplex

end
