module

public import Mathlib.Topology.Gluing
public import Mathlib.Topology.Homeomorph.Lemmas

/-!
# Gluing a jointly surjective family of open embeddings

This is the source-indexed analogue of `TopCat.GlueData.ofOpenSubsets`: the pieces need not
literally be open subtypes of the covered space.  Their pairwise overlaps are pulled back from the
open ranges, and the resulting gluing is canonically homeomorphic to the covered space.
-/

@[expose] public section

noncomputable section

open CategoryTheory CategoryTheory.Limits Function Set TopologicalSpace Topology

namespace SphereSixComplex
namespace OpenEmbeddingGluing

universe u

variable {J : Type u} {X : Type u} [TopologicalSpace X]
  (U : J → Type u) [∀ i, TopologicalSpace (U i)]
  (e : ∀ i, U i → X) (he : ∀ i, IsOpenEmbedding (e i))

include U e he

/-- The part of piece `i` whose image also lies in piece `j`. -/
public def overlap (i j : J) : Opens (U i) where
  carrier := e i ⁻¹' Set.range (e j)
  is_open' := (he j).isOpen_range.preimage (he i).continuous

@[simp]
public theorem mem_overlap {i j : J} (x : U i) :
    x ∈ overlap U e he i j ↔ e i x ∈ Set.range (e j) :=
  Iff.rfl

/-- The change-of-piece map on an overlap, obtained by the inverse of the target embedding. -/
public def transition (i j : J) (x : overlap U e he i j) : overlap U e he j i := by
  let y : U j := (he j).isEmbedding.toHomeomorph.symm ⟨e i x.1, x.2⟩
  refine ⟨y, ?_⟩
  refine ⟨x.1, ?_⟩
  exact (congrArg Subtype.val
    ((he j).isEmbedding.toHomeomorph.apply_symm_apply ⟨e i x.1, x.2⟩)).symm

/-- A transition map represents the same point in the covered space. -/
public theorem map_transition (i j : J) (x : overlap U e he i j) :
    e j (transition U e he i j x) = e i x.1 := by
  change e j ((he j).isEmbedding.toHomeomorph.symm ⟨e i x.1, x.2⟩) = e i x.1
  exact congrArg Subtype.val
    ((he j).isEmbedding.toHomeomorph.apply_symm_apply ⟨e i x.1, x.2⟩)

/-- Transition maps are continuous. -/
public theorem continuous_transition (i j : J) : Continuous (transition U e he i j) := by
  apply Continuous.subtype_mk
  exact (he j).isEmbedding.toHomeomorph.symm.continuous.comp
    (((he i).continuous.comp continuous_subtype_val).subtype_mk _)

/-- The elementary open-gluing data associated to the open embeddings. -/
public abbrev mkCore (U : J → Type u) [∀ i, TopologicalSpace (U i)]
    (e : ∀ i, U i → X) (he : ∀ i, IsOpenEmbedding (e i)) :
    TopCat.GlueData.MkCore.{u} where
  J := J
  U := fun i ↦ TopCat.of (U i)
  V := overlap U e he
  t := fun i j ↦ TopCat.ofHom ⟨transition U e he i j, continuous_transition U e he i j⟩
  V_id := by
    intro i
    ext x
    simp [overlap]
  t_id := by
    intro i
    funext x
    change transition U e he i i x = x
    apply Subtype.ext
    apply (he i).injective
    exact map_transition U e he i i x
  t_inter := by
    intro i j k x hx
    change e j (transition U e he i j x) ∈ Set.range (e k)
    rw [map_transition U e he i j x]
    exact hx
  cocycle := by
    intro i j k x hx
    change (transition U e he j k ⟨transition U e he i j x, _⟩).1 =
      (transition U e he i k ⟨x, hx⟩).1
    apply (he k).injective
    rw [map_transition U e he j k, map_transition U e he i k,
      map_transition U e he i j]

/-- The `TopCat.GlueData` generated by a family of open embeddings. -/
public abbrev glueData (U : J → Type u) [∀ i, TopologicalSpace (U i)]
    (e : ∀ i, U i → X) (he : ∀ i, IsOpenEmbedding (e i)) : TopCat.GlueData.{u} :=
  TopCat.GlueData.mk' (mkCore U e he)

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

/-- The canonical map of a source piece into the abstract gluing. -/
public def pieceInclusion (i : J) : U i → (glueData U e he).toGlueData.glued :=
  (glueData U e he).toGlueData.ι i

/-- The canonical map from the abstract gluing to the covered space. -/
public def gluedTo : (glueData U e he).toGlueData.glued ⟶ TopCat.of X :=
  Multicoequalizer.desc _ _ (fun i ↦ TopCat.ofHom ⟨e i, (he i).continuous⟩) (by
    rintro ⟨i, j⟩
    ext x
    change e i x.1 = e j (transition U e he i j x)
    exact (map_transition U e he i j x).symm)

@[simp, elementwise nosimp]
public theorem ι_gluedTo (i : J) :
    (glueData U e he).toGlueData.ι i ≫ gluedTo U e he =
      TopCat.ofHom ⟨e i, (he i).continuous⟩ :=
  Multicoequalizer.π_desc _ _ _ _ _

set_option backward.isDefEq.respectTransparency.types false in
/-- The canonical map is injective. -/
public theorem gluedTo_injective : Function.Injective (gluedTo U e he) := by
  intro x y hxy
  obtain ⟨i, xi, rfl⟩ := (glueData U e he).ι_jointly_surjective x
  obtain ⟨j, yj, rfl⟩ := (glueData U e he).ι_jointly_surjective y
  rw [ι_gluedTo_apply, ι_gluedTo_apply] at hxy
  rw [(glueData U e he).ι_eq_iff_rel]
  let z : overlap U e he i j := ⟨xi, ⟨yj, hxy.symm⟩⟩
  refine ⟨z, rfl, ?_⟩
  change (transition U e he i j z).1 = yj
  apply (he j).injective
  exact (map_transition U e he i j z).trans hxy

set_option backward.isDefEq.respectTransparency false in
/-- The canonical map is open. -/
public theorem gluedTo_isOpenMap : IsOpenMap (gluedTo U e he) := by
  intro s hs
  rw [(glueData U e he).isOpen_iff] at hs
  rw [isOpen_iff_forall_mem_open]
  rintro _ ⟨x, hx, rfl⟩
  obtain ⟨i, xi, rfl⟩ := (glueData U e he).ι_jointly_surjective x
  change J at i
  change U i at xi
  refine ⟨gluedTo U e he '' s ∩ Set.range (e i), Set.inter_subset_left, ?_, ?_⟩
  · rw [← Set.image_preimage_eq_inter_range]
    apply (he i).isOpenMap
    have hsi : IsOpen (pieceInclusion U e he i ⁻¹' s) := by
      simpa only [pieceInclusion, glueData, TopCat.GlueData.mk', mkCore] using hs i
    convert hsi using 1
    ext x
    rw [Set.mem_preimage, Set.mem_preimage]
    constructor
    · rintro ⟨q, hqs, hq⟩
      have hqx : q = pieceInclusion U e he i x := by
        apply gluedTo_injective U e he
        unfold pieceInclusion
        exact hq.trans (ι_gluedTo_apply U e he i x).symm
      exact hqx ▸ hqs
    · intro hx
      exact ⟨pieceInclusion U e he i x, hx, ι_gluedTo_apply U e he i x⟩
  · constructor
    · exact Set.mem_image_of_mem _ hx
    · rw [ι_gluedTo_apply]
      exact Set.mem_range_self xi

/-- The range of the canonical map is the union of the ranges of the pieces. -/
public theorem range_gluedTo :
    Set.range (gluedTo U e he) = ⋃ i, Set.range (e i) := by
  ext x
  constructor
  · rintro ⟨q, rfl⟩
    obtain ⟨i, y, rfl⟩ := (glueData U e he).ι_jointly_surjective q
    rw [ι_gluedTo_apply]
    exact Set.subset_iUnion (fun i ↦ Set.range (e i)) i ⟨y, rfl⟩
  · rintro ⟨_, ⟨i, rfl⟩, y, rfl⟩
    exact ⟨(glueData U e he).toGlueData.ι i y, ι_gluedTo_apply U e he i y⟩

/-- A jointly surjective family of open embeddings presents its target as their open gluing. -/
public def glueHomeomorph (hcover : ⋃ i, Set.range (e i) = Set.univ) :
    (glueData U e he).toGlueData.glued ≃ₜ X :=
  Equiv.toHomeomorphOfContinuousOpen
    (Equiv.ofBijective (gluedTo U e he)
      ⟨gluedTo_injective U e he,
        Set.range_eq_univ.mp ((range_gluedTo U e he).symm ▸ hcover)⟩)
    (gluedTo U e he).hom.continuous (gluedTo_isOpenMap U e he)

@[simp]
public theorem glueHomeomorph_ι (hcover : ⋃ i, Set.range (e i) = Set.univ)
    (i : J) (x : U i) :
    glueHomeomorph U e he hcover ((glueData U e he).toGlueData.ι i x) = e i x :=
  ι_gluedTo_apply U e he i x

end OpenEmbeddingGluing
end SphereSixComplex
