module

public import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
public import Mathlib.Topology.UnitInterval

/-!
# Fundamental-group generation from an open cover

This file proves the generation part of the Seifert--van Kampen argument directly from compact
subdivision of the unit interval.  If every member of an open cover contains the chosen basepoint
and every pairwise intersection is path connected, then the fundamental group is generated by
the classes of based loops contained in single cover members.

Only generation is asserted: no pushout or presentation theorem is assumed.
-/

@[expose] public section

noncomputable section

open Set Function Topology CategoryTheory
open scoped unitInterval

namespace Path

/-- The part of a path between two ordered unit-interval parameters, with its endpoints expressed
by evaluation rather than by the extended path. -/
public def monotoneTruncate {X : Type*} [TopologicalSpace X] {x y : X}
    (γ : Path x y) (a b : unitInterval) (hab : a ≤ b) :
    Path (γ a) (γ b) :=
  (γ.truncateOfLE (show (a : ℝ) ≤ b from hab)).cast
    (γ.extend_extends' a).symm (γ.extend_extends' b).symm

@[simp]
public theorem monotoneTruncate_apply {X : Type*} [TopologicalSpace X] {x y : X}
    (γ : Path x y) (a b t : unitInterval) (hab : a ≤ b) :
    γ.monotoneTruncate a b hab t =
      γ ⟨min (max (t : ℝ) (a : ℝ)) (b : ℝ), by
        constructor
        · exact a.2.1.trans (le_min (le_max_right _ _) hab)
        · exact (min_le_right _ _).trans b.2.2⟩ := by
  simp only [monotoneTruncate, cast_coe, truncateOfLE, truncate]
  change γ.extend (min (max (t : ℝ) (a : ℝ)) (b : ℝ)) = _
  simpa only using γ.extend_extends'
    (⟨min (max (t : ℝ) (a : ℝ)) (b : ℝ), by
      constructor
      · exact a.2.1.trans (le_min (le_max_right _ _) hab)
      · exact (min_le_right _ _).trans b.2.2⟩ : unitInterval)

/-- A monotone truncation stays in any set containing the corresponding parameter interval. -/
public theorem monotoneTruncate_mem {X : Type*} [TopologicalSpace X] {x y : X}
    (γ : Path x y) (a b : unitInterval) (hab : a ≤ b) (U : Set X)
    (hU : ∀ s ∈ Set.Icc a b, γ s ∈ U) (t : unitInterval) :
    γ.monotoneTruncate a b hab t ∈ U := by
  rw [monotoneTruncate_apply]
  apply hU
  constructor
  · exact le_min (le_max_right _ _) hab
  · change min (max (t : ℝ) (a : ℝ)) (b : ℝ) ≤ (b : ℝ)
    exact min_le_right _ _

public def splitSchedule (b c t : unitInterval) : ℝ :=
  if (t : ℝ) ≤ 1 / 2 then min (2 * (t : ℝ)) (b : ℝ)
  else min (max (2 * (t : ℝ) - 1) (b : ℝ)) (c : ℝ)

public theorem continuous_splitSchedule (b c : unitInterval) (hbc : b ≤ c) :
    Continuous (splitSchedule b c) := by
  apply continuous_if_le continuous_subtype_val continuous_const
  · fun_prop
  · fun_prop
  · intro t ht
    have ht' : (t : ℝ) = 1 / 2 := by linarith
    norm_num [ht']
    have hbc' : (b : ℝ) ≤ (c : ℝ) := hbc
    rw [min_eq_right b.2.2, max_eq_right b.2.1]
    exact (min_eq_left hbc').symm

public def prefixSchedule (c t : unitInterval) : ℝ := min (t : ℝ) (c : ℝ)

public theorem continuous_prefixSchedule (c : unitInterval) :
    Continuous (prefixSchedule c) :=
  continuous_subtype_val.min continuous_const

public def splitBlend (b c : unitInterval) (u : unitInterval × unitInterval) : ℝ :=
  (1 - (u.1 : ℝ)) * splitSchedule b c u.2 +
    (u.1 : ℝ) * prefixSchedule c u.2

public theorem continuous_splitBlend (b c : unitInterval) (hbc : b ≤ c) :
    Continuous (splitBlend b c) := by
  unfold splitBlend
  have hu : Continuous (fun u : unitInterval × unitInterval ↦ (u.1 : ℝ)) :=
    continuous_subtype_val.comp continuous_fst
  have hs : Continuous (fun u : unitInterval × unitInterval ↦ splitSchedule b c u.2) :=
    (continuous_splitSchedule b c hbc).comp continuous_snd
  have hp : Continuous (fun u : unitInterval × unitInterval ↦ prefixSchedule c u.2) :=
    (continuous_prefixSchedule c).comp continuous_snd
  exact ((continuous_const.sub hu).mul hs).add (hu.mul hp)

/-- Concatenating a prefix with the next monotone truncation is homotopic, relative endpoints, to
the longer prefix. -/
public def monotoneTruncatePrefixTransHomotopy
    {X : Type*} [TopologicalSpace X] {x y : X}
    (γ : Path x y) (b c : unitInterval) (hbc : b ≤ c) :
    Homotopy
      ((γ.monotoneTruncate 0 b (unitInterval.nonneg b)).trans
        (γ.monotoneTruncate b c hbc))
      (γ.monotoneTruncate 0 c (unitInterval.nonneg c)) where
  toFun u := γ.extend (splitBlend b c u)
  continuous_toFun := γ.continuous_extend.comp (continuous_splitBlend b c hbc)
  map_zero_left t := by
    change γ.extend (splitBlend b c (0, t)) =
      ((γ.monotoneTruncate 0 b (unitInterval.nonneg b)).trans
        (γ.monotoneTruncate b c hbc)) t
    simp only [splitBlend]
    rw [Path.trans_apply]
    split_ifs with ht
    · rw [monotoneTruncate_apply]
      norm_num [splitBlend]
      simp only [splitSchedule, ht, ↓reduceIte]
      let v : unitInterval := ⟨min (2 * (t : ℝ)) (b : ℝ), by
          constructor
          · exact le_min
              (mul_nonneg (by norm_num : (0 : ℝ) ≤ 2) t.2.1) b.2.1
          · exact (min_le_right _ _).trans b.2.2⟩
      calc
        γ.extend (min (2 * (t : ℝ)) (b : ℝ)) = γ v := γ.extend_extends' v
        _ = _ := congrArg γ (Subtype.ext (by
          dsimp only [v]
          rw [max_eq_left
            (mul_nonneg (by norm_num : (0 : ℝ) ≤ 2) t.2.1)]))
    · rw [monotoneTruncate_apply]
      norm_num [splitBlend]
      simp only [splitSchedule, ht, ↓reduceIte]
      simpa only using γ.extend_extends'
        (⟨min (max (2 * (t : ℝ) - 1) (b : ℝ)) (c : ℝ), by
          constructor
          · exact b.2.1.trans (le_min (le_max_right _ _) hbc)
          · exact (min_le_right _ _).trans c.2.2⟩ : unitInterval)
  map_one_left t := by
    change γ.extend (splitBlend b c (1, t)) =
      (γ.monotoneTruncate 0 c (unitInterval.nonneg c)) t
    simp only [splitBlend]
    rw [monotoneTruncate_apply]
    norm_num [splitBlend]
    simp only [prefixSchedule]
    let v : unitInterval := ⟨min (t : ℝ) (c : ℝ), by
        constructor
        · exact le_min t.2.1 c.2.1
        · exact (min_le_right _ _).trans c.2.2⟩
    calc
      γ.extend (min (t : ℝ) (c : ℝ)) = γ v := γ.extend_extends' v
      _ = _ := congrArg γ (Subtype.ext (by
        dsimp only [v]
        rw [max_eq_left t.2.1]))
  prop' u t ht := by
    rcases ht with rfl | ht
    · change γ.extend (splitBlend b c (u, 0)) =
        ((γ.monotoneTruncate 0 b (unitInterval.nonneg b)).trans
          (γ.monotoneTruncate b c hbc)) 0
      rw [Path.source]
      rw [show splitBlend b c (u, 0) = 0 by
        simp [splitBlend, splitSchedule, prefixSchedule,
          min_eq_left b.2.1, min_eq_left c.2.1]]
      exact γ.extend_extends' 0
    · rw [Set.mem_singleton_iff] at ht
      subst t
      change γ.extend (splitBlend b c (u, 1)) =
        ((γ.monotoneTruncate 0 b (unitInterval.nonneg b)).trans
          (γ.monotoneTruncate b c hbc)) 1
      rw [Path.target]
      rw [show splitBlend b c (u, 1) = c by
        norm_num [splitBlend, splitSchedule, prefixSchedule,
          min_eq_right c.2.2, max_eq_left b.2.2]
        ring]
      exact γ.extend_extends' c

end Path

namespace SphereSixComplex.Topology

/-- Regard a based loop as its fundamental-group class. -/
public def openCoverLoopClass {X : Type*} [TopologicalSpace X] {b : X}
    (L : Path b b) : FundamentalGroup X b :=
  Path.Homotopic.Quotient.mk L

/-- Classes represented by loops contained in one member of a specified cover. -/
public def openCoverLoopClasses {X ι : Type*} [TopologicalSpace X]
    (U : ι → Set X) (b : X) : Set (FundamentalGroup X b) :=
  {g | ∃ (i : ι) (L : Path b b), Set.range L ⊆ U i ∧ openCoverLoopClass L = g}

/-- A based loop whose range lies in the image of an open embedding lifts to a based loop in
the source, so its class belongs to the range of the induced fundamental-group map. -/
public theorem openEmbedding_loopClass_mem_fundamentalGroupMap_range
    {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : C(X, Y)) (hf : IsOpenEmbedding f) (x : X)
    (L : Path (f x) (f x)) (hL : Set.range L ⊆ Set.range f) :
    openCoverLoopClass L ∈ (FundamentalGroup.map f x).range := by
  let R : Set Y := Set.range f
  let e : X ≃ₜ R := hf.isEmbedding.toHomeomorph
  let bR : R := ⟨f x, ⟨x, rfl⟩⟩
  let LR : Path bR bR :=
    { toFun := fun t ↦ ⟨L t, hL ⟨t, rfl⟩⟩
      continuous_toFun :=
        Continuous.subtype_mk L.continuous fun t ↦ hL ⟨t, rfl⟩
      source' := Subtype.ext L.source
      target' := Subtype.ext L.target }
  have hb : bR = e x := by
    apply Subtype.ext
    exact (Topology.IsEmbedding.toHomeomorph_apply_coe hf.isEmbedding x).symm
  have hx : e.symm bR = x := by
    rw [hb, e.symm_apply_apply]
  let LX : Path x x := (LR.map e.symm.continuous).cast hx.symm hx.symm
  refine ⟨openCoverLoopClass LX, ?_⟩
  change Path.Homotopic.Quotient.map
      (Path.Homotopic.Quotient.mk LX) f = Path.Homotopic.Quotient.mk L
  rw [← Path.Homotopic.Quotient.mk_map]
  apply congrArg Path.Homotopic.Quotient.mk
  apply Path.ext
  funext t
  change f (e.symm (LR t)) = L t
  calc
    f (e.symm (LR t)) = (e (e.symm (LR t))).1 :=
      (Topology.IsEmbedding.toHomeomorph_apply_coe hf.isEmbedding _).symm
    _ = (LR t).1 := congrArg Subtype.val (e.apply_symm_apply (LR t))
    _ = L t := rfl

/-- The preceding lifting result with a propositionally named target basepoint. -/
public theorem openEmbedding_loopClass_mem_fundamentalGroupMapOfEq_range
    {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : C(X, Y)) (hf : IsOpenEmbedding f) (x : X) (y : Y)
    (hxy : f x = y) (L : Path y y) (hL : Set.range L ⊆ Set.range f) :
    openCoverLoopClass L ∈ (FundamentalGroup.mapOfEq f hxy).range := by
  let L' : Path (f x) (f x) := L.cast hxy hxy
  have hL' : Set.range L' ⊆ Set.range f := by
    intro z hz
    obtain ⟨t, rfl⟩ := hz
    exact hL ⟨t, rfl⟩
  obtain ⟨q, hq⟩ :=
    openEmbedding_loopClass_mem_fundamentalGroupMap_range f hf x L' hL'
  refine ⟨q, ?_⟩
  rw [FundamentalGroup.mapOfEq_apply]
  change Path.Homotopic.Quotient.map q f = openCoverLoopClass L' at hq
  rw [hq]
  unfold openCoverLoopClass
  change (Path.Homotopic.Quotient.mk L').cast hxy.symm hxy.symm =
    Path.Homotopic.Quotient.mk L
  dsimp only [L']
  rw [Path.Homotopic.Quotient.mk_cast,
    Path.Homotopic.Quotient.cast_cast]
  simp

/-- Multiplication of successive rebased path segments cancels their common reference path. -/
public theorem basedSegmentLoop_mul_prefix
    {X : Type*} [TopologicalSpace X] {b x y : X}
    (p q : Path b x) (s : Path x y) (r : Path b y) :
    openCoverLoopClass (q.trans (s.trans r.symm)) *
        openCoverLoopClass (p.trans q.symm) =
      openCoverLoopClass ((p.trans s).trans r.symm) := by
  simp only [openCoverLoopClass, FundamentalGroup.mul_def,
    Path.Homotopic.Quotient.mk_trans, Path.Homotopic.Quotient.mk_symm]
  simp only [Path.Homotopic.Quotient.trans_assoc]
  rw [← Path.Homotopic.Quotient.trans_assoc
      (Path.Homotopic.Quotient.symm (Path.Homotopic.Quotient.mk q))
      (Path.Homotopic.Quotient.mk q),
    Path.Homotopic.Quotient.symm_trans,
    Path.Homotopic.Quotient.refl_trans]

public theorem castPath_trans_castRefl_symm_class
    {X : Type*} [TopologicalSpace X] {b y : X}
    (p : Path b b) (h : y = b) :
    openCoverLoopClass
        ((p.cast rfl h).trans (((Path.refl b).cast rfl h).symm)) =
      openCoverLoopClass p := by
  have hp : (p.cast rfl h).trans (((Path.refl b).cast rfl h).symm) =
      p.trans (Path.refl b) := by
    apply Path.ext
    funext s
    rw [Path.trans_apply, Path.trans_apply]
    split_ifs
    · simp only [Path.cast_coe]
    · rfl
  rw [hp]
  unfold openCoverLoopClass
  exact Path.Homotopic.Quotient.eq.mpr (Path.Homotopic.trans_refl p)

/-- Reversing a composite path class reverses the order of its factors. -/
public theorem quotient_symm_trans
    {X : Type*} [TopologicalSpace X] {x y z : X}
    (p : Path.Homotopic.Quotient x y) (q : Path.Homotopic.Quotient y z) :
    (p.trans q).symm = q.symm.trans p.symm := by
  let p' : (FundamentalGroupoid.mk x ⟶ FundamentalGroupoid.mk y) := p
  let q' : (FundamentalGroupoid.mk y ⟶ FundamentalGroupoid.mk z) := q
  change CategoryTheory.Groupoid.inv (p' ≫ q') =
    CategoryTheory.Groupoid.inv q' ≫ CategoryTheory.Groupoid.inv p'
  simp only [CategoryTheory.Groupoid.inv_eq_inv]
  exact CategoryTheory.IsIso.inv_comp (f := p') (h := q')

/-- If an open cover has a common basepoint and all pairwise intersections are path connected,
then loops contained in individual cover members generate the entire fundamental group. -/
public theorem openCoverLoopClasses_generate
    {X ι : Type*} [TopologicalSpace X]
    (U : ι → Set X) (b : X)
    (hopen : ∀ i, IsOpen (U i))
    (hcover : Set.univ ⊆ ⋃ i, U i)
    (hb : ∀ i, b ∈ U i)
    (hpair : ∀ i j, IsPathConnected (U i ∩ U j)) :
    Subgroup.closure (openCoverLoopClasses U b) = ⊤ := by
  apply top_unique
  intro g _
  induction g using Quotient.ind with
  | _ γ =>
    let H : Subgroup (FundamentalGroup X b) :=
      Subgroup.closure (openCoverLoopClasses U b)
    obtain ⟨t, ht0, htmono, ⟨m, hm⟩, hpart⟩ :=
      exists_monotone_Icc_subset_open_cover_unitInterval
        (c := fun i ↦ γ ⁻¹' U i)
        (fun i ↦ (hopen i).preimage γ.continuous)
        (by
          intro s _
          have hs := hcover (Set.mem_univ (γ s))
          rw [Set.mem_iUnion] at hs ⊢
          obtain ⟨i, hi⟩ := hs
          exact ⟨i, hi⟩)
    let k : ℕ → ι := fun n ↦ Classical.choose (hpart n)
    have hk (n : ℕ) : Set.Icc (t n) (t (n + 1)) ⊆ γ ⁻¹' U (k n) :=
      Classical.choose_spec (hpart n)
    have hmpos : 0 < m := by
      by_contra h
      have hm0 : m = 0 := Nat.eq_zero_of_not_pos h
      have h01 : (0 : unitInterval) = 1 := by
        rw [← ht0]
        simpa [hm0] using hm m le_rfl
      exact zero_ne_one h01
    let pre (n : ℕ) : Path b (γ (t n)) :=
      (γ.monotoneTruncate 0 (t n) (unitInterval.nonneg (t n))).cast
        γ.source.symm rfl
    have hpre_step (n : ℕ) :
        Path.Homotopic.Quotient.mk
            ((pre n).trans
              (γ.monotoneTruncate (t n) (t (n + 1))
                (htmono (Nat.le_succ n)))) =
          Path.Homotopic.Quotient.mk (pre (n + 1)) := by
      apply Path.Homotopic.Quotient.eq.mpr
      exact ⟨(Path.monotoneTruncatePrefixTransHomotopy γ
        (t n) (t (n + 1)) (htmono (Nat.le_succ n))).pathCast
          γ.source.symm rfl⟩
    have hprefix : ∀ n, n ≤ m →
        ∃ q : Path b (γ (t n)),
          openCoverLoopClass ((pre n).trans q.symm) ∈ H ∧
          ((n < m ∧ Set.range q ⊆ U (k n)) ∨
            (n = m ∧ ∀ s, q s = b)) := by
      intro n hn
      induction n with
      | zero =>
          have htpoint : γ (t 0) = b := by
            rw [ht0]
            exact γ.source
          let q : Path b (γ (t 0)) := (Path.refl b).cast rfl htpoint
          have hpq : pre 0 = q := by
            apply Path.ext
            funext s
            change γ.monotoneTruncate 0 (t 0) (unitInterval.nonneg (t 0)) s = q s
            rw [Path.monotoneTruncate_apply]
            let u : unitInterval :=
              ⟨min (max (s : ℝ) 0) (t 0 : ℝ), by
                constructor
                · exact le_min (le_max_right _ _) (unitInterval.nonneg (t 0))
                · exact (min_le_right _ _).trans (t 0).2.2⟩
            change γ u = b
            have hu : u = t 0 := by
              apply Subtype.ext
              dsimp only [u]
              rw [ht0]
              simp
            rw [hu]
            exact htpoint
          refine ⟨q, ?_, Or.inl ⟨hmpos, ?_⟩⟩
          · rw [hpq]
            change Path.Homotopic.Quotient.mk (q.trans q.symm) ∈ H
            rw [Path.Homotopic.Quotient.mk_trans,
              Path.Homotopic.Quotient.mk_symm,
              Path.Homotopic.Quotient.trans_symm]
            exact H.one_mem
          · intro z hz
            obtain ⟨s, rfl⟩ := hz
            change b ∈ U (k 0)
            exact hb (k 0)
      | succ n ih =>
          have hnlt : n < m := by omega
          obtain ⟨q, hqH, hqstate⟩ := ih (Nat.le_of_lt hnlt)
          have hqrange : Set.range q ⊆ U (k n) := by
            rcases hqstate with hqstate | hqstate
            · exact hqstate.2
            · omega
          let seg : Path (γ (t n)) (γ (t (n + 1))) :=
            γ.monotoneTruncate (t n) (t (n + 1))
              (htmono (Nat.le_succ n))
          have hseg : Set.range seg ⊆ U (k n) := by
            intro z hz
            obtain ⟨s, rfl⟩ := hz
            exact Path.monotoneTruncate_mem γ (t n) (t (n + 1))
              (htmono (Nat.le_succ n)) (U (k n))
              (fun u hu ↦ hk n hu) s
          have finish (r : Path b (γ (t (n + 1))))
              (hrange : Set.range r ⊆ U (k n))
              (hrstate : ((n + 1 < m ∧ Set.range r ⊆ U (k (n + 1))) ∨
                (n + 1 = m ∧ ∀ s, r s = b))) :
              ∃ q' : Path b (γ (t (n + 1))),
                openCoverLoopClass ((pre (n + 1)).trans q'.symm) ∈ H ∧
                ((n + 1 < m ∧ Set.range q' ⊆ U (k (n + 1))) ∨
                  (n + 1 = m ∧ ∀ s, q' s = b)) := by
            let leaf : Path b b := q.trans (seg.trans r.symm)
            have hleafRange : Set.range leaf ⊆ U (k n) := by
              rw [show Set.range leaf =
                  Set.range q ∪ (Set.range seg ∪ Set.range r) by
                simp [leaf, Path.trans_range, Path.symm_range]]
              exact Set.union_subset hqrange (Set.union_subset hseg hrange)
            have hleaf : openCoverLoopClass leaf ∈ H :=
              Subgroup.subset_closure ⟨k n, leaf, hleafRange, rfl⟩
            have hmul := H.mul_mem hleaf hqH
            rw [show openCoverLoopClass leaf *
                  openCoverLoopClass ((pre n).trans q.symm) =
                openCoverLoopClass (((pre n).trans seg).trans r.symm) by
              exact basedSegmentLoop_mul_prefix (pre n) q seg r] at hmul
            have hnext : openCoverLoopClass (((pre n).trans seg).trans r.symm) =
                openCoverLoopClass ((pre (n + 1)).trans r.symm) := by
              unfold openCoverLoopClass
              apply Path.Homotopic.Quotient.eq.mpr
              have hs : ((pre n).trans seg).Homotopic (pre (n + 1)) :=
                Path.Homotopic.Quotient.eq.mp (hpre_step n)
              exact hs.hcomp (Path.Homotopic.refl r.symm)
            rw [hnext] at hmul
            exact ⟨r, hmul, hrstate⟩
          by_cases heq : n + 1 = m
          · have htpoint : γ (t (n + 1)) = b := by
              rw [heq, hm m (by rfl)]
              exact γ.target
            let r : Path b (γ (t (n + 1))) :=
              (Path.refl b).cast rfl htpoint
            refine finish r ?_ ?_
            · intro z hz
              obtain ⟨s, rfl⟩ := hz
              change b ∈ U (k n)
              exact hb (k n)
            · exact Or.inr ⟨heq, fun s ↦ by rfl⟩
          · have hsucc : n + 1 < m := by omega
            have hpointLeft : γ (t (n + 1)) ∈ U (k n) :=
              hk n ⟨htmono (Nat.le_succ n), le_rfl⟩
            have hpointRight : γ (t (n + 1)) ∈ U (k (n + 1)) :=
              hk (n + 1) ⟨le_rfl, htmono (Nat.le_succ (n + 1))⟩
            let J : JoinedIn (U (k n) ∩ U (k (n + 1))) b (γ (t (n + 1))) :=
              (hpair (k n) (k (n + 1))).joinedIn
                (x := b) (y := γ (t (n + 1)))
                ⟨hb (k n), hb (k (n + 1))⟩
                ⟨hpointLeft, hpointRight⟩
            let r : Path b (γ (t (n + 1))) := J.somePath
            refine finish r ?_ ?_
            · intro z hz
              obtain ⟨s, rfl⟩ := hz
              exact (J.somePath_mem s).1
            · exact Or.inl ⟨hsucc, by
                intro z hz
                obtain ⟨s, rfl⟩ := hz
                exact (J.somePath_mem s).2⟩
    obtain ⟨q, hqH, hqstate⟩ := hprefix m le_rfl
    have hqconst : ∀ s, q s = b := by
      rcases hqstate with hqstate | hqstate
      · omega
      · exact hqstate.2
    have htm : t m = 1 := hm m le_rfl
    have hq : q = (Path.refl b).cast rfl (by
        rw [htm]
        exact γ.target) := by
      apply Path.ext
      funext s
      simpa using hqconst s
    have hpre : pre m = γ.cast rfl (by
        rw [htm]
        exact γ.target) := by
      apply Path.ext
      funext s
      change γ.monotoneTruncate 0 (t m) (unitInterval.nonneg (t m)) s = γ s
      rw [Path.monotoneTruncate_apply]
      apply congrArg γ
      apply Subtype.ext
      rw [htm]
      simp [s.2.1, s.2.2]
    change openCoverLoopClass γ ∈ H
    rw [hq, hpre] at hqH
    rw [castPath_trans_castRefl_symm_class γ] at hqH
    exact hqH

/-! ## Loops in a union of two open subsets -/

/-- Classes represented by loops contained in either of two specified subsets. -/
public def binaryOpenCoverLoopClasses {X : Type*} [TopologicalSpace X]
    (U V : Set X) (b : X) : Set (FundamentalGroup X b) :=
  {g | ∃ L : Path b b,
    (Set.range L ⊆ U ∨ Set.range L ⊆ V) ∧ openCoverLoopClass L = g}

/-- A loop contained in the union of two path-connected open subsets is generated by loops in
the individual subsets, provided the basepoint lies in both and their intersection is path
connected.  The ambient space need not be covered: the ordinary open-cover theorem is applied to
the subtype `U ∪ V` and then mapped back to the ambient fundamental group. -/
public theorem binaryOpenCoverLoopClass_mem_closure
    {X : Type*} [TopologicalSpace X]
    (U V : Set X) (b : X)
    (hopenU : IsOpen U) (hopenV : IsOpen V)
    (hbU : b ∈ U) (hbV : b ∈ V)
    (hU : IsPathConnected U) (hV : IsPathConnected V)
    (hUV : IsPathConnected (U ∩ V))
    (L : Path b b) (hL : Set.range L ⊆ U ∪ V) :
    openCoverLoopClass L ∈ Subgroup.closure (binaryOpenCoverLoopClasses U V b) := by
  let R : Set X := U ∪ V
  let bR : R := ⟨b, Or.inl hbU⟩
  let LR : Path bR bR :=
    { toFun := fun t ↦ ⟨L t, hL ⟨t, rfl⟩⟩
      continuous_toFun := Continuous.subtype_mk L.continuous fun _ ↦ hL ⟨_, rfl⟩
      source' := Subtype.ext L.source
      target' := Subtype.ext L.target }
  let W : Bool → Set R
    | false => {x | x.1 ∈ U}
    | true => {x | x.1 ∈ V}
  have hopenW : ∀ i, IsOpen (W i) := by
    intro i
    cases i
    · exact hopenU.preimage continuous_subtype_val
    · exact hopenV.preimage continuous_subtype_val
  have hcoverW : Set.univ ⊆ ⋃ i, W i := by
    intro x _
    rcases x.2 with hx | hx
    · exact Set.mem_iUnion.2 ⟨false, hx⟩
    · exact Set.mem_iUnion.2 ⟨true, hx⟩
  have hbW : ∀ i, bR ∈ W i := by
    intro i
    cases i
    · exact hbU
    · exact hbV
  have hUR : IsPathConnected (W false) := by
    rw [IsInducing.subtypeVal.isPathConnected_iff]
    simpa [W, R] using hU
  have hVR : IsPathConnected (W true) := by
    rw [IsInducing.subtypeVal.isPathConnected_iff]
    simpa [W, R] using hV
  have hUVR : IsPathConnected (W false ∩ W true) := by
    rw [IsInducing.subtypeVal.isPathConnected_iff]
    simpa [W, R, Set.image_image] using hUV
  have hpairW : ∀ i j, IsPathConnected (W i ∩ W j) := by
    intro i j
    cases i <;> cases j
    · simpa using hUR
    · exact hUVR
    · simpa [Set.inter_comm] using hUVR
    · simpa using hVR
  have hgenerate := openCoverLoopClasses_generate W bR hopenW hcoverW hbW hpairW
  let inc : C(R, X) := ⟨Subtype.val, continuous_subtype_val⟩
  let f := FundamentalGroup.map inc bR
  let H : Subgroup (FundamentalGroup X b) :=
    Subgroup.closure (binaryOpenCoverLoopClasses U V b)
  have hle : Subgroup.closure (openCoverLoopClasses W bR) ≤ H.comap f := by
    apply (Subgroup.closure_le _).2
    intro q hq
    obtain ⟨i, P, hP, rfl⟩ := hq
    change f (openCoverLoopClass P) ∈ H
    change Path.Homotopic.Quotient.map (Path.Homotopic.Quotient.mk P) inc ∈ H
    rw [← Path.Homotopic.Quotient.mk_map]
    apply Subgroup.subset_closure
    cases i
    · refine ⟨P.map continuous_subtype_val, Or.inl ?_, rfl⟩
      intro x hx
      obtain ⟨t, rfl⟩ := hx
      simpa [W] using hP ⟨t, rfl⟩
    · refine ⟨P.map continuous_subtype_val, Or.inr ?_, rfl⟩
      intro x hx
      obtain ⟨t, rfl⟩ := hx
      simpa [W] using hP ⟨t, rfl⟩
  rw [hgenerate] at hle
  have hLR : openCoverLoopClass LR ∈ H.comap f := hle (by trivial)
  change f (openCoverLoopClass LR) ∈ H at hLR
  change Path.Homotopic.Quotient.map (Path.Homotopic.Quotient.mk LR) inc ∈ H at hLR
  rw [← Path.Homotopic.Quotient.mk_map] at hLR
  have hpath : LR.map continuous_subtype_val = L := by
    apply Path.ext
    funext t
    rfl
  rw [hpath] at hLR
  exact hLR

/-! ## Generation for a rooted star cover -/

/-- Loop classes contributed by a rooted star cover.  A root loop is based at the global
basepoint and stays in the root member.  A leaf loop is based at a point of the corresponding
root--leaf overlap and is transported to the global basepoint along a path in the root. -/
public def rootedStarCoverLoopClasses {X ι : Type*} [TopologicalSpace X]
    (R : Set X) (V : ι → Set X) (b : X) : Set (FundamentalGroup X b) :=
  {g | (∃ L : Path b b, Set.range L ⊆ R ∧ openCoverLoopClass L = g) ∨
    ∃ (i : ι) (x : X), x ∈ R ∩ V i ∧
      ∃ (W : Path b x) (L : Path x x),
        Set.range W ⊆ R ∧ Set.range L ⊆ V i ∧
          openCoverLoopClass (W.trans (L.trans W.symm)) = g}

/-- A rooted open star cover generates the fundamental group by root loops and leaf loops
whiskered through the root.  Distinct leaves are required to be disjoint, exactly as in a star
gluing; connected root--leaf overlaps supply coherent changes between root and leaf paths. -/
public theorem rootedStarCoverLoopClasses_generate
    {X ι : Type*} [TopologicalSpace X]
    (R : Set X) (V : ι → Set X) (b : X)
    (hopenR : IsOpen R) (hopenV : ∀ i, IsOpen (V i))
    (hcover : Set.univ ⊆ R ∪ ⋃ i, V i)
    (hbR : b ∈ R) (hbV : ∀ i, b ∉ V i)
    (hR : IsPathConnected R) (hV : ∀ i, IsPathConnected (V i))
    (hoverlap : ∀ i, IsPathConnected (R ∩ V i))
    (hdisjoint : ∀ i j, i ≠ j → Disjoint (V i) (V j)) :
    Subgroup.closure (rootedStarCoverLoopClasses R V b) = ⊤ := by
  let U : Option ι → Set X
    | none => R
    | some i => V i
  have hopen : ∀ i, IsOpen (U i) := by
    intro i
    cases i with
    | none => exact hopenR
    | some i => exact hopenV i
  have hUcover : Set.univ ⊆ ⋃ i, U i := by
    intro x _
    have hx := hcover (Set.mem_univ x)
    rcases hx with hx | hx
    · exact Set.mem_iUnion.2 ⟨none, hx⟩
    · rw [Set.mem_iUnion] at hx
      obtain ⟨i, hi⟩ := hx
      exact Set.mem_iUnion.2 ⟨some i, hi⟩
  let a : ι → X := fun i => Classical.choose (hoverlap i).nonempty
  have ha (i : ι) : a i ∈ R ∩ V i := Classical.choose_spec (hoverlap i).nonempty
  let w : ∀ i, Path b (a i) := fun i =>
    (hR.joinedIn (x := b) (y := a i) hbR (ha i).1).somePath
  have hw (i : ι) : Set.range (w i) ⊆ R := by
    intro x hx
    obtain ⟨t, rfl⟩ := hx
    exact (hR.joinedIn (x := b) (y := a i) hbR (ha i).1).somePath_mem t
  apply top_unique
  intro g _
  induction g using Quotient.ind with
  | _ γ =>
    let H : Subgroup (FundamentalGroup X b) :=
      Subgroup.closure (rootedStarCoverLoopClasses R V b)
    obtain ⟨t, ht0, htmono, ⟨m, hm⟩, hpart⟩ :=
      exists_monotone_Icc_subset_open_cover_unitInterval
        (c := fun i => γ ⁻¹' U i)
        (fun i => (hopen i).preimage γ.continuous)
        (by
          intro s _
          have hs := hUcover (Set.mem_univ (γ s))
          rw [Set.mem_iUnion] at hs ⊢
          obtain ⟨i, hi⟩ := hs
          exact ⟨i, hi⟩)
    let k : ℕ → Option ι := fun n => Classical.choose (hpart n)
    have hk (n : ℕ) : Set.Icc (t n) (t (n + 1)) ⊆ γ ⁻¹' U (k n) :=
      Classical.choose_spec (hpart n)
    have hmpos : 0 < m := by
      by_contra h
      have hm0 : m = 0 := Nat.eq_zero_of_not_pos h
      have h01 : (0 : unitInterval) = 1 := by
        rw [← ht0]
        simpa [hm0] using hm m le_rfl
      exact zero_ne_one h01
    let pre (n : ℕ) : Path b (γ (t n)) :=
      (γ.monotoneTruncate 0 (t n) (unitInterval.nonneg (t n))).cast
        γ.source.symm rfl
    have hpre_step (n : ℕ) :
        Path.Homotopic.Quotient.mk
            ((pre n).trans
              (γ.monotoneTruncate (t n) (t (n + 1))
                (htmono (Nat.le_succ n)))) =
          Path.Homotopic.Quotient.mk (pre (n + 1)) := by
      apply Path.Homotopic.Quotient.eq.mpr
      exact ⟨(Path.monotoneTruncatePrefixTransHomotopy γ
        (t n) (t (n + 1)) (htmono (Nat.le_succ n))).pathCast
          γ.source.symm rfl⟩
    have hprefix : ∀ n, n ≤ m →
        ∃ q : Path b (γ (t n)),
          openCoverLoopClass ((pre n).trans q.symm) ∈ H ∧
          ((n < m ∧
              ((k n = none ∧ Set.range q ⊆ R) ∨
                ∃ i, k n = some i ∧
                  ∃ v : Path (a i) (γ (t n)),
                    q = (w i).trans v ∧ Set.range v ⊆ V i)) ∨
            (n = m ∧ ∀ s, q s = b)) := by
      intro n hn
      induction n with
      | zero =>
          have htpoint : γ (t 0) = b := by
            rw [ht0]
            exact γ.source
          have hkzero : k 0 = none := by
            cases hko : k 0 with
            | none => rfl
            | some i =>
                exfalso
                apply hbV i
                have hmem := hk 0 ⟨le_rfl, htmono (Nat.le_succ 0)⟩
                rw [hko] at hmem
                change γ (t 0) ∈ V i at hmem
                rwa [htpoint] at hmem
          let q : Path b (γ (t 0)) := (Path.refl b).cast rfl htpoint
          have hpq : pre 0 = q := by
            apply Path.ext
            funext s
            change γ.monotoneTruncate 0 (t 0) (unitInterval.nonneg (t 0)) s = q s
            rw [Path.monotoneTruncate_apply]
            let u : unitInterval :=
              ⟨min (max (s : ℝ) 0) (t 0 : ℝ), by
                constructor
                · exact le_min (le_max_right _ _) (unitInterval.nonneg (t 0))
                · exact (min_le_right _ _).trans (t 0).2.2⟩
            change γ u = b
            have hu : u = t 0 := by
              apply Subtype.ext
              dsimp only [u]
              rw [ht0]
              simp
            rw [hu]
            exact htpoint
          refine ⟨q, ?_, Or.inl ⟨hmpos, Or.inl ⟨hkzero, ?_⟩⟩⟩
          · rw [hpq]
            change Path.Homotopic.Quotient.mk (q.trans q.symm) ∈ H
            rw [Path.Homotopic.Quotient.mk_trans,
              Path.Homotopic.Quotient.mk_symm,
              Path.Homotopic.Quotient.trans_symm]
            exact H.one_mem
          · intro x hx
            obtain ⟨s, rfl⟩ := hx
            exact hbR
      | succ n ih =>
          have hnlt : n < m := by omega
          obtain ⟨q, hqH, hqstate⟩ := ih (Nat.le_of_lt hnlt)
          have hqmember :
              (k n = none ∧ Set.range q ⊆ R) ∨
                ∃ i, k n = some i ∧
                  ∃ v : Path (a i) (γ (t n)),
                    q = (w i).trans v ∧ Set.range v ⊆ V i := by
            rcases hqstate with hqstate | hqstate
            · exact hqstate.2
            · omega
          let seg : Path (γ (t n)) (γ (t (n + 1))) :=
            γ.monotoneTruncate (t n) (t (n + 1))
              (htmono (Nat.le_succ n))
          have hseg : Set.range seg ⊆ U (k n) := by
            intro x hx
            obtain ⟨s, rfl⟩ := hx
            exact Path.monotoneTruncate_mem γ (t n) (t (n + 1))
              (htmono (Nat.le_succ n)) (U (k n))
              (fun u hu => hk n hu) s
          have finish (r : Path b (γ (t (n + 1))))
              (hleaf : openCoverLoopClass (q.trans (seg.trans r.symm)) ∈ H)
              (hrstate : ((n + 1 < m ∧
                  ((k (n + 1) = none ∧ Set.range r ⊆ R) ∨
                    ∃ i, k (n + 1) = some i ∧
                      ∃ v : Path (a i) (γ (t (n + 1))),
                        r = (w i).trans v ∧ Set.range v ⊆ V i)) ∨
                (n + 1 = m ∧ ∀ s, r s = b))) :
              ∃ q' : Path b (γ (t (n + 1))),
                openCoverLoopClass ((pre (n + 1)).trans q'.symm) ∈ H ∧
                ((n + 1 < m ∧
                    ((k (n + 1) = none ∧ Set.range q' ⊆ R) ∨
                      ∃ i, k (n + 1) = some i ∧
                        ∃ v : Path (a i) (γ (t (n + 1))),
                          q' = (w i).trans v ∧ Set.range v ⊆ V i)) ∨
                  (n + 1 = m ∧ ∀ s, q' s = b)) := by
            have hmul := H.mul_mem hleaf hqH
            rw [show openCoverLoopClass (q.trans (seg.trans r.symm)) *
                  openCoverLoopClass ((pre n).trans q.symm) =
                openCoverLoopClass (((pre n).trans seg).trans r.symm) by
              exact basedSegmentLoop_mul_prefix (pre n) q seg r] at hmul
            have hnext : openCoverLoopClass (((pre n).trans seg).trans r.symm) =
                openCoverLoopClass ((pre (n + 1)).trans r.symm) := by
              unfold openCoverLoopClass
              apply Path.Homotopic.Quotient.eq.mpr
              have hs : ((pre n).trans seg).Homotopic (pre (n + 1)) :=
                Path.Homotopic.Quotient.eq.mp (hpre_step n)
              exact hs.hcomp (Path.Homotopic.refl r.symm)
            rw [hnext] at hmul
            exact ⟨r, hmul, hrstate⟩
          by_cases heq : n + 1 = m
          · have htpoint : γ (t (n + 1)) = b := by
              rw [heq, hm m (by rfl)]
              exact γ.target
            have hkn : k n = none := by
              rcases hqmember with hroot | hleaf
              · exact hroot.1
              · obtain ⟨i, hki, v, hqv, hv⟩ := hleaf
                exfalso
                apply hbV i
                have hend := hseg ⟨1, seg.target⟩
                rw [hki] at hend
                change γ (t (n + 1)) ∈ V i at hend
                rwa [htpoint] at hend
            obtain ⟨_, hqR⟩ := hqmember.resolve_right (by
              rintro ⟨i, hki, _⟩
              rw [hkn] at hki
              contradiction)
            have hsegR : Set.range seg ⊆ R := by simpa [U, hkn] using hseg
            let r : Path b (γ (t (n + 1))) :=
              (Path.refl b).cast rfl htpoint
            have hrR : Set.range r ⊆ R := by
              intro x hx
              obtain ⟨s, rfl⟩ := hx
              exact hbR
            let leaf : Path b b := q.trans (seg.trans r.symm)
            have hleafRange : Set.range leaf ⊆ R := by
              rw [show Set.range leaf =
                  Set.range q ∪ (Set.range seg ∪ Set.range r) by
                simp [leaf, Path.trans_range, Path.symm_range]]
              exact Set.union_subset hqR (Set.union_subset hsegR hrR)
            have hleafH : openCoverLoopClass leaf ∈ H :=
              Subgroup.subset_closure (Or.inl ⟨leaf, hleafRange, rfl⟩)
            exact finish r hleafH (Or.inr ⟨heq, fun s => by rfl⟩)
          · have hsucc : n + 1 < m := by omega
            have hleft : γ (t (n + 1)) ∈ U (k n) :=
              hk n ⟨htmono (Nat.le_succ n), le_rfl⟩
            have hright : γ (t (n + 1)) ∈ U (k (n + 1)) :=
              hk (n + 1) ⟨le_rfl, htmono (Nat.le_succ (n + 1))⟩
            rcases hqmember with hroot | hleaf
            · obtain ⟨hkn, hqR⟩ := hroot
              cases hnext : k (n + 1) with
              | none =>
                  let J : JoinedIn R b (γ (t (n + 1))) :=
                    hR.joinedIn (x := b) (y := γ (t (n + 1))) hbR
                      (by simpa [U, hnext] using hright)
                  let r : Path b (γ (t (n + 1))) := J.somePath
                  have hrR : Set.range r ⊆ R := by
                    intro x hx
                    obtain ⟨s, rfl⟩ := hx
                    exact J.somePath_mem s
                  have hsegR : Set.range seg ⊆ R := by simpa [U, hkn] using hseg
                  let leaf : Path b b := q.trans (seg.trans r.symm)
                  have hleafRange : Set.range leaf ⊆ R := by
                    rw [show Set.range leaf =
                        Set.range q ∪ (Set.range seg ∪ Set.range r) by
                      simp [leaf, Path.trans_range, Path.symm_range]]
                    exact Set.union_subset hqR (Set.union_subset hsegR hrR)
                  have hleafH : openCoverLoopClass leaf ∈ H :=
                    Subgroup.subset_closure (Or.inl ⟨leaf, hleafRange, rfl⟩)
                  simpa [hnext] using finish r hleafH
                    (Or.inl ⟨hsucc, Or.inl ⟨hnext, hrR⟩⟩)
              | some j =>
                  have hxR : γ (t (n + 1)) ∈ R := by simpa [U, hkn] using hleft
                  have hxV : γ (t (n + 1)) ∈ V j := by simpa [U, hnext] using hright
                  let J : JoinedIn (R ∩ V j) (a j) (γ (t (n + 1))) :=
                    (hoverlap j).joinedIn (x := a j) (y := γ (t (n + 1)))
                      (ha j) ⟨hxR, hxV⟩
                  let v : Path (a j) (γ (t (n + 1))) := J.somePath
                  let r : Path b (γ (t (n + 1))) := (w j).trans v
                  have hvR : Set.range v ⊆ R := by
                    intro x hx
                    obtain ⟨s, rfl⟩ := hx
                    exact (J.somePath_mem s).1
                  have hvV : Set.range v ⊆ V j := by
                    intro x hx
                    obtain ⟨s, rfl⟩ := hx
                    exact (J.somePath_mem s).2
                  have hrR : Set.range r ⊆ R := by
                    rw [show Set.range r = Set.range (w j) ∪ Set.range v by
                      simp [r, Path.trans_range]]
                    exact Set.union_subset (hw j) hvR
                  have hsegR : Set.range seg ⊆ R := by simpa [U, hkn] using hseg
                  let leaf : Path b b := q.trans (seg.trans r.symm)
                  have hleafRange : Set.range leaf ⊆ R := by
                    rw [show Set.range leaf =
                        Set.range q ∪ (Set.range seg ∪ Set.range r) by
                      simp [leaf, Path.trans_range, Path.symm_range]]
                    exact Set.union_subset hqR (Set.union_subset hsegR hrR)
                  have hleafH : openCoverLoopClass leaf ∈ H :=
                    Subgroup.subset_closure (Or.inl ⟨leaf, hleafRange, rfl⟩)
                  simpa [hnext] using finish r hleafH (Or.inl ⟨hsucc, Or.inr
                    ⟨j, hnext, v, rfl, hvV⟩⟩)
            · obtain ⟨i, hkn, v, hqv, hv⟩ := hleaf
              cases hnext : k (n + 1) with
              | none =>
                  have hxR : γ (t (n + 1)) ∈ R := by simpa [U, hnext] using hright
                  have hxV : γ (t (n + 1)) ∈ V i := by simpa [U, hkn] using hleft
                  let J : JoinedIn (R ∩ V i) (a i) (γ (t (n + 1))) :=
                    (hoverlap i).joinedIn (x := a i) (y := γ (t (n + 1)))
                      (ha i) ⟨hxR, hxV⟩
                  let v' : Path (a i) (γ (t (n + 1))) := J.somePath
                  let r : Path b (γ (t (n + 1))) := (w i).trans v'
                  have hv'R : Set.range v' ⊆ R := by
                    intro x hx
                    obtain ⟨s, rfl⟩ := hx
                    exact (J.somePath_mem s).1
                  have hv'V : Set.range v' ⊆ V i := by
                    intro x hx
                    obtain ⟨s, rfl⟩ := hx
                    exact (J.somePath_mem s).2
                  have hrR : Set.range r ⊆ R := by
                    rw [show Set.range r = Set.range (w i) ∪ Set.range v' by
                      simp [r, Path.trans_range]]
                    exact Set.union_subset (hw i) hv'R
                  have hsegV : Set.range seg ⊆ V i := by simpa [U, hkn] using hseg
                  let ell : Path (a i) (a i) := v.trans (seg.trans v'.symm)
                  have hell : Set.range ell ⊆ V i := by
                    rw [show Set.range ell =
                        Set.range v ∪ (Set.range seg ∪ Set.range v') by
                      simp [ell, Path.trans_range, Path.symm_range]]
                    exact Set.union_subset hv (Set.union_subset hsegV hv'V)
                  let leaf : Path b b := q.trans (seg.trans r.symm)
                  have hclass : openCoverLoopClass leaf =
                      openCoverLoopClass ((w i).trans (ell.trans (w i).symm)) := by
                    subst q
                    simp only [leaf, r, ell, openCoverLoopClass,
                      Path.Homotopic.Quotient.mk_trans,
                      Path.Homotopic.Quotient.mk_symm,
                      Path.Homotopic.Quotient.trans_assoc]
                    rw [quotient_symm_trans]
                  have hleafH : openCoverLoopClass leaf ∈ H := by
                    rw [hclass]
                    exact Subgroup.subset_closure (Or.inr
                      ⟨i, a i, ha i, w i, ell, hw i, hell, rfl⟩)
                  simpa [hnext] using finish r hleafH
                    (Or.inl ⟨hsucc, Or.inl ⟨hnext, hrR⟩⟩)
              | some j =>
                  by_cases hij : i = j
                  · subst j
                    let J : JoinedIn (V i) (a i) (γ (t (n + 1))) :=
                      (hV i).joinedIn (x := a i) (y := γ (t (n + 1)))
                        (ha i).2 (by simpa [U, hnext] using hright)
                    let v' : Path (a i) (γ (t (n + 1))) := J.somePath
                    let r : Path b (γ (t (n + 1))) := (w i).trans v'
                    have hv' : Set.range v' ⊆ V i := by
                      intro x hx
                      obtain ⟨s, rfl⟩ := hx
                      exact J.somePath_mem s
                    have hsegV : Set.range seg ⊆ V i := by simpa [U, hkn] using hseg
                    let ell : Path (a i) (a i) := v.trans (seg.trans v'.symm)
                    have hell : Set.range ell ⊆ V i := by
                      rw [show Set.range ell =
                          Set.range v ∪ (Set.range seg ∪ Set.range v') by
                        simp [ell, Path.trans_range, Path.symm_range]]
                      exact Set.union_subset hv (Set.union_subset hsegV hv')
                    let leaf : Path b b := q.trans (seg.trans r.symm)
                    have hclass : openCoverLoopClass leaf =
                        openCoverLoopClass ((w i).trans (ell.trans (w i).symm)) := by
                      subst q
                      simp only [leaf, r, ell, openCoverLoopClass,
                        Path.Homotopic.Quotient.mk_trans,
                        Path.Homotopic.Quotient.mk_symm,
                        Path.Homotopic.Quotient.trans_assoc]
                      rw [quotient_symm_trans]
                    have hleafH : openCoverLoopClass leaf ∈ H := by
                      rw [hclass]
                      exact Subgroup.subset_closure (Or.inr
                        ⟨i, a i, ha i, w i, ell, hw i, hell, rfl⟩)
                    simpa [hnext] using finish r hleafH (Or.inl ⟨hsucc, Or.inr
                      ⟨i, hnext, v', rfl, hv'⟩⟩)
                  · exfalso
                    have hxi : γ (t (n + 1)) ∈ V i := by simpa [U, hkn] using hleft
                    have hxj : γ (t (n + 1)) ∈ V j := by simpa [U, hnext] using hright
                    exact Set.disjoint_left.1 (hdisjoint i j hij) hxi hxj
    obtain ⟨q, hqH, hqstate⟩ := hprefix m le_rfl
    have hqconst : ∀ s, q s = b := by
      rcases hqstate with hqstate | hqstate
      · omega
      · exact hqstate.2
    have htm : t m = 1 := hm m le_rfl
    have hq : q = (Path.refl b).cast rfl (by
        rw [htm]
        exact γ.target) := by
      apply Path.ext
      funext s
      simpa using hqconst s
    have hpre : pre m = γ.cast rfl (by
        rw [htm]
        exact γ.target) := by
      apply Path.ext
      funext s
      change γ.monotoneTruncate 0 (t m) (unitInterval.nonneg (t m)) s = γ s
      rw [Path.monotoneTruncate_apply]
      apply congrArg γ
      apply Subtype.ext
      rw [htm]
      simp [s.2.1, s.2.2]
    change openCoverLoopClass γ ∈ H
    rw [hq, hpre] at hqH
    rw [castPath_trans_castRefl_symm_class γ] at hqH
    exact hqH

end SphereSixComplex.Topology
