module

public import SphereSixComplex.Topology.PaperActualVanKampenNiceness
public import SphereSixComplex.Topology.PaperVanKampenAlgebraAdapter
public import SphereSixComplex.Topology.PaperActualAffineCoreData
public import TauCeti.AlgebraicTopology.FundamentalGroup.Homeomorph

/-!
# The van Kampen datum for the actual analytic star

The generic van Kampen machinery is complete, so the paper's fundamental-group contract for the
glued star follows from purely geometric inputs. This module performs the transport.

`centralAffineCorePiOneData` presents the fundamental group of the punctured central family. The
core piece of the van Kampen cover is homeomorphic to that family, and the core inclusion surjects
on the fundamental group of the star once each filling's fundamental group is generated by its
overlap with the core. Composing the base-point change, that homeomorphism and the core inclusion
gives a surjection which transports the presentation to the star, and the paper's algebraic
reduction then yields `HasVanKampenData`.

What remains are exactly the two geometric obligations named in
`hasVanKampenData_of_overlapSurjective_of_relations`: the three overlap surjectivities and the
star filling relations.
-/

@[expose] public section

noncomputable section

open scoped ContDiff Manifold

namespace SphereSixComplex.Geometry.PaperAnalyticData

variable (P : PaperAnalyticData)

/-- The core piece of the actual van Kampen cover, identified with the central family. -/
public noncomputable def centralToCoreEquiv :
    FundamentalGroup P.CentralFamily
        (P.openEmbeddingStarData.centralToSectionSevenEulerPieceHomeomorph.symm
          ⟨P.vanKampenBase, P.actualVanKampenFourPieceCover.base_mem_core⟩) ≃*
      FundamentalGroup (P.actualVanKampenFourPieceCover.core)
        ⟨P.vanKampenBase, P.actualVanKampenFourPieceCover.base_mem_core⟩ :=
  TauCeti.FundamentalGroup.homeomorphMulEquivOfEq
    P.openEmbeddingStarData.centralToSectionSevenEulerPieceHomeomorph
    (P.openEmbeddingStarData.centralToSectionSevenEulerPieceHomeomorph.apply_symm_apply _)

/-- A path in the central family from its chosen affine base point to the point corresponding to
the van Kampen base point. -/
public noncomputable def centralAffineBasePath :
    Path P.centralAffineBase
      (P.openEmbeddingStarData.centralToSectionSevenEulerPieceHomeomorph.symm
        ⟨P.vanKampenBase, P.actualVanKampenFourPieceCover.base_mem_core⟩) := by
  let _ : PathConnectedSpace P.CentralFamily := P.starCentral_pathConnected
  exact PathConnectedSpace.somePath _ _

/-- The surjection from the central family's fundamental group onto that of the glued star. -/
public noncomputable def vanKampenCoreHom
 :
    FundamentalGroup P.CentralFamily P.centralAffineBase →*
      FundamentalGroup (VanKampenSpace P) P.vanKampenBase :=
  (P.actualVanKampenFourPieceCover.coreFundamentalGroupMap).comp
    ((P.centralToCoreEquiv).toMonoidHom.comp
      (FundamentalGroup.fundamentalGroupMulEquivOfPath P.centralAffineBasePath).toMonoidHom)

public theorem vanKampenCoreHom_surjective
    (hcusp : Function.Surjective
      (P.actualVanKampenFourPieceCover.cuspOverlapFundamentalGroupMap))
    (hthree : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticThreeOverlapFundamentalGroupMap))
    (hfour : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticFourOverlapFundamentalGroupMap)) :
    Function.Surjective (P.vanKampenCoreHom) :=
  (P.actualCoreFundamentalGroupMap_surjective hcusp hthree hfour).comp
    ((P.centralToCoreEquiv).surjective.comp
      (FundamentalGroup.fundamentalGroupMulEquivOfPath P.centralAffineBasePath).surjective)

/-- The affine core presentation, transported to the fundamental group of the glued star. -/
public noncomputable def vanKampenCorePiOneData
    (hcusp : Function.Surjective
      (P.actualVanKampenFourPieceCover.cuspOverlapFundamentalGroupMap))
    (hthree : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticThreeOverlapFundamentalGroupMap))
    (hfour : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticFourOverlapFundamentalGroupMap)) :
    SphereSixComplex.AffineTorusCorePiOneData
      (FundamentalGroup (VanKampenSpace P) P.vanKampenBase) LatticeData.Lattice
      Topology.paperMonodromyOne Topology.paperMonodromyTwo :=
  (P.centralAffineCorePiOneData).mapSurjective (P.vanKampenCoreHom)
    (P.vanKampenCoreHom_surjective hcusp hthree hfour)

/-- The paper's van Kampen contract for the actual star, from the two remaining geometric
inputs: the overlap surjectivities and the filling relations. -/
public theorem hasVanKampenData_of_overlapSurjective_of_relations
    (hcusp : Function.Surjective
      (P.actualVanKampenFourPieceCover.cuspOverlapFundamentalGroupMap))
    (hthree : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticThreeOverlapFundamentalGroupMap))
    (hfour : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticFourOverlapFundamentalGroupMap))
    (F : SphereSixComplex.AffineTorusStarFillingRelations
      (P.vanKampenCorePiOneData hcusp hthree hfour) 3 4 LatticeData.epsilon
      (-LatticeData.epsilon') 0 Topology.paperToricSubgroup) :
    Topology.HasVanKampenData (VanKampenSpace P) 0 1 (-1) :=
  Topology.hasVanKampenData_of_affineData P.vanKampenBase
    (P.vanKampenCorePiOneData hcusp hthree hfour) F

end SphereSixComplex.Geometry.PaperAnalyticData

end

end
