module

public import SphereSixComplex.Topology.PaperEllipticReducedCentralFiberCoverModels
public import SphereSixComplex.Topology.PaperEllipticCollarFundamentalDomainProof
public import SphereSixComplex.Topology.PaperEllipticTorusHomologyBasisProof
public import SphereSixComplex.Topology.PaperEllipticTorusHomologyBasis
public import SphereSixComplex.Geometry.EllipticFixedPointCriterion
public import Mathlib.Topology.Constructions

/-!
# Affine cyclic reduced fibres as mapping-torus candidates

The reduced central fibre is first identified with the orbit quotient of its central torus by
the affine cyclic fibre action.  This removes the ambient disc coordinate and is the first
topological reduction toward a mapping-torus model over the primitive character `gamma`.
-/

@[expose] public section

noncomputable section

open Set Topology
open scoped ContinuousMap

namespace SphereSixComplex.Topology.PaperEllipticReducedCentralFiberCoverModels.RadialEllipticActionData

open Geometry Geometry.EquivariantQuotientHomeomorph
open Geometry.EllipticLocalCoordinates
open PaperEllipticFillingRadialRetraction
open TriangleGroup

variable {m : ℕ} [NeZero m] {T : Type} [TopologicalSpace T] [AddCommGroup T]

/-- The cyclic representation on the central torus generated by the affine fibre map. -/
public noncomputable def centralFiberRepresentation
    (D : RadialEllipticActionData m T) : FiniteCyclic m →* Equiv.Perm T :=
  cyclicRepresentation m D.actionData.fiberGenerator D.actionData.fiberGenerator_pow

@[simp]
public theorem centralFiberRepresentation_generator
    (D : RadialEllipticActionData m T) :
    centralFiberRepresentation D (cyclicGenerator m) = D.actionData.fiberGenerator :=
  cyclicRepresentation_generator m D.actionData.fiberGenerator
    D.actionData.fiberGenerator_pow

/-- The affine cyclic action induced on the central torus. -/
@[instance_reducible] public noncomputable def centralFiberAction
    (D : RadialEllipticActionData m T) : MulAction (FiniteCyclic m) T where
  smul g x := centralFiberRepresentation D g x
  one_smul x := by
    change centralFiberRepresentation D 1 x = x
    rw [map_one]
    rfl
  mul_smul g h x := by
    change centralFiberRepresentation D (g * h) x =
      centralFiberRepresentation D g (centralFiberRepresentation D h x)
    rw [map_mul]
    rfl

/-- The central-torus action is the second coordinate of the diagonal action at its centre. -/
public theorem rotation_pow_center
    (D : RadialEllipticActionData m T) (k : ℕ) :
    (D.actionData.rotation ^ k) D.actionData.center = D.actionData.center := by
  have hgenerator : D.actionData.rotation D.actionData.center = D.actionData.center := by
    have hm : 0 < m := NeZero.pos m
    by_cases hmOne : m = 1
    · subst m
      simpa using congrArg (fun e : Equiv.Perm _ ↦ e D.actionData.center)
        D.actionData.rotation_pow
    · exact (D.actionData.rotation_fixed_iff 1 (by omega) (by omega)
          D.actionData.center).2 rfl
  induction k with
  | zero => rfl
  | succ k ih =>
      rw [pow_succ, Equiv.Perm.mul_apply, hgenerator, ih]

/-- At the centre, the diagonal action is the affine fibre action. -/
public theorem centralFiberRepresentation_eq_diagonal
    (D : RadialEllipticActionData m T) (g : FiniteCyclic m) (x : T) :
    actionMap D.actionData.diagonalAction g (D.actionData.center, x) =
      (D.actionData.center, centralFiberRepresentation D g x) := by
  change D.actionData.representation g (D.actionData.center, x) = _
  rw [cyclic_eq_generator_pow g, map_pow, map_pow,
    centralFiberRepresentation_generator D,
    D.actionData.representation_generator,
    D.actionData.diagonalGenerator_pow_apply,
    rotation_pow_center D]

public theorem centralFiberRepresentation_eq_diagonal_snd
    (D : RadialEllipticActionData m T) (g : FiniteCyclic m) (x : T) :
    centralFiberRepresentation D g x =
      (D.actionData.representation g (D.actionData.center, x)).2 := by
  have h := congrArg Prod.snd (centralFiberRepresentation_eq_diagonal D g x)
  exact h.symm

/-- Projection of the central torus onto the reduced central fibre. -/
public noncomputable def centralFiberOrbitProjection
    (D : RadialEllipticActionData m T) : C(T, D.reducedCentralFiber) :=
  (centralFiberCoverProjection D).comp (centralFiberCoverSourceHomeomorph D).symm

@[simp]
public theorem centralFiberOrbitProjection_apply
    (D : RadialEllipticActionData m T) (x : T) :
    centralFiberOrbitProjection D x =
      ⟨Quotient.mk (orbitRelOf D.actionData.diagonalAction)
        (D.actionData.center, x), by
          apply (mem_centralSlice_iff_quotient_mem_reducedCentralFiber D
            (D.actionData.center, x)).2
          exact D.center_eq⟩ :=
  rfl

/-- Every point of the reduced central fibre has a representative on the central torus. -/
public theorem centralFiberOrbitProjection_surjective
    (D : RadialEllipticActionData m T) :
    Function.Surjective (centralFiberOrbitProjection D) := by
  intro q
  obtain ⟨p, hp, hpq⟩ := q.2
  refine ⟨p.2, ?_⟩
  apply Subtype.ext
  rw [centralFiberOrbitProjection_apply]
  change Quotient.mk _ (D.actionData.center, p.2) = q.1
  rw [D.center_eq]
  have hpair : (discCenter, p.2) = p := by
    apply Prod.ext
    · exact hp.symm
    · rfl
  rw [hpair]
  exact hpq

/-- The central-torus projection is a quotient map. -/
public theorem centralFiberOrbitProjection_isQuotientMap
    (D : RadialEllipticActionData m T)
    [T2Space D.Product] [LocallyCompactSpace D.Product]
    (hfree : letI := D.actionData.diagonalAction
      IsCancelSMul (FiniteCyclic m) D.Product) :
    IsQuotientMap (centralFiberOrbitProjection D) := by
  have hcover := centralFiberCoverProjection_isCovering D hfree
  have hsurjective : Function.Surjective (centralFiberCoverProjection D) := by
    intro q
    obtain ⟨x, hx⟩ := centralFiberOrbitProjection_surjective D q
    exact ⟨(centralFiberCoverSourceHomeomorph D).symm x, hx⟩
  exact (hcover.isQuotientMap hsurjective).comp
    (centralFiberCoverSourceHomeomorph D).symm.isQuotientMap

/-- Two central-torus points have the same image precisely when they are in the same affine
cyclic orbit. -/
public theorem centralFiberOrbitRel_iff_projection_eq
    (D : RadialEllipticActionData m T) (x y : T) :
    letI := centralFiberAction D
    MulAction.orbitRel (FiniteCyclic m) T x y ↔
      centralFiberOrbitProjection D x = centralFiberOrbitProjection D y := by
  let _ := centralFiberAction D
  rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff]
  constructor
  · rintro ⟨g, hg⟩
    apply Subtype.ext
    rw [centralFiberOrbitProjection_apply, centralFiberOrbitProjection_apply]
    apply Quotient.sound
    change ∃ g : FiniteCyclic m,
      actionMap D.actionData.diagonalAction g (D.actionData.center, y) =
        (D.actionData.center, x)
    refine ⟨g, ?_⟩
    change centralFiberRepresentation D g y = x at hg
    rw [centralFiberRepresentation_eq_diagonal D g y, hg]
  · intro hxy
    have hquot := congrArg Subtype.val hxy
    rw [centralFiberOrbitProjection_apply, centralFiberOrbitProjection_apply] at hquot
    have horbit := Quotient.exact hquot
    change ∃ g : FiniteCyclic m,
      actionMap D.actionData.diagonalAction g (D.actionData.center, y) =
        (D.actionData.center, x) at horbit
    obtain ⟨g, hg⟩ := horbit
    refine ⟨g, ?_⟩
    rw [centralFiberRepresentation_eq_diagonal D g y] at hg
    exact congrArg Prod.snd hg

/-- The reduced central fibre is homeomorphic to the explicit affine cyclic quotient of its
central torus. -/
public noncomputable def centralFiberOrbitQuotientHomeomorph
    (D : RadialEllipticActionData m T)
    [T2Space D.Product] [LocallyCompactSpace D.Product]
    (hfree : letI := D.actionData.diagonalAction
      IsCancelSMul (FiniteCyclic m) D.Product) :
    letI := centralFiberAction D
    MulAction.orbitRel.Quotient (FiniteCyclic m) T ≃ₜ D.reducedCentralFiber := by
  let _ := centralFiberAction D
  let hq := centralFiberOrbitProjection_isQuotientMap D hfree
  exact (Homeomorph.Quotient.congrRight fun x y ↦
    centralFiberOrbitRel_iff_projection_eq D x y).trans hq.homeomorph

end SphereSixComplex.Topology.PaperEllipticReducedCentralFiberCoverModels.RadialEllipticActionData

namespace SphereSixComplex.Topology.PaperAffineCyclicReducedFiberMappingTorus

open Geometry Geometry.ComplexTorus Geometry.EllipticFamilySpecialization
open Geometry.AnalyticTorusFamily
open Geometry.EllipticFixedPointCriterion
open Geometry.EllipticLocalCoordinates
open Geometry.EquivariantQuotientHomeomorph
open Geometry.GlobalTorusFamily LatticeData Periods
open SphereSixComplex.CyclicAngularFundamentalDomain
open SphereSixComplex.StandardTorusHomology
open TriangleGroup

/-! ## The gamma-coordinate splitting -/

/-- Head--tail coordinates split real period space into the `gamma` coordinate and its
three-dimensional kernel direction. -/
public noncomputable def gammaRealSplit :
    RealPeriods ≃L[ℝ] ℝ × (Fin 3 → ℝ) :=
  (Fin.consLinearEquiv ℝ (fun _ : Fin 4 ↦ ℝ)).symm.toContinuousLinearEquiv

@[simp]
public theorem gammaRealSplit_apply (u : RealPeriods) :
    gammaRealSplit u = (u 0, Fin.tail u) :=
  rfl

/-- The real extension of `gamma` is literally the first period coordinate. -/
public theorem gammaReal_eq_head (u : RealPeriods) :
    gammaReal u = u 0 := by
  rw [gammaReal, Fintype.linearCombination_apply]
  simp [gamma, integralBasisVector, Fin.sum_univ_succ]

/-- The analogous integral head--tail splitting of the period lattice. -/
public def gammaLatticeSplit :
    Lattice ≃ₗ[ℤ] ℤ × (Fin 3 → ℤ) :=
  (Fin.consLinearEquiv ℤ (fun _ : Fin 4 ↦ ℤ)).symm

@[simp]
public theorem gammaLatticeSplit_apply (u : Lattice) :
    gammaLatticeSplit u = (gamma u, Fin.tail u) :=
  rfl

/-- The standard four-torus split into its `gamma` circle and the remaining three-torus. -/
public def standardFourTorusGammaSplit :
    StdTorus 4 ≃ₜ UnitAddCircle × StdTorus 3 where
  toEquiv := (Fin.consEquiv (fun _ : Fin 4 ↦ UnitAddCircle)).symm
  continuous_toFun := by fun_prop
  continuous_invFun := by fun_prop

@[simp]
public theorem standardFourTorusGammaSplit_apply (u : StdTorus 4) :
    standardFourTorusGammaSplit u = (u 0, Fin.tail u) :=
  rfl

/-- Gamma coordinates on a full-rank period torus. -/
public noncomputable def additiveTorusGammaSplit (p : Parameters) (h : FullRank p) :
    AdditiveTorus p ≃ₜ UnitAddCircle × StdTorus 3 :=
  (additiveTorusStdHomeomorph p h).trans standardFourTorusGammaSplit

@[simp]
public theorem additiveTorusGammaSplit_apply_projection
    (p : Parameters) (h : FullRank p) (z : ComplexTwoSpace) :
    additiveTorusGammaSplit p h (torusProjection p z) =
      ((((h.realEquiv.symm z) 0 : ℝ) : UnitAddCircle),
        fun i ↦ (((h.realEquiv.symm z) i.succ : ℝ) : UnitAddCircle)) :=
  rfl

/-- On a period-domain fibre, the first circle of the split is exactly `gammaCoordinate`
modulo its integral periods. -/
public theorem additiveTorusGammaSplit_fst_projection_periodDomain
    (x : PeriodDomain) (z : ComplexTwoSpace) :
    (additiveTorusGammaSplit x.1 (fullRankDomain x) (torusProjection x.1 z)).1 =
      ((gammaCoordinate x z : ℝ) : UnitAddCircle) := by
  change (((fullRankDomain x).realEquiv.symm z 0 : ℝ) : UnitAddCircle) =
    ((gammaReal ((fullRankDomain x).realEquiv.symm z) : ℝ) : UnitAddCircle)
  rw [gammaReal_eq_head]

/-! ## The two explicit paper shears and three-torus clutching maps -/

/-- The order-three invariant shear, including reversal of the gamma circle. -/
public def orderThreeStandardGammaShear :
    StdTorus 4 ≃ₜ UnitAddCircle × StdTorus 3 where
  toFun u := (-u 0, ![u 1 - 2 • u 0, u 2 + 4 • u 0, u 3])
  invFun p := ![-p.1, p.2 0 - 2 • p.1, p.2 1 + 4 • p.1, p.2 2]
  left_inv u := by
    funext i
    fin_cases i <;> simp
  right_inv p := by
    apply Prod.ext
    · simp
    · funext i
      fin_cases i <;> simp
  continuous_toFun := by fun_prop
  continuous_invFun := by fun_prop

/-- The order-four invariant shear. -/
public def orderFourStandardGammaShear :
    StdTorus 4 ≃ₜ UnitAddCircle × StdTorus 3 where
  toFun u := (u 0, ![u 1 - 3 • u 0, u 2 + 3 • u 0, u 3])
  invFun p := ![p.1, p.2 0 + 3 • p.1, p.2 1 - 3 • p.1, p.2 2]
  left_inv u := by
    funext i
    fin_cases i <;> simp
  right_inv p := by
    apply Prod.ext
    · rfl
    · funext i
      fin_cases i <;> simp
  continuous_toFun := by fun_prop
  continuous_invFun := by fun_prop

/-- Order-three clutching on the transverse three-torus. -/
public def orderThreeThreeTorusClutching : StdTorus 3 ≃ₜ StdTorus 3 where
  toFun v := ![v 1, -v 0 - v 1, v 0 + v 2]
  invFun v := ![-v 0 - v 1, v 0, v 2 + v 0 + v 1]
  left_inv v := by
    funext i
    fin_cases i <;> (simp <;> abel)
  right_inv v := by
    funext i
    fin_cases i <;> simp
  continuous_toFun := by fun_prop
  continuous_invFun := by fun_prop

/-- Order-four clutching on the transverse three-torus. -/
public def orderFourThreeTorusClutching : StdTorus 3 ≃ₜ StdTorus 3 where
  toFun v := ![-v 1, v 0, v 1 + v 2]
  invFun v := ![v 1, -v 0, v 2 + v 0]
  left_inv v := by
    funext i
    fin_cases i <;> simp
  right_inv v := by
    funext i
    fin_cases i <;> simp
  continuous_toFun := by fun_prop
  continuous_invFun := by fun_prop

public theorem orderThreeThreeTorusClutching_pow :
    orderThreeThreeTorusClutching ^ 3 = 1 := by
  ext v i
  fin_cases i <;> simp [orderThreeThreeTorusClutching, pow_succ] <;> abel

public theorem orderFourThreeTorusClutching_pow :
    orderFourThreeTorusClutching ^ 4 = 1 := by
  ext v i
  fin_cases i <;> (simp [orderFourThreeTorusClutching, pow_succ] <;> abel)

public theorem rhoLambdaReal_gOne_explicit (u : RealPeriods) :
    rhoLambdaReal g₁ u =
      ![u 0, 6 • u 0 + u 2, -(6 • u 0) - u 1 - u 2,
        -(2 • u 0) + u 1 + u (Fin.succ 2)] := by
  change realExtension (rhoLambda g₁) u = _
  rw [realExtension_apply]
  change Matrix.mulVec ((LinearMap.toMatrix' (rhoLambda g₁).toLinearMap).map
    (Int.castRingHom ℝ)) u = _
  rw [integralMatrix_rhoLambda_gOne]
  ext i
  fin_cases i <;>
    norm_num [A₁, Matrix.mulVec, dotProduct, Fin.sum_univ_succ] <;> ring

public theorem rhoLambdaReal_gTwo_explicit (u : RealPeriods) :
    rhoLambdaReal g₂ u =
      ![u 0, -u 2, -(6 • u 0) + u 1, 3 • u 0 + u 2 + u (Fin.succ 2)] := by
  change realExtension (rhoLambda g₂) u = _
  rw [realExtension_apply]
  change Matrix.mulVec ((LinearMap.toMatrix' (rhoLambda g₂).toLinearMap).map
    (Int.castRingHom ℝ)) u = _
  rw [integralMatrix_rhoLambda_gTwo]
  ext i
  fin_cases i <;>
    (norm_num [A₂, Matrix.mulVec, dotProduct, Fin.sum_univ_succ] <;> ring)

variable {U : TriangleUniformization} (F : PeriodFunctions U)

/-- Gamma-normal coordinates on the actual order-three central torus. -/
public noncomputable def orderThreeGammaNormalFormHomeomorph :
    AdditiveTorus (parameterMap F U.zOne).1 ≃ₜ UnitAddCircle × StdTorus 3 :=
  (additiveTorusStdHomeomorph _ (fullRankDomain (parameterMap F U.zOne))).trans
    orderThreeStandardGammaShear

/-- Gamma-normal coordinates on the actual order-four central torus. -/
public noncomputable def orderFourGammaNormalFormHomeomorph :
    AdditiveTorus (parameterMap F U.zTwo).1 ≃ₜ UnitAddCircle × StdTorus 3 :=
  (additiveTorusStdHomeomorph _ (fullRankDomain (parameterMap F U.zTwo))).trans
    orderFourStandardGammaShear

public theorem orderThreeGammaNormalForm_generator
    (q : AdditiveTorus (parameterMap F U.zOne).1) :
    orderThreeGammaNormalFormHomeomorph F ((orderThreeActionData F).fiberGenerator q) =
      ((orderThreeGammaNormalFormHomeomorph F q).1 - (((1 : ℝ) / 3 : ℝ) : UnitAddCircle),
        orderThreeThreeTorusClutching (orderThreeGammaNormalFormHomeomorph F q).2) := by
  induction q using Quotient.inductionOn with
  | _ z =>
      change orderThreeStandardGammaShear
          (additiveTorusStdHomeomorph _ (fullRankDomain (parameterMap F U.zOne))
            (orderThreeFiberAutomorphism F (Quotient.mk _ z) +
              orderThreeTranslation (parameterMap F U.zOne).1)) = _
      rw [orderThreeFiberAutomorphism_mk, orderThreeTranslation.eq_def,
        additiveTorusProjection.eq_def, ← additiveTorus_mk_add]
      change orderThreeStandardGammaShear
          (fun i ↦ (((periodCoordinates (parameterMap F U.zOne)
            (periodTransport g₁ (parameterMap F U.zOne) z +
              (3 : ℂ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon)) i : ℝ) :
                UnitAddCircle)) =
        ((orderThreeStandardGammaShear
            (fun i ↦ (((periodCoordinates (parameterMap F U.zOne) z) i : ℝ) :
              UnitAddCircle))).1 - (((1 : ℝ) / 3 : ℝ) : UnitAddCircle),
          orderThreeThreeTorusClutching
            (orderThreeStandardGammaShear
              (fun i ↦ (((periodCoordinates (parameterMap F U.zOne) z) i : ℝ) :
                UnitAddCircle))).2)
      let u := periodCoordinates (parameterMap F U.zOne) z
      have htransport :
          periodCoordinates (parameterMap F U.zOne)
              (periodTransport g₁ (parameterMap F U.zOne) z) =
            rhoLambdaReal g₁ u := by
        have h := periodCoordinates_transport g₁ (parameterMap F U.zOne) z
        rw [parameterMap_zOne_fixed F] at h
        exact h
      have htranslation :
          periodCoordinates (parameterMap F U.zOne)
              ((3 : ℂ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon) =
            (3 : ℝ)⁻¹ • integerToReal epsilon := by
        change (fullRankDomain (parameterMap F U.zOne)).realEquiv.symm
            ((3 : ℂ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon) = _
        rw [show (3 : ℂ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon =
            (3 : ℝ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon by
              ext i; norm_num]
        rw [map_smul]
        change (3 : ℝ)⁻¹ • periodCoordinates (parameterMap F U.zOne)
            (periodVector (parameterMap F U.zOne).1 epsilon) = _
        rw [periodCoordinates_periodVector]
      rw [show periodCoordinates (parameterMap F U.zOne)
          (periodTransport g₁ (parameterMap F U.zOne) z +
            (3 : ℂ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon) =
          rhoLambdaReal g₁ u + (3 : ℝ)⁻¹ • integerToReal epsilon by
            change (fullRankDomain (parameterMap F U.zOne)).realEquiv.symm (_ + _) = _
            rw [map_add]
            change periodCoordinates (parameterMap F U.zOne)
                (periodTransport g₁ (parameterMap F U.zOne) z) +
              periodCoordinates (parameterMap F U.zOne)
                ((3 : ℂ)⁻¹ • periodVector (parameterMap F U.zOne).1 epsilon) = _
            rw [htransport, htranslation]]
      rw [rhoLambdaReal_gOne_explicit]
      have hcoe_nsmul (n : ℕ) (x : ℝ) :
          (((n : ℝ) * x : ℝ) : UnitAddCircle) = n • ((x : ℝ) : UnitAddCircle) := by
        rw [← QuotientAddGroup.mk_nsmul]
        congr 1
        simp [nsmul_eq_mul]
      have htwoThird :
          (((2 / 3 : ℝ) : ℝ) : UnitAddCircle) =
            2 • (((1 / 3 : ℝ) : ℝ) : UnitAddCircle) := by
        rw [← hcoe_nsmul]
        congr 1
        norm_num
      have hfourThird :
          (((4 / 3 : ℝ) : ℝ) : UnitAddCircle) =
            4 • (((1 / 3 : ℝ) : ℝ) : UnitAddCircle) := by
        rw [← hcoe_nsmul]
        congr 1
        norm_num
      have hcoeSix (x : ℝ) :
          (((6 * x : ℝ)) : UnitAddCircle) = 6 • ((x : ℝ) : UnitAddCircle) := by
        simpa using hcoe_nsmul 6 x
      have hcoeTwo (x : ℝ) :
          (((2 * x : ℝ)) : UnitAddCircle) = 2 • ((x : ℝ) : UnitAddCircle) := by
        simpa using hcoe_nsmul 2 x
      have hscaleTwo :
          ((((3 : ℝ)⁻¹ * 2 : ℝ)) : UnitAddCircle) =
            2 • (((1 / 3 : ℝ) : ℝ) : UnitAddCircle) := by
        convert htwoThird using 1; norm_num
      have hscaleFour :
          ((((3 : ℝ)⁻¹ * 4 : ℝ)) : UnitAddCircle) =
            4 • (((1 / 3 : ℝ) : ℝ) : UnitAddCircle) := by
        convert hfourThird using 1; norm_num
      have hthird :
          (((3 : ℝ)⁻¹ : ℝ) : UnitAddCircle) =
            (((1 / 3 : ℝ) : ℝ) : UnitAddCircle) := by
        congr 1
        norm_num
      apply Prod.ext
      · simp [u, orderThreeStandardGammaShear, epsilon, integerToReal]
        abel
      · funext i
        fin_cases i
        · simp [u, orderThreeStandardGammaShear, orderThreeThreeTorusClutching,
            epsilon, integerToReal]
          rw [hcoeSix, hscaleTwo, hthird]
          abel
        · simp [u, orderThreeStandardGammaShear, orderThreeThreeTorusClutching,
            epsilon, integerToReal]
          rw [hcoeSix, hscaleFour, hthird]
          abel
        · simp [u, orderThreeStandardGammaShear, orderThreeThreeTorusClutching,
            epsilon, integerToReal]
          rw [hcoeTwo]
          abel

public theorem orderFourGammaNormalForm_generator
    (q : AdditiveTorus (parameterMap F U.zTwo).1) :
    orderFourGammaNormalFormHomeomorph F ((orderFourActionData F).fiberGenerator q) =
      ((orderFourGammaNormalFormHomeomorph F q).1 - (((1 : ℝ) / 4 : ℝ) : UnitAddCircle),
        orderFourThreeTorusClutching (orderFourGammaNormalFormHomeomorph F q).2) := by
  induction q using Quotient.inductionOn with
  | _ z =>
      change orderFourStandardGammaShear
          (additiveTorusStdHomeomorph _ (fullRankDomain (parameterMap F U.zTwo))
            (orderFourFiberAutomorphism F (Quotient.mk _ z) +
              orderFourTranslation (parameterMap F U.zTwo).1)) = _
      rw [orderFourFiberAutomorphism_mk, orderFourTranslation.eq_def,
        additiveTorusProjection.eq_def, ← additiveTorus_mk_add]
      change orderFourStandardGammaShear
          (fun i ↦ (((periodCoordinates (parameterMap F U.zTwo)
            (periodTransport g₂ (parameterMap F U.zTwo) z +
              (4 : ℂ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon'))) i : ℝ) :
                UnitAddCircle)) =
        ((orderFourStandardGammaShear
            (fun i ↦ (((periodCoordinates (parameterMap F U.zTwo) z) i : ℝ) :
              UnitAddCircle))).1 - (((1 : ℝ) / 4 : ℝ) : UnitAddCircle),
          orderFourThreeTorusClutching
            (orderFourStandardGammaShear
              (fun i ↦ (((periodCoordinates (parameterMap F U.zTwo) z) i : ℝ) :
                UnitAddCircle))).2)
      let u := periodCoordinates (parameterMap F U.zTwo) z
      have htransport :
          periodCoordinates (parameterMap F U.zTwo)
              (periodTransport g₂ (parameterMap F U.zTwo) z) =
            rhoLambdaReal g₂ u := by
        have h := periodCoordinates_transport g₂ (parameterMap F U.zTwo) z
        rw [parameterMap_zTwo_fixed F] at h
        exact h
      have htranslation :
          periodCoordinates (parameterMap F U.zTwo)
              ((4 : ℂ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon')) =
            (4 : ℝ)⁻¹ • integerToReal (-epsilon') := by
        change (fullRankDomain (parameterMap F U.zTwo)).realEquiv.symm
            ((4 : ℂ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon')) = _
        rw [show (4 : ℂ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon') =
            (4 : ℝ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon') by
              ext i; norm_num]
        rw [map_smul]
        change (4 : ℝ)⁻¹ • periodCoordinates (parameterMap F U.zTwo)
            (periodVector (parameterMap F U.zTwo).1 (-epsilon')) = _
        rw [periodCoordinates_periodVector]
      rw [show periodCoordinates (parameterMap F U.zTwo)
          (periodTransport g₂ (parameterMap F U.zTwo) z +
            (4 : ℂ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon')) =
          rhoLambdaReal g₂ u + (4 : ℝ)⁻¹ • integerToReal (-epsilon') by
            change (fullRankDomain (parameterMap F U.zTwo)).realEquiv.symm (_ + _) = _
            rw [map_add]
            change periodCoordinates (parameterMap F U.zTwo)
                (periodTransport g₂ (parameterMap F U.zTwo) z) +
              periodCoordinates (parameterMap F U.zTwo)
                ((4 : ℂ)⁻¹ • periodVector (parameterMap F U.zTwo).1 (-epsilon')) = _
            rw [htransport, htranslation]]
      rw [rhoLambdaReal_gTwo_explicit]
      have hcoe_nsmul (n : ℕ) (x : ℝ) :
          (((n : ℝ) * x : ℝ) : UnitAddCircle) = n • ((x : ℝ) : UnitAddCircle) := by
        rw [← QuotientAddGroup.mk_nsmul]
        congr 1
        simp [nsmul_eq_mul]
      have hcoeSix (x : ℝ) :
          (((6 * x : ℝ)) : UnitAddCircle) = 6 • ((x : ℝ) : UnitAddCircle) := by
        simpa using hcoe_nsmul 6 x
      have hcoeThree (x : ℝ) :
          (((3 * x : ℝ)) : UnitAddCircle) = 3 • ((x : ℝ) : UnitAddCircle) := by
        simpa using hcoe_nsmul 3 x
      have hthreeQuarter :
          ((((4 : ℝ)⁻¹ * 3 : ℝ)) : UnitAddCircle) =
            3 • (((1 / 4 : ℝ) : ℝ) : UnitAddCircle) := by
        rw [← hcoe_nsmul]
        congr 1
        norm_num
      have hquarter :
          (((4 : ℝ)⁻¹ : ℝ) : UnitAddCircle) =
            (((1 / 4 : ℝ) : ℝ) : UnitAddCircle) := by
        congr 1
        norm_num
      apply Prod.ext
      · simp [u, orderFourStandardGammaShear, epsilon', integerToReal]
        abel
      · funext i
        fin_cases i
        · simp [u, orderFourStandardGammaShear, orderFourThreeTorusClutching,
            epsilon', integerToReal]
          rw [hthreeQuarter, hquarter]
          abel
        · simp [u, orderFourStandardGammaShear, orderFourThreeTorusClutching,
            epsilon', integerToReal]
          rw [hthreeQuarter, hquarter, hcoeSix]
          abel
        · simp [u, orderFourStandardGammaShear, orderFourThreeTorusClutching,
            epsilon', integerToReal]
          rw [hcoeThree]
          abel

/-! ## A normal affine cyclic quotient -/

variable {m : ℕ} {F : Type} [TopologicalSpace F]

/-- The integer lift of the normalized affine cyclic generator.  It advances the gamma circle
by `-k/m` and applies the `k`-th power of the three-torus clutching map. -/
public noncomputable def normalizedAffineShift (phi : F ≃ₜ F) (k : ℤ) :
    UnitAddCircle × F ≃ₜ UnitAddCircle × F :=
  (Homeomorph.addRight
    (-((((k : ℤ) : ℝ) / (m : ℝ) : ℝ) : UnitAddCircle))).prodCongr (phi ^ k)

@[simp]
public theorem normalizedAffineShift_apply (phi : F ≃ₜ F) (k : ℤ)
    (p : UnitAddCircle × F) :
    normalizedAffineShift (m := m) phi k p =
      (p.1 - ((((k : ℤ) : ℝ) / (m : ℝ) : ℝ) : UnitAddCircle),
        (phi ^ k) p.2) :=
  rfl

public theorem normalizedAffineShift_zero (phi : F ≃ₜ F) (p : UnitAddCircle × F) :
    normalizedAffineShift (m := m) phi 0 p = p := by
  simp

public theorem normalizedAffineShift_add (phi : F ≃ₜ F) (k l : ℤ)
    (p : UnitAddCircle × F) :
    normalizedAffineShift (m := m) phi (k + l) p =
      normalizedAffineShift (m := m) phi k (normalizedAffineShift (m := m) phi l p) := by
  rw [normalizedAffineShift_apply, normalizedAffineShift_apply, normalizedAffineShift_apply]
  apply Prod.ext
  · rw [show (((((k + l : ℤ) : ℝ) / (m : ℝ) : ℝ)) : UnitAddCircle) =
        (((((k : ℤ) : ℝ) / (m : ℝ) : ℝ)) : UnitAddCircle) +
        (((((l : ℤ) : ℝ) / (m : ℝ) : ℝ)) : UnitAddCircle) by
          rw [← QuotientAddGroup.mk_add]
          congr 1
          push_cast
          ring]
    simp only [sub_eq_add_neg, neg_add_rev]
    ac_rfl
  · rw [zpow_add]
    rfl

/-- Orbit relation of the normalized integer lift.  When `phi ^ m = 1`, this is the same
relation as the corresponding finite cyclic action. -/
public def normalizedAffineCyclicSetoid (phi : F ≃ₜ F) : Setoid (UnitAddCircle × F) where
  r p q := ∃ k : ℤ, q = normalizedAffineShift (m := m) phi k p
  iseqv := by
    refine ⟨fun p ↦ ⟨0, (normalizedAffineShift_zero phi p).symm⟩, ?_, ?_⟩
    · rintro p q ⟨k, rfl⟩
      exact ⟨-k, by rw [← normalizedAffineShift_add, neg_add_cancel,
        normalizedAffineShift_zero]⟩
    · rintro p q r ⟨k, rfl⟩ ⟨l, rfl⟩
      exact ⟨l + k, by rw [normalizedAffineShift_add]⟩

/-- The normalized affine cyclic quotient in gamma coordinates. -/
public abbrev NormalizedAffineCyclicQuotient (phi : F ≃ₜ F) :=
  Quotient (normalizedAffineCyclicSetoid (m := m) phi)

section NonzeroOrder

variable [NeZero m]

/-- Common real cover of the normalized affine cyclic quotient and its mapping torus. -/
public def normalizedAffineBaseCover (_phi : F ≃ₜ F) :
    C(ℝ × F, UnitAddCircle × F) where
  toFun w := (((w.1 / (m : ℝ) : ℝ) : UnitAddCircle), w.2)
  continuous_toFun := by fun_prop

public theorem normalizedAffineBaseCover_surjective (phi : F ≃ₜ F) :
    Function.Surjective (normalizedAffineBaseCover (m := m) phi) := by
  rintro ⟨s, x⟩
  obtain ⟨t, ht⟩ := QuotientAddGroup.mk_surjective
    (s := AddSubgroup.zmultiples (1 : ℝ)) s
  refine ⟨((m : ℝ) * t, x), ?_⟩
  apply Prod.ext
  · change ((((m : ℝ) * t) / (m : ℝ) : ℝ) : UnitAddCircle) = s
    rw [mul_div_cancel_left₀ t (by exact_mod_cast (NeZero.ne m))]
    exact ht
  · rfl

public def normalizedAffineQuotientMap (phi : F ≃ₜ F) :
    C(ℝ × F, NormalizedAffineCyclicQuotient (m := m) phi) where
  toFun w := Quotient.mk _ (normalizedAffineBaseCover (m := m) phi w)
  continuous_toFun := continuous_quot_mk.comp
    (normalizedAffineBaseCover (m := m) phi).continuous

public theorem normalizedAffineQuotientMap_surjective (phi : F ≃ₜ F) :
    Function.Surjective (normalizedAffineQuotientMap (m := m) phi) :=
  Quotient.mk_surjective.comp (normalizedAffineBaseCover_surjective phi)

omit [NeZero m] in
public theorem isOpenMap_normalizedAffineCyclicQuotientMk (phi : F ≃ₜ F) :
    IsOpenMap (Quotient.mk (normalizedAffineCyclicSetoid (m := m) phi)) := by
  intro U hU
  rw [← (isQuotientMap_quotient_mk'
    (s := normalizedAffineCyclicSetoid (m := m) phi)).isOpen_preimage]
  show IsOpen (Quotient.mk (normalizedAffineCyclicSetoid (m := m) phi) ⁻¹'
    (Quotient.mk (normalizedAffineCyclicSetoid (m := m) phi) '' U))
  have hpre : Quotient.mk (normalizedAffineCyclicSetoid (m := m) phi) ⁻¹'
      (Quotient.mk (normalizedAffineCyclicSetoid (m := m) phi) '' U) =
      ⋃ k : ℤ, normalizedAffineShift (m := m) phi k '' U := by
    ext q
    simp only [Set.mem_preimage, Set.mem_image, Set.mem_iUnion]
    constructor
    · rintro ⟨u, hu, heq⟩
      change Quotient.mk _ u = Quotient.mk _ q at heq
      obtain ⟨k, hk⟩ := Quotient.exact heq
      exact ⟨k, u, hu, hk.symm⟩
    · rintro ⟨k, u, hu, hk⟩
      refine ⟨u, hu, ?_⟩
      apply Quotient.sound
      exact ⟨k, hk.symm⟩
  rw [hpre]
  exact isOpen_iUnion fun k ↦ (normalizedAffineShift (m := m) phi k).isOpenMap U hU

public theorem isOpenMap_normalizedAffineBaseCover (phi : F ≃ₜ F) :
    IsOpenMap (normalizedAffineBaseCover (m := m) phi) := by
  have hm : ((m : ℝ)⁻¹) ≠ 0 := inv_ne_zero (by exact_mod_cast (NeZero.ne m))
  have hscale : IsOpenMap (fun t : ℝ ↦ t / (m : ℝ)) := by
    convert (Homeomorph.mulLeft₀ ((m : ℝ)⁻¹) hm).isOpenMap using 1
    funext t
    simp [div_eq_inv_mul]
  have hcircle : IsOpenMap (fun t : ℝ ↦ ((t / (m : ℝ) : ℝ) : UnitAddCircle)) :=
    (AddCircle.isLocalHomeomorph_coe (1 : ℝ)).isOpenMap.comp hscale
  exact hcircle.prodMap IsOpenMap.id

public theorem normalizedAffineQuotientMap_isQuotientMap (phi : F ≃ₜ F) :
    IsQuotientMap (normalizedAffineQuotientMap (m := m) phi) := by
  apply IsOpenMap.isQuotientMap
  · exact (isOpenMap_normalizedAffineCyclicQuotientMk phi).comp
      (isOpenMap_normalizedAffineBaseCover phi)
  · exact (normalizedAffineQuotientMap (m := m) phi).continuous
  · exact normalizedAffineQuotientMap_surjective phi

omit [NeZero m] in
public theorem homeomorph_zpow_of_dvd (phi : F ≃ₜ F) (hpow : phi ^ m = 1)
    (j : ℤ) (hj : (m : ℤ) ∣ j) : phi ^ j = 1 := by
  obtain ⟨t, rfl⟩ := hj
  rw [zpow_mul, zpow_natCast, hpow, one_zpow]

public theorem normalizedAffineQuotientMap_eq_iff
    (phi : F ≃ₜ F) (hpow : phi ^ m = 1) (w w' : ℝ × F) :
    normalizedAffineQuotientMap (m := m) phi w =
        normalizedAffineQuotientMap (m := m) phi w' ↔
      Quotient.mk (realMappingTorusSetoid phi) w =
        Quotient.mk (realMappingTorusSetoid phi) w' := by
  constructor
  · intro h
    change Quotient.mk _ (normalizedAffineBaseCover (m := m) phi w) =
      Quotient.mk _ (normalizedAffineBaseCover (m := m) phi w') at h
    obtain ⟨j, hj⟩ := Quotient.exact h
    have hcircle := congrArg Prod.fst hj
    have hfibre := congrArg Prod.snd hj
    change ((w'.1 / (m : ℝ) : ℝ) : UnitAddCircle) =
      ((w.1 / (m : ℝ) - (j : ℝ) / (m : ℝ) : ℝ) : UnitAddCircle) at hcircle
    obtain ⟨n, hn⟩ := (unitAddCircle_eq_iff _ _).mp hcircle
    apply (realMappingTorusMk_eq_iff phi w w').mpr
    refine ⟨j - n * (m : ℤ), ?_⟩
    rw [mappingTorusShift_apply]
    apply Prod.ext
    · have hm : (m : ℝ) ≠ 0 := by exact_mod_cast (NeZero.ne m)
      push_cast at hn ⊢
      field_simp [hm] at hn ⊢
      linarith
    · change w'.2 = (phi ^ (j - n * (m : ℤ))) w.2
      have heq : phi ^ (j - n * (m : ℤ)) = phi ^ j := by
        rw [zpow_sub, homeomorph_zpow_of_dvd phi hpow
          (n * (m : ℤ)) ⟨n, by ring⟩]
        simp
      rw [heq]
      exact hfibre
  · intro h
    obtain ⟨k, hk⟩ := (realMappingTorusMk_eq_iff phi w w').mp h
    change Quotient.mk _ (normalizedAffineBaseCover (m := m) phi w) =
      Quotient.mk _ (normalizedAffineBaseCover (m := m) phi w')
    apply Quotient.sound
    refine ⟨k, ?_⟩
    rw [hk, mappingTorusShift_apply]
    apply Prod.ext
    · change (((w.1 - (k : ℝ)) / (m : ℝ) : ℝ) : UnitAddCircle) =
        ((w.1 / (m : ℝ) - (k : ℝ) / (m : ℝ) : ℝ) : UnitAddCircle)
      congr 1
      ring
    · rfl

/-- The normalized affine cyclic quotient is the real-line model of the mapping torus. -/
public noncomputable def normalizedAffineCyclicQuotientRealMappingTorusHomeomorph
    (phi : F ≃ₜ F) (hpow : phi ^ m = 1) :
    NormalizedAffineCyclicQuotient (m := m) phi ≃ₜ RealMappingTorus phi :=
  homeomorphOfQuotientMaps
    (normalizedAffineQuotientMap_isQuotientMap phi)
    ((isOpenMap_realMappingTorusMk phi).isQuotientMap continuous_quot_mk
      Quotient.mk_surjective)
    (normalizedAffineQuotientMap_eq_iff phi hpow)

/-- The normalized affine cyclic quotient is the ordinary circle mapping torus. -/
public noncomputable def normalizedAffineCyclicQuotientCircleMappingTorusHomeomorph
    (phi : F ≃ₜ F) (hpow : phi ^ m = 1) :
    NormalizedAffineCyclicQuotient (m := m) phi ≃ₜ CircleMappingTorus phi :=
  (normalizedAffineCyclicQuotientRealMappingTorusHomeomorph phi hpow).trans
    (realMappingTorusHomeomorph phi)

/-! ## Recognition of a finite cyclic action in normal form -/

variable {X : Type} [TopologicalSpace X]

omit [NeZero m] in
public theorem finiteCyclicGeneratorPow_conjugates_normalizedAffineShift
    (A : MulAction (FiniteCyclic m) X) (e : X ≃ₜ UnitAddCircle × F)
    (phi : F ≃ₜ F)
    (hgen : ∀ x, e (actionMap A (cyclicGenerator m) x) =
      normalizedAffineShift (m := m) phi 1 (e x))
    (k : ℕ) (x : X) :
    e (actionMap A (cyclicGenerator m ^ k) x) =
      normalizedAffineShift (m := m) phi (k : ℤ) (e x) := by
  induction k with
  | zero =>
      simp [actionMap]
  | succ k ih =>
      calc
        e (actionMap A (cyclicGenerator m ^ (k + 1)) x) =
            e (actionMap A (cyclicGenerator m)
              (actionMap A (cyclicGenerator m ^ k) x)) := by
                rw [pow_succ', actionMap_mul]
        _ = normalizedAffineShift (m := m) phi 1
              (e (actionMap A (cyclicGenerator m ^ k) x)) := hgen _
        _ = normalizedAffineShift (m := m) phi 1
              (normalizedAffineShift (m := m) phi (k : ℤ) (e x)) := by rw [ih]
        _ = normalizedAffineShift (m := m) phi (1 + (k : ℤ)) (e x) :=
              (normalizedAffineShift_add phi 1 (k : ℤ) (e x)).symm
        _ = normalizedAffineShift (m := m) phi (k + 1 : ℕ) (e x) := by
              congr 2
              omega

public theorem normalizedAffineShift_eq_self_of_dvd
    (phi : F ≃ₜ F) (hpow : phi ^ m = 1) (j : ℤ) (hj : (m : ℤ) ∣ j)
    (p : UnitAddCircle × F) :
    normalizedAffineShift (m := m) phi j p = p := by
  obtain ⟨t, rfl⟩ := hj
  rw [normalizedAffineShift_apply]
  apply Prod.ext
  · have hm : (m : ℝ) ≠ 0 := by exact_mod_cast (NeZero.ne m)
    change p.1 - ((((((m : ℤ) * t : ℤ) : ℝ) / (m : ℝ) : ℝ)) : UnitAddCircle) = p.1
    rw [Int.cast_mul, Int.cast_natCast, mul_div_cancel_left₀ (t : ℝ) hm]
    simp
  · rw [homeomorph_zpow_of_dvd phi hpow ((m : ℤ) * t) ⟨t, rfl⟩]
    rfl

/-- A finite cyclic action whose generator has the normalized gamma-coordinate formula has
exactly the integer-lift relation used in `NormalizedAffineCyclicQuotient`. -/
public theorem finiteCyclicOrbitRel_iff_normalizedAffineCyclicSetoid
    (A : MulAction (FiniteCyclic m) X) (e : X ≃ₜ UnitAddCircle × F)
    (phi : F ≃ₜ F) (hpow : phi ^ m = 1)
    (hgen : ∀ x, e (actionMap A (cyclicGenerator m) x) =
      normalizedAffineShift (m := m) phi 1 (e x))
    (x y : X) :
    MulAction.orbitRel (FiniteCyclic m) X x y ↔
      normalizedAffineCyclicSetoid (m := m) phi (e x) (e y) := by
  rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff]
  constructor
  · rintro ⟨g, hg⟩
    rw [cyclic_eq_generator_pow g] at hg
    let k := (Multiplicative.toAdd g).val
    have hconj := finiteCyclicGeneratorPow_conjugates_normalizedAffineShift
      A e phi hgen k y
    change actionMap A (cyclicGenerator m ^ k) y = x at hg
    rw [hg] at hconj
    apply (normalizedAffineCyclicSetoid (m := m) phi).symm
    exact ⟨k, hconj⟩
  · rintro ⟨k, hk⟩
    obtain ⟨n, hn⟩ := exists_natCast_add_dvd (m := m) k
    refine ⟨cyclicGenerator m ^ n, ?_⟩
    change actionMap A (cyclicGenerator m ^ n) y = x
    apply e.injective
    rw [finiteCyclicGeneratorPow_conjugates_normalizedAffineShift A e phi hgen]
    rw [hk, ← normalizedAffineShift_add]
    exact normalizedAffineShift_eq_self_of_dvd phi hpow ((n : ℤ) + k) hn (e x)

/-- Quotient-to-mapping-torus recognition theorem.  Its only geometric input is the literal
generator formula in gamma-circle times three-torus coordinates. -/
public noncomputable def finiteCyclicOrbitQuotientCircleMappingTorusHomeomorph
    (A : MulAction (FiniteCyclic m) X) (e : X ≃ₜ UnitAddCircle × F)
    (phi : F ≃ₜ F) (hpow : phi ^ m = 1)
    (hgen : ∀ x, e (actionMap A (cyclicGenerator m) x) =
      normalizedAffineShift (m := m) phi 1 (e x)) :
    Quotient (MulAction.orbitRel (FiniteCyclic m) X) ≃ₜ CircleMappingTorus phi :=
  (Homeomorph.Quotient.congr e fun x y ↦
    finiteCyclicOrbitRel_iff_normalizedAffineCyclicSetoid A e phi hpow hgen x y).trans
      (normalizedAffineCyclicQuotientCircleMappingTorusHomeomorph phi hpow)

open PaperEllipticReducedCentralFiberCoverModels
open PaperEllipticReducedCentralFiberCoverModels.RadialEllipticActionData
open PaperEllipticFillingRadialRetraction

/-- Final reduction for a paper reduced central fibre.  Once its actual affine generator is
put in normalized gamma-circle times three-torus coordinates, the reduced fibre is the claimed
three-torus mapping torus. -/
public noncomputable def reducedCentralFiberCircleMappingTorusHomeomorphOfGammaNormalForm
    {T : Type} [TopologicalSpace T] [AddCommGroup T]
    (D : RadialEllipticActionData m T)
    [T2Space D.Product] [LocallyCompactSpace D.Product]
    (hfree : letI := D.actionData.diagonalAction
      IsCancelSMul (FiniteCyclic m) D.Product)
    (e : T ≃ₜ UnitAddCircle × F) (phi : F ≃ₜ F) (hpow : phi ^ m = 1)
    (hgen : ∀ x, e (D.actionData.fiberGenerator x) =
      normalizedAffineShift (m := m) phi 1 (e x)) :
    D.reducedCentralFiber ≃ₜ CircleMappingTorus phi := by
  let A := centralFiberAction D
  exact (centralFiberOrbitQuotientHomeomorph D hfree).symm.trans
    (finiteCyclicOrbitQuotientCircleMappingTorusHomeomorph A e phi hpow (by
      intro x
      rw [show actionMap A (cyclicGenerator m) x = D.actionData.fiberGenerator x by
        exact congrArg (fun g : Equiv.Perm T ↦ g x)
          (centralFiberRepresentation_generator D)]
      exact hgen x))

/-- The actual order-three reduced central fibre is the mapping torus of its transverse
three-torus clutching map. -/
public noncomputable def orderThreeReducedCentralFiberCircleMappingTorusHomeomorph
    {U : TriangleUniformization} (PF : PeriodFunctions U) :
    (orderThreeRadialActionData PF).reducedCentralFiber ≃ₜ
      CircleMappingTorus orderThreeThreeTorusClutching := by
  let p := parameterMap PF U.zOne
  let hfull := fullRankDomain p
  let _ : ProperlyDiscontinuousSMul (PeriodGroup p.1) ComplexTwoSpace :=
    periodLattice_properlyDiscontinuousSMul hfull
  let _ : T2Space (AdditiveTorus p.1) := inferInstance
  let _ : CompactSpace (AdditiveTorus p.1) := torus_compactSpace p.1 hfull
  let _ : LocallyCompactSpace (AdditiveTorus p.1) := inferInstance
  let _ : LocallyCompactSpace ComplexUnitDisc :=
    (isOpen_lt continuous_norm continuous_const).locallyCompactSpace
  exact reducedCentralFiberCircleMappingTorusHomeomorphOfGammaNormalForm
    (orderThreeRadialActionData PF)
    (orderThreeAction_free PF)
    (orderThreeGammaNormalFormHomeomorph PF)
    orderThreeThreeTorusClutching
    orderThreeThreeTorusClutching_pow
    (by
      intro x
      change orderThreeGammaNormalFormHomeomorph PF
          ((orderThreeActionData PF).fiberGenerator x) = _
      simpa [normalizedAffineShift_apply] using
        orderThreeGammaNormalForm_generator PF x)

/-- The actual order-four reduced central fibre is the mapping torus of its transverse
three-torus clutching map. -/
public noncomputable def orderFourReducedCentralFiberCircleMappingTorusHomeomorph
    {U : TriangleUniformization} (PF : PeriodFunctions U) :
    (orderFourRadialActionData PF).reducedCentralFiber ≃ₜ
      CircleMappingTorus orderFourThreeTorusClutching := by
  let p := parameterMap PF U.zTwo
  let hfull := fullRankDomain p
  let _ : ProperlyDiscontinuousSMul (PeriodGroup p.1) ComplexTwoSpace :=
    periodLattice_properlyDiscontinuousSMul hfull
  let _ : T2Space (AdditiveTorus p.1) := inferInstance
  let _ : CompactSpace (AdditiveTorus p.1) := torus_compactSpace p.1 hfull
  let _ : LocallyCompactSpace (AdditiveTorus p.1) := inferInstance
  let _ : LocallyCompactSpace ComplexUnitDisc :=
    (isOpen_lt continuous_norm continuous_const).locallyCompactSpace
  exact reducedCentralFiberCircleMappingTorusHomeomorphOfGammaNormalForm
    (orderFourRadialActionData PF)
    (orderFourAction_free PF)
    (orderFourGammaNormalFormHomeomorph PF)
    orderFourThreeTorusClutching
    orderFourThreeTorusClutching_pow
    (by
      intro x
      change orderFourGammaNormalFormHomeomorph PF
          ((orderFourActionData PF).fiberGenerator x) = _
      simpa [normalizedAffineShift_apply] using
        orderFourGammaNormalForm_generator PF x)

end NonzeroOrder

end SphereSixComplex.Topology.PaperAffineCyclicReducedFiberMappingTorus

end

end
