module

public import SphereSixComplex.Geometry.GlobalTorusFiberFundamentalGroup
public import SphereSixComplex.Geometry.PaperMarkedPuncturedBase
public import SphereSixComplex.Topology.EstablishedAffineVanKampen

/-!
# Geometric generation of the central-family fundamental group

The central family is obtained from `RegularBase × ℂ²` by the labelled period lattice and then
by the triangle group.  The two quotient-cover exact sequences, together with the zero section,
show directly that its fundamental group is generated by fibre translations and zero-section
base loops.
-/

@[expose] public section

noncomputable section

open Set Topology

namespace SphereSixComplex.Geometry.GlobalTorusFamily

open SphereSixComplex
open SphereSixComplex.Periods SphereSixComplex.TriangleGroup
open SphereSixComplex.Geometry.ComplexTorus SphereSixComplex.Geometry.TorusFamily
open SphereSixComplex.Geometry.AnalyticTorusFamily
open SphereSixComplex.TriangleGroup.FuchsianProperFreeness

variable {U : TriangleUniformization} (F : PeriodFunctions U)

/-- Pointwise-identical based paths represent the same loop class after the forced endpoint
cast. -/
private theorem loopClass_cast_eq_of_pointwise
    {X : Type*} [TopologicalSpace X] {x y : X}
    (L : Path x x) (R : Path y y) (hxy : y = x)
    (h : ∀ t, L t = R t) :
    (Path.Homotopic.Quotient.mk L).cast hxy hxy =
      Path.Homotopic.Quotient.mk R := by
  rw [← Path.Homotopic.Quotient.mk_cast]
  apply congrArg Path.Homotopic.Quotient.mk
  apply Path.ext
  funext t
  exact h t

/-- Integral period classes in the regular family, based at the zero vector over `b`. -/
public noncomputable def regularFamilyTranslationAtZero
    (b : RegularBase (U := U)) :
    IntegerPeriods →+ Additive
      (FundamentalGroup (RegularTotalSpace F)
        (regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace)))) :=
  (FundamentalGroup.mapOfEq (fiberTorusToRegularTotalSpaceContinuousMap F b)
      (by rfl)).toAdditive.comp
    (fiberTorusTranslation F b 0)

/-- The same period classes after the outer triangle-group quotient. -/
public noncomputable def centralTranslationAtZero
    (b : RegularBase (U := U)) :
    IntegerPeriods →+ Additive
      (FundamentalGroup (PuncturedGlobalFamily F)
        (regularFamilyQuotientMap F
          (regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace))))) :=
  (FundamentalGroup.map (regularFamilyQuotientMap F)
      (regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace)))).toAdditive.comp
    (regularFamilyTranslationAtZero F b)

/-- Include base loops along the zero section, with target basepoint chosen to be the same
literal quotient representative used by `centralTranslationAtZero`. -/
public noncomputable def centralZeroSectionAtLiftMap
    (b : RegularBase (U := U)) :
    FundamentalGroup (PuncturedOrbifoldBase (U := U))
        (regularBaseQuotientMap (U := U) b) →*
      FundamentalGroup (PuncturedGlobalFamily F)
        (regularFamilyQuotientMap F
          (regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace)))) :=
  FundamentalGroup.mapOfEq (puncturedGlobalZeroSection F)
    (show puncturedGlobalZeroSection F (regularBaseQuotientMap (U := U) b) =
      regularFamilyQuotientMap F
        (regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace))) by rfl)

/-- A regular-family translation is represented by the literal straight labelled-period loop. -/
public theorem regularFamilyTranslationAtZero_apply_eq_periodLoop
    (b : RegularBase (U := U)) (a : IntegerPeriods) :
    Additive.toMul (regularFamilyTranslationAtZero F b a) =
      Path.Homotopic.Quotient.mk
        (regularFamilyPeriodLoop F (b, (0 : ComplexTwoSpace)) a) := by
  unfold regularFamilyTranslationAtZero
  simp only [AddMonoidHom.comp_apply, MonoidHom.coe_toAdditive, Function.comp_apply]
  rw [fiberTorusTranslation_apply_eq_fiberPeriodClass]
  unfold fiberPeriodClass
  rw [FundamentalGroup.mapOfEq_apply]
  simp only [toMul_ofMul]
  rw [← Path.Homotopic.Quotient.mk_map]
  change ((Path.Homotopic.Quotient.mk (fiberPeriodLoop F b 0 a)).map
      (fiberTorusToRegularTotalSpaceContinuousMap F b)).cast _ _ =
    Path.Homotopic.Quotient.mk
      (regularFamilyPeriodLoop F (b, (0 : ComplexTwoSpace)) a)
  change Path.Homotopic.Quotient.mk
      (((fiberPeriodLoop F b 0 a).map
        (fiberTorusToRegularTotalSpaceContinuousMap F b).continuous).cast _ _) =
    Path.Homotopic.Quotient.mk
      (regularFamilyPeriodLoop F (b, (0 : ComplexTwoSpace)) a)
  apply congrArg Path.Homotopic.Quotient.mk
  apply Path.ext
  funext t
  rw [Path.cast_coe]
  change fiberTorusToRegularTotalSpace F b (fiberPeriodLoop F b 0 a t) =
    regularFamilyPeriodLoop F (b, (0 : ComplexTwoSpace)) a t
  rw [fiberPeriodLoop_apply, regularFamilyPeriodLoop_apply]
  change (Quotient.mk _ (b, fiberPeriodLiftPath F b 0 a t) :
      RegularTotalSpace F) =
    Quotient.mk _ (regularFamilyPeriodLiftPath F (b, 0) a t)
  apply congrArg (fun p : RegularBase (U := U) × ComplexTwoSpace ↦
    (Quotient.mk _ p : RegularTotalSpace F))
  apply Prod.ext
  · rfl
  · change AffineMap.lineMap 0
        (periodVector (regularParameterMap F b).1 a + 0) (t : ℝ) =
      (t : ℝ) • periodVector (regularParameterMap F b).1 a + 0
    simp [AffineMap.lineMap_apply_module']

/-- The inner quotient monodromy reads the exact integral label of each regular-family
translation. -/
public theorem regularFamilyTranslationAtZero_deck
    (hproper : SourceActionProperlyDiscontinuous (U := U))
    (b : RegularBase (U := U)) (a : IntegerPeriods) :
    let hp := regularFamilyCoverProjection_isQuotientCoveringMap F hproper
    hp.fundamentalGroupToMulOpposite
        ⟨(b, (0 : ComplexTwoSpace)), rfl⟩
        (Additive.toMul (regularFamilyTranslationAtZero F b a)) =
      MulOpposite.op
        (regularFamilyPeriodGroupElement F a) := by
  let hp := regularFamilyCoverProjection_isQuotientCoveringMap F hproper
  let e : (regularFamilyCoverProjection F) ⁻¹'
      {regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace))} :=
    ⟨(b, (0 : ComplexTwoSpace)), by simp⟩
  change hp.fundamentalGroupToMulOpposite
      e
      (Additive.toMul (regularFamilyTranslationAtZero F b a)) = _
  rw [regularFamilyTranslationAtZero_apply_eq_periodLoop]
  apply (hp.fundamentalGroupToMulOpposite_apply_eq_Iff).mpr
  have hend : regularFamilyCoverProjection F
        (regularFamilyPeriodGroupElement F a •
          (b, (0 : ComplexTwoSpace))) =
      regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace)) := by
    exact regularFamilyProjection_period_smul F (b, (0 : ComplexTwoSpace)) a
  let e' : (regularFamilyCoverProjection F) ⁻¹'
      {regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace))} :=
    ⟨regularFamilyPeriodGroupElement F a •
      (b, (0 : ComplexTwoSpace)), hend⟩
  have hm : hp.isCoveringMap.monodromy
        (Path.Homotopic.Quotient.mk
          (regularFamilyPeriodLoop F (b, (0 : ComplexTwoSpace)) a)) e = e' :=
    hp.isCoveringMap.monodromy_eq_of_map_eq
      (Path.Homotopic.Quotient.mk
        (regularFamilyPeriodLiftPath F (b, (0 : ComplexTwoSpace)) a)) (by rfl)
  exact congrArg Subtype.val hm.symm

/-- The zero section intertwines base-cover and central-family monodromy with the identity map on
the common triangle-group deck group. -/
public theorem zeroSection_fundamentalGroupToMulOpposite
    (hsource : U.sourceAction = fuchsianSourceAction)
    (hproper : SourceActionProperlyDiscontinuous (U := U))
    (b : RegularBase (U := U))
    (γ : FundamentalGroup (PuncturedOrbifoldBase (U := U))
      (regularBaseQuotientMap (U := U) b)) :
    letI := regularSourceMulAction U
    letI := regularFamilyDeckAction F
    let hpB := regularBaseQuotientMap_isQuotientCoveringMap hsource hproper
    let hpE := regularFamilyQuotientMap_isQuotientCoveringMap F hsource hproper
    let hzero : regularFamilyQuotientMap F (regularFamilyZeroSection F b) =
        puncturedGlobalZeroSection F (regularBaseQuotientMap (U := U) b) := rfl
    hpE.fundamentalGroupToMulOpposite
        ⟨regularFamilyZeroSection F b, hzero⟩
        (centralZeroSectionAtLiftMap F b γ) =
      hpB.fundamentalGroupToMulOpposite ⟨b, rfl⟩ γ := by
  let _ := regularSourceMulAction U
  let _ := regularFamilyDeckAction F
  let hpB := regularBaseQuotientMap_isQuotientCoveringMap hsource hproper
  let hpE := regularFamilyQuotientMap_isQuotientCoveringMap F hsource hproper
  let eB : (regularBaseQuotientMap (U := U)) ⁻¹'
      {regularBaseQuotientMap (U := U) b} := ⟨b, by simp⟩
  change hpE.fundamentalGroupToMulOpposite
      ⟨regularFamilyZeroSection F b, rfl⟩
      (FundamentalGroup.mapOfEq (puncturedGlobalZeroSection F)
        (puncturedGlobalZeroSection_mk F b) γ) =
    hpB.fundamentalGroupToMulOpposite eB γ
  refine (hpE.fundamentalGroupToMulOpposite_apply_eq_Iff).mpr ?_
  have hbase :
      (hpB.fundamentalGroupToMulOpposite eB γ).unop • b =
        (hpB.isCoveringMap.monodromy γ eB : RegularBase (U := U)) :=
    hpB.unop_fundamentalGroupToMulOpposite_smul
  have hnat := monodromy_naturality hpB.isCoveringMap hpE.isCoveringMap
    (regularFamilyZeroSection F) (puncturedGlobalZeroSection F)
    (puncturedGlobalZeroSection_mk F) b γ
  change regularFamilyDeckMap F
      (hpB.fundamentalGroupToMulOpposite eB γ).unop
      (regularFamilyZeroSection F b) =
    (hpE.isCoveringMap.monodromy
      (FundamentalGroup.mapOfEq (puncturedGlobalZeroSection F)
        (puncturedGlobalZeroSection_mk F b) γ)
      ⟨regularFamilyZeroSection F b, rfl⟩ : RegularTotalSpace F)
  calc
    _ = regularFamilyZeroSection F
          ((hpB.fundamentalGroupToMulOpposite eB γ).unop • b) :=
      regularFamilyZeroSection_equivariant F _ b
    _ = regularFamilyZeroSection F
          (hpB.isCoveringMap.monodromy γ eB : RegularBase (U := U)) :=
      congrArg (regularFamilyZeroSection F) hbase
    _ = _ := by
      convert hnat.symm using 1 <;> congr 2

/-- A loop in the labelled vector-bundle cover contributes, after passage to the central
family, only a zero-section base loop. -/
public theorem regularCoverFundamentalGroup_map_mem_zeroSection_range
    (b : RegularBase (U := U))
    (ε : FundamentalGroup (RegularBase (U := U) × ComplexTwoSpace)
      (b, (0 : ComplexTwoSpace))) :
    FundamentalGroup.map
        ((regularFamilyQuotientMap F).comp (regularFamilyCoverProjection F))
        (b, (0 : ComplexTwoSpace)) ε ∈
      (centralZeroSectionAtLiftMap F b).range := by
  induction ε using Quotient.ind with
  | _ P =>
      let β : FundamentalGroup (PuncturedOrbifoldBase (U := U))
          (regularBaseQuotientMap (U := U) b) :=
        Path.Homotopic.Quotient.mk
          ((P.map continuous_fst).map (regularBaseQuotientMap (U := U)).continuous)
      refine ⟨β, ?_⟩
      unfold β
      unfold centralZeroSectionAtLiftMap
      rw [FundamentalGroup.mapOfEq_apply]
      change
        ((Path.Homotopic.Quotient.mk
          ((P.map continuous_fst).map
            (regularBaseQuotientMap (U := U)).continuous)).map
            (puncturedGlobalZeroSection F)).cast _ _ =
          (Path.Homotopic.Quotient.mk P).map
            ((regularFamilyQuotientMap F).comp (regularFamilyCoverProjection F))
      rw [← Path.Homotopic.Quotient.mk_map,
        ← Path.Homotopic.Quotient.mk_map]
      let L := (((P.map continuous_fst).map
        (regularBaseQuotientMap (U := U)).continuous).map
          (puncturedGlobalZeroSection F).continuous)
      let R := (regularCoverBaseZeroPath P).map
        (((regularFamilyQuotientMap F).comp
          (regularFamilyCoverProjection F)).continuous)
      have hcast : (Path.Homotopic.Quotient.mk L).cast
          (puncturedGlobalZeroSection_mk F b).symm
          (puncturedGlobalZeroSection_mk F b).symm =
        Path.Homotopic.Quotient.mk R := by
        apply loopClass_cast_eq_of_pointwise
        intro t
        rfl
      have hmapped := Path.Homotopic.map
        (regularCoverLoop_homotopic_baseZero P)
        ((regularFamilyQuotientMap F).comp (regularFamilyCoverProjection F))
      calc
        _ = Path.Homotopic.Quotient.mk R := hcast
        _ = _ := (Path.Homotopic.Quotient.eq.mpr hmapped).symm

/-- The kernel of the labelled-period monodromy maps into the zero-section subgroup after the
outer quotient. -/
public theorem regularFamily_innerKernel_map_mem_zeroSection_range
    (hproper : SourceActionProperlyDiscontinuous (U := U))
    (b : RegularBase (U := U))
    (δ : FundamentalGroup (RegularTotalSpace F) (regularFamilyZeroSection F b))
    (hδ :
      let hp := regularFamilyCoverProjection_isQuotientCoveringMap F hproper
      hp.fundamentalGroupToMulOpposite
        ⟨(b, (0 : ComplexTwoSpace)), rfl⟩ δ = 1) :
    FundamentalGroup.map (regularFamilyQuotientMap F)
        (regularFamilyZeroSection F b) δ ∈
      (centralZeroSectionAtLiftMap F b).range := by
  let hp := regularFamilyCoverProjection_isQuotientCoveringMap F hproper
  let e : (regularFamilyCoverProjection F) ⁻¹'
      {regularFamilyZeroSection F b} :=
    ⟨(b, (0 : ComplexTwoSpace)), rfl⟩
  change hp.fundamentalGroupToMulOpposite e δ = 1 at hδ
  have hker : δ ∈ (hp.fundamentalGroupToMulOpposite e).ker :=
    (MonoidHom.mem_ker).mpr hδ
  rw [hp.ker_fundamentalGroupToMulOpposite,
    hp.ker_monodromyPerm e] at hker
  obtain ⟨ε, hε⟩ := hker
  let p' : C(RegularBase (U := U) × ComplexTwoSpace, RegularTotalSpace F) :=
    ⟨regularFamilyCoverProjection F, hp.continuous⟩
  change FundamentalGroup.mapOfEq p' e.property ε = δ at hε
  dsimp [e] at ε hε
  let hzero : regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace)) =
      regularFamilyZeroSection F b := rfl
  have hp' : p' = regularFamilyCoverProjection F := by
    apply ContinuousMap.ext
    intro x
    rfl
  have hε' : FundamentalGroup.mapOfEq (regularFamilyCoverProjection F) hzero ε = δ :=
    (TauCeti.FundamentalGroup.mapOfEq_congr hp' _ hzero ε).symm.trans hε
  have hdirect := regularCoverFundamentalGroup_map_mem_zeroSection_range F b ε
  let C' := (regularFamilyQuotientMap F).comp (regularFamilyCoverProjection F)
  let hC : C' (b, (0 : ComplexTwoSpace)) =
      regularFamilyQuotientMap F (regularFamilyZeroSection F b) := rfl
  have hcomp := TauCeti.FundamentalGroup.mapOfEq_comp
    (regularFamilyQuotientMap F) (regularFamilyCoverProjection F)
    hzero
    (rfl : regularFamilyQuotientMap F (regularFamilyZeroSection F b) =
      regularFamilyQuotientMap F (regularFamilyZeroSection F b)) ε
  have hcomp' :
      FundamentalGroup.map (regularFamilyQuotientMap F)
          (regularFamilyZeroSection F b)
          (FundamentalGroup.mapOfEq (regularFamilyCoverProjection F)
            hzero ε) =
        FundamentalGroup.mapOfEq C' hC ε := by
    simpa only [TauCeti.FundamentalGroup.mapOfEq_rfl] using hcomp
  have hCeq : FundamentalGroup.mapOfEq C' hC ε =
      FundamentalGroup.map C' (b, (0 : ComplexTwoSpace)) ε := by
    have hrfl := congrArg (fun f ↦ f ε)
      (TauCeti.FundamentalGroup.mapOfEq_rfl
        (x := (b, (0 : ComplexTwoSpace))) C')
    calc
      _ = FundamentalGroup.mapOfEq C'
          (rfl : C' (b, (0 : ComplexTwoSpace)) =
            C' (b, (0 : ComplexTwoSpace))) ε :=
        TauCeti.FundamentalGroup.mapOfEq_congr rfl hC rfl ε
      _ = _ := hrfl
  rw [← hε', hcomp', hCeq]
  exact hdirect

/-- Fibre translations together with all zero-section loops generate the fundamental group of
the punctured central family. -/
public theorem centralFundamentalGroup_generated_by_translations_and_zeroSection
    (hsource : U.sourceAction = fuchsianSourceAction)
    (hproper : SourceActionProperlyDiscontinuous (U := U))
    (b : RegularBase (U := U)) :
    Subgroup.closure
      (Set.range (fun a ↦ Additive.toMul (centralTranslationAtZero F b a)) ∪
        Set.range (centralZeroSectionAtLiftMap F b)) = ⊤ := by
  let _ := regularSourceMulAction U
  let _ := regularFamilyDeckAction F
  let _ : PathConnectedSpace (RegularBase (U := U)) := regularBase_pathConnected U
  let _ : PathConnectedSpace (RegularTotalSpace F) := regularTotalSpace_pathConnected F
  let hpB := regularBaseQuotientMap_isQuotientCoveringMap hsource hproper
  let hpE := regularFamilyQuotientMap_isQuotientCoveringMap F hsource hproper
  let hpI := regularFamilyCoverProjection_isQuotientCoveringMap F hproper
  let eB : (regularBaseQuotientMap (U := U)) ⁻¹'
      {regularBaseQuotientMap (U := U) b} := ⟨b, by simp⟩
  let eE : (regularFamilyQuotientMap F) ⁻¹'
      {regularFamilyQuotientMap F
        (regularFamilyCoverProjection F (b, (0 : ComplexTwoSpace)))} :=
    ⟨regularFamilyZeroSection F b, rfl⟩
  let eI : (regularFamilyCoverProjection F) ⁻¹'
      {regularFamilyZeroSection F b} :=
    ⟨(b, (0 : ComplexTwoSpace)), rfl⟩
  let zeroMap := centralZeroSectionAtLiftMap F b
  let K := Subgroup.closure
    (Set.range (fun a ↦ Additive.toMul (centralTranslationAtZero F b a)) ∪
      Set.range zeroMap)
  apply top_unique
  intro γ _
  obtain ⟨β, hβ⟩ := hpB.fundamentalGroupToMulOpposite_surjective eB
    (hpE.fundamentalGroupToMulOpposite eE γ)
  have hzeroDeck : hpE.fundamentalGroupToMulOpposite eE (zeroMap β) =
      hpB.fundamentalGroupToMulOpposite eB β := by
    convert zeroSection_fundamentalGroupToMulOpposite F hsource hproper b β using 1 <;>
      congr 2
  let κ := γ * (zeroMap β)⁻¹
  have hκker : κ ∈ (hpE.fundamentalGroupToMulOpposite eE).ker := by
    apply (MonoidHom.mem_ker).mpr
    change hpE.fundamentalGroupToMulOpposite eE
      (γ * (zeroMap β)⁻¹) = 1
    rw [map_mul, map_inv, hzeroDeck, hβ]
    simp
  rw [hpE.ker_fundamentalGroupToMulOpposite,
    hpE.ker_monodromyPerm eE] at hκker
  obtain ⟨δ, hδ⟩ := hκker
  change FundamentalGroup (RegularTotalSpace F)
    (regularFamilyZeroSection F b) at δ
  let a : IntegerPeriods :=
    (hpI.fundamentalGroupToMulOpposite eI δ).unop.coeff
  let τ : FundamentalGroup (RegularTotalSpace F) (regularFamilyZeroSection F b) :=
    Additive.toMul (regularFamilyTranslationAtZero F b a)
  have hτdeck : hpI.fundamentalGroupToMulOpposite eI τ =
      MulOpposite.op (regularFamilyPeriodGroupElement F a) := by
    convert regularFamilyTranslationAtZero_deck F hproper b a using 1 <;>
      congr 2
  have hδdeck : hpI.fundamentalGroupToMulOpposite eI δ =
      MulOpposite.op (regularFamilyPeriodGroupElement F a) := by
    apply MulOpposite.unop_injective
    dsimp [a]
    rfl
  let r := δ * τ⁻¹
  have hrdeck : hpI.fundamentalGroupToMulOpposite eI r = 1 := by
    change hpI.fundamentalGroupToMulOpposite eI (δ * τ⁻¹) = 1
    rw [map_mul, map_inv, hδdeck, hτdeck]
    simp
  have hrange := regularFamily_innerKernel_map_mem_zeroSection_range
    F hproper b r (by convert hrdeck using 1 <;> congr 2)
  have hrK : FundamentalGroup.map (regularFamilyQuotientMap F)
      (regularFamilyZeroSection F b) r ∈ K := by
    apply Subgroup.subset_closure
    exact Or.inr hrange
  have hτK : FundamentalGroup.map (regularFamilyQuotientMap F)
      (regularFamilyZeroSection F b) τ ∈ K := by
    apply Subgroup.subset_closure
    apply Or.inl
    refine ⟨a, ?_⟩
    rfl
  have hδK : FundamentalGroup.map (regularFamilyQuotientMap F)
      (regularFamilyZeroSection F b) δ ∈ K := by
    have hrmul : r * τ = δ := by
      change (δ * τ⁻¹) * τ = δ
      exact inv_mul_cancel_right δ τ
    rw [← hrmul, map_mul]
    exact K.mul_mem hrK hτK
  let q' : C(RegularTotalSpace F, PuncturedGlobalFamily F) :=
    ⟨regularFamilyQuotientMap F, hpE.continuous⟩
  change FundamentalGroup.mapOfEq q' eE.property δ = κ at hδ
  have hq' : q' = regularFamilyQuotientMap F := by
    apply ContinuousMap.ext
    intro x
    rfl
  have hmapδ : FundamentalGroup.mapOfEq q' eE.property δ =
      FundamentalGroup.map (regularFamilyQuotientMap F)
        (regularFamilyZeroSection F b) δ := by
    have hcongr := TauCeti.FundamentalGroup.mapOfEq_congr hq' eE.property
      (rfl : regularFamilyQuotientMap F (regularFamilyZeroSection F b) =
        regularFamilyQuotientMap F (regularFamilyZeroSection F b)) δ
    calc
      _ = FundamentalGroup.mapOfEq (regularFamilyQuotientMap F)
          (rfl : regularFamilyQuotientMap F (regularFamilyZeroSection F b) =
            regularFamilyQuotientMap F (regularFamilyZeroSection F b)) δ := hcongr
      _ = _ := congrArg (fun f ↦ f δ)
        (TauCeti.FundamentalGroup.mapOfEq_rfl
          (x := regularFamilyZeroSection F b) (regularFamilyQuotientMap F))
  have hκK : κ ∈ K := by
    rw [← hδ, hmapδ]
    exact hδK
  have hzeroK : zeroMap β ∈ K := by
    apply Subgroup.subset_closure
    exact Or.inr ⟨β, rfl⟩
  have hκmul : κ * zeroMap β = γ := by
    change (γ * (zeroMap β)⁻¹) * zeroMap β = γ
    exact inv_mul_cancel_right γ (zeroMap β)
  rw [← hκmul]
  exact K.mul_mem hκK hzeroK

end SphereSixComplex.Geometry.GlobalTorusFamily

end
