module

public import SphereSixComplex.Geometry.PaperSectionSevenHomology
public import SphereSixComplex.Topology.PaperActualVanKampenCover
public import SphereSixComplex.Topology.ManifoldLocallyContractible
public import SphereSixComplex.Topology.EstablishedBasedVanKampen

/-!
# Van Kampen inputs for the actual analytic star

The glued star is a complex manifold, so it is strongly locally contractible, hence locally path
connected and semilocally simply connected, and — being connected — path connected. Those are
exactly the hypotheses of the covering-space van Kampen generation theorem, so for the actual star
the core inclusion surjects on the fundamental group as soon as each filling's fundamental group is
generated by its overlap with the core.

That last statement is the remaining geometric input on this side: it is the assertion that
`π₁(collar) → π₁(filling)` is onto for the cusp filling and the two elliptic fillings, which the
filling cover squares supply through `ToricFillingPiOneData.map_surjective` and
`CyclicAffineFillingPiOneData.map_surjective` once those squares are built for the actual fillings.
-/

@[expose] public section

noncomputable section

open scoped ContDiff Manifold

namespace SphereSixComplex.Geometry.PaperAnalyticData

variable (P : PaperAnalyticData)

/-- The charted structure on the glued analytic star. -/
@[instance_reducible]
public noncomputable def vanKampenCharts :
    ChartedSpace ComplexModel (VanKampenSpace P) := by
  let A := P.openEmbeddingStarData.toFourPieceStarGluingData
  let D := A.glueData
  let _ := A.nonemptyPieceOfCollars P.fourPieceStarGluingData_nonemptyCentralCollar
  let _ := P.biholomorphicFourPieceStarData.complexCharts
  exact gluedChartedSpace D

public theorem vanKampen_locallyNice :
    letI := P.vanKampenCharts
    StronglyLocallyContractibleSpace (VanKampenSpace P) := by
  let _ := P.vanKampenCharts
  have _ : StronglyLocallyContractibleSpace ComplexModel :=
    normedSpace_stronglyLocallyContractibleSpace
  exact ChartedSpace.stronglyLocallyContractibleSpace (H := ComplexModel)

/-- The base point of the actual four-piece van Kampen cover. -/
public noncomputable def vanKampenBase : VanKampenSpace P :=
  P.openEmbeddingStarData.collarSourceToGlued 0
    (Classical.choice (P.starCollarSourceType_nonempty 0))

public theorem vanKampen_connected : ConnectedSpace (VanKampenSpace P) := by
  let A := P.openEmbeddingStarData.toFourPieceStarGluingData
  let D := A.glueData
  let _ : Nonempty D.J := by
    change Nonempty (Option (Fin 3))
    infer_instance
  let _ := A.nonemptyPieceOfCollars P.fourPieceStarGluingData_nonemptyCentralCollar
  let _ (i : D.J) := P.starPiece_connected i
  exact connectedSpace_gluedSpace D
    (A.intersectionGraphConnected P.fourPieceStarGluingData_nonemptyCentralCollar)

public theorem vanKampen_pathConnected :
    letI := P.vanKampenCharts
    PathConnectedSpace (VanKampenSpace P) := by
  let _ := P.vanKampenCharts
  have _ : StronglyLocallyContractibleSpace (VanKampenSpace P) := P.vanKampen_locallyNice
  have _ : ConnectedSpace (VanKampenSpace P) := P.vanKampen_connected
  exact pathConnectedSpace_iff_connectedSpace.mpr inferInstance

public theorem vanKampen_semilocallySimplyConnected :
    letI := P.vanKampenCharts
    TauCeti.SemilocallySimplyConnectedSpace (VanKampenSpace P) := by
  let _ := P.vanKampenCharts
  have _ : StronglyLocallyContractibleSpace ComplexModel :=
    normedSpace_stronglyLocallyContractibleSpace
  exact ChartedSpace.semilocallySimplyConnectedSpace (H := ComplexModel)

/-- For the actual star, the core inclusion surjects on the fundamental group as soon as each
filling's fundamental group is generated by its overlap with the core. -/
public theorem actualCoreFundamentalGroupMap_surjective
    (hcusp : Function.Surjective
      (P.actualVanKampenFourPieceCover.cuspOverlapFundamentalGroupMap))
    (hthree : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticThreeOverlapFundamentalGroupMap))
    (hfour : Function.Surjective
      (P.actualVanKampenFourPieceCover.ellipticFourOverlapFundamentalGroupMap)) :
    Function.Surjective (P.actualVanKampenFourPieceCover.coreFundamentalGroupMap) := by
  let _ := P.vanKampenCharts
  have _ : StronglyLocallyContractibleSpace (VanKampenSpace P) := P.vanKampen_locallyNice
  have _ : PathConnectedSpace (VanKampenSpace P) := P.vanKampen_pathConnected
  have _ : TauCeti.SemilocallySimplyConnectedSpace (VanKampenSpace P) :=
    P.vanKampen_semilocallySimplyConnected
  exact Topology.PaperVanKampenFourPieceCover.coreFundamentalGroupMap_surjective_of_overlap_surjective
    P.actualVanKampenFourPieceCover hcusp hthree hfour

end SphereSixComplex.Geometry.PaperAnalyticData

end

end
