module

public import SphereSixComplex.Geometry.PaperOpenEmbeddingStar
public import SphereSixComplex.Topology.PaperEllipticTorusHomologyBasis
public import SphereSixComplex.Topology.WangHomologyPresentation

/-!
# Mapping-torus adapters for the three paper collars

The analytic collar files already provide the actual cusp transport and the two actual affine
elliptic fibre generators.  What they do not yet provide is a global angular fundamental domain
whose two ends are identified by those maps.  This file isolates exactly that remaining
clutching-presentation input.

The general comparison with `CircleMappingTorus` is proved from quotient topology.  No homology
of a paper collar and no map in the paper's Mayer--Vietoris sequence is assumed here.
-/

@[expose] public section

noncomputable section

open Topology
open scoped ContinuousMap

namespace SphereSixComplex

variable {E F : Type} [TopologicalSpace E] [TopologicalSpace F]

/-- The cylinder projection to the explicit one-loop mapping torus. -/
public def circleMappingTorusCylinderProjection (φ : F ≃ₜ F) :
    C(unitInterval × F, CircleMappingTorus φ) :=
  ⟨fun p ↦ Quotient.mk (finiteBouquetMappingTorusSetoid (fun _ : Unit ↦ φ)) ((), p),
    continuous_quot_mk.comp (continuous_const.prodMk continuous_id)⟩

/-- A chosen interval trivialization of a circle bundle, stated at the exact quotient-topology
level needed to recover its total space.  The last field says that its only identifications are
the endpoint identifications generated by the clutching homeomorphism. -/
public structure IntervalClutchingQuotientData (E F : Type)
    [TopologicalSpace E] [TopologicalSpace F] (φ : F ≃ₜ F) where
  projection : C(unitInterval × F, E)
  projection_surjective : Function.Surjective projection
  projection_isQuotientMap : IsQuotientMap projection
  projection_eq_iff : ∀ p q,
    projection p = projection q ↔
      circleMappingTorusCylinderProjection φ p =
        circleMappingTorusCylinderProjection φ q

namespace IntervalClutchingQuotientData

variable {φ : F ≃ₜ F} (D : IntervalClutchingQuotientData E F φ)

/-- The map from the explicit mapping torus to a total space presented by the same clutching
quotient. -/
public def circleToTotal : CircleMappingTorus φ → E :=
  Quotient.lift (fun p ↦ D.projection p.2) fun p q hpq ↦ by
    apply (D.projection_eq_iff p.2 q.2).mpr
    exact Quotient.sound hpq

public theorem circleToTotal_mk (p : unitInterval × F) :
    D.circleToTotal (circleMappingTorusCylinderProjection φ p) = D.projection p :=
  rfl

public theorem circleToTotal_continuous : Continuous D.circleToTotal := by
  apply continuous_quot_lift
  exact D.projection.continuous.comp continuous_snd

public theorem circleToTotal_bijective : Function.Bijective D.circleToTotal := by
  constructor
  · intro x y hxy
    induction x using Quotient.inductionOn with
    | _ p =>
      induction y using Quotient.inductionOn with
      | _ q =>
        apply (D.projection_eq_iff p.2 q.2).mp
        exact hxy
  · intro y
    obtain ⟨p, hp⟩ := D.projection_surjective y
    exact ⟨circleMappingTorusCylinderProjection φ p, by simpa [hp]⟩

/-- A total space with an exact interval clutching presentation is homeomorphic to the explicit
mapping torus of its clutching map. -/
public def totalHomeomorphCircleMappingTorus : E ≃ₜ CircleMappingTorus φ := by
  let e : CircleMappingTorus φ ≃ E := Equiv.ofBijective D.circleToTotal D.circleToTotal_bijective
  have he : Continuous e := D.circleToTotal_continuous
  have hcomp : e.symm ∘ D.projection = circleMappingTorusCylinderProjection φ := by
    funext p
    apply e.injective
    simp only [Function.comp_apply, Equiv.apply_symm_apply]
    exact D.circleToTotal_mk p
  exact (Homeomorph.mk e he
    (D.projection_isQuotientMap.continuous_iff.mpr (hcomp ▸
      (circleMappingTorusCylinderProjection φ).continuous))).symm

end IntervalClutchingQuotientData

namespace WangHomologyPresentation

variable {HighRelations High Total Total' LowRelations Low : Type*}
  [AddCommGroup HighRelations] [AddCommGroup High] [AddCommGroup Total]
  [AddCommGroup Total'] [AddCommGroup LowRelations] [AddCommGroup Low]

/-- Transport only the middle group of a Wang presentation across an additive equivalence. -/
public def transportTotal
    (P : WangHomologyPresentation HighRelations High Total LowRelations Low)
    (e : Total' ≃+ Total) :
    WangHomologyPresentation HighRelations High Total' LowRelations Low where
  highDifference := P.highDifference
  inclusion := e.symm.toAddMonoidHom.comp P.inclusion
  boundary := P.boundary.comp e.toAddMonoidHom
  lowDifference := P.lowDifference
  exact_highDifference_inclusion := by
    intro y
    change e.symm (P.inclusion y) = 0 ↔ _
    rw [← P.exact_highDifference_inclusion y]
    constructor
    · intro h
      exact e.symm.injective (by simpa using h)
    · intro h
      simp [h]
  exact_inclusion_boundary := by
    intro y
    change P.boundary (e y) = 0 ↔ _
    rw [P.exact_inclusion_boundary (e y)]
    constructor
    · rintro ⟨x, hx⟩
      exact ⟨x, e.injective (by simpa using hx)⟩
    · rintro ⟨x, rfl⟩
      exact ⟨x, by simp⟩
  exact_boundary_lowDifference := by
    intro y
    rw [P.exact_boundary_lowDifference y]
    constructor
    · rintro ⟨x, hx⟩
      exact ⟨e.symm x, by simpa using hx⟩
    · rintro ⟨x, hx⟩
      exact ⟨e x, by simpa using hx⟩

end WangHomologyPresentation

/-- Transport the circle Wang presentation to any total space homeomorphic to the explicit
mapping torus. -/
public def circleWangPresentationOfTotalHomeomorph
    {E F : Type} [TopologicalSpace E] [TopologicalSpace F]
    (φ : F ≃ₜ F) (e : E ≃ₜ CircleMappingTorus φ) (k : ℕ) :
    WangHomologyPresentation
      (IntegralSingularHomology (k + 1) F)
      (IntegralSingularHomology (k + 1) F)
      (IntegralSingularHomology (k + 1) E)
      (IntegralSingularHomology k F)
      (IntegralSingularHomology k F) :=
  (circleMappingTorusWangPresentation φ k).transportTotal
    (integralSingularHomologyEquiv (k + 1) e)

namespace Geometry

open Matrix
open AnalyticTorusFamily ComplexTorus EllipticActualActionTopology EllipticFamilySpecialization
open EllipticFixedPointCriterion
open EllipticLogarithmicGaugeDescent EllipticPuncturedCollarGaugeHomeomorph
open EllipticVaryingFamilyQuotient
open EquivariantQuotientHomeomorph
open FamilyEquivariance GlobalTorusFamily
open SphereSixComplex.LatticeData SphereSixComplex.Periods SphereSixComplex.TriangleGroup

/-- A continuous permutation of order three is a self-homeomorphism. -/
public noncomputable def orderThreeHomeomorphOfContinuousPerm
    {X : Type} [TopologicalSpace X] (e : Equiv.Perm X) (he : Continuous e)
    (hp : e ^ 3 = 1) : X ≃ₜ X := by
  have hi : e.symm = e ^ 2 := by
    change e⁻¹ = e ^ 2
    calc
      e⁻¹ = e⁻¹ * 1 := by simp
      _ = e⁻¹ * e ^ 3 := by rw [hp]
      _ = e ^ 2 := by group
  refine { toEquiv := e, continuous_toFun := he, continuous_invFun := ?_ }
  change Continuous (e.symm : X → X)
  rw [hi]
  exact continuous_equiv_pow e he 2

/-- A continuous permutation of order four is a self-homeomorphism. -/
public noncomputable def orderFourHomeomorphOfContinuousPerm
    {X : Type} [TopologicalSpace X] (e : Equiv.Perm X) (he : Continuous e)
    (hp : e ^ 4 = 1) : X ≃ₜ X := by
  have hi : e.symm = e ^ 3 := by
    change e⁻¹ = e ^ 3
    calc
      e⁻¹ = e⁻¹ * 1 := by simp
      _ = e⁻¹ * e ^ 4 := by rw [hp]
      _ = e ^ 3 := by group
  refine { toEquiv := e, continuous_toFun := he, continuous_invFun := ?_ }
  change Continuous (e.symm : X → X)
  rw [hi]
  exact continuous_equiv_pow e he 3

/-- The actual translated order-three affine generator, now packaged as a homeomorphism. -/
public noncomputable def orderThreeAffineClutchingHomeomorph
    {U : TriangleUniformization} (F : PeriodFunctions U) :
    AdditiveTorus (parameterMap F U.zOne).1 ≃ₜ
      AdditiveTorus (parameterMap F U.zOne).1 :=
  orderThreeHomeomorphOfContinuousPerm
    (orderThreeActionData F).fiberGenerator
    (orderThreeFiberGenerator_continuous F)
    (orderThreeActionData F).fiberGenerator_pow

/-- The actual translated order-four affine generator, now packaged as a homeomorphism. -/
public noncomputable def orderFourAffineClutchingHomeomorph
    {U : TriangleUniformization} (F : PeriodFunctions U) :
    AdditiveTorus (parameterMap F U.zTwo).1 ≃ₜ
      AdditiveTorus (parameterMap F U.zTwo).1 :=
  orderFourHomeomorphOfContinuousPerm
    (orderFourActionData F).fiberGenerator
    (orderFourFiberGenerator_continuous F)
    (orderFourActionData F).fiberGenerator_pow

public theorem orderThreeAffineClutchingHomeomorph_apply
    {U : TriangleUniformization} (F : PeriodFunctions U)
    (x : AdditiveTorus (parameterMap F U.zOne).1) :
    orderThreeAffineClutchingHomeomorph F x =
      (orderThreeDescendedAffineTorusAutomorphism F).map x := by
  change (orderThreeActionData F).fiberGenerator x =
    orderThreeFiberAutomorphism F x +
      orderThreeTranslation (parameterMap F U.zOne).1
  rfl

public theorem orderFourAffineClutchingHomeomorph_apply
    {U : TriangleUniformization} (F : PeriodFunctions U)
    (x : AdditiveTorus (parameterMap F U.zTwo).1) :
    orderFourAffineClutchingHomeomorph F x =
      (orderFourDescendedAffineTorusAutomorphism F).map x := by
  change (orderFourActionData F).fiberGenerator x =
    orderFourFiberAutomorphism F x +
      orderFourTranslation (parameterMap F U.zTwo).1
  rfl

/-- In the established degree-one torus basis, the actual order-three clutching map is `A₁`. -/
public theorem orderThreeAffineClutching_homology_degreeOne_matrix
    {U : TriangleUniformization} (F : PeriodFunctions U)
    (x : IntegralSingularHomology 1 (AdditiveTorus (parameterMap F U.zOne).1)) :
    (orderThreeTorusHomologyBasis F).degreeOne
        (integralSingularHomologyMap 1 (orderThreeAffineClutchingHomeomorph F) x) =
      A₁ *ᵥ (orderThreeTorusHomologyBasis F).degreeOne x := by
  have hmap :
      (orderThreeAffineClutchingHomeomorph F :
        C(AdditiveTorus (parameterMap F U.zOne).1,
          AdditiveTorus (parameterMap F U.zOne).1)) =
        (orderThreeDescendedAffineTorusAutomorphism F).map := by
    ext y
    exact orderThreeAffineClutchingHomeomorph_apply F y
  rw [hmap, orderThreeFiberGenerator_homology_degreeOne]
  exact rhoLambda_g₁_apply _

/-- In the established degree-one torus basis, the actual order-four clutching map is `A₂`. -/
public theorem orderFourAffineClutching_homology_degreeOne_matrix
    {U : TriangleUniformization} (F : PeriodFunctions U)
    (x : IntegralSingularHomology 1 (AdditiveTorus (parameterMap F U.zTwo).1)) :
    (orderFourTorusHomologyBasis F).degreeOne
        (integralSingularHomologyMap 1 (orderFourAffineClutchingHomeomorph F) x) =
      A₂ *ᵥ (orderFourTorusHomologyBasis F).degreeOne x := by
  have hmap :
      (orderFourAffineClutchingHomeomorph F :
        C(AdditiveTorus (parameterMap F U.zTwo).1,
          AdditiveTorus (parameterMap F U.zTwo).1)) =
        (orderFourDescendedAffineTorusAutomorphism F).map := by
    ext y
    exact orderFourAffineClutchingHomeomorph_apply F y
  rw [hmap, orderFourFiberGenerator_homology_degreeOne]
  exact rhoLambda_g₂_apply _

/-- The raw cusp endpoint transport sends period `n` to the period indexed by `M₀ n`. -/
public theorem cuspRawTransport_period_mZero
    (x : PeriodDomain) (n : IntegerPeriods) :
    periodTransport g₀ x (periodVector x.1 n) =
      periodVector (rhoParameters g₀ x).1 (M₀ *ᵥ n) := by
  rw [periodTransport_periodVector, rhoLambda_g₀_apply]

namespace PaperAnalyticData

variable (A : PaperAnalyticData)

/-- The restricted linear cyclic quotient already reached by the proved order-three gauge. -/
public noncomputable abbrev orderThreeLinearCollarType :=
  Quotient (restrictedOrbitRel (orderThreeLinearFamilyAction A.periods)
    (orderThreeLinearPuncturedCarrier A.periods
      A.modular.modularParameter.toTriangleUniformization_sourceAction
      A.starSeparation.orderThree.radius))

/-- The restricted linear cyclic quotient already reached by the proved order-four gauge. -/
public noncomputable abbrev orderFourLinearCollarType :=
  Quotient (restrictedOrbitRel (orderFourLinearFamilyAction A.periods)
    (orderFourLinearPuncturedCarrier A.periods
      A.modular.modularParameter.toTriangleUniformization_sourceAction
      A.starSeparation.orderFour.radius))

/-- The existing analytic gauge reduces the actual order-three collar to its linear quotient. -/
public noncomputable def orderThreeCollarGaugeHomeomorph :
    A.starCollarSourceType 1 ≃ₜ A.orderThreeLinearCollarType := by
  let _ := A.totalSpaceCharts
  change Quotient (restrictedOrbitRel (orderThreeAffineFamilyAction A.periods)
      (orderThreeAffinePuncturedCarrier A.periods
        A.modular.modularParameter.toTriangleUniformization_sourceAction
        A.starSeparation.orderThree.radius)) ≃ₜ _
  exact orderThreePuncturedCollarQuotientHomeomorph A.periods
    A.totalSpace_projection_isLocalDiffeomorph
    A.modular.modularParameter.toTriangleUniformization_sourceAction
    A.starSeparation.orderThree.radius

/-- The existing analytic gauge reduces the actual order-four collar to its linear quotient. -/
public noncomputable def orderFourCollarGaugeHomeomorph :
    A.starCollarSourceType 2 ≃ₜ A.orderFourLinearCollarType := by
  let _ := A.totalSpaceCharts
  change Quotient (restrictedOrbitRel (orderFourAffineFamilyAction A.periods)
      (orderFourAffinePuncturedCarrier A.periods
        A.modular.modularParameter.toTriangleUniformization_sourceAction
        A.starSeparation.orderFour.radius)) ≃ₜ _
  exact orderFourPuncturedCollarQuotientHomeomorph A.periods
    A.totalSpace_projection_isLocalDiffeomorph
    A.modular.modularParameter.toTriangleUniformization_sourceAction
    A.starSeparation.orderFour.radius

end PaperAnalyticData

end Geometry

end SphereSixComplex
