module

public import SphereSixComplex.Topology.PaperEllipticReducedCentralFiberCoverModels

/-!
# Affine cyclic reduced fibres as mapping-torus candidates

The reduced central fibre is first identified with the orbit quotient of its central torus by
the affine cyclic fibre action.  This removes the ambient disc coordinate and is the first
topological reduction toward a mapping-torus model over the primitive character `gamma`.
-/

@[expose] public section

noncomputable section

open Set Topology
open scoped ContinuousMap

namespace SphereSixComplex.Topology.PaperEllipticReducedCentralFiberCoverModels.RadialEllipticActionData

open Geometry Geometry.EquivariantQuotientHomeomorph
open Geometry.EllipticLocalCoordinates
open PaperEllipticFillingRadialRetraction
open TriangleGroup

variable {m : ℕ} [NeZero m] {T : Type} [TopologicalSpace T] [AddCommGroup T]

/-- The cyclic representation on the central torus generated by the affine fibre map. -/
public noncomputable def centralFiberRepresentation
    (D : RadialEllipticActionData m T) : FiniteCyclic m →* Equiv.Perm T :=
  cyclicRepresentation m D.actionData.fiberGenerator D.actionData.fiberGenerator_pow

@[simp]
public theorem centralFiberRepresentation_generator
    (D : RadialEllipticActionData m T) :
    centralFiberRepresentation D (cyclicGenerator m) = D.actionData.fiberGenerator :=
  cyclicRepresentation_generator m D.actionData.fiberGenerator
    D.actionData.fiberGenerator_pow

/-- The affine cyclic action induced on the central torus. -/
@[instance_reducible] public noncomputable def centralFiberAction
    (D : RadialEllipticActionData m T) : MulAction (FiniteCyclic m) T where
  smul g x := centralFiberRepresentation D g x
  one_smul x := by
    change centralFiberRepresentation D 1 x = x
    rw [map_one]
    rfl
  mul_smul g h x := by
    change centralFiberRepresentation D (g * h) x =
      centralFiberRepresentation D g (centralFiberRepresentation D h x)
    rw [map_mul]
    rfl

/-- The central-torus action is the second coordinate of the diagonal action at its centre. -/
public theorem rotation_pow_center
    (D : RadialEllipticActionData m T) (k : ℕ) :
    (D.actionData.rotation ^ k) D.actionData.center = D.actionData.center := by
  have hgenerator : D.actionData.rotation D.actionData.center = D.actionData.center := by
    have hm : 0 < m := NeZero.pos m
    by_cases hmOne : m = 1
    · subst m
      simpa using congrArg (fun e : Equiv.Perm _ ↦ e D.actionData.center)
        D.actionData.rotation_pow
    · exact (D.actionData.rotation_fixed_iff 1 (by omega) (by omega)
          D.actionData.center).2 rfl
  induction k with
  | zero => rfl
  | succ k ih =>
      rw [pow_succ, Equiv.Perm.mul_apply, hgenerator, ih]

/-- At the centre, the diagonal action is the affine fibre action. -/
public theorem centralFiberRepresentation_eq_diagonal
    (D : RadialEllipticActionData m T) (g : FiniteCyclic m) (x : T) :
    actionMap D.actionData.diagonalAction g (D.actionData.center, x) =
      (D.actionData.center, centralFiberRepresentation D g x) := by
  change D.actionData.representation g (D.actionData.center, x) = _
  rw [cyclic_eq_generator_pow g, map_pow, map_pow,
    centralFiberRepresentation_generator D,
    D.actionData.representation_generator,
    D.actionData.diagonalGenerator_pow_apply,
    rotation_pow_center D]

public theorem centralFiberRepresentation_eq_diagonal_snd
    (D : RadialEllipticActionData m T) (g : FiniteCyclic m) (x : T) :
    centralFiberRepresentation D g x =
      (D.actionData.representation g (D.actionData.center, x)).2 := by
  have h := congrArg Prod.snd (centralFiberRepresentation_eq_diagonal D g x)
  exact h.symm

/-- Projection of the central torus onto the reduced central fibre. -/
public noncomputable def centralFiberOrbitProjection
    (D : RadialEllipticActionData m T) : C(T, D.reducedCentralFiber) :=
  (centralFiberCoverProjection D).comp (centralFiberCoverSourceHomeomorph D).symm

@[simp]
public theorem centralFiberOrbitProjection_apply
    (D : RadialEllipticActionData m T) (x : T) :
    centralFiberOrbitProjection D x =
      ⟨Quotient.mk (orbitRelOf D.actionData.diagonalAction)
        (D.actionData.center, x), by
          apply (mem_centralSlice_iff_quotient_mem_reducedCentralFiber D
            (D.actionData.center, x)).2
          exact D.center_eq⟩ :=
  rfl

/-- Every point of the reduced central fibre has a representative on the central torus. -/
public theorem centralFiberOrbitProjection_surjective
    (D : RadialEllipticActionData m T) :
    Function.Surjective (centralFiberOrbitProjection D) := by
  intro q
  obtain ⟨p, hp, hpq⟩ := q.2
  refine ⟨p.2, ?_⟩
  apply Subtype.ext
  rw [centralFiberOrbitProjection_apply]
  change Quotient.mk _ (D.actionData.center, p.2) = q.1
  rw [D.center_eq]
  have hpair : (discCenter, p.2) = p := by
    apply Prod.ext
    · exact hp.symm
    · rfl
  rw [hpair]
  exact hpq

/-- The central-torus projection is a quotient map. -/
public theorem centralFiberOrbitProjection_isQuotientMap
    (D : RadialEllipticActionData m T)
    [T2Space D.Product] [LocallyCompactSpace D.Product]
    (hfree : letI := D.actionData.diagonalAction
      IsCancelSMul (FiniteCyclic m) D.Product) :
    IsQuotientMap (centralFiberOrbitProjection D) := by
  have hcover := centralFiberCoverProjection_isCovering D hfree
  have hsurjective : Function.Surjective (centralFiberCoverProjection D) := by
    intro q
    obtain ⟨x, hx⟩ := centralFiberOrbitProjection_surjective D q
    exact ⟨(centralFiberCoverSourceHomeomorph D).symm x, hx⟩
  exact (hcover.isQuotientMap hsurjective).comp
    (centralFiberCoverSourceHomeomorph D).symm.isQuotientMap

/-- Two central-torus points have the same image precisely when they are in the same affine
cyclic orbit. -/
public theorem centralFiberOrbitRel_iff_projection_eq
    (D : RadialEllipticActionData m T) (x y : T) :
    letI := centralFiberAction D
    MulAction.orbitRel (FiniteCyclic m) T x y ↔
      centralFiberOrbitProjection D x = centralFiberOrbitProjection D y := by
  let _ := centralFiberAction D
  rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff]
  constructor
  · rintro ⟨g, hg⟩
    apply Subtype.ext
    rw [centralFiberOrbitProjection_apply, centralFiberOrbitProjection_apply]
    apply Quotient.sound
    change ∃ g : FiniteCyclic m,
      actionMap D.actionData.diagonalAction g (D.actionData.center, y) =
        (D.actionData.center, x)
    refine ⟨g, ?_⟩
    change centralFiberRepresentation D g y = x at hg
    rw [centralFiberRepresentation_eq_diagonal D g y, hg]
  · intro hxy
    have hquot := congrArg Subtype.val hxy
    rw [centralFiberOrbitProjection_apply, centralFiberOrbitProjection_apply] at hquot
    have horbit := Quotient.exact hquot
    change ∃ g : FiniteCyclic m,
      actionMap D.actionData.diagonalAction g (D.actionData.center, y) =
        (D.actionData.center, x) at horbit
    obtain ⟨g, hg⟩ := horbit
    refine ⟨g, ?_⟩
    rw [centralFiberRepresentation_eq_diagonal D g y] at hg
    exact congrArg Prod.snd hg

/-- The reduced central fibre is homeomorphic to the explicit affine cyclic quotient of its
central torus. -/
public noncomputable def centralFiberOrbitQuotientHomeomorph
    (D : RadialEllipticActionData m T)
    [T2Space D.Product] [LocallyCompactSpace D.Product]
    (hfree : letI := D.actionData.diagonalAction
      IsCancelSMul (FiniteCyclic m) D.Product) :
    letI := centralFiberAction D
    MulAction.orbitRel.Quotient (FiniteCyclic m) T ≃ₜ D.reducedCentralFiber := by
  let _ := centralFiberAction D
  let hq := centralFiberOrbitProjection_isQuotientMap D hfree
  exact (Homeomorph.Quotient.congrRight fun x y ↦
    centralFiberOrbitRel_iff_projection_eq D x y).trans hq.homeomorph

end SphereSixComplex.Topology.PaperEllipticReducedCentralFiberCoverModels.RadialEllipticActionData

end

end
