module

public import Mathlib.Analysis.Complex.CoveringMap
public import Mathlib.Analysis.Convex.Contractible
public import Mathlib.Topology.Homotopy.Lifting

/-!
# The fundamental group of the punctured complex plane

The exponential map is Mathlib's additive quotient covering of `ℂ \ {0}` by the deck group
generated by `2πi`.  This file specializes the general monodromy equivalence to that covering and
computes the resulting deck value of an explicit integer circle.  It is the winding-number bridge
needed to compare the paper's local meridians with fixed standard circles.
-/

@[expose] public section

noncomputable section

open Set Function Topology

namespace SphereSixComplex.Topology

/-- The punctured complex plane, written as a subtype suited to the exponential covering. -/
public abbrev PuncturedComplex := {z : ℂ // z ≠ 0}

/-- The exponential covering map with its nonvanishing codomain bundled. -/
public def complexExpCoverMap : ℂ → PuncturedComplex :=
  fun z ↦ ⟨Complex.exp z, Complex.exp_ne_zero z⟩

/-- The exponential covering bundled as a continuous map. -/
public def complexExpCoverContinuousMap : C(ℂ, PuncturedComplex) where
  toFun := complexExpCoverMap
  continuous_toFun := by
    apply Continuous.subtype_mk
    exact Complex.continuous_exp

/-- The deck group of the complex exponential covering. -/
public abbrev ComplexExpDeckGroup : AddSubgroup ℂ :=
  AddSubgroup.zmultiples (2 * Real.pi * Complex.I)

/-- The deck-group element corresponding to `n` turns. -/
public def complexExpDeckMultiple (n : ℤ) : ComplexExpDeckGroup :=
  ⟨n • (2 * Real.pi * Complex.I), AddSubgroup.zsmul_mem_zmultiples _ _⟩

/-- A chosen logarithm of a punctured point is a point in the fibre of the exponential cover. -/
public def complexExpFiberPoint (a : ℂ) (ha : a ≠ 0) :
    complexExpCoverMap ⁻¹' ({⟨a, ha⟩} : Set PuncturedComplex) :=
  ⟨Complex.log a, by
    rw [Set.mem_preimage, Set.mem_singleton_iff]
    apply Subtype.ext
    exact Complex.exp_log ha⟩

/-- The exponential-cover monodromy equivalence identifies the fundamental group of `ℂ \ {0}`
with the opposite of the additive deck group generated by `2πi`. -/
public def puncturedComplexFundamentalGroupEquiv (a : ℂ) (ha : a ≠ 0) :
    FundamentalGroup PuncturedComplex ⟨a, ha⟩ ≃*
      (Multiplicative ComplexExpDeckGroup)ᵐᵒᵖ :=
  Complex.isAddQuotientCoveringMap_exp.fundamentalGroupEquiv
    (complexExpFiberPoint a ha)

/-- The exponential-cover deck value (winding datum) of a based loop in `ℂ \ {0}`. -/
public def puncturedComplexLoopDeckValue {a : PuncturedComplex}
    (L : Path a a) : (Multiplicative ComplexExpDeckGroup)ᵐᵒᵖ :=
  puncturedComplexFundamentalGroupEquiv a.1 a.2
    (Path.Homotopic.Quotient.mk L)

/-- Equality of exponential-cover deck values is exactly equality of based loop classes. -/
public theorem puncturedComplex_loopClass_eq_iff_deckValue_eq
    {a : PuncturedComplex} (L₁ L₂ : Path a a) :
    Path.Homotopic.Quotient.mk L₁ = Path.Homotopic.Quotient.mk L₂ ↔
      puncturedComplexLoopDeckValue L₁ = puncturedComplexLoopDeckValue L₂ := by
  constructor
  · exact fun h ↦ congrArg (puncturedComplexFundamentalGroupEquiv a.1 a.2) h
  · exact fun h ↦ (puncturedComplexFundamentalGroupEquiv a.1 a.2).injective h

/-- The point making `n` counterclockwise turns around zero from a nonzero starting value `a`.
Negative `n` gives clockwise turns. -/
public def puncturedComplexIntegerCirclePoint
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) (t : unitInterval) : PuncturedComplex :=
  ⟨a * Complex.exp
      ((2 * Real.pi * (n : ℝ) * (t : ℝ) : ℂ) * Complex.I),
    mul_ne_zero ha (Complex.exp_ne_zero _)⟩

public theorem puncturedComplexIntegerCirclePoint_zero
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) :
    puncturedComplexIntegerCirclePoint a ha n 0 = ⟨a, ha⟩ := by
  apply Subtype.ext
  simp [puncturedComplexIntegerCirclePoint]

public theorem puncturedComplexIntegerCirclePoint_one
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) :
    puncturedComplexIntegerCirclePoint a ha n 1 = ⟨a, ha⟩ := by
  apply Subtype.ext
  change a * Complex.exp
      ((2 * Real.pi * (n : ℝ) * (1 : ℝ) : ℂ) * Complex.I) = a
  rw [mul_eq_left₀ ha]
  rw [Complex.exp_eq_one_iff]
  refine ⟨n, ?_⟩
  push_cast
  norm_num
  ring

/-- The explicit `n`-turn circle as a based path in the punctured plane. -/
public def puncturedComplexIntegerCircle
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) :
    Path (⟨a, ha⟩ : PuncturedComplex) ⟨a, ha⟩ where
  toFun := puncturedComplexIntegerCirclePoint a ha n
  continuous_toFun := by
    apply Continuous.subtype_mk
    fun_prop
  source' := puncturedComplexIntegerCirclePoint_zero a ha n
  target' := puncturedComplexIntegerCirclePoint_one a ha n

/-- The evident logarithmic lift of the integer circle. -/
public def puncturedComplexIntegerCircleLift
    (a : ℂ) (_ha : a ≠ 0) (n : ℤ) :
    Path (Complex.log a) (Complex.log a + n • (2 * Real.pi * Complex.I)) where
  toFun t := Complex.log a +
    ((t : ℝ) : ℂ) * (n • (2 * Real.pi * Complex.I))
  continuous_toFun := by fun_prop
  source' := by simp
  target' := by simp

public theorem complexExpCoverContinuousMap_log
    (a : ℂ) (ha : a ≠ 0) :
    complexExpCoverContinuousMap (Complex.log a) = ⟨a, ha⟩ := by
  apply Subtype.ext
  exact Complex.exp_log ha

public theorem complexExpCoverContinuousMap_log_add_deck
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) :
    complexExpCoverContinuousMap
        (Complex.log a + n • (2 * Real.pi * Complex.I)) = ⟨a, ha⟩ := by
  apply Subtype.ext
  change Complex.exp
      (Complex.log a + n • (2 * Real.pi * Complex.I)) = a
  rw [show n • (2 * Real.pi * Complex.I) =
      (n : ℤ) * (2 * Real.pi * Complex.I) by ring]
  rw [Complex.exp_add, Complex.exp_log ha, Complex.exp_int_mul]
  simp

/-- Exponentiating the explicit logarithmic lift gives the integer circle pointwise. -/
public theorem puncturedComplexIntegerCircleLift_map_exp
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) :
    ((puncturedComplexIntegerCircleLift a ha n).map
        complexExpCoverContinuousMap.continuous).cast
          (complexExpCoverContinuousMap_log a ha).symm
          (complexExpCoverContinuousMap_log_add_deck a ha n).symm =
      puncturedComplexIntegerCircle a ha n := by
  apply Path.ext
  funext t
  apply Subtype.ext
  change Complex.exp
      (Complex.log a + ((t : ℝ) : ℂ) *
        (n • (2 * Real.pi * Complex.I))) =
    a * Complex.exp
      ((2 * Real.pi * (n : ℝ) * (t : ℝ) : ℂ) * Complex.I)
  rw [Complex.exp_add, Complex.exp_log ha]
  congr 1
  congr 1
  push_cast
  ring

/-- Under exponential-cover monodromy, the explicit integer circle has deck value
`n • (2πi)`.  In particular, clockwise and counterclockwise circles are distinguished without
introducing a separate winding-number axiom. -/
public theorem puncturedComplexFundamentalGroupEquiv_integerCircle
    (a : ℂ) (ha : a ≠ 0) (n : ℤ) :
    puncturedComplexFundamentalGroupEquiv a ha
        (Path.Homotopic.Quotient.mk (puncturedComplexIntegerCircle a ha n)) =
      MulOpposite.op (Multiplicative.ofAdd (complexExpDeckMultiple n)) := by
  unfold puncturedComplexFundamentalGroupEquiv
  change Complex.isAddQuotientCoveringMap_exp.fundamentalGroupToMulOpposite
      (complexExpFiberPoint a ha)
        (Path.Homotopic.Quotient.mk (puncturedComplexIntegerCircle a ha n)) = _
  unfold complexExpFiberPoint complexExpCoverMap
  rw [IsAddQuotientCoveringMap.fundamentalGroupToMulOpposite_apply_eq_Iff]
  let ex : (fun z : ℂ ↦
      (⟨Complex.exp z, Complex.exp_ne_zero z⟩ : PuncturedComplex)) ⁻¹'
        ({⟨a, ha⟩} : Set PuncturedComplex) :=
    ⟨Complex.log a, by
      rw [Set.mem_preimage, Set.mem_singleton_iff]
      apply Subtype.ext
      exact Complex.exp_log ha⟩
  let ey : (fun z : ℂ ↦
      (⟨Complex.exp z, Complex.exp_ne_zero z⟩ : PuncturedComplex)) ⁻¹'
        ({⟨a, ha⟩} : Set PuncturedComplex) :=
    ⟨Complex.log a + n • (2 * Real.pi * Complex.I), by
      rw [Set.mem_preimage, Set.mem_singleton_iff]
      exact complexExpCoverContinuousMap_log_add_deck a ha n⟩
  have hmono := Complex.isCoveringMap_exp.monodromy_eq_of_map_eq
    (γ := Path.Homotopic.Quotient.mk (puncturedComplexIntegerCircle a ha n))
    (ex := ex) (ey := ey)
    (Γ := Path.Homotopic.Quotient.mk
      (puncturedComplexIntegerCircleLift a ha n))
    (by
      dsimp [ex, ey]
      change (Path.Homotopic.Quotient.mk
          (puncturedComplexIntegerCircleLift a ha n)).map
            complexExpCoverContinuousMap =
        (Path.Homotopic.Quotient.mk
          (puncturedComplexIntegerCircle a ha n)).cast
            (complexExpCoverContinuousMap_log a ha)
            (complexExpCoverContinuousMap_log_add_deck a ha n)
      rw [← Path.Homotopic.Quotient.mk_map,
        ← Path.Homotopic.Quotient.mk_cast]
      apply congrArg Path.Homotopic.Quotient.mk
      apply Path.ext
      funext t
      apply Subtype.ext
      simp only [Path.map_coe, Path.cast_coe, Function.comp_apply]
      change Complex.exp
          (Complex.log a + ((t : ℝ) : ℂ) *
            (n • (2 * Real.pi * Complex.I))) =
        a * Complex.exp
          ((2 * Real.pi * (n : ℝ) * (t : ℝ) : ℂ) * Complex.I)
      rw [Complex.exp_add, Complex.exp_log ha]
      congr 1
      congr 1
      push_cast
      ring)
  rw [hmono]
  change n • (2 * Real.pi * Complex.I) + Complex.log a =
    Complex.log a + n • (2 * Real.pi * Complex.I)
  exact add_comm _ _

/-- A concrete logarithmic lift with endpoint displaced by `n • 2πi` identifies a based loop
with the explicit `n`-turn circle.  This is the path-level criterion used to turn local analytic
factorizations into fundamental-group equalities. -/
public theorem puncturedComplex_loopClass_eq_integerCircle_of_lift
    (a : ℂ) (ha : a ≠ 0) (n : ℤ)
    (L : Path (⟨a, ha⟩ : PuncturedComplex) ⟨a, ha⟩)
    (Γ : Path (Complex.log a)
      (Complex.log a + n • (2 * Real.pi * Complex.I)))
    (hΓ : (Γ.map complexExpCoverContinuousMap.continuous).cast
        (complexExpCoverContinuousMap_log a ha).symm
        (complexExpCoverContinuousMap_log_add_deck a ha n).symm = L) :
    Path.Homotopic.Quotient.mk L =
      Path.Homotopic.Quotient.mk
        (puncturedComplexIntegerCircle a ha n) := by
  have hΓq := congrArg Path.Homotopic.Quotient.mk hΓ
  have hLift : Path.Homotopic.Quotient.mk Γ =
      Path.Homotopic.Quotient.mk
        (puncturedComplexIntegerCircleLift a ha n) :=
    Subsingleton.elim _ _
  have hMapped := congrArg
    (fun q ↦ q.map complexExpCoverContinuousMap) hLift
  have hCasted := congrArg
    (fun q ↦ q.cast
      (complexExpCoverContinuousMap_log a ha).symm
      (complexExpCoverContinuousMap_log_add_deck a ha n).symm) hMapped
  calc
    Path.Homotopic.Quotient.mk L =
        (Path.Homotopic.Quotient.mk
          (Γ.map complexExpCoverContinuousMap.continuous)).cast
            (complexExpCoverContinuousMap_log a ha).symm
            (complexExpCoverContinuousMap_log_add_deck a ha n).symm := by
      simpa only [Path.Homotopic.Quotient.mk_cast] using hΓq.symm
    _ = (Path.Homotopic.Quotient.mk
          ((puncturedComplexIntegerCircleLift a ha n).map
            complexExpCoverContinuousMap.continuous)).cast
              (complexExpCoverContinuousMap_log a ha).symm
              (complexExpCoverContinuousMap_log_add_deck a ha n).symm := by
      simpa only [Path.Homotopic.Quotient.mk_map] using hCasted
    _ = Path.Homotopic.Quotient.mk
          (puncturedComplexIntegerCircle a ha n) := by
      exact congrArg Path.Homotopic.Quotient.mk
        (puncturedComplexIntegerCircleLift_map_exp a ha n)

end SphereSixComplex.Topology
