module

public import SphereSixComplex.Topology.HomologyComputation

/-!
# The graded Mayer--Vietoris algebra in Section 7

The paper specifies homology groups and maps between them, not cellular chain complexes for the
seven local spaces.  This file records exactly the finite graded algebra that is stated: the two
interior Mayer--Vietoris maps, their cokernel coordinates, and the two final attachment
coefficients.  It does not identify these groups with a chain-level homotopy pushout.
-/

@[expose] public section

noncomputable section

open Matrix

namespace SphereSixComplex

/-- The cokernel coordinate for `α₁`; it identifies the two copies of the class `γ`. -/
public def alphaOneCokernelFunctional (x : Fin 4 → ℤ) : ℤ :=
  x 0 + x 2

/-- The displayed matrix for `α₁` lands in the kernel of its cokernel coordinate. -/
public theorem alphaOneCokernelFunctional_relation (x : Fin 4 → ℤ) :
    alphaOneCokernelFunctional (alphaOneMatrix.mulVec x) = 0 := by
  simp [alphaOneCokernelFunctional, alphaOneMatrix, Matrix.mulVec, dotProduct,
    Fin.sum_univ_succ]

/-- The image of `α₁` is exactly the kernel of its primitive cokernel coordinate. -/
public theorem alphaOne_image_iff (x : Fin 4 → ℤ) :
    (∃ y : Fin 4 → ℤ, alphaOneMatrix.mulVec y = x) ↔
      alphaOneCokernelFunctional x = 0 := by
  constructor
  · rintro ⟨y, rfl⟩
    exact alphaOneCokernelFunctional_relation y
  · intro h
    refine ⟨![x 0, x 1 + x 3, -x 1 - 2 * x 3, 0], ?_⟩
    funext i
    fin_cases i <;>
      simp [alphaOneMatrix, alphaOneCokernelFunctional, Matrix.mulVec, dotProduct,
        Fin.sum_univ_succ] at h ⊢ <;>
      omega

/-- Exactness of the degree-one interior Mayer--Vietoris presentation. -/
public theorem alphaOnePresentation_exact :
    Function.Exact alphaOneMatrix.mulVec alphaOneCokernelFunctional := by
  intro x
  simpa only [Set.mem_range] using (alphaOne_image_iff x).symm

/-- The degree-one interior cokernel coordinate is primitive. -/
public theorem alphaOneCokernelFunctional_surjective :
    Function.Surjective alphaOneCokernelFunctional := by
  intro z
  exact ⟨![z, 0, 0, 0], by simp [alphaOneCokernelFunctional]⟩

/-- The final degree-one attachment in the chosen construction is multiplication by `p = -1`. -/
public def sectionSevenMayerVietorisDegreeOneAttachment : ℤ →+ ℤ where
  toFun x := twistObstruction 0 1 (-1) * x
  map_zero' := by simp
  map_add' x y := by ring

/-- The final degree-two attachment has coefficient `±p`; `sign` records the orientation choice. -/
public def sectionSevenMayerVietorisDegreeTwoAttachment (sign : ℤ) : ℤ →+ ℤ where
  toFun x := sign * twistObstruction 0 1 (-1) * x
  map_zero' := by simp
  map_add' x y := by ring

/-- The degree-one attachment is an isomorphism of underlying abelian groups. -/
public theorem sectionSevenMayerVietorisDegreeOneAttachment_bijective :
    Function.Bijective sectionSevenMayerVietorisDegreeOneAttachment := by
  constructor
  · intro x y h
    simpa [sectionSevenMayerVietorisDegreeOneAttachment, twistObstruction] using h
  · intro y
    exact ⟨-y, by simp [sectionSevenMayerVietorisDegreeOneAttachment, twistObstruction]⟩

/-- Either orientation makes the degree-two attachment an isomorphism. -/
public theorem sectionSevenMayerVietorisDegreeTwoAttachment_bijective (sign : ℤ)
    (hsign : sign = 1 ∨ sign = -1) :
    Function.Bijective (sectionSevenMayerVietorisDegreeTwoAttachment sign) := by
  rcases hsign with rfl | rfl <;> constructor
  · intro x y h
    simpa [sectionSevenMayerVietorisDegreeTwoAttachment, twistObstruction] using h
  · intro y
    exact ⟨-y, by simp [sectionSevenMayerVietorisDegreeTwoAttachment, twistObstruction]⟩
  · intro x y h
    simpa [sectionSevenMayerVietorisDegreeTwoAttachment, twistObstruction] using h
  · intro y
    exact ⟨y, by simp [sectionSevenMayerVietorisDegreeTwoAttachment, twistObstruction]⟩

/-- The source-stated finite algebra for the chosen Mayer--Vietoris calculation. -/
public structure SectionSevenMayerVietorisGradedAlgebra where
  /-- The degree-one interior map is the displayed `α₁` matrix. -/
  alphaOne : Matrix (Fin 4) (Fin 4) ℤ
  /-- The degree-one interior cokernel coordinate. -/
  alphaOneCoordinate : (Fin 4 → ℤ) → ℤ
  /-- The degree-one interior sequence is exact. -/
  alphaOneExact : Function.Exact alphaOne.mulVec alphaOneCoordinate
  /-- The degree-one kernel is generated by `ν₀`. -/
  alphaOneKernel : ∀ x, alphaOne.mulVec x = 0 ↔
    ∃ t : ℤ, x = t • alphaOneKernelGenerator
  /-- The degree-one presentation after adjoining the multiple-fibre generators. -/
  degreeOneRelations : Matrix (Fin 3) (Fin 2) ℤ
  /-- The primitive coordinate on that presentation. -/
  degreeOneCoordinate : (Fin 3 → ℤ) → ℤ
  /-- Exactness of the degree-one presentation. -/
  degreeOneExact : Function.Exact degreeOneRelations.mulVec degreeOneCoordinate
  /-- The degree-two interior map is the displayed `α₂` matrix. -/
  alphaTwo : Matrix (Fin 4) (Fin 6) ℤ
  /-- The primitive coordinate on the degree-two cokernel. -/
  alphaTwoCoordinate : (Fin 4 → ℤ) → ℤ
  /-- Exactness of the degree-two interior presentation. -/
  alphaTwoExact : Function.Exact alphaTwo.mulVec alphaTwoCoordinate
  /-- The final degree-one attachment coefficient. -/
  degreeOneAttachment : ℤ →+ ℤ
  /-- The final degree-one attachment is invertible. -/
  degreeOneAttachment_bijective : Function.Bijective degreeOneAttachment
  /-- The final degree-two attachment coefficient, up to orientation. -/
  degreeTwoAttachment : ℤ →+ ℤ
  /-- The final degree-two attachment is invertible. -/
  degreeTwoAttachment_bijective : Function.Bijective degreeTwoAttachment

/-- The exact graded Mayer--Vietoris algebra for twists `(0,1,-1)`, with positive orientation. -/
public def chosenSectionSevenMayerVietorisGradedAlgebra :
    SectionSevenMayerVietorisGradedAlgebra where
  alphaOne := alphaOneMatrix
  alphaOneCoordinate := alphaOneCokernelFunctional
  alphaOneExact := alphaOnePresentation_exact
  alphaOneKernel := alphaOne_kernel
  degreeOneRelations := firstHomologyRelationMatrix
  degreeOneCoordinate := firstHomologyFunctional
  degreeOneExact := firstHomologyPresentation_exact
  alphaTwo := alphaTwoMatrix
  alphaTwoCoordinate := alphaTwoFunctional
  alphaTwoExact := alphaTwoPresentation_exact
  degreeOneAttachment := sectionSevenMayerVietorisDegreeOneAttachment
  degreeOneAttachment_bijective := sectionSevenMayerVietorisDegreeOneAttachment_bijective
  degreeTwoAttachment := sectionSevenMayerVietorisDegreeTwoAttachment 1
  degreeTwoAttachment_bijective :=
    sectionSevenMayerVietorisDegreeTwoAttachment_bijective 1 (Or.inl rfl)

end SphereSixComplex
