module

public import SphereSixComplex.Topology.WangHomologyPresentation
public import SphereSixComplex.Topology.EstablishedMayerVietoris
public import SphereSixComplex.Topology.MayerVietorisDegreeZeroBridge

/-!
# The Wang sequence of a finite-bouquet mapping torus, from Mayer--Vietoris

`WangHomologyPresentation.lean` isolates the Wang exact sequence of the explicit finite-bouquet
mapping torus as `establishedFiniteBouquetMappingTorusWangSequence`.  This file removes the
homological bookkeeping from that boundary: everything except the geometric identification of the
Mayer--Vietoris cover is proved here, unconditionally.

## Main results

* `monodromyDifference`, `coverDifference`: the two algebraic maps occurring in the Wang and
  Mayer--Vietoris sequences of a bouquet with `ι` loops.
* `wangExactness_of_mayerVietoris`: the purely algebraic splice.  From the three exactness
  statements of the five-term Mayer--Vietoris segment
  `(ι → G)² → G × (ι → G) → T → (ι → H)² → H × (ι → H)`
  together with the description `S (u, v) = incl (u + ∑ i, v i)` of the sum map, the first
  projection of the Mayer--Vietoris boundary is a Wang boundary: it is exact with the fibre
  inclusion on the left and with the monodromy difference on the right.
* `finiteBouquetMappingTorusWangSequence_of_mayerVietoris`: the same statement in the exact shape
  of `FiniteBouquetMappingTorusWangSequence`, i.e. the axiom of `WangHomologyPresentation.lean`
  follows from the geometric Mayer--Vietoris input alone.

The algebra uses no invertibility of the monodromies: `ψ` and `χ` below are arbitrary additive
endomorphisms, which is what the induced maps on homology of a bouquet of self-maps supply.

The remaining sections prepare that geometric input.

* `bouquetKey` and `eqvGen_iff_bouquetKey`: the equivalence relation generated by the bouquet
  identifications is exactly equality of an explicit invariant, so `bouquetMk_eq_iff` decides when
  two points of the disjoint union of cylinders agree in the mapping torus.
* `bouquetPiece`: the saturated subsets cut out by a condition on the cylinder coordinate, with
  `preimage_bouquetPiece`, `isOpen_bouquetPiece` and the bandwise union and intersection rules.
* `vertexPiece`, `edgePiece`: the two-set open cover of the mapping torus by a neighbourhood of the
  fibre over the bouquet vertex and by the cylinder interiors, together with
  `vertexPiece_union_edgePiece`, `vertexPiece_inter_edgePiece` and
  `bouquetMk_injOn_edgeBand`, which says that the cylinder interiors are embedded.

What is still missing for an unconditional proof of the axiom is the homological identification of
that cover: the vertex piece deformation-retracts to the fibre, the edge piece and the overlap are
finite disjoint unions of copies of the fibre, and integral singular homology takes those finite
disjoint unions to finite products.
-/

@[expose] public section

noncomputable section

open scoped ContinuousMap

namespace SphereSixComplex

namespace WangFromMayerVietoris

variable {ι : Type*} [Fintype ι] {G T H : Type*}
  [AddCommGroup G] [AddCommGroup T] [AddCommGroup H]

/-- The Wang differential of a bouquet with loops indexed by `ι`: the sum of `ψ i - 1` over the
oriented loops.  This is the algebraic shape of `finiteBouquetMonodromyDifference`. -/
public def monodromyDifference (ψ : ι → G →+ G) : (ι → G) →+ G where
  toFun a := ∑ i, (ψ i (a i) - a i)
  map_zero' := by simp
  map_add' a b := by
    simp only [Pi.add_apply, map_add]
    rw [← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun i _ ↦ by abel

@[simp]
public theorem monodromyDifference_apply (ψ : ι → G →+ G) (a : ι → G) :
    monodromyDifference ψ a = ∑ i, (ψ i (a i) - a i) := rfl

/-- The Mayer--Vietoris difference map of the two-set cover of a bouquet mapping torus, in
algebraic form.  The first argument records the legs of the overlap at the zero ends of the
cylinders, the second those at the one ends, which enter the fibre through the monodromies. -/
public def coverDifference (ψ : ι → G →+ G) :
    ((ι → G) × (ι → G)) →+ G × (ι → G) where
  toFun p := (∑ i, (p.1 i + ψ i (p.2 i)), -(p.1 + p.2))
  map_zero' := by simp
  map_add' p q := by
    refine Prod.ext ?_ ?_
    · show ∑ i, ((p + q).1 i + ψ i ((p + q).2 i)) = _
      simp only [Prod.fst_add, Prod.snd_add, Pi.add_apply, map_add]
      rw [← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ ↦ by abel
    · show -((p + q).1 + (p + q).2) = _
      simp only [Prod.fst_add, Prod.snd_add]
      abel

@[simp]
public theorem coverDifference_apply (ψ : ι → G →+ G) (p : (ι → G) × (ι → G)) :
    coverDifference ψ p = (∑ i, (p.1 i + ψ i (p.2 i)), -(p.1 + p.2)) := rfl

/-- The Wang differential is the cover difference read on the antidiagonal, up to sign. -/
public theorem coverDifference_antidiagonal (ψ : ι → G →+ G) (a : ι → G) :
    coverDifference ψ (-a, a) = (monodromyDifference ψ a, 0) := by
  refine Prod.ext ?_ ?_
  · simp only [coverDifference_apply, monodromyDifference_apply, Pi.neg_apply]
    exact Finset.sum_congr rfl fun i _ ↦ by abel
  · simp

/-- Only the antidiagonal survives the cover difference. -/
public theorem snd_eq_neg_fst_of_coverDifference_snd_eq_zero {ψ : ι → G →+ G}
    {p : (ι → G) × (ι → G)} (h : (coverDifference ψ p).2 = 0) : p.2 = -p.1 := by
  have h2 : p.1 + p.2 = 0 := neg_eq_zero.mp h
  have h3 := congrArg (fun z : ι → G ↦ -p.1 + z) h2
  simpa using h3

/-- On the antidiagonal the cover difference is minus the Wang differential. -/
public theorem coverDifference_fst_of_eq_neg (ψ : ι → G →+ G) (a : ι → G) :
    (coverDifference ψ (a, -a)).1 = -(monodromyDifference ψ a) := by
  simp only [coverDifference_apply, monodromyDifference_apply, Pi.neg_apply, map_neg]
  rw [← Finset.sum_neg_distrib]
  exact Finset.sum_congr rfl fun i _ ↦ by abel

/-! ## The splice -/

variable (ψ : ι → G →+ G) (χ : ι → H →+ H)

/-- The Wang boundary carried by a Mayer--Vietoris boundary: its leg at the zero ends of the
cylinders.  The other leg carries no further information, being its negative. -/
public def wangBoundary (bdry : T →+ (ι → H) × (ι → H)) : T →+ (ι → H) :=
  (AddMonoidHom.fst (ι → H) (ι → H)).comp bdry

omit [Fintype ι] in
@[simp]
public theorem wangBoundary_apply (bdry : T →+ (ι → H) × (ι → H)) (y : T) :
    wangBoundary bdry y = (bdry y).1 := rfl

variable {incl : G →+ T} {S : G × (ι → G) →+ T} {bdry : T →+ (ι → H) × (ι → H)}

/-- Exactness of the Wang sequence at the upper fibre group: the kernel of the fibre inclusion is
the image of the monodromy difference.  This uses only exactness of Mayer--Vietoris at the
homology of the two pieces, plus the description of the Mayer--Vietoris sum map. -/
public theorem exact_monodromyDifference_inclusion
    (hS : ∀ p : G × (ι → G), S p = incl (p.1 + ∑ i, p.2 i))
    (h₁ : Function.Exact (coverDifference ψ) S) :
    Function.Exact (monodromyDifference ψ) incl := by
  intro x
  constructor
  · intro hx
    have hSx : S (x, 0) = 0 := by
      rw [hS]
      simpa using hx
    obtain ⟨p, hp⟩ := (h₁ (x, 0)).mp hSx
    have hsnd : p.2 = -p.1 :=
      snd_eq_neg_fst_of_coverDifference_snd_eq_zero (by rw [hp])
    refine ⟨-p.1, ?_⟩
    have hp1 : (coverDifference ψ (p.1, -p.1)).1 = x := by
      rw [← hsnd]
      exact congrArg Prod.fst hp
    rw [coverDifference_fst_of_eq_neg] at hp1
    rw [map_neg]
    exact hp1
  · rintro ⟨c, rfl⟩
    have hmem : (monodromyDifference ψ c, (0 : ι → G)) ∈
        Set.range (coverDifference ψ) := ⟨(-c, c), coverDifference_antidiagonal ψ c⟩
    have hzero := (h₁ (monodromyDifference ψ c, 0)).mpr hmem
    rw [hS] at hzero
    simpa using hzero

/-- Exactness of the Wang sequence at the total group: the kernel of the Wang boundary is the
image of the fibre inclusion. -/
public theorem exact_inclusion_wangBoundary
    (hS : ∀ p : G × (ι → G), S p = incl (p.1 + ∑ i, p.2 i))
    (h₂ : Function.Exact S bdry)
    (h₃ : Function.Exact bdry (coverDifference χ)) :
    Function.Exact incl (wangBoundary bdry) := by
  intro y
  constructor
  · intro hy
    have hz : coverDifference χ (bdry y) = 0 := h₃.apply_apply_eq_zero y
    have hsnd : (bdry y).2 = -(bdry y).1 :=
      snd_eq_neg_fst_of_coverDifference_snd_eq_zero (congrArg Prod.snd hz)
    have hy' : (bdry y).1 = 0 := hy
    have hzero : bdry y = 0 := by
      refine Prod.ext hy' ?_
      show (bdry y).2 = (0 : ι → H)
      rw [hsnd, hy', neg_zero]
    obtain ⟨p, hp⟩ := (h₂ y).mp hzero
    exact ⟨p.1 + ∑ i, p.2 i, by rw [← hS]; exact hp⟩
  · rintro ⟨x, rfl⟩
    have hx : incl x = S (x, 0) := by
      rw [hS]
      simp
    rw [hx]
    change (bdry (S (x, 0))).1 = 0
    rw [h₂.apply_apply_eq_zero (x, 0)]
    rfl

/-- Exactness of the Wang sequence at the lower edge-indexed group: the image of the Wang boundary
is the kernel of the monodromy difference. -/
public theorem exact_wangBoundary_monodromyDifference
    (h₃ : Function.Exact bdry (coverDifference χ)) :
    Function.Exact (wangBoundary bdry) (monodromyDifference χ) := by
  intro a
  constructor
  · intro ha
    have hzero : coverDifference χ (a, -a) = 0 := by
      refine Prod.ext ?_ ?_
      · show (coverDifference χ (a, -a)).1 = (0 : H)
        rw [coverDifference_fst_of_eq_neg, ha, neg_zero]
      · show (coverDifference χ (a, -a)).2 = (0 : ι → H)
        change -(a + -a) = (0 : ι → H)
        simp
    obtain ⟨y, hy⟩ := (h₃ (a, -a)).mp hzero
    exact ⟨y, congrArg Prod.fst hy⟩
  · rintro ⟨y, rfl⟩
    have hz : coverDifference χ (bdry y) = 0 := h₃.apply_apply_eq_zero y
    have hsnd : (bdry y).2 = -(bdry y).1 :=
      snd_eq_neg_fst_of_coverDifference_snd_eq_zero (congrArg Prod.snd hz)
    have hpair : bdry y = ((bdry y).1, -(bdry y).1) := Prod.ext rfl hsnd
    have hfst : (coverDifference χ ((bdry y).1, -(bdry y).1)).1 = 0 := by
      rw [← hpair]
      exact congrArg Prod.fst hz
    rw [coverDifference_fst_of_eq_neg] at hfst
    exact neg_eq_zero.mp hfst

/-- The full algebraic splice: a five-term Mayer--Vietoris segment of the shape produced by the
two-set cover of a bouquet mapping torus contains a Wang exact sequence. -/
public theorem wangExactness_of_mayerVietoris
    (hS : ∀ p : G × (ι → G), S p = incl (p.1 + ∑ i, p.2 i))
    (h₁ : Function.Exact (coverDifference ψ) S)
    (h₂ : Function.Exact S bdry)
    (h₃ : Function.Exact bdry (coverDifference χ)) :
    Function.Exact (monodromyDifference ψ) incl ∧
      Function.Exact incl (wangBoundary bdry) ∧
      Function.Exact (wangBoundary bdry) (monodromyDifference χ) :=
  ⟨exact_monodromyDifference_inclusion ψ hS h₁,
    exact_inclusion_wangBoundary χ hS h₂ h₃,
    exact_wangBoundary_monodromyDifference χ h₃⟩

end WangFromMayerVietoris

/-! ## The Wang sequence of the explicit finite-bouquet mapping torus -/

section FiniteBouquet

open WangFromMayerVietoris

/-- The cellular local-coefficient differential of `WangHomologyPresentation.lean` is the
algebraic monodromy difference of the induced maps on homology. -/
public theorem finiteBouquetMonodromyDifference_eq {ι F : Type} [Fintype ι]
    [TopologicalSpace F] (φ : ι → F ≃ₜ F) (k : ℕ) :
    finiteBouquetMonodromyDifference φ k =
      monodromyDifference (fun i ↦ integralSingularHomologyMap k (φ i)) := rfl

variable {ι F : Type}
  [Fintype ι] [Inhabited ι] [TopologicalSpace ι] [DiscreteTopology ι] [TopologicalSpace F]

/-- The fibre inclusion of the finite-bouquet mapping torus, on homology. -/
public noncomputable def finiteBouquetFiberInclusionMap (φ : ι → F ≃ₜ F) (k : ℕ) :
    IntegralSingularHomology k F →+
      IntegralSingularHomology k (FiniteBouquetMappingTorus φ) :=
  integralSingularHomologyMap k (finiteBouquetMappingTorusFiberInclusion φ)

/-- The axiom `establishedFiniteBouquetMappingTorusWangSequence` follows from the geometric
Mayer--Vietoris input alone.

The hypotheses are exactly what the two-set open cover of the mapping torus supplies: `S` is the
Mayer--Vietoris sum map of the cover, read through the identification of the homology of the
vertex piece with that of the fibre and of the homology of the edge piece with the `ι`-indexed
sum of copies of it; `bdry` is the Mayer--Vietoris boundary read through the identification of the
homology of the overlap with two such `ι`-indexed sums; `hS` records that each edge of the bouquet
enters the total space through the fibre; and `h₁, h₂, h₃` are three consecutive exactness
statements of the Mayer--Vietoris sequence of the cover. -/
public noncomputable def finiteBouquetMappingTorusWangSequence_of_mayerVietoris
    (φ : ι → F ≃ₜ F) (k : ℕ)
    (S : IntegralSingularHomology (k + 1) F × (ι → IntegralSingularHomology (k + 1) F) →+
      IntegralSingularHomology (k + 1) (FiniteBouquetMappingTorus φ))
    (bdry : IntegralSingularHomology (k + 1) (FiniteBouquetMappingTorus φ) →+
      (ι → IntegralSingularHomology k F) × (ι → IntegralSingularHomology k F))
    (hS : ∀ p, S p = finiteBouquetFiberInclusionMap φ (k + 1) (p.1 + ∑ i, p.2 i))
    (h₁ : Function.Exact
      (coverDifference (fun i ↦ integralSingularHomologyMap (k + 1) (φ i))) S)
    (h₂ : Function.Exact S bdry)
    (h₃ : Function.Exact bdry
      (coverDifference (fun i ↦ integralSingularHomologyMap k (φ i)))) :
    FiniteBouquetMappingTorusWangSequence φ k where
  boundary := wangBoundary bdry
  exact_highDifference_inclusion := by
    rw [finiteBouquetMonodromyDifference_eq]
    exact exact_monodromyDifference_inclusion _ hS h₁
  exact_inclusion_boundary :=
    exact_inclusion_wangBoundary _ hS h₂ h₃
  exact_boundary_lowDifference := by
    rw [finiteBouquetMonodromyDifference_eq]
    exact exact_wangBoundary_monodromyDifference _ h₃

end FiniteBouquet

/-! ## The quotient relation of the finite-bouquet mapping torus -/

section QuotientRelation

open scoped Classical

variable {ι F : Type} [TopologicalSpace F]

/-- The complete invariant of the finite-bouquet gluing: a point of a cylinder end is remembered
only through the point of the vertex fibre it is glued to, and an interior point only through
itself. -/
public def bouquetKey (φ : ι → F ≃ₜ F) (p : ι × unitInterval × F) :
    F ⊕ (ι × unitInterval × F) :=
  if p.2.1 = 0 then Sum.inl p.2.2
  else if p.2.1 = 1 then Sum.inl (φ p.1 p.2.2)
  else Sum.inr p

@[simp]
public theorem bouquetKey_zero (φ : ι → F ≃ₜ F) (i : ι) (x : F) :
    bouquetKey φ (i, 0, x) = Sum.inl x := by
  simp [bouquetKey]

@[simp]
public theorem bouquetKey_one (φ : ι → F ≃ₜ F) (i : ι) (x : F) :
    bouquetKey φ (i, 1, x) = Sum.inl (φ i x) := by
  have h : (1 : unitInterval) ≠ 0 := by
    intro h
    exact one_ne_zero (congrArg Subtype.val h)
  simp [bouquetKey, h]

public theorem bouquetKey_of_ne (φ : ι → F ≃ₜ F) {p : ι × unitInterval × F}
    (h0 : p.2.1 ≠ 0) (h1 : p.2.1 ≠ 1) : bouquetKey φ p = Sum.inr p := by
  simp [bouquetKey, h0, h1]

/-- The generating identifications preserve the invariant. -/
public theorem bouquetKey_of_relation {φ : ι → F ≃ₜ F} {p q : ι × unitInterval × F}
    (h : finiteBouquetMappingTorusRelation φ p q) : bouquetKey φ p = bouquetKey φ q := by
  obtain ⟨h1, h2⟩ | ⟨h0, h0', hx⟩ | ⟨h1, h0, hx⟩ := h
  · exact congrArg _ (Prod.ext h1 h2)
  · have hp : p = (p.1, 0, p.2.2) := by
      refine Prod.ext rfl (Prod.ext ?_ rfl)
      exact h0
    have hq : q = (q.1, 0, q.2.2) := by
      refine Prod.ext rfl (Prod.ext ?_ rfl)
      exact h0'
    rw [hp, hq, bouquetKey_zero, bouquetKey_zero, hx]
  · have hp : p = (p.1, 1, p.2.2) := by
      refine Prod.ext rfl (Prod.ext ?_ rfl)
      exact h1
    have hq : q = (q.1, 0, q.2.2) := by
      refine Prod.ext rfl (Prod.ext ?_ rfl)
      exact h0
    rw [hp, hq, bouquetKey_one, bouquetKey_zero, hx]

/-- Equal invariants are identified by the generating relation. -/
public theorem eqvGen_of_bouquetKey {φ : ι → F ≃ₜ F} {p q : ι × unitInterval × F}
    (h : bouquetKey φ p = bouquetKey φ q) :
    Relation.EqvGen (finiteBouquetMappingTorusRelation φ) p q := by
  by_cases hp0 : p.2.1 = 0
  · have hp : p = (p.1, 0, p.2.2) := Prod.ext rfl (Prod.ext hp0 rfl)
    by_cases hq0 : q.2.1 = 0
    · have hq : q = (q.1, 0, q.2.2) := Prod.ext rfl (Prod.ext hq0 rfl)
      have hx : p.2.2 = q.2.2 := by
        have := h
        rw [hp, hq, bouquetKey_zero, bouquetKey_zero] at this
        exact Sum.inl.inj this
      exact Relation.EqvGen.rel _ _ (Or.inr (Or.inl ⟨hp0, hq0, hx⟩))
    · by_cases hq1 : q.2.1 = 1
      · have hq : q = (q.1, 1, q.2.2) := Prod.ext rfl (Prod.ext hq1 rfl)
        have hx : p.2.2 = φ q.1 q.2.2 := by
          have := h
          rw [hp, hq, bouquetKey_zero, bouquetKey_one] at this
          exact Sum.inl.inj this
        exact Relation.EqvGen.symm _ _
          (Relation.EqvGen.rel _ _ (Or.inr (Or.inr ⟨hq1, hp0, hx⟩)))
      · exfalso
        have := h
        rw [hp, bouquetKey_zero, bouquetKey_of_ne φ hq0 hq1] at this
        exact absurd this (by simp)
  · by_cases hp1 : p.2.1 = 1
    · have hp : p = (p.1, 1, p.2.2) := Prod.ext rfl (Prod.ext hp1 rfl)
      by_cases hq0 : q.2.1 = 0
      · have hq : q = (q.1, 0, q.2.2) := Prod.ext rfl (Prod.ext hq0 rfl)
        have hx : q.2.2 = φ p.1 p.2.2 := by
          have := h
          rw [hp, hq, bouquetKey_one, bouquetKey_zero] at this
          exact (Sum.inl.inj this).symm
        exact Relation.EqvGen.rel _ _ (Or.inr (Or.inr ⟨hp1, hq0, hx⟩))
      · by_cases hq1 : q.2.1 = 1
        · have hq : q = (q.1, 1, q.2.2) := Prod.ext rfl (Prod.ext hq1 rfl)
          have hx : φ p.1 p.2.2 = φ q.1 q.2.2 := by
            have := h
            rw [hp, hq, bouquetKey_one, bouquetKey_one] at this
            exact Sum.inl.inj this
          refine Relation.EqvGen.trans _ (q.1, 0, φ p.1 p.2.2) _
            (Relation.EqvGen.rel _ _ (Or.inr (Or.inr ⟨hp1, rfl, rfl⟩))) ?_
          refine Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ (Or.inr (Or.inr ?_)))
          exact ⟨hq1, rfl, hx⟩
        · exfalso
          have := h
          rw [hp, bouquetKey_one, bouquetKey_of_ne φ hq0 hq1] at this
          exact absurd this (by simp)
    · have hp := bouquetKey_of_ne φ hp0 hp1
      by_cases hq0 : q.2.1 = 0
      · exfalso
        have hq : q = (q.1, 0, q.2.2) := Prod.ext rfl (Prod.ext hq0 rfl)
        have := h
        rw [hp, hq, bouquetKey_zero] at this
        exact absurd this (by simp)
      · by_cases hq1 : q.2.1 = 1
        · exfalso
          have hq : q = (q.1, 1, q.2.2) := Prod.ext rfl (Prod.ext hq1 rfl)
          have := h
          rw [hp, hq, bouquetKey_one] at this
          exact absurd this (by simp)
        · have hq := bouquetKey_of_ne φ hq0 hq1
          have : p = q := by
            have := h
            rw [hp, hq] at this
            exact Sum.inr.inj this
          exact this ▸ Relation.EqvGen.refl p

/-- The equivalence relation generated by the bouquet identifications is exactly equality of the
invariant `bouquetKey`.  In particular the quotient map is injective away from the cylinder
ends. -/
public theorem eqvGen_iff_bouquetKey (φ : ι → F ≃ₜ F) (p q : ι × unitInterval × F) :
    Relation.EqvGen (finiteBouquetMappingTorusRelation φ) p q ↔
      bouquetKey φ p = bouquetKey φ q := by
  refine ⟨fun h ↦ ?_, eqvGen_of_bouquetKey⟩
  induction h with
  | rel _ _ hr => exact bouquetKey_of_relation hr
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- The quotient map onto the finite-bouquet mapping torus. -/
public def bouquetMk (φ : ι → F ≃ₜ F) (p : ι × unitInterval × F) :
    FiniteBouquetMappingTorus φ :=
  Quotient.mk (finiteBouquetMappingTorusSetoid φ) p

public theorem bouquetMk_surjective (φ : ι → F ≃ₜ F) : Function.Surjective (bouquetMk φ) :=
  fun z ↦ Quotient.exists_rep z

public theorem continuous_bouquetMk [TopologicalSpace ι] (φ : ι → F ≃ₜ F) :
    Continuous (bouquetMk φ) :=
  continuous_quot_mk

/-- Two points of the disjoint union of cylinders have the same image in the finite-bouquet
mapping torus exactly when they have the same invariant. -/
public theorem bouquetMk_eq_iff (φ : ι → F ≃ₜ F) (p q : ι × unitInterval × F) :
    bouquetMk φ p = bouquetMk φ q ↔ bouquetKey φ p = bouquetKey φ q := by
  show Quotient.mk (finiteBouquetMappingTorusSetoid φ) p =
      Quotient.mk (finiteBouquetMappingTorusSetoid φ) q ↔ _
  rw [Quotient.eq]
  exact eqvGen_iff_bouquetKey φ p q

/-- Points with the same invariant are equal unless both lie on the cylinder ends. -/
public theorem eq_or_mem_ends_of_bouquetKey {φ : ι → F ≃ₜ F} {p q : ι × unitInterval × F}
    (h : bouquetKey φ p = bouquetKey φ q) :
    p = q ∨ ((p.2.1 = 0 ∨ p.2.1 = 1) ∧ (q.2.1 = 0 ∨ q.2.1 = 1)) := by
  by_cases hp0 : p.2.1 = 0
  · by_cases hq0 : q.2.1 = 0
    · exact Or.inr ⟨Or.inl hp0, Or.inl hq0⟩
    · by_cases hq1 : q.2.1 = 1
      · exact Or.inr ⟨Or.inl hp0, Or.inr hq1⟩
      · exfalso
        have hp : p = (p.1, 0, p.2.2) := Prod.ext rfl (Prod.ext hp0 rfl)
        rw [hp, bouquetKey_zero, bouquetKey_of_ne φ hq0 hq1] at h
        exact absurd h (by simp)
  · by_cases hp1 : p.2.1 = 1
    · by_cases hq0 : q.2.1 = 0
      · exact Or.inr ⟨Or.inr hp1, Or.inl hq0⟩
      · by_cases hq1 : q.2.1 = 1
        · exact Or.inr ⟨Or.inr hp1, Or.inr hq1⟩
        · exfalso
          have hp : p = (p.1, 1, p.2.2) := Prod.ext rfl (Prod.ext hp1 rfl)
          rw [hp, bouquetKey_one, bouquetKey_of_ne φ hq0 hq1] at h
          exact absurd h (by simp)
    · left
      by_cases hq0 : q.2.1 = 0
      · exfalso
        have hq : q = (q.1, 0, q.2.2) := Prod.ext rfl (Prod.ext hq0 rfl)
        rw [hq, bouquetKey_zero, bouquetKey_of_ne φ hp0 hp1] at h
        exact absurd h (by simp)
      · by_cases hq1 : q.2.1 = 1
        · exfalso
          have hq : q = (q.1, 1, q.2.2) := Prod.ext rfl (Prod.ext hq1 rfl)
          rw [hq, bouquetKey_one, bouquetKey_of_ne φ hp0 hp1] at h
          exact absurd h (by simp)
        · rw [bouquetKey_of_ne φ hp0 hp1, bouquetKey_of_ne φ hq0 hq1] at h
          exact Sum.inr.inj h


/-- The subset of the finite-bouquet mapping torus cut out by a condition on the cylinder
coordinate. -/
public def bouquetPiece (φ : ι → F ≃ₜ F) (c : Set unitInterval) :
    Set (FiniteBouquetMappingTorus φ) :=
  bouquetMk φ '' {p | p.2.1 ∈ c}

/-- A condition on the cylinder coordinate which does not separate the two cylinder ends cuts out
a saturated subset. -/
public theorem preimage_bouquetPiece (φ : ι → F ≃ₜ F) {c : Set unitInterval}
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c) :
    bouquetMk φ ⁻¹' bouquetPiece φ c = {p | p.2.1 ∈ c} := by
  ext p
  constructor
  · rintro ⟨q, hq, hqp⟩
    have hkey : bouquetKey φ q = bouquetKey φ p :=
      (bouquetMk_eq_iff φ q p).mp hqp
    rcases eq_or_mem_ends_of_bouquetKey hkey with rfl | ⟨hq', hp⟩
    · exact hq
    · show p.2.1 ∈ c
      have hqc : q.2.1 ∈ c := hq
      rcases hq' with h | h <;> rcases hp with h' | h' <;> rw [h'] <;> rw [h] at hqc
      · exact hqc
      · exact hc.mp hqc
      · exact hc.mpr hqc
      · exact hqc
  · intro hp
    exact ⟨p, hp, rfl⟩


end QuotientRelation

/-! ## The two-set open cover of a finite-bouquet mapping torus -/

section Cover

open scoped Classical

/-- A saturated subset cut out by an open condition on the cylinder coordinate is open. -/
public theorem isOpen_bouquetPiece {ι F : Type} [TopologicalSpace ι] [TopologicalSpace F]
    (φ : ι → F ≃ₜ F) {c : Set unitInterval} (hopen : IsOpen c)
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c) :
    IsOpen (bouquetPiece φ c) := by
  have hpre : IsOpen (bouquetMk φ ⁻¹' bouquetPiece φ c) := by
    rw [preimage_bouquetPiece φ hc]
    exact hopen.preimage (continuous_fst.comp continuous_snd)
  exact hpre

variable {ι F : Type} [TopologicalSpace F]

/-- Membership in a saturated piece is tested on any representative. -/
public theorem mem_bouquetPiece_mk_iff (φ : ι → F ≃ₜ F) {c : Set unitInterval}
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c) (p : ι × unitInterval × F) :
    bouquetMk φ p ∈ bouquetPiece φ c ↔ p.2.1 ∈ c := by
  have h := preimage_bouquetPiece φ (c := c) hc
  constructor
  · intro hp
    have hmem : p ∈ bouquetMk φ ⁻¹' bouquetPiece φ c := hp
    rw [h] at hmem
    exact hmem
  · intro hp
    have hmem : p ∈ bouquetMk φ ⁻¹' bouquetPiece φ c := by
      rw [h]
      exact hp
    exact hmem

/-- Saturated pieces intersect bandwise. -/
public theorem bouquetPiece_inter (φ : ι → F ≃ₜ F) {c d : Set unitInterval}
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c)
    (hd : (0 : unitInterval) ∈ d ↔ (1 : unitInterval) ∈ d) :
    bouquetPiece φ c ∩ bouquetPiece φ d = bouquetPiece φ (c ∩ d) := by
  refine (bouquetMk_surjective φ).preimage_injective ?_
  rw [Set.preimage_inter, preimage_bouquetPiece φ hc, preimage_bouquetPiece φ hd,
    preimage_bouquetPiece φ
      (show (0 : unitInterval) ∈ c ∩ d ↔ (1 : unitInterval) ∈ c ∩ d from
        ⟨fun h ↦ ⟨hc.mp h.1, hd.mp h.2⟩, fun h ↦ ⟨hc.mpr h.1, hd.mpr h.2⟩⟩)]
  rfl

/-- Saturated pieces unite bandwise. -/
public theorem bouquetPiece_union (φ : ι → F ≃ₜ F) {c d : Set unitInterval}
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c)
    (hd : (0 : unitInterval) ∈ d ↔ (1 : unitInterval) ∈ d) :
    bouquetPiece φ c ∪ bouquetPiece φ d = bouquetPiece φ (c ∪ d) := by
  refine (bouquetMk_surjective φ).preimage_injective ?_
  rw [Set.preimage_union, preimage_bouquetPiece φ hc, preimage_bouquetPiece φ hd,
    preimage_bouquetPiece φ
      (show (0 : unitInterval) ∈ c ∪ d ↔ (1 : unitInterval) ∈ c ∪ d from
        ⟨fun h ↦ h.imp hc.mp hd.mp, fun h ↦ h.imp hc.mpr hd.mpr⟩)]
  rfl

/-- A saturated piece whose band is everything is the whole mapping torus. -/
public theorem bouquetPiece_univ (φ : ι → F ≃ₜ F) :
    bouquetPiece φ (Set.univ : Set unitInterval) = Set.univ := by
  refine (bouquetMk_surjective φ).preimage_injective ?_
  rw [Set.preimage_univ, preimage_bouquetPiece φ Iff.rfl]
  rfl

/-! ### The vertex and edge bands -/

/-- The band around the two cylinder ends. -/
public def vertexBand : Set unitInterval := {t | (t : ℝ) < 1 / 3 ∨ 2 / 3 < (t : ℝ)}

/-- The band around the cylinder interiors. -/
public def edgeBand : Set unitInterval := {t | 1 / 6 < (t : ℝ) ∧ (t : ℝ) < 5 / 6}

public theorem isOpen_vertexBand : IsOpen vertexBand :=
  (isOpen_lt continuous_subtype_val continuous_const).union
    (isOpen_lt continuous_const continuous_subtype_val)

public theorem isOpen_edgeBand : IsOpen edgeBand :=
  (isOpen_lt continuous_const continuous_subtype_val).inter
    (isOpen_lt continuous_subtype_val continuous_const)

public theorem vertexBand_ends :
    (0 : unitInterval) ∈ vertexBand ↔ (1 : unitInterval) ∈ vertexBand := by
  constructor
  · intro _
    exact Or.inr (by norm_num)
  · intro _
    exact Or.inl (by norm_num)

public theorem edgeBand_ends :
    (0 : unitInterval) ∈ edgeBand ↔ (1 : unitInterval) ∈ edgeBand := by
  constructor
  · rintro ⟨h, -⟩
    exact absurd h (by norm_num)
  · rintro ⟨-, h⟩
    exact absurd h (by norm_num)

public theorem vertexBand_union_edgeBand : vertexBand ∪ edgeBand = Set.univ := by
  ext t
  constructor
  · intro _
    trivial
  · intro _
    rcases lt_or_ge (t : ℝ) (1 / 3) with h | h
    · exact Or.inl (Or.inl h)
    · rcases lt_or_ge (2 / 3 : ℝ) (t : ℝ) with h' | h'
      · exact Or.inl (Or.inr h')
      · exact Or.inr ⟨by linarith, by linarith⟩

/-- The vertex piece of the two-set cover: a neighbourhood of the fibre over the bouquet vertex,
consisting of the two collars of every cylinder. -/
public def vertexPiece (φ : ι → F ≃ₜ F) : Set (FiniteBouquetMappingTorus φ) :=
  bouquetPiece φ vertexBand

/-- The edge piece of the two-set cover: the disjoint interiors of the cylinders. -/
public def edgePiece (φ : ι → F ≃ₜ F) : Set (FiniteBouquetMappingTorus φ) :=
  bouquetPiece φ edgeBand

public theorem isOpen_vertexPiece [TopologicalSpace ι] (φ : ι → F ≃ₜ F) :
    IsOpen (vertexPiece φ) :=
  isOpen_bouquetPiece φ isOpen_vertexBand vertexBand_ends

public theorem isOpen_edgePiece [TopologicalSpace ι] (φ : ι → F ≃ₜ F) :
    IsOpen (edgePiece φ) :=
  isOpen_bouquetPiece φ isOpen_edgeBand edgeBand_ends

/-- The vertex and edge pieces cover the finite-bouquet mapping torus. -/
public theorem vertexPiece_union_edgePiece (φ : ι → F ≃ₜ F) :
    vertexPiece φ ∪ edgePiece φ = Set.univ := by
  rw [vertexPiece, edgePiece, bouquetPiece_union φ vertexBand_ends edgeBand_ends,
    vertexBand_union_edgeBand, bouquetPiece_univ]

/-- The overlap of the two pieces is the saturated piece over the two collar bands. -/
public theorem vertexPiece_inter_edgePiece (φ : ι → F ≃ₜ F) :
    vertexPiece φ ∩ edgePiece φ = bouquetPiece φ (vertexBand ∩ edgeBand) :=
  bouquetPiece_inter φ vertexBand_ends edgeBand_ends

/-! ### The cylinder interiors are embedded -/

public theorem ne_zero_of_mem_edgeBand {t : unitInterval} (h : t ∈ edgeBand) : t ≠ 0 := by
  intro h0
  have : (1 : ℝ) / 6 < 0 := by
    have := h.1
    rw [h0] at this
    exact this
  linarith

public theorem ne_one_of_mem_edgeBand {t : unitInterval} (h : t ∈ edgeBand) : t ≠ 1 := by
  intro h1
  have : (1 : ℝ) < 5 / 6 := by
    have := h.2
    rw [h1] at this
    exact this
  linarith

/-- Away from the cylinder ends the quotient map is injective: the interiors of the cylinders of
the bouquet are embedded and pairwise disjoint in the mapping torus. -/
public theorem bouquetMk_injOn_of_ne_ends (φ : ι → F ≃ₜ F) :
    Set.InjOn (bouquetMk φ) {p : ι × unitInterval × F | p.2.1 ≠ 0 ∧ p.2.1 ≠ 1} := by
  intro p hp q hq hpq
  have hkey := (bouquetMk_eq_iff φ p q).mp hpq
  rw [bouquetKey_of_ne φ hp.1 hp.2, bouquetKey_of_ne φ hq.1 hq.2] at hkey
  exact Sum.inr.inj hkey

/-- The quotient map is injective on the edge band. -/
public theorem bouquetMk_injOn_edgeBand (φ : ι → F ≃ₜ F) :
    Set.InjOn (bouquetMk φ) {p : ι × unitInterval × F | p.2.1 ∈ edgeBand} := by
  refine Set.InjOn.mono (fun p hp ↦ ?_) (bouquetMk_injOn_of_ne_ends φ)
  exact ⟨ne_zero_of_mem_edgeBand hp, ne_one_of_mem_edgeBand hp⟩

/-! ### The fibre over the bouquet vertex -/

public theorem finiteBouquetMappingTorusFiberInclusion_eq [TopologicalSpace ι] [Inhabited ι]
    (φ : ι → F ≃ₜ F) (x : F) :
    finiteBouquetMappingTorusFiberInclusion φ x = bouquetMk φ (default, 0, x) := rfl

/-- The fibre over the bouquet vertex lies in the vertex piece of the cover. -/
public theorem fiberInclusion_mem_vertexPiece [TopologicalSpace ι] [Inhabited ι]
    (φ : ι → F ≃ₜ F) (x : F) :
    finiteBouquetMappingTorusFiberInclusion φ x ∈ vertexPiece φ := by
  rw [finiteBouquetMappingTorusFiberInclusion_eq, vertexPiece,
    mem_bouquetPiece_mk_iff φ vertexBand_ends]
  exact Or.inl (by norm_num)

/-- The fibre over the bouquet vertex misses the edge piece. -/
public theorem fiberInclusion_notMem_edgePiece [TopologicalSpace ι] [Inhabited ι]
    (φ : ι → F ≃ₜ F) (x : F) :
    finiteBouquetMappingTorusFiberInclusion φ x ∉ edgePiece φ := by
  rw [finiteBouquetMappingTorusFiberInclusion_eq, edgePiece,
    mem_bouquetPiece_mk_iff φ edgeBand_ends]
  intro h
  exact ne_zero_of_mem_edgeBand h rfl

end Cover

/-! ## Homology of an empty space, and of a disjoint open pair -/

section Additivity

open CategoryTheory CategoryTheory.Limits AlgebraicTopology IntegralMayerVietoris

/-- The coproduct of an empty family of objects is an initial object. -/
public noncomputable def isInitialSigmaOfIsEmpty {C : Type*} [Category C] {J : Type} [IsEmpty J]
    (f : J → C) [HasCoproduct f] : IsInitial (∐ f) :=
  IsInitial.ofUniqueHom (fun _ ↦ Sigma.desc fun i ↦ isEmptyElim i)
    (fun _ _ ↦ Sigma.hom_ext _ _ fun i ↦ isEmptyElim i)

/-- Integral singular homology of an empty space vanishes in every degree.  In positive degrees
this is the totally disconnected computation; in degree zero the free group on the (empty) set of
path components is trivial. -/
public theorem subsingleton_integralSingularHomology_of_isEmpty
    (Y : Type) [TopologicalSpace Y] [IsEmpty Y] (k : ℕ) :
    Subsingleton (IntegralSingularHomology k Y) := by
  match k with
  | 0 =>
    have hiso := singularHomologyFunctorZeroOfTotallyDisconnectedSpace AddCommGrpCat
      (AddCommGrpCat.of ℤ) (TopCat.of Y)
    have hz : IsZero (∐ fun _ : (TopCat.of Y) ↦ (AddCommGrpCat.of ℤ)) :=
      (isInitialSigmaOfIsEmpty _).isZero
    exact AddCommGrpCat.subsingleton_of_isZero (hz.of_iso hiso)
  | (k + 1) =>
    exact AddCommGrpCat.subsingleton_of_isZero
      (isZero_singularHomologyFunctor_of_totallyDisconnectedSpace AddCommGrpCat (k + 1)
        (AddCommGrpCat.of ℤ) (TopCat.of Y) (Nat.succ_ne_zero k))

/-- For a disjoint pair of open sets, the Mayer--Vietoris sum map is an isomorphism in every
degree: integral singular homology is additive on finite disjoint open unions. -/
public theorem sumMap_bijective_of_isEmpty_inter {X : Type} [TopologicalSpace X] (A B : Set X)
    (hA : IsOpen A) (hB : IsOpen B) [IsEmpty (A ∩ B : Set X)] (k : ℕ) :
    Function.Bijective (sumMap A B k) := by
  obtain ⟨boundary, hb⟩ := establishedIntegralMayerVietorisExactSequence A B hA hB
  constructor
  · obtain ⟨-, -, h₃⟩ := hb k
    rw [injective_iff_map_eq_zero]
    intro y hy
    obtain ⟨z, rfl⟩ := (h₃ y).mp hy
    have := subsingleton_integralSingularHomology_of_isEmpty (A ∩ B : Set X) k
    rw [Subsingleton.elim z 0, map_zero]
  · match k with
    | 0 => exact sumMap_zero_surjective A B hA hB
    | (k + 1) =>
      obtain ⟨h₁, -, -⟩ := hb k
      intro y
      have := subsingleton_integralSingularHomology_of_isEmpty (A ∩ B : Set X) k
      exact (h₁ y).mp (Subsingleton.elim _ _)

end Additivity

/-! ## Descending maps and homotopies to the pieces of the cover -/

section Descent

open Topology

variable {ι F : Type} [TopologicalSpace ι] [TopologicalSpace F]

/-- The restriction of a quotient map over an open subset of the target is a quotient map. -/
public theorem isQuotientMap_restrictPreimage_of_isOpen {A B : Type*} [TopologicalSpace A]
    [TopologicalSpace B] {f : A → B} (hf : IsQuotientMap f) {S : Set B} (hS : IsOpen S) :
    IsQuotientMap (S.restrictPreimage f) := by
  have hcont : Continuous (S.restrictPreimage f) := hf.continuous.restrictPreimage
  refine (isQuotientMap_iff _).mpr ⟨IsCoinducing.of_isOpen_preimage_iff_isOpen fun T ↦ ?_, ?_⟩
  · refine ⟨fun hT ↦ ?_, fun hT ↦ hcont.isOpen_preimage T hT⟩
    have hpre : f ⁻¹' (Subtype.val '' T) = Subtype.val '' (S.restrictPreimage f ⁻¹' T) := by
      ext a
      constructor
      · rintro ⟨y, hyT, hy⟩
        have haS : a ∈ f ⁻¹' S := by
          rw [Set.mem_preimage, ← hy]
          exact y.2
        refine ⟨⟨a, haS⟩, ?_, rfl⟩
        show (⟨f a, haS⟩ : ↥S) ∈ T
        convert hyT using 1
        exact Subtype.ext hy.symm
      · rintro ⟨x, hxT, rfl⟩
        exact ⟨⟨f x.1, x.2⟩, hxT, rfl⟩
    have hopen : IsOpen (f ⁻¹' (Subtype.val '' T)) := by
      rw [hpre]
      exact ((hS.preimage hf.continuous).isOpenMap_subtype_val) _ hT
    have hT' : IsOpen (Subtype.val '' T) := hf.isCoinducing.isOpen_preimage.mp hopen
    have hTT : T = Subtype.val ⁻¹' (Subtype.val '' T) := by
      ext b
      simp
    rw [hTT]
    exact hT'.preimage continuous_subtype_val
  · rintro ⟨b, hb⟩
    obtain ⟨a, ha⟩ := hf.surjective b
    refine ⟨⟨a, ?_⟩, ?_⟩
    · show a ∈ f ⁻¹' S
      rw [Set.mem_preimage, ha]
      exact hb
    · exact Subtype.ext ha

public theorem isQuotientMap_bouquetMk (φ : ι → F ≃ₜ F) : IsQuotientMap (bouquetMk φ) :=
  isQuotientMap_quot_mk

/-- The quotient map onto a saturated piece, from the corresponding band of cylinders. -/
public def pieceMk (φ : ι → F ≃ₜ F) (c : Set unitInterval)
    (p : {p : ι × unitInterval × F // p.2.1 ∈ c}) : ↥(bouquetPiece φ c) :=
  ⟨bouquetMk φ p.1, ⟨p.1, p.2, rfl⟩⟩

public theorem continuous_pieceMk (φ : ι → F ≃ₜ F) (c : Set unitInterval) :
    Continuous (pieceMk φ c) :=
  ((continuous_bouquetMk φ).comp continuous_subtype_val).subtype_mk _

/-- The quotient map onto a saturated piece, bundled as a continuous map. -/
public def pieceMkCM (φ : ι → F ≃ₜ F) (c : Set unitInterval) :
    C({p : ι × unitInterval × F // p.2.1 ∈ c}, ↥(bouquetPiece φ c)) :=
  ⟨pieceMk φ c, continuous_pieceMk φ c⟩

/-- Each saturated open piece carries the quotient topology from its band of cylinders. -/
public theorem isQuotientMap_pieceMk (φ : ι → F ≃ₜ F) {c : Set unitInterval} (hopen : IsOpen c)
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c) :
    IsQuotientMap (pieceMk φ c) := by
  have hrestrict : IsQuotientMap ((bouquetPiece φ c).restrictPreimage (bouquetMk φ)) :=
    isQuotientMap_restrictPreimage_of_isOpen (isQuotientMap_bouquetMk φ)
      (isOpen_bouquetPiece φ hopen hc)
  have hcongr : IsQuotientMap
      (Homeomorph.setCongr (preimage_bouquetPiece φ hc).symm) :=
    Homeomorph.isQuotientMap _
  have hcomp := hrestrict.comp hcongr
  have heq : ((bouquetPiece φ c).restrictPreimage (bouquetMk φ)) ∘
      (Homeomorph.setCongr (preimage_bouquetPiece φ hc).symm) = pieceMk φ c := by
    funext p
    exact Subtype.ext rfl
  rwa [heq] at hcomp

public theorem isQuotientMap_pieceMkCM (φ : ι → F ≃ₜ F) {c : Set unitInterval} (hopen : IsOpen c)
    (hc : (0 : unitInterval) ∈ c ↔ (1 : unitInterval) ∈ c) :
    IsQuotientMap ⇑(pieceMkCM φ c) :=
  isQuotientMap_pieceMk φ hopen hc

end Descent

/-! ## The vertex piece retracts onto the fibre -/

section VertexRetraction

open Topology
open scoped Classical

/-- A map which agrees with a continuous map on each member of an open cover by two sets is
continuous. -/
public theorem continuous_of_isOpen_pair {A Z : Type*} [TopologicalSpace A] [TopologicalSpace Z]
    {s t : Set A} (hs : IsOpen s) (ht : IsOpen t) (hcover : ∀ a : A, a ∈ s ∨ a ∈ t)
    {h f g : A → Z} (hf : Continuous f) (hg : Continuous g)
    (hfs : Set.EqOn h f s) (hgt : Set.EqOn h g t) : Continuous h := by
  rw [continuous_iff_continuousAt]
  intro a
  rcases hcover a with ha | ha
  · exact hf.continuousAt.congr (Filter.eventuallyEq_of_mem (hs.mem_nhds ha) hfs).symm
  · exact hg.continuousAt.congr (Filter.eventuallyEq_of_mem (ht.mem_nhds ha) hgt).symm

variable {ι F : Type} [TopologicalSpace F]

/-- The retraction of a vertex band onto the fibre: the low collar is projected to the fibre
directly, the high collar through the monodromy of its loop. -/
public def vertexRetractFun (φ : ι → F ≃ₜ F) (p : ι × unitInterval × F) : F :=
  if (p.2.1 : ℝ) < 1 / 3 then p.2.2 else φ p.1 p.2.2

public theorem vertexRetractFun_of_lt (φ : ι → F ≃ₜ F) {p : ι × unitInterval × F}
    (h : (p.2.1 : ℝ) < 1 / 3) : vertexRetractFun φ p = p.2.2 := by
  rw [vertexRetractFun]
  split
  · rfl
  · exact absurd h (by assumption)

public theorem vertexRetractFun_of_gt (φ : ι → F ≃ₜ F) {p : ι × unitInterval × F}
    (h : ¬ (p.2.1 : ℝ) < 1 / 3) : vertexRetractFun φ p = φ p.1 p.2.2 := by
  rw [vertexRetractFun]
  split
  · exact absurd (by assumption) h
  · rfl

/-- The band of collars around the two cylinder ends, in the disjoint union of cylinders. -/
public abbrev VertexBandSet (ι F : Type) [TopologicalSpace F] :=
  {p : ι × unitInterval × F // p.2.1 ∈ vertexBand}


/-! ### Sliding the collars onto the fibre -/

section Slide

variable {ι F : Type}

/-- The end selected by a point of the vertex band: `0` on the low collar and `1` on the high
collar, interpolated continuously in between. -/
public def endSelector (t : unitInterval) : ℝ := max 0 (min 1 (3 * (t : ℝ) - 1))

public theorem endSelector_nonneg (t : unitInterval) : 0 ≤ endSelector t := le_max_left _ _

public theorem endSelector_le_one (t : unitInterval) : endSelector t ≤ 1 :=
  max_le zero_le_one (min_le_left _ _)

public theorem continuous_endSelector : Continuous endSelector := by
  refine continuous_const.max (continuous_const.min ?_)
  exact (continuous_const.mul continuous_subtype_val).sub continuous_const

public theorem endSelector_of_lt {t : unitInterval} (h : (t : ℝ) < 1 / 3) : endSelector t = 0 := by
  have h1 : min 1 (3 * (t : ℝ) - 1) ≤ 0 := le_trans (min_le_right _ _) (by linarith)
  exact max_eq_left h1

public theorem endSelector_of_gt {t : unitInterval} (h : 2 / 3 < (t : ℝ)) : endSelector t = 1 := by
  have h1 : min 1 (3 * (t : ℝ) - 1) = 1 := min_eq_left (by linarith)
  rw [endSelector, h1]
  exact max_eq_right zero_le_one

public theorem endSelector_zero : endSelector 0 = 0 :=
  endSelector_of_lt (by norm_num)

public theorem endSelector_one : endSelector 1 = 1 :=
  endSelector_of_gt (by norm_num)

/-- Slide a point of a cylinder towards the end selected by its collar. -/
public def vertexSlideFun (p : ι × unitInterval × F) (s : unitInterval) :
    ι × unitInterval × F :=
  (p.1, ⟨(1 - (s : ℝ)) * (p.2.1 : ℝ) + (s : ℝ) * endSelector p.2.1, by
    have hs0 : (0 : ℝ) ≤ (s : ℝ) := s.2.1
    have hs1 : (s : ℝ) ≤ 1 := s.2.2
    have ht0 : (0 : ℝ) ≤ (p.2.1 : ℝ) := p.2.1.2.1
    have ht1 : (p.2.1 : ℝ) ≤ 1 := p.2.1.2.2
    have he0 : 0 ≤ endSelector p.2.1 := endSelector_nonneg _
    have he1 : endSelector p.2.1 ≤ 1 := endSelector_le_one _
    constructor
    · nlinarith
    · nlinarith⟩, p.2.2)

@[simp]
public theorem vertexSlideFun_fst (p : ι × unitInterval × F) (s : unitInterval) :
    (vertexSlideFun p s).1 = p.1 := rfl

@[simp]
public theorem vertexSlideFun_snd_snd (p : ι × unitInterval × F) (s : unitInterval) :
    (vertexSlideFun p s).2.2 = p.2.2 := rfl

@[simp]
public theorem vertexSlideFun_coe (p : ι × unitInterval × F) (s : unitInterval) :
    (((vertexSlideFun p s).2.1 : unitInterval) : ℝ) =
      (1 - (s : ℝ)) * (p.2.1 : ℝ) + (s : ℝ) * endSelector p.2.1 := rfl

/-- At time zero the slide is the identity. -/
public theorem vertexSlideFun_zero (p : ι × unitInterval × F) : vertexSlideFun p 0 = p := by
  refine Prod.ext rfl (Prod.ext (Subtype.ext ?_) rfl)
  show (1 - ((0 : unitInterval) : ℝ)) * (p.2.1 : ℝ) + ((0 : unitInterval) : ℝ) * _ = _
  norm_num

/-- Points of the cylinder ends are fixed by the slide. -/
public theorem vertexSlideFun_of_eq_zero {p : ι × unitInterval × F} (h : p.2.1 = 0)
    (s : unitInterval) : vertexSlideFun p s = p := by
  refine Prod.ext rfl (Prod.ext (Subtype.ext ?_) rfl)
  rw [vertexSlideFun_coe, h, endSelector_zero]
  show (1 - (s : ℝ)) * ((0 : unitInterval) : ℝ) + (s : ℝ) * 0 = ((0 : unitInterval) : ℝ)
  norm_num

public theorem vertexSlideFun_of_eq_one {p : ι × unitInterval × F} (h : p.2.1 = 1)
    (s : unitInterval) : vertexSlideFun p s = p := by
  refine Prod.ext rfl (Prod.ext (Subtype.ext ?_) rfl)
  rw [vertexSlideFun_coe, h, endSelector_one]
  show (1 - (s : ℝ)) * ((1 : unitInterval) : ℝ) + (s : ℝ) * 1 = ((1 : unitInterval) : ℝ)
  have h1 : ((1 : unitInterval) : ℝ) = 1 := rfl
  rw [h1]
  ring

/-- The slide keeps the vertex band inside itself. -/
public theorem vertexSlideFun_mem_vertexBand {p : ι × unitInterval × F}
    (hp : p.2.1 ∈ vertexBand) (s : unitInterval) : (vertexSlideFun p s).2.1 ∈ vertexBand := by
  have hs0 : (0 : ℝ) ≤ (s : ℝ) := s.2.1
  have hs1 : (s : ℝ) ≤ 1 := s.2.2
  have ht0 : (0 : ℝ) ≤ (p.2.1 : ℝ) := p.2.1.2.1
  have ht1 : (p.2.1 : ℝ) ≤ 1 := p.2.1.2.2
  rcases hp with h | h
  · left
    rw [vertexSlideFun_coe, endSelector_of_lt h]
    nlinarith
  · right
    rw [vertexSlideFun_coe, endSelector_of_gt h]
    nlinarith

end Slide

/-- On the cylinder ends the invariant is the value of the retraction. -/
public theorem bouquetKey_eq_inl_vertexRetract (φ : ι → F ≃ₜ F) {p : ι × unitInterval × F}
    (h : p.2.1 = 0 ∨ p.2.1 = 1) : bouquetKey φ p = Sum.inl (vertexRetractFun φ p) := by
  rcases h with h | h
  · rw [show p = (p.1, 0, p.2.2) from Prod.ext rfl (Prod.ext h rfl), bouquetKey_zero,
      vertexRetractFun_of_lt φ (show (((0 : unitInterval)) : ℝ) < 1 / 3 by norm_num)]
  · rw [show p = (p.1, 1, p.2.2) from Prod.ext rfl (Prod.ext h rfl), bouquetKey_one,
      vertexRetractFun_of_gt φ (show ¬ (((1 : unitInterval)) : ℝ) < 1 / 3 by norm_num)]

/-- At time one the slide lands on the fibre point named by the retraction. -/
public theorem bouquetKey_vertexSlideFun_one (φ : ι → F ≃ₜ F) {p : ι × unitInterval × F}
    (hp : p.2.1 ∈ vertexBand) :
    bouquetKey φ (vertexSlideFun p 1) = Sum.inl (vertexRetractFun φ p) := by
  have hone : (((1 : unitInterval)) : ℝ) = 1 := rfl
  rcases hp with h | h
  · have hslide : vertexSlideFun p 1 = (p.1, 0, p.2.2) := by
      refine Prod.ext rfl (Prod.ext (Subtype.ext ?_) rfl)
      rw [vertexSlideFun_coe, endSelector_of_lt h, hone]
      show (1 - 1) * (p.2.1 : ℝ) + 1 * 0 = (((0 : unitInterval)) : ℝ)
      norm_num
    rw [hslide, bouquetKey_zero, vertexRetractFun_of_lt φ h]
  · have hslide : vertexSlideFun p 1 = (p.1, 1, p.2.2) := by
      refine Prod.ext rfl (Prod.ext (Subtype.ext ?_) rfl)
      rw [vertexSlideFun_coe, endSelector_of_gt h, hone]
      show (1 - 1) * (p.2.1 : ℝ) + 1 * 1 = (((1 : unitInterval)) : ℝ)
      norm_num
    rw [hslide, bouquetKey_one]
    refine congrArg Sum.inl (vertexRetractFun_of_gt φ ?_).symm
    intro hlt
    linarith

/-- Identified points of the band have identified slides. -/
public theorem bouquetKey_vertexSlideFun_congr (φ : ι → F ≃ₜ F) {p q : ι × unitInterval × F}
    (h : bouquetKey φ p = bouquetKey φ q) (s : unitInterval) :
    bouquetKey φ (vertexSlideFun p s) = bouquetKey φ (vertexSlideFun q s) := by
  rcases eq_or_mem_ends_of_bouquetKey h with hpq | ⟨hp, hq⟩
  · rw [hpq]
  · have hfp : vertexSlideFun p s = p := by
      rcases hp with h0 | h1
      · exact vertexSlideFun_of_eq_zero h0 s
      · exact vertexSlideFun_of_eq_one h1 s
    have hfq : vertexSlideFun q s = q := by
      rcases hq with h0 | h1
      · exact vertexSlideFun_of_eq_zero h0 s
      · exact vertexSlideFun_of_eq_one h1 s
    rw [hfp, hfq]
    exact h

variable [TopologicalSpace ι]

public theorem continuous_vertexSlideFun :
    Continuous fun q : (ι × unitInterval × F) × unitInterval ↦ vertexSlideFun q.1 q.2 := by
  refine (continuous_fst.comp continuous_fst).prodMk (Continuous.prodMk ?_ ?_)
  · refine Continuous.subtype_mk (Continuous.add ?_ ?_) _
    · exact (continuous_const.sub (continuous_subtype_val.comp continuous_snd)).mul
        (continuous_subtype_val.comp (continuous_fst.comp (continuous_snd.comp continuous_fst)))
    · exact (continuous_subtype_val.comp continuous_snd).mul
        (continuous_endSelector.comp (continuous_fst.comp (continuous_snd.comp continuous_fst)))
  · exact continuous_snd.comp (continuous_snd.comp continuous_fst)


/-- The slide of the vertex band, as a continuous family of paths in the vertex piece. -/
public noncomputable def vertexSlideBand (φ : ι → F ≃ₜ F) :
    C(VertexBandSet ι F, C(unitInterval, ↥(vertexPiece φ))) :=
  ContinuousMap.curry
    ⟨fun q ↦ pieceMk φ vertexBand
        ⟨vertexSlideFun q.1.1 q.2, vertexSlideFun_mem_vertexBand q.1.2 q.2⟩,
      (continuous_pieceMk φ vertexBand).comp
        ((continuous_vertexSlideFun.comp
          ((continuous_subtype_val.comp continuous_fst).prodMk continuous_snd)).subtype_mk _)⟩

@[simp]
public theorem vertexSlideBand_apply (φ : ι → F ≃ₜ F) (p : VertexBandSet ι F)
    (s : unitInterval) :
    vertexSlideBand φ p s =
      pieceMk φ vertexBand ⟨vertexSlideFun p.1 s, vertexSlideFun_mem_vertexBand p.2 s⟩ := rfl

public theorem vertexSlideBand_factorsThrough (φ : ι → F ≃ₜ F) :
    Function.FactorsThrough (vertexSlideBand φ) (pieceMkCM φ vertexBand) := by
  intro p q hpq
  have hkey : bouquetKey φ p.1 = bouquetKey φ q.1 :=
    (bouquetMk_eq_iff φ p.1 q.1).mp (congrArg Subtype.val hpq)
  refine ContinuousMap.ext fun s ↦ ?_
  rw [vertexSlideBand_apply, vertexSlideBand_apply]
  exact Subtype.ext ((bouquetMk_eq_iff φ _ _).mpr (bouquetKey_vertexSlideFun_congr φ hkey s))

/-- The slide of the vertex piece, as a continuous family of paths. -/
public noncomputable def vertexSlidePath (φ : ι → F ≃ₜ F) :
    C(↥(vertexPiece φ), C(unitInterval, ↥(vertexPiece φ))) :=
  (isQuotientMap_pieceMkCM φ isOpen_vertexBand vertexBand_ends).lift (vertexSlideBand φ)
    (vertexSlideBand_factorsThrough φ)

@[simp]
public theorem vertexSlidePath_pieceMk (φ : ι → F ≃ₜ F) (p : VertexBandSet ι F) :
    vertexSlidePath φ (pieceMk φ vertexBand p) = vertexSlideBand φ p :=
  congrFun (congrArg DFunLike.coe
    ((isQuotientMap_pieceMkCM φ isOpen_vertexBand vertexBand_ends).lift_comp
      (vertexSlideBand φ) (vertexSlideBand_factorsThrough φ))) p

variable [DiscreteTopology ι]

/-- Evaluating the monodromies is continuous, the loops of the bouquet being discrete. -/
public theorem continuous_monodromyEval (φ : ι → F ≃ₜ F) :
    Continuous fun p : ι × F ↦ φ p.1 p.2 :=
  continuous_prod_of_discrete_left.mpr fun i ↦ (φ i).continuous

public theorem continuous_vertexRetract (φ : ι → F ≃ₜ F) :
    Continuous fun p : VertexBandSet ι F ↦ vertexRetractFun φ p.1 := by
  refine continuous_of_isOpen_pair (s := {p : VertexBandSet ι F | (p.1.2.1 : ℝ) < 1 / 3})
    (t := {p : VertexBandSet ι F | 2 / 3 < (p.1.2.1 : ℝ)})
    (f := fun p ↦ p.1.2.2) (g := fun p ↦ φ p.1.1 p.1.2.2) ?_ ?_ ?_ ?_ ?_ ?_ ?_
  · exact isOpen_lt (continuous_subtype_val.comp
      (continuous_fst.comp (continuous_snd.comp continuous_subtype_val))) continuous_const
  · exact isOpen_lt continuous_const (continuous_subtype_val.comp
      (continuous_fst.comp (continuous_snd.comp continuous_subtype_val)))
  · intro p
    exact p.2
  · exact continuous_snd.comp (continuous_snd.comp continuous_subtype_val)
  · exact (continuous_monodromyEval φ).comp
      ((continuous_fst.comp continuous_subtype_val).prodMk
        (continuous_snd.comp (continuous_snd.comp continuous_subtype_val)))
  · intro p hp
    exact vertexRetractFun_of_lt φ hp
  · intro p hp
    refine vertexRetractFun_of_gt φ ?_
    have hgt : (2 : ℝ) / 3 < (p.1.2.1 : ℝ) := hp
    intro hlt
    linarith

/-- The retraction of the vertex band onto the fibre, as a bundled continuous map. -/
public def vertexRetractBand (φ : ι → F ≃ₜ F) : C(VertexBandSet ι F, F) :=
  ⟨fun p ↦ vertexRetractFun φ p.1, continuous_vertexRetract φ⟩

/-! ### The vertex piece is homotopy equivalent to the fibre -/

public theorem zero_mem_vertexBand : (0 : unitInterval) ∈ vertexBand :=
  Or.inl (by norm_num)

public theorem vertexRetractBand_factorsThrough (φ : ι → F ≃ₜ F) :
    Function.FactorsThrough (vertexRetractBand φ) (pieceMkCM φ vertexBand) := by
  intro p q hpq
  have hkey : bouquetKey φ p.1 = bouquetKey φ q.1 :=
    (bouquetMk_eq_iff φ p.1 q.1).mp (congrArg Subtype.val hpq)
  rcases eq_or_mem_ends_of_bouquetKey hkey with h | ⟨hp, hq⟩
  · exact congrArg (vertexRetractFun φ) h
  · exact Sum.inl.inj
      (((bouquetKey_eq_inl_vertexRetract φ hp).symm.trans hkey).trans
        (bouquetKey_eq_inl_vertexRetract φ hq))

/-- The retraction of the vertex piece onto the fibre over the bouquet vertex. -/
public noncomputable def vertexRetract (φ : ι → F ≃ₜ F) : C(↥(vertexPiece φ), F) :=
  (isQuotientMap_pieceMkCM φ isOpen_vertexBand vertexBand_ends).lift (vertexRetractBand φ)
    (vertexRetractBand_factorsThrough φ)

@[simp]
public theorem vertexRetract_pieceMk (φ : ι → F ≃ₜ F) (p : VertexBandSet ι F) :
    vertexRetract φ (pieceMk φ vertexBand p) = vertexRetractFun φ p.1 :=
  congrFun (congrArg DFunLike.coe
    ((isQuotientMap_pieceMkCM φ isOpen_vertexBand vertexBand_ends).lift_comp
      (vertexRetractBand φ) (vertexRetractBand_factorsThrough φ))) p

variable [Inhabited ι]

/-- The inclusion of the fibre over the bouquet vertex into the vertex piece. -/
public def vertexFiberInclusion (φ : ι → F ≃ₜ F) : C(F, ↥(vertexPiece φ)) :=
  ⟨fun x ↦ pieceMk φ vertexBand ⟨(default, 0, x), zero_mem_vertexBand⟩,
    (continuous_pieceMk φ vertexBand).comp
      (Continuous.subtype_mk
        (continuous_const.prodMk (continuous_const.prodMk continuous_id)) _)⟩

@[simp]
public theorem vertexRetract_vertexFiberInclusion (φ : ι → F ≃ₜ F) (x : F) :
    vertexRetract φ (vertexFiberInclusion φ x) = x := by
  rw [vertexFiberInclusion]
  change vertexRetract φ (pieceMk φ vertexBand ⟨(default, 0, x), zero_mem_vertexBand⟩) = x
  rw [vertexRetract_pieceMk]
  exact vertexRetractFun_of_lt φ (show (((0 : unitInterval)) : ℝ) < 1 / 3 by norm_num)


/-- The vertex piece deformation-retracts onto the fibre over the bouquet vertex. -/
public noncomputable def vertexSlideHomotopy (φ : ι → F ≃ₜ F) :
    ContinuousMap.Homotopy (ContinuousMap.id ↥(vertexPiece φ))
      ((vertexFiberInclusion φ).comp (vertexRetract φ)) where
  toFun q := vertexSlidePath φ q.2 q.1
  continuous_toFun :=
    (ContinuousMap.uncurry (vertexSlidePath φ)).continuous.comp continuous_swap
  map_zero_left u := by
    obtain ⟨p, rfl⟩ :=
      (isQuotientMap_pieceMkCM φ isOpen_vertexBand vertexBand_ends).surjective u
    change vertexSlidePath φ (pieceMk φ vertexBand p) 0 = _
    rw [vertexSlidePath_pieceMk, vertexSlideBand_apply]
    exact Subtype.ext (congrArg (bouquetMk φ) (vertexSlideFun_zero p.1))
  map_one_left u := by
    obtain ⟨p, rfl⟩ :=
      (isQuotientMap_pieceMkCM φ isOpen_vertexBand vertexBand_ends).surjective u
    change vertexSlidePath φ (pieceMk φ vertexBand p) 1 = _
    rw [vertexSlidePath_pieceMk, vertexSlideBand_apply]
    change (⟨bouquetMk φ (vertexSlideFun p.1 1), _⟩ : ↥(vertexPiece φ)) =
      vertexFiberInclusion φ (vertexRetract φ (pieceMk φ vertexBand p))
    rw [vertexRetract_pieceMk]
    refine Subtype.ext ((bouquetMk_eq_iff φ _ _).mpr ?_)
    rw [bouquetKey_vertexSlideFun_one φ p.2, bouquetKey_zero]

/-- The vertex piece of the cover is homotopy equivalent to the fibre, by the retraction. -/
public noncomputable def vertexPieceHomotopyEquiv (φ : ι → F ≃ₜ F) :
    ↥(vertexPiece φ) ≃ₕ F where
  toFun := vertexRetract φ
  invFun := vertexFiberInclusion φ
  left_inv := ⟨(vertexSlideHomotopy φ).symm⟩
  right_inv := by
    have h : (vertexRetract φ).comp (vertexFiberInclusion φ) = ContinuousMap.id F :=
      ContinuousMap.ext fun x ↦ vertexRetract_vertexFiberInclusion φ x
    rw [h]


end VertexRetraction

/-! ## Additivity over a finite disjoint open cover -/

section FiniteAdditivity

open IntegralMayerVietoris CategoryTheory AlgebraicTopology

/-- The inclusion of a subspace, as a continuous map. -/
public def subsetInclusion {X : Type} [TopologicalSpace X] (A : Set X) : C(↥A, X) :=
  ⟨Subtype.val, continuous_subtype_val⟩

/-- The sum of the inclusions of a family of subspaces, on integral singular homology. -/
public noncomputable def coverSumMap {X : Type} [TopologicalSpace X] {J : Type} [Fintype J]
    (A : J → Set X) (k : ℕ) :
    (∀ j, IntegralSingularHomology k ↥(A j)) →+ IntegralSingularHomology k X where
  toFun v := ∑ j, integralSingularHomologyMap k (subsetInclusion (A j)) (v j)
  map_zero' := by simp
  map_add' u v := by
    simp only [Pi.add_apply, map_add]
    exact Finset.sum_add_distrib

@[simp]
public theorem coverSumMap_apply {X : Type} [TopologicalSpace X] {J : Type} [Fintype J]
    (A : J → Set X) (k : ℕ) (v : ∀ j, IntegralSingularHomology k ↥(A j)) :
    coverSumMap A k v = ∑ j, integralSingularHomologyMap k (subsetInclusion (A j)) (v j) := rfl

/-- A subspace of a subspace, as a subspace. -/
public def subtypePreimageHomeo {X : Type} [TopologicalSpace X] {B W : Set X} (h : W ⊆ B) :
    ↥((Subtype.val : ↥B → X) ⁻¹' W) ≃ₜ ↥W where
  toFun x := ⟨x.1.1, x.2⟩
  invFun y := ⟨⟨y.1, h y.2⟩, y.2⟩
  left_inv _ := rfl
  right_inv _ := rfl
  continuous_toFun := (continuous_subtype_val.comp continuous_subtype_val).subtype_mk _
  continuous_invFun := (continuous_subtype_val.subtype_mk _).subtype_mk _

public theorem subsetInclusion_comp_subtypePreimageHomeo {X : Type} [TopologicalSpace X]
    {B W : Set X} (h : W ⊆ B) :
    (subsetInclusion B).comp (subsetInclusion ((Subtype.val : ↥B → X) ⁻¹' W)) =
      (subsetInclusion W).comp
        ⟨subtypePreimageHomeo h, (subtypePreimageHomeo h).continuous⟩ :=
  rfl

/-- Integral singular homology is additive over a finite disjoint open cover: the sum of the
inclusions of the members is an isomorphism. -/
public theorem coverSumMap_bijective {J : Type} [Fintype J] :
    ∀ (X : Type) (_ : TopologicalSpace X) (A : J → Set X), (∀ j, IsOpen (A j)) →
      (∀ j j', j ≠ j' → Disjoint (A j) (A j')) → (⋃ j, A j = Set.univ) → ∀ k : ℕ,
      Function.Bijective (coverSumMap A k) := by
  refine Fintype.induction_empty_option (P := fun J ↦ ∀ (X : Type)
    (_ : TopologicalSpace X) (A : J → Set X), (∀ j, IsOpen (A j)) →
      (∀ j j', j ≠ j' → Disjoint (A j) (A j')) → (⋃ j, A j = Set.univ) → ∀ k : ℕ,
      Function.Bijective (coverSumMap A k)) ?_ ?_ ?_ J
  · intro J J' _ e ih
    let _ : Fintype J := Fintype.ofEquiv J' e.symm
    intro X _ A hopen hdisj hcover k
    have hbij := ih X ‹_› (fun j ↦ A (e j)) (fun j ↦ hopen _)
      (fun j j' hjj' ↦ hdisj _ _ fun h ↦ hjj' (e.injective h))
      (by
        rw [← hcover]
        apply Set.Subset.antisymm
        · intro x hx
          obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hx
          exact Set.mem_iUnion.mpr ⟨e j, hj⟩
        · intro x hx
          obtain ⟨j', hj'⟩ := Set.mem_iUnion.mp hx
          obtain ⟨j, rfl⟩ := e.surjective j'
          exact Set.mem_iUnion.mpr ⟨j, hj'⟩) k
    have hre : Function.Bijective
        (fun v : (∀ j', IntegralSingularHomology k ↥(A j')) ↦ fun j ↦ v (e j)) :=
      (Equiv.piCongrLeft (fun j' ↦ IntegralSingularHomology k ↥(A j')) e).symm.bijective
    have hcomp : ⇑(coverSumMap A k) =
        (coverSumMap (fun j ↦ A (e j)) k) ∘ (fun v ↦ fun j ↦ v (e j)) := by
      funext v
      exact (Fintype.sum_equiv e _ _ fun j ↦ rfl).symm
    rw [hcomp]
    exact hbij.comp hre
  ·
    intro X _ A _ _ hcover k
    have hempty : IsEmpty X := by
      constructor
      intro x
      have : x ∈ (⋃ j : PEmpty, A j) := hcover ▸ Set.mem_univ x
      obtain ⟨-, ⟨j, rfl⟩, -⟩ := this
      exact j.elim
    have hsub := subsingleton_integralSingularHomology_of_isEmpty X k
    refine ⟨fun u v _ ↦ ?_, fun y ↦ ⟨0, Subsingleton.elim _ _⟩⟩
    funext j
    exact j.elim
  · intro J _ ih X _ A hopen hdisj hcover k
    classical
    set B : Set X := ⋃ j', A (some j') with hB
    have hBopen : IsOpen B := isOpen_iUnion fun j' ↦ hopen _
    have hAB : A none ∩ B = ∅ := by
      rw [hB, Set.inter_iUnion]
      refine Set.iUnion_eq_empty.mpr fun j' ↦ ?_
      exact Set.disjoint_iff_inter_eq_empty.mp (hdisj none (some j') (by simp))
    have hunion : A none ∪ B = Set.univ := by
      rw [hB, ← hcover]
      ext x
      constructor
      · rintro (hx | hx)
        · exact Set.mem_iUnion.mpr ⟨none, hx⟩
        · obtain ⟨j', hj'⟩ := Set.mem_iUnion.mp hx
          exact Set.mem_iUnion.mpr ⟨some j', hj'⟩
      · rintro hx
        obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hx
        match j, hj with
        | none, hj => exact Or.inl hj
        | some j', hj => exact Or.inr (Set.mem_iUnion.mpr ⟨j', hj⟩)
    let C : J → Set B := fun j ↦ (Subtype.val : B → X) ⁻¹' A (some j)
    have hCopen : ∀ j, IsOpen (C j) := fun j ↦
      (hopen (some j)).preimage continuous_subtype_val
    have hCdisj : ∀ j j', j ≠ j' → Disjoint (C j) (C j') := by
      intro j j' hjj'
      rw [Set.disjoint_left]
      intro x hx hx'
      exact Set.disjoint_left.mp (hdisj (some j) (some j') (by simpa)) hx hx'
    have hCcover : ⋃ j, C j = Set.univ := by
      ext x
      constructor
      · intro _
        exact Set.mem_univ x
      · intro _
        have hx : x.1 ∈ ⋃ j, A (some j) := by simpa only [← hB] using x.2
        obtain ⟨j, hj⟩ := Set.mem_iUnion.mp hx
        exact Set.mem_iUnion.mpr ⟨j, hj⟩
    have hinner := ih B inferInstance C hCopen hCdisj hCcover k
    have hsub (j : J) : A (some j) ⊆ B := by
      rw [hB]
      exact Set.subset_iUnion (fun j' ↦ A (some j')) j
    let eC (j : J) : IntegralSingularHomology k ↥(A (some j)) ≃+
        IntegralSingularHomology k ↥(C j) :=
      integralSingularHomologyEquiv k (subtypePreimageHomeo (hsub j)).symm
    have hcoords : Function.Bijective
        (fun v : (∀ q, IntegralSingularHomology k ↥(A q)) ↦
          (v none, fun j ↦ eC j (v (some j)))) := by
      let eTail := AddEquiv.piCongrRight eC
      exact ((Equiv.piOptionEquivProd :
          (∀ q, IntegralSingularHomology k ↥(A q)) ≃
            IntegralSingularHomology k ↥(A none) ×
              (∀ j, IntegralSingularHomology k ↥(A (some j)))).trans
        (Equiv.prodCongr (Equiv.refl _) eTail.toEquiv)).bijective
    have hpair : Function.Bijective
        (fun p : IntegralSingularHomology k ↥(A none) ×
            (∀ j, IntegralSingularHomology k ↥(C j)) ↦
          (p.1, coverSumMap C k p.2)) :=
      Function.bijective_id.prodMap hinner
    let _ : IsEmpty (A none ∩ B : Set X) :=
      ⟨fun x ↦ by
        have hx : x.1 ∈ (∅ : Set X) := by rw [← hAB]; exact x.2
        exact hx⟩
    have hbinary := sumMap_bijective_of_isEmpty_inter (A none) B (hopen none) hBopen k
    let eUnion : (A none ∪ B : Set X) ≃ₜ X :=
      (Homeomorph.setCongr hunion).trans (Homeomorph.Set.univ X)
    have htotal : Function.Bijective
        (fun v : (∀ q, IntegralSingularHomology k ↥(A q)) ↦
          integralSingularHomologyEquiv k eUnion
            (sumMap (A none) B k
              (v none, coverSumMap C k (fun j ↦ eC j (v (some j)))))) :=
      (integralSingularHomologyEquiv k eUnion).bijective.comp
        (hbinary.comp (hpair.comp hcoords))
    have hmapcomp : ∀ {Y Z W : Type} [TopologicalSpace Y] [TopologicalSpace Z]
        [TopologicalSpace W] (f : C(Y, Z)) (g : C(Z, W))
        (z : IntegralSingularHomology k Y),
        integralSingularHomologyMap k g (integralSingularHomologyMap k f z) =
          integralSingularHomologyMap k (g.comp f) z := by
      intro Y Z W _ _ _ f g z
      symm
      change ConcreteCategory.hom
        (((singularHomologyFunctor AddCommGrpCat k).obj (AddCommGrpCat.of ℤ)).map
          (TopCat.ofHom (g.comp f))) z = _
      rw [show TopCat.ofHom (g.comp f) = TopCat.ofHom f ≫ TopCat.ofHom g by rfl,
        Functor.map_comp]
      rfl
    have hleft (z : IntegralSingularHomology k ↥(A none)) :
        integralSingularHomologyEquiv k eUnion
            (integralSingularHomologyMap k (leftToUnion (A none) B) z) =
          integralSingularHomologyMap k (subsetInclusion (A none)) z := by
      rw [show integralSingularHomologyEquiv k eUnion
          (integralSingularHomologyMap k (leftToUnion (A none) B) z) =
        integralSingularHomologyMap k ⟨eUnion, eUnion.continuous⟩
          (integralSingularHomologyMap k (leftToUnion (A none) B) z) by rfl,
        hmapcomp]
      congr 1
    have htail (j : J) (z : IntegralSingularHomology k ↥(A (some j))) :
        integralSingularHomologyEquiv k eUnion
            (integralSingularHomologyMap k (rightToUnion (A none) B)
              (integralSingularHomologyMap k (subsetInclusion (C j)) (eC j z))) =
          integralSingularHomologyMap k (subsetInclusion (A (some j))) z := by
      rw [show integralSingularHomologyEquiv k eUnion
          (integralSingularHomologyMap k (rightToUnion (A none) B)
            (integralSingularHomologyMap k (subsetInclusion (C j)) (eC j z))) =
        integralSingularHomologyMap k ⟨eUnion, eUnion.continuous⟩
          (integralSingularHomologyMap k (rightToUnion (A none) B)
            (integralSingularHomologyMap k (subsetInclusion (C j)) (eC j z))) by rfl]
      rw [show eC j z = integralSingularHomologyMap k
        ⟨(subtypePreimageHomeo (hsub j)).symm,
          (subtypePreimageHomeo (hsub j)).symm.continuous⟩ z by rfl]
      rw [hmapcomp, hmapcomp, hmapcomp]
      congr 1
    convert htotal using 1
    funext v
    rw [coverSumMap_apply, Fintype.sum_option]
    change _ = integralSingularHomologyEquiv k eUnion
      (integralSingularHomologyMap k (leftToUnion (A none) B) (v none) +
        integralSingularHomologyMap k (rightToUnion (A none) B)
          (∑ j, integralSingularHomologyMap k (subsetInclusion (C j))
            (eC j (v (some j)))))
    simp only [map_add, map_sum, hleft]
    exact congrArg (fun y ↦ integralSingularHomologyMap k (subsetInclusion (A none))
      (v none) + y) (Finset.sum_congr rfl fun j _ ↦ (htail j (v (some j))).symm)

end FiniteAdditivity

end SphereSixComplex
