module

public import SphereSixComplex.Geometry.Quotient
public import SphereSixComplex.Periods.Nondegeneracy
public import Mathlib.NumberTheory.Modular

/-!
# Complex tori from period matrices

This file constructs the rank-four period lattice in `ℂ²`, proves proper discontinuity of its
translation action from a full-rank real period map, and applies the quotient-manifold theorem.
-/

open scoped Manifold

namespace SphereSixComplex.Geometry.ComplexTorus

open Filter Matrix SphereSixComplex.Geometry SphereSixComplex.Periods

public noncomputable section

/-- The group of integral coefficients for four periods. -/
public abbrev IntegerPeriods := Fin 4 → ℤ

/-- The real coefficient space underlying four periods. -/
public abbrev RealPeriods := Fin 4 → ℝ

/-- The complex vector space `ℂ²`. -/
public abbrev ComplexTwoSpace := Fin 2 → ℂ

/-- Evaluation of a period matrix on integral coefficients. -/
@[expose] public def periodVector (x : Parameters) (n : IntegerPeriods) : ComplexTwoSpace :=
  periodMatrix x *ᵥ fun j ↦ (n j : ℂ)

/-- The additive period map `ℤ⁴ → ℂ²`. -/
@[expose] public def periodHom (x : Parameters) : IntegerPeriods →+ ComplexTwoSpace where
  toFun := periodVector x
  map_zero' := by
    ext i
    simp [periodVector, Matrix.mulVec]
  map_add' a b := by
    simp only [periodVector, Pi.add_apply, Int.cast_add]
    change periodMatrix x *ᵥ ((fun j ↦ (a j : ℂ)) + fun j ↦ (b j : ℂ)) = _
    exact Matrix.mulVec_add _ _ _

@[simp]
public theorem periodVector_zero (x : Parameters) :
    periodVector x 0 = 0 :=
  (periodHom x).map_zero

@[simp]
public theorem periodVector_add (x : Parameters) (a b : IntegerPeriods) :
    periodVector x (a + b) = periodVector x a + periodVector x b :=
  (periodHom x).map_add a b

/-- The additive subgroup generated by the four columns of the period matrix. -/
@[expose] public def periodLattice (x : Parameters) : AddSubgroup ComplexTwoSpace :=
  (periodHom x).range

/-- The standard inclusion of `ℤ⁴` into `ℝ⁴`. -/
public def integerToReal (n : IntegerPeriods) : RealPeriods := fun i ↦ n i

/-- The standard inclusion of integral coefficients into real coefficients is injective. -/
public theorem integerToReal_injective : Function.Injective integerToReal := by
  intro a b h
  funext i
  have hi := congrFun h i
  change (a i : ℝ) = (b i : ℝ) at hi
  exact_mod_cast hi

/-- Full real rank of the period map: its real extension is a continuous linear equivalence. -/
public structure FullRank (x : Parameters) where
  realEquiv : RealPeriods ≃L[ℝ] ComplexTwoSpace
  map_integer (n : IntegerPeriods) : realEquiv (integerToReal n) = periodVector x n

/-- The inequalities from the construction supply a full-rank period map. -/
public noncomputable def FullRank.ofSetupInequalities (x : Parameters) (h : SetupInequalities x) :
    FullRank x where
  realEquiv := (periodRealLinearEquiv x h).toContinuousLinearEquiv
  map_integer n := by
    change periodRealLinearEquiv x h (integerToReal n) = periodVector x n
    rw [periodRealLinearEquiv_apply, periodRealLinear_eq_mulVec]
    rfl

/-- The standard integral lattice in `ℝ⁴` escapes every compact set. -/
public theorem integerToReal_tendsto_cofinite_cocompact :
    Tendsto integerToReal cofinite (cocompact RealPeriods) := by
  convert! Tendsto.pi_map_coprodᵢ fun _ : Fin 4 ↦ Int.tendsto_coe_cofinite
  · rw [coprodᵢ_cofinite]
  · rw [coprodᵢ_cocompact]

/-- A full-rank period map is injective on integral coefficients. -/
public theorem periodHom_injective {x : Parameters} (h : FullRank x) :
    Function.Injective (periodHom x) := by
  intro a b hab
  have hc : integerToReal a = integerToReal b := h.realEquiv.injective <| by
    rw [h.map_integer, h.map_integer]
    exact hab
  funext i
  have hi := congrFun hc i
  change (a i : ℝ) = (b i : ℝ) at hi
  exact_mod_cast hi

/-- A full-rank period map escapes every compact subset of `ℂ²`. -/
public theorem periodHom_tendsto_cofinite_cocompact {x : Parameters} (h : FullRank x) :
    Tendsto (periodHom x) cofinite (cocompact ComplexTwoSpace) := by
  have he := h.realEquiv.toHomeomorph.isClosedEmbedding.tendsto_cocompact.comp
    integerToReal_tendsto_cofinite_cocompact
  convert he using 1
  funext n
  exact (h.map_integer n).symm

/-- The inclusion of a full-rank period lattice escapes every compact subset of `ℂ²`. -/
public theorem periodLattice_subtype_tendsto_cofinite_cocompact {x : Parameters}
    (h : FullRank x) :
    Tendsto (periodLattice x).subtype cofinite (cocompact ComplexTwoSpace) := by
  let e : IntegerPeriods ≃+ periodLattice x :=
    AddMonoidHom.ofInjective (periodHom_injective h)
  show map (periodLattice x).subtype cofinite ≤ cocompact ComplexTwoSpace
  calc
    map (periodLattice x).subtype cofinite ≤
        map (periodLattice x).subtype (map e cofinite) :=
      map_mono e.surjective.le_map_cofinite
    _ = map ((periodLattice x).subtype ∘ e) cofinite := map_map.symm
    _ = map (periodHom x) cofinite := by
      congr 1
    _ ≤ cocompact ComplexTwoSpace := periodHom_tendsto_cofinite_cocompact h

/-- The multiplicative wrapper of an additive subgroup acts by translations. -/
public instance continuousConstSMul_multiplicative_addSubgroup
    (L : AddSubgroup ComplexTwoSpace) :
    ContinuousConstSMul (Multiplicative L) ComplexTwoSpace where
  continuous_const_smul g := by
    change Continuous fun z : ComplexTwoSpace ↦ (g.toAdd : ComplexTwoSpace) + z
    exact continuous_const_add _

/-- Translation by a subgroup is a free action. -/
public instance isCancelSMul_multiplicative_addSubgroup (L : AddSubgroup ComplexTwoSpace) :
    IsCancelSMul (Multiplicative L) ComplexTwoSpace where
  right_cancel' g g' z h := by
    change g.toAdd = g'.toAdd
    apply Subtype.ext
    change (g.toAdd : ComplexTwoSpace) + z = (g'.toAdd : ComplexTwoSpace) + z at h
    exact add_right_cancel h

/-- A period translation fixing one point is the identity translation. -/
public theorem periodTranslation_fixed_iff (x : Parameters)
    (g : Multiplicative (periodLattice x))
    (z : ComplexTwoSpace) : g • z = z ↔ g = 1 := by
  constructor
  · exact isCancelSMul_iff_eq_one_of_smul_eq.mp inferInstance g z
  · rintro rfl
    exact one_smul _ _

/-- Proper discontinuity of an additive action passes to its multiplicative wrapper. -/
public theorem properlyDiscontinuousSMul_multiplicative_of_vadd
    (L : AddSubgroup ComplexTwoSpace) (h : ProperlyDiscontinuousVAdd L ComplexTwoSpace) :
    ProperlyDiscontinuousSMul (Multiplicative L) ComplexTwoSpace where
  finite_disjoint_inter_image {K} {L'} hK hL :=
    @ProperlyDiscontinuousVAdd.finite_disjoint_inter_image L ComplexTwoSpace _ _ h K L' hK hL

/-- Full real rank makes the period-lattice translation action properly discontinuous. -/
public theorem periodLattice_properlyDiscontinuousSMul {x : Parameters} (h : FullRank x) :
    ProperlyDiscontinuousSMul (Multiplicative (periodLattice x)) ComplexTwoSpace :=
  properlyDiscontinuousSMul_multiplicative_of_vadd (periodLattice x)
    ((periodLattice x).properlyDiscontinuousVAdd_of_tendsto_cofinite
      (periodLattice_subtype_tendsto_cofinite_cocompact h))

/-- The rank-four group acting on `ℂ²` by period translations. -/
public abbrev PeriodGroup (x : Parameters) := Multiplicative (periodLattice x)

/-- The complex torus associated to a full-rank period matrix. -/
public abbrev Torus (x : Parameters) :=
  SphereSixComplex.Geometry.OrbitQuotient (M := ComplexTwoSpace) (G := PeriodGroup x)

/-- Projection from `ℂ²` to its period-lattice quotient. -/
public def torusProjection (x : Parameters) : ComplexTwoSpace → Torus x :=
  SphereSixComplex.Geometry.quotientProjection

/-- A full-rank period quotient is compact.  The image of the standard closed unit cube in
real period coordinates is the whole quotient. -/
public theorem torus_compactSpace (x : Parameters) (h : FullRank x) :
    CompactSpace (Torus x) := by
  let C : Set RealPeriods := Set.Icc 0 1
  let f : RealPeriods → Torus x := fun r ↦ Quotient.mk _ (h.realEquiv r)
  have hC : IsCompact C := isCompact_Icc
  have hf : Continuous f := continuous_quot_mk.comp h.realEquiv.continuous
  have hsurj : f '' C = Set.univ := by
    apply Set.eq_univ_of_forall
    intro q
    induction q using Quotient.inductionOn with
    | _ z =>
      let r : RealPeriods := h.realEquiv.symm z
      let a : IntegerPeriods := fun i ↦ ⌊ r i ⌋
      let u : RealPeriods := r - integerToReal a
      have hu : u ∈ C := by
        constructor
        · intro i
          exact sub_nonneg.mpr (Int.floor_le (r i))
        · intro i
          change r i - integerToReal a i ≤ (1 : ℝ)
          rw [show integerToReal a i = (a i : ℝ) by rfl]
          exact le_of_lt (sub_lt_iff_lt_add.mpr <| by
            simpa [add_comm] using Int.lt_floor_add_one (r i))
      refine ⟨u, hu, ?_⟩
      apply Quotient.sound
      change (MulAction.orbitRel (PeriodGroup x) ComplexTwoSpace) (h.realEquiv u) z
      rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff]
      let g : PeriodGroup x := Multiplicative.ofAdd
        ⟨periodVector x (-a), ⟨-a, rfl⟩⟩
      refine ⟨g, ?_⟩
      change periodVector x (-a) + z = h.realEquiv u
      rw [show periodVector x (-a) = -periodVector x a by
        have ha := periodVector_add x (-a) a
        rw [neg_add_cancel, periodVector_zero] at ha
        exact eq_neg_of_add_eq_zero_left ha.symm]
      rw [← h.map_integer]
      change -h.realEquiv (integerToReal a) + z =
        h.realEquiv (r - integerToReal a)
      rw [map_sub, h.realEquiv.apply_symm_apply]
      abel
  rw [← isCompact_univ_iff, ← hsurj]
  exact hC.image hf

/-- Every period-lattice translation is complex smooth. -/
public theorem periodTranslation_contMDiff (x : Parameters) (g : PeriodGroup x)
    (n : WithTop ℕ∞) :
    ContMDiff (modelWithCornersSelf ℂ ComplexTwoSpace)
      (modelWithCornersSelf ℂ ComplexTwoSpace) n (fun z : ComplexTwoSpace ↦ g • z) := by
  rw [contMDiff_iff_contDiff]
  change ContDiff ℂ n (fun z : ComplexTwoSpace ↦ (g.toAdd : ComplexTwoSpace) + z)
  exact contDiff_const.add contDiff_id

/-- A full-rank period matrix defines a complex manifold quotient, and the quotient projection is
a local diffeomorphism. -/
public theorem torus_isManifold_and_projection_isLocalDiffeomorph
    (x : Parameters) (h : FullRank x) (n : WithTop ℕ∞) :
    letI := periodLattice_properlyDiscontinuousSMul h
    IsManifold (modelWithCornersSelf ℂ ComplexTwoSpace) n (Torus x) ∧
      IsLocalDiffeomorph (modelWithCornersSelf ℂ ComplexTwoSpace)
        (modelWithCornersSelf ℂ ComplexTwoSpace) n (torusProjection x) := by
  let _ : ProperlyDiscontinuousSMul (PeriodGroup x) ComplexTwoSpace :=
    periodLattice_properlyDiscontinuousSMul h
  exact orbitQuotient_isManifold_and_projection_isLocalDiffeomorph_of_contMDiff_smul
    (modelWithCornersSelf ℂ ComplexTwoSpace) n fun g ↦ periodTranslation_contMDiff x g n

/-- At order one, a full-rank period matrix defines a complex torus with locally holomorphic
quotient projection. -/
public theorem torus_isManifold_and_projection_mdifferentiable
    (x : Parameters) (h : FullRank x) :
    letI := periodLattice_properlyDiscontinuousSMul h
    IsManifold (modelWithCornersSelf ℂ ComplexTwoSpace) 1 (Torus x) ∧
      MDifferentiable (modelWithCornersSelf ℂ ComplexTwoSpace)
        (modelWithCornersSelf ℂ ComplexTwoSpace) (torusProjection x) := by
  let _ : ProperlyDiscontinuousSMul (PeriodGroup x) ComplexTwoSpace :=
    periodLattice_properlyDiscontinuousSMul h
  exact orbitQuotient_isManifold_and_projection_mdifferentiable_of_contMDiff_smul
    (modelWithCornersSelf ℂ ComplexTwoSpace) fun g ↦ periodTranslation_contMDiff x g 1

/-- The setup inequalities imply the complex-torus quotient conclusion. -/
public theorem torus_of_setupInequalities
    (x : Parameters) (h : SetupInequalities x) :
    let hfull := FullRank.ofSetupInequalities x h
    letI := periodLattice_properlyDiscontinuousSMul hfull
    IsManifold (modelWithCornersSelf ℂ ComplexTwoSpace) 1 (Torus x) ∧
      MDifferentiable (modelWithCornersSelf ℂ ComplexTwoSpace)
        (modelWithCornersSelf ℂ ComplexTwoSpace) (torusProjection x) := by
  exact torus_isManifold_and_projection_mdifferentiable x
    (FullRank.ofSetupInequalities x h)

end

end SphereSixComplex.Geometry.ComplexTorus
