module

public import SphereSixComplex.Geometry.GlobalDeckQuotient
public import SphereSixComplex.Geometry.CuspFilling
public import SphereSixComplex.TriangleGroup.FuchsianAction

/-!
# The cyclic quotient at the Fuchsian cusp

The parabolic generator `g₀` acts on the explicit source upper half-plane by translation through
`-(1 + sqrt 2)`.  This file isolates the resulting integer action, proves its freeness and proper
discontinuity on the invariant horodisc, and records the corresponding conclusions for the
product lift with trivial fibre transport.  No assertion about proper discontinuity of the full
triangle group is made here.
-/

open scoped Manifold

namespace SphereSixComplex.Geometry.CyclicCuspQuotient

open SphereSixComplex.TriangleGroup
open SphereSixComplex.Geometry.GlobalTorusFamily
open SphereSixComplex.Geometry.CuspFilling
open SphereSixComplex.Geometry.ComplexTorus

noncomputable section

/-- The positive translation width of the explicit Fuchsian cusp. -/
@[expose] public noncomputable def cuspWidth : ℝ := 1 + Real.sqrt 2

public theorem cuspWidth_pos : 0 < cuspWidth := by
  unfold cuspWidth
  positivity

/-- Translation by an integral multiple of the cusp width on the upper half-plane. -/
@[expose] public noncomputable def cuspTranslate (k : ℤ) (z : UpperHalfPlane) :
    UpperHalfPlane :=
  ⟨(z : ℂ) - (k : ℝ) * cuspWidth, by simpa using z.im_pos⟩

@[simp]
public theorem cuspTranslate_coe (k : ℤ) (z : UpperHalfPlane) :
    ((cuspTranslate k z : UpperHalfPlane) : ℂ) = z - (k : ℝ) * cuspWidth := rfl

@[simp]
public theorem cuspTranslate_re (k : ℤ) (z : UpperHalfPlane) :
    (cuspTranslate k z).re = z.re - (k : ℝ) * cuspWidth := by
  simp [cuspTranslate]

@[simp]
public theorem cuspTranslate_im (k : ℤ) (z : UpperHalfPlane) :
    (cuspTranslate k z).im = z.im := by
  simp [cuspTranslate]

public theorem cuspTranslate_zero (z : UpperHalfPlane) : cuspTranslate 0 z = z := by
  apply UpperHalfPlane.coe_injective
  simp

public theorem cuspTranslate_add (k l : ℤ) (z : UpperHalfPlane) :
    cuspTranslate (k + l) z = cuspTranslate k (cuspTranslate l z) := by
  apply UpperHalfPlane.coe_injective
  simp [cuspTranslate]
  ring

/-- The integer translation as a permutation of the upper half-plane. -/
@[expose] public noncomputable def cuspTranslateEquiv (k : ℤ) :
    Equiv.Perm UpperHalfPlane where
  toFun := cuspTranslate k
  invFun := cuspTranslate (-k)
  left_inv z := by rw [← cuspTranslate_add, neg_add_cancel, cuspTranslate_zero]
  right_inv z := by rw [← cuspTranslate_add, add_neg_cancel, cuspTranslate_zero]

@[simp]
public theorem cuspTranslateEquiv_apply (k : ℤ) (z : UpperHalfPlane) :
    cuspTranslateEquiv k z = cuspTranslate k z := rfl

/-- The abstract cyclic cusp subgroup, with multiplication corresponding to addition of exponents. -/
@[expose] public noncomputable def cuspCyclicRepresentation :
    Multiplicative ℤ →* Equiv.Perm UpperHalfPlane where
  toFun k := cuspTranslateEquiv (Multiplicative.toAdd k)
  map_one' := by
    apply Equiv.ext
    exact cuspTranslate_zero
  map_mul' k l := by
    apply Equiv.ext
    exact cuspTranslate_add _ _

@[instance_reducible] public noncomputable instance cuspCyclicAction :
    MulAction (Multiplicative ℤ) UpperHalfPlane where
  smul k z := cuspCyclicRepresentation k z
  one_smul z := by
    change cuspCyclicRepresentation 1 z = z
    exact DFunLike.congr_fun (map_one cuspCyclicRepresentation) z
  mul_smul k l z := by
    change cuspCyclicRepresentation (k * l) z =
      cuspCyclicRepresentation k (cuspCyclicRepresentation l z)
    exact DFunLike.congr_fun (map_mul cuspCyclicRepresentation k l) z

@[instance_reducible] public noncomputable instance cuspCyclicSMul :
    SMul (Multiplicative ℤ) UpperHalfPlane := cuspCyclicAction.toSMul

@[simp]
public theorem cuspCyclic_smul (k : Multiplicative ℤ) (z : UpperHalfPlane) :
    k • z = cuspTranslate (Multiplicative.toAdd k) z := rfl

/-- The positive generator of the cyclic action is exactly the Fuchsian action of `g₀`. -/
public theorem cuspCyclic_generator_eq_gZero (z : UpperHalfPlane) :
    cuspTranslate 1 z = fuchsianSourceAction g₀ • z := by
  apply UpperHalfPlane.coe_injective
  change ((cuspTranslate 1 z : UpperHalfPlane) : ℂ) =
    (((fuchsianSourceAction g₀) z : UpperHalfPlane) : ℂ)
  rw [fuchsianSourceAction_g₀_apply]
  simp [cuspWidth]

/-- Every integer translation is the corresponding element of the cyclic subgroup generated by
`g₀` in the explicit Fuchsian action. -/
public theorem cuspTranslate_eq_fuchsian_gZero_zpow (k : ℤ) (z : UpperHalfPlane) :
    cuspTranslate k z = fuchsianSourceAction (g₀ ^ k) • z := by
  have hk : Multiplicative.ofAdd k = (Multiplicative.ofAdd (1 : ℤ)) ^ k := by
    apply Multiplicative.toAdd.injective
    simp
  have hgen : cuspCyclicRepresentation (Multiplicative.ofAdd (1 : ℤ)) =
      fuchsianSourceAction g₀ := by
    apply Equiv.ext
    exact cuspCyclic_generator_eq_gZero
  have hrep : cuspCyclicRepresentation (Multiplicative.ofAdd k) =
      fuchsianSourceAction (g₀ ^ k) := by
    rw [hk, map_zpow, map_zpow, hgen]
  exact DFunLike.congr_fun hrep z

/-- The closed invariant horodisc used for the explicit cusp model. -/
public abbrev CuspHorodisc := {z : UpperHalfPlane // z ∈ fuchsianCuspRegion}

public theorem cuspTranslate_mem_horodisc (k : ℤ) (z : CuspHorodisc) :
    cuspTranslate k z.1 ∈ fuchsianCuspRegion := by
  change 1 ≤ (cuspTranslate k z.1).im
  rw [cuspTranslate_im]
  exact z.2

/-- Restriction of the cyclic translation to the invariant horodisc. -/
@[expose] public noncomputable def cuspHorodiscTranslateEquiv (k : ℤ) :
    Equiv.Perm CuspHorodisc where
  toFun z := ⟨cuspTranslate k z.1, cuspTranslate_mem_horodisc k z⟩
  invFun z := ⟨cuspTranslate (-k) z.1, cuspTranslate_mem_horodisc (-k) z⟩
  left_inv z := by
    apply Subtype.ext
    change cuspTranslate (-k) (cuspTranslate k z.1) = z.1
    rw [← cuspTranslate_add, neg_add_cancel, cuspTranslate_zero]
  right_inv z := by
    apply Subtype.ext
    change cuspTranslate k (cuspTranslate (-k) z.1) = z.1
    rw [← cuspTranslate_add, add_neg_cancel, cuspTranslate_zero]

@[expose] public noncomputable def cuspHorodiscRepresentation :
    Multiplicative ℤ →* Equiv.Perm CuspHorodisc where
  toFun k := cuspHorodiscTranslateEquiv (Multiplicative.toAdd k)
  map_one' := by
    apply Equiv.ext
    intro z
    apply Subtype.ext
    change cuspTranslate 0 z.1 = z.1
    exact cuspTranslate_zero z.1
  map_mul' k l := by
    apply Equiv.ext
    intro z
    apply Subtype.ext
    change cuspTranslate (Multiplicative.toAdd k + Multiplicative.toAdd l) z.1 =
      cuspTranslate (Multiplicative.toAdd k) (cuspTranslate (Multiplicative.toAdd l) z.1)
    exact cuspTranslate_add _ _ z.1

@[instance_reducible] public noncomputable instance cuspHorodiscAction :
    MulAction (Multiplicative ℤ) CuspHorodisc where
  smul k z := cuspHorodiscRepresentation k z
  one_smul z := by
    change cuspHorodiscRepresentation 1 z = z
    exact DFunLike.congr_fun (map_one cuspHorodiscRepresentation) z
  mul_smul k l z := by
    change cuspHorodiscRepresentation (k * l) z =
      cuspHorodiscRepresentation k (cuspHorodiscRepresentation l z)
    exact DFunLike.congr_fun (map_mul cuspHorodiscRepresentation k l) z

@[instance_reducible] public noncomputable instance cuspHorodiscSMul :
    SMul (Multiplicative ℤ) CuspHorodisc := cuspHorodiscAction.toSMul

@[simp]
public theorem cuspHorodisc_smul_val (k : Multiplicative ℤ) (z : CuspHorodisc) :
    (k • z).1 = cuspTranslate (Multiplicative.toAdd k) z.1 := rfl

/-- The cyclic cusp action is free. -/
public theorem cuspHorodisc_action_free :
    IsCancelSMul (Multiplicative ℤ) CuspHorodisc := by
  rw [isCancelSMul_iff_eq_one_of_smul_eq]
  intro k z hk
  have hre := congrArg (fun w : CuspHorodisc ↦ w.1.re) hk
  simp only [cuspHorodisc_smul_val, cuspTranslate_re] at hre
  have hcast : ((Multiplicative.toAdd k : ℤ) : ℝ) = 0 := by
    have hw := cuspWidth_pos
    nlinarith
  apply Multiplicative.toAdd.injective
  change Multiplicative.toAdd k = 0
  exact_mod_cast hcast

private def horodiscRealPart (z : CuspHorodisc) : ℝ := z.1.re

private theorem horodiscRealPart_continuous : Continuous horodiscRealPart := by
  exact Complex.continuous_re.comp
    (UpperHalfPlane.continuous_coe.comp continuous_subtype_val)

/-- Compact sets in the horodisc meet only finitely many integer translates. -/
public theorem cuspHorodisc_compact_overlap_finite
    (K L : Set CuspHorodisc) (hK : IsCompact K) (hL : IsCompact L) :
    Set.Finite {k : ℤ |
      ((fun z : CuspHorodisc ↦ cuspHorodiscTranslateEquiv k z) '' K ∩ L).Nonempty} := by
  have hKupper : BddAbove (horodiscRealPart '' K) :=
    hK.bddAbove_image horodiscRealPart_continuous.continuousOn
  have hKlower : BddBelow (horodiscRealPart '' K) :=
    hK.bddBelow_image horodiscRealPart_continuous.continuousOn
  have hLupper : BddAbove (horodiscRealPart '' L) :=
    hL.bddAbove_image horodiscRealPart_continuous.continuousOn
  have hLlower : BddBelow (horodiscRealPart '' L) :=
    hL.bddBelow_image horodiscRealPart_continuous.continuousOn
  rcases hKupper with ⟨bK, hbK⟩
  rcases hKlower with ⟨aK, haK⟩
  rcases hLupper with ⟨bL, hbL⟩
  rcases hLlower with ⟨aL, haL⟩
  apply (Set.finite_Icc (⌈(aK - bL) / cuspWidth⌉ : ℤ)
    (⌊(bK - aL) / cuspWidth⌋ : ℤ)).subset
  intro k hk
  rcases hk with ⟨q, ⟨p, hpK, hpq⟩, hqL⟩
  have hpUpper : horodiscRealPart p ≤ bK := hbK ⟨p, hpK, rfl⟩
  have hpLower : aK ≤ horodiscRealPart p := haK ⟨p, hpK, rfl⟩
  have hqUpper : horodiscRealPart q ≤ bL := hbL ⟨q, hqL, rfl⟩
  have hqLower : aL ≤ horodiscRealPart q := haL ⟨q, hqL, rfl⟩
  change p.1.re ≤ bK at hpUpper
  change aK ≤ p.1.re at hpLower
  change q.1.re ≤ bL at hqUpper
  change aL ≤ q.1.re at hqLower
  have hpqVal := congrArg (fun z : CuspHorodisc ↦ z.1) hpq
  change cuspTranslate k p.1 = q.1 at hpqVal
  have hpqRe := congrArg UpperHalfPlane.re hpqVal
  rw [cuspTranslate_re] at hpqRe
  have hw := cuspWidth_pos
  constructor
  · rw [Int.ceil_le]
    apply (div_le_iff₀ hw).2
    nlinarith
  · rw [Int.le_floor]
    apply (le_div_iff₀ hw).2
    nlinarith

/-- Proper discontinuity of the cyclic action on the explicit horodisc. -/
public theorem cuspHorodisc_action_properlyDiscontinuous :
    ProperlyDiscontinuousSMul (Multiplicative ℤ) CuspHorodisc := by
  refine ⟨?_⟩
  intro K L hK hL
  have hpre := (cuspHorodisc_compact_overlap_finite K L hK hL).preimage
    (Set.injOn_of_injective Multiplicative.toAdd.injective)
  change {gamma : Multiplicative ℤ |
    ((fun z : CuspHorodisc ↦ cuspHorodiscTranslateEquiv
      (Multiplicative.toAdd gamma) z) '' K ∩ L).Nonempty}.Finite
  exact hpre

/-- Continuity of every cyclic cusp translation on the horodisc. -/
public theorem cuspHorodisc_action_continuousConstSMul :
    ContinuousConstSMul (Multiplicative ℤ) CuspHorodisc := by
  refine ⟨?_⟩
  intro k
  change Continuous fun z : CuspHorodisc ↦
    (⟨cuspTranslate (Multiplicative.toAdd k) z.1,
      cuspTranslate_mem_horodisc (Multiplicative.toAdd k) z⟩ : CuspHorodisc)
  apply Continuous.subtype_mk
  unfold cuspTranslate
  apply Continuous.upperHalfPlaneMk
  exact (UpperHalfPlane.continuous_coe.comp continuous_subtype_val).sub
    (continuous_const.mul continuous_const)

private theorem fuchsianCuspRegion_isClosed : IsClosed fuchsianCuspRegion := by
  change IsClosed ((fun z : UpperHalfPlane ↦ z.im) ⁻¹' Set.Ici 1)
  exact isClosed_Ici.preimage
    (Complex.continuous_im.comp UpperHalfPlane.continuous_coe)

public noncomputable instance : LocallyCompactSpace CuspHorodisc :=
  fuchsianCuspRegion_isClosed.locallyCompactSpace

/-- The explicit cyclic horodisc quotient is a covering quotient. -/
public theorem cuspHorodisc_quotient_isQuotientCoveringMap :
    IsQuotientCoveringMap
      (Quotient.mk (MulAction.orbitRel (Multiplicative ℤ) CuspHorodisc))
      (Multiplicative ℤ) := by
  let _ : IsCancelSMul (Multiplicative ℤ) CuspHorodisc := cuspHorodisc_action_free
  let _ : ProperlyDiscontinuousSMul (Multiplicative ℤ) CuspHorodisc :=
    cuspHorodisc_action_properlyDiscontinuous
  let _ : ContinuousConstSMul (Multiplicative ℤ) CuspHorodisc :=
    cuspHorodisc_action_continuousConstSMul
  exact isQuotientCoveringMap_quotientMk_of_properlyDiscontinuousSMul

/-- The cusp model before quotienting by the fibre lattice.  The parabolic transport on the
complex vector-space fibre is the identity. -/
public abbrev CuspProduct := CuspHorodisc × ComplexTwoSpace

@[instance_reducible] public noncomputable instance cuspProductAction :
    MulAction (Multiplicative ℤ) CuspProduct where
  smul k p := (k • p.1, p.2)
  one_smul p := by
    apply Prod.ext
    · exact cuspHorodiscAction.one_smul p.1
    · rfl
  mul_smul k l p := by
    apply Prod.ext
    · exact cuspHorodiscAction.mul_smul k l p.1
    · rfl

@[instance_reducible] public noncomputable instance cuspProductSMul :
    SMul (Multiplicative ℤ) CuspProduct := cuspProductAction.toSMul

@[simp]
public theorem cuspProduct_smul_fst (k : Multiplicative ℤ) (p : CuspProduct) :
    (k • p).1 = k • p.1 := rfl

@[simp]
public theorem cuspProduct_smul_snd (k : Multiplicative ℤ) (p : CuspProduct) :
    (k • p).2 = p.2 := rfl

/-- Freeness of the lifted cyclic action follows from freeness on the cusp base. -/
public theorem cuspProduct_action_free :
    IsCancelSMul (Multiplicative ℤ) CuspProduct := by
  rw [isCancelSMul_iff_eq_one_of_smul_eq]
  intro k p hp
  apply (isCancelSMul_iff_eq_one_of_smul_eq.mp cuspHorodisc_action_free) k p.1
  exact congrArg Prod.fst hp

/-- Proper discontinuity of the product lift follows by projecting compact sets to the base. -/
public theorem cuspProduct_action_properlyDiscontinuous :
    ProperlyDiscontinuousSMul (Multiplicative ℤ) CuspProduct := by
  refine ⟨?_⟩
  intro K L hK hL
  have hKbase : IsCompact (Prod.fst '' K) := hK.image continuous_fst
  have hLbase : IsCompact (Prod.fst '' L) := hL.image continuous_fst
  apply (cuspHorodisc_action_properlyDiscontinuous.finite_disjoint_inter_image
    hKbase hLbase).subset
  intro k hk
  rcases hk with ⟨q, ⟨p, hpK, hpq⟩, hqL⟩
  refine ⟨q.1, ⟨p.1, ⟨p, hpK, rfl⟩, ?_⟩, ⟨q, hqL, rfl⟩⟩
  exact congrArg Prod.fst hpq

/-- Every lifted cyclic cusp transformation is continuous. -/
public theorem cuspProduct_action_continuousConstSMul :
    ContinuousConstSMul (Multiplicative ℤ) CuspProduct := by
  let _ : ContinuousConstSMul (Multiplicative ℤ) CuspHorodisc :=
    cuspHorodisc_action_continuousConstSMul
  refine ⟨?_⟩
  intro k
  exact ((continuous_const_smul k).comp continuous_fst).prodMk continuous_snd

/-- The cyclic product quotient is a covering quotient, by the same generic quotient API used by
the phase-corrected cusp-filling construction. -/
public theorem cuspProduct_quotient_isQuotientCoveringMap :
    IsQuotientCoveringMap
      (Quotient.mk (MulAction.orbitRel (Multiplicative ℤ) CuspProduct))
      (Multiplicative ℤ) := by
  let _ : IsCancelSMul (Multiplicative ℤ) CuspProduct := cuspProduct_action_free
  let _ : ProperlyDiscontinuousSMul (Multiplicative ℤ) CuspProduct :=
    cuspProduct_action_properlyDiscontinuous
  let _ : ContinuousConstSMul (Multiplicative ℤ) CuspProduct :=
    cuspProduct_action_continuousConstSMul
  exact isQuotientCoveringMap_quotientMk_of_properlyDiscontinuousSMul

/-- Inclusion of the explicit cusp product into the ambient global deck space. -/
@[expose] public def cuspProductInclusion :
    CuspProduct → UpperHalfPlane × ComplexTwoSpace := fun p ↦ (p.1.1, p.2)

open SphereSixComplex.Periods
open SphereSixComplex.Geometry.AnalyticTorusFamily
open SphereSixComplex.Geometry.TorusFamily

/-- If a triangle uniformization uses the explicit Fuchsian parabolic on the cusp, its lifted
`g₀` deck map agrees with the positive generator of the cyclic product action.  The fibre equality
is unconditional: canonical cusp transport is the identity. -/
public theorem cuspProduct_generator_agrees_with_deckMap
    {U : TriangleUniformization} (F : PeriodFunctions U)
    (hsource : ∀ z : CuspHorodisc,
      U.sourceAction g₀ • z.1 = fuchsianSourceAction g₀ • z.1)
    (p : CuspProduct) :
    cuspProductInclusion (Multiplicative.ofAdd (1 : ℤ) • p) =
      deckMap F g₀ (cuspProductInclusion p) := by
  apply Prod.ext
  · change cuspTranslate 1 p.1.1 = U.sourceAction g₀ • p.1.1
    rw [cuspCyclic_generator_eq_gZero]
    exact (hsource p.1).symm
  · change p.2 = periodTransport g₀ (parameterMap F p.1.1) p.2
    rw [periodTransport_gZero]
    rfl

/-- The preceding generator comparison descends through the varying-torus projection.  This is
the direct interface with the global torus family; constructing a uniformization satisfying
`hsource` remains separate from the cyclic cusp geometry proved here. -/
public theorem cuspProduct_generator_agrees_with_familyDeckMap
    {U : TriangleUniformization} (F : PeriodFunctions U)
    (hsource : ∀ z : CuspHorodisc,
      U.sourceAction g₀ • z.1 = fuchsianSourceAction g₀ • z.1)
    (p : CuspProduct) :
    (⟦cuspProductInclusion (Multiplicative.ofAdd (1 : ℤ) • p)⟧ :
      TotalSpace (parameterMap F)) =
      familyDeckMap F g₀ (⟦cuspProductInclusion p⟧ : TotalSpace (parameterMap F)) := by
  calc
    (⟦cuspProductInclusion (Multiplicative.ofAdd (1 : ℤ) • p)⟧ :
        TotalSpace (parameterMap F)) =
      ⟦deckMap F g₀ (cuspProductInclusion p)⟧ :=
        congrArg (fun x : UpperHalfPlane × ComplexTwoSpace ↦
          (⟦x⟧ : TotalSpace (parameterMap F)))
          (cuspProduct_generator_agrees_with_deckMap F hsource p)
    _ = familyDeckMap F g₀
        (⟦cuspProductInclusion p⟧ : TotalSpace (parameterMap F)) := by
      exact (familyDeckMap_mk F g₀ (cuspProductInclusion p)).symm

end

end SphereSixComplex.Geometry.CyclicCuspQuotient
