module

public import SphereSixComplex.ComplexStructure
public import SphereSixComplex.Construction
public import SphereSixComplex.Geometry.AtlasTransport
public import SphereSixComplex.Geometry.AnalyticTorusFamily
public import SphereSixComplex.Geometry.ComplexTorus
public import SphereSixComplex.Geometry.ComplexThreefoldGluing
public import SphereSixComplex.Geometry.CuspCombinatorics
public import SphereSixComplex.Geometry.CuspFilling
public import SphereSixComplex.Geometry.CyclicCuspQuotient
public import SphereSixComplex.Geometry.EllipticComplexFilling
public import SphereSixComplex.Geometry.EllipticFilling
public import SphereSixComplex.Geometry.EllipticCayleyHomeomorph
public import SphereSixComplex.Geometry.EllipticFamilySpecialization
public import SphereSixComplex.Geometry.EllipticFixedPointCriterion
public import SphereSixComplex.Geometry.EllipticLocalCoordinates
public import SphereSixComplex.Geometry.FamilyEquivariance
public import SphereSixComplex.Geometry.FuchsianRegularTorusFamily
public import SphereSixComplex.Geometry.Gluing
public import SphereSixComplex.Geometry.GlobalTorusFamily
public import SphereSixComplex.Geometry.GlobalDeckSmoothness
public import SphereSixComplex.Geometry.GlobalDeckQuotient
public import SphereSixComplex.Geometry.PaperAssembly
public import SphereSixComplex.Final
public import SphereSixComplex.Geometry.Quotient
public import SphereSixComplex.Geometry.RegularBaseTopology
public import SphereSixComplex.Geometry.RegularTorusFamily
public import SphereSixComplex.Geometry.TorusFamily
public import SphereSixComplex.LatticeData
public import SphereSixComplex.Periods.Domain
public import SphereSixComplex.Periods.CanonicalObstruction
public import SphereSixComplex.Periods.Functions
public import SphereSixComplex.Periods.FuchsianCompactCore
public import SphereSixComplex.Periods.FuchsianUniformizationBridge
public import SphereSixComplex.Periods.Invariant
public import SphereSixComplex.Periods.LocalOrbifoldCompatibility
public import SphereSixComplex.Periods.Matrix
public import SphereSixComplex.Periods.Nondegeneracy
public import SphereSixComplex.Periods.Transformations
public import SphereSixComplex.Periods.TorsorAlgebra
public import SphereSixComplex.Periods.ProjectiveLineTorsors
public import SphereSixComplex.Periods.SchurCompactness
public import SphereSixComplex.Topology.FundamentalGroup
public import SphereSixComplex.Topology.FundamentalGroupComputation
public import SphereSixComplex.Topology.HomologyComputation
public import SphereSixComplex.Topology.HomologySphere
public import SphereSixComplex.Topology.HurewiczWhitehead
public import SphereSixComplex.Topology.MayerVietoris
public import SphereSixComplex.Topology.SectionSevenChainModel
public import SphereSixComplex.Topology.SectionSevenLerayChainModel
public import SphereSixComplex.Topology.SectionSevenLerayDuality
public import SphereSixComplex.Topology.SectionSevenLerayChainDuality
public import SphereSixComplex.Topology.SectionSevenLerayHomologyDuality
public import SphereSixComplex.Topology.SectionSevenLerayRealization
public import SphereSixComplex.Topology.EstablishedRecognition
public import SphereSixComplex.Topology.SmoothRecognition
public import SphereSixComplex.Topology.SmoothRecognitionFoundations
public import SphereSixComplex.Topology.SphereSimplyConnected
public import SphereSixComplex.Topology.StandardSphere
public import SphereSixComplex.Topology.StandardSphereHomologyZero
public import SphereSixComplex.Topology.DiskBoundaryQuotient
public import SphereSixComplex.Topology.RelativeSingularHomology
public import SphereSixComplex.Topology.SingularExcision
public import SphereSixComplex.Topology.SingularBarycentricChains
public import SphereSixComplex.Topology.SingularSubdivision
public import SphereSixComplex.Topology.TwistObstruction
public import SphereSixComplex.TriangleGroup.ModularParameter
public import SphereSixComplex.TriangleGroup.FuchsianAction
public import SphereSixComplex.TriangleGroup.FuchsianArithmetic
public import SphereSixComplex.TriangleGroup.FuchsianArithmeticTermination
public import SphereSixComplex.TriangleGroup.FuchsianFundamentalDomain
public import SphereSixComplex.TriangleGroup.FuchsianPingPong
public import SphereSixComplex.TriangleGroup.FuchsianTessellation
public import SphereSixComplex.TriangleGroup.FuchsianTriangleCover
public import SphereSixComplex.TriangleGroup.FuchsianSmoothAction
public import SphereSixComplex.TriangleGroup.FreeProductTorsion
public import SphereSixComplex.TriangleGroup.BinaryIndexedCoprod
public import SphereSixComplex.TriangleGroup.FuchsianProperFreeness
public import SphereSixComplex.TriangleGroup.Representation

/-!
# A Complex Structure on the Six-Sphere

This module will expose the main theorem formalizing the construction in `references/s6.pdf`.
-/

namespace SphereSixComplex

end SphereSixComplex
