import SphereSixComplex.Geometry.PaperAnalyticData

open SphereSixComplex.Periods

#print axioms establishedOrbifoldAffineLineTorsorTwoChartDescent
#print axioms exists_muAffineCechSections
#print axioms exists_betaAffineCechSections
#print axioms establishedFuchsianAffineTorsorLocalTriviality
#print axioms exists_fuchsianPeriodLocalData
#print axioms exists_establishedFuchsianPeriodFunctions
#print axioms SphereSixComplex.Geometry.exists_paperAnalyticData
