module

public import SphereSixComplex.Paper.LatticeData
public import SphereSixComplex.Paper.Topology.PaperVanKampenAlgebraAdapter
public import SphereSixComplex.Prerequisites.Topology.EstablishedAffineVanKampen
public import Mathlib.GroupTheory.FreeGroup.CyclicallyReduced
public import SphereSixComplex.Prerequisites.Topology.ExactLocalFactorizationCircleHomotopy
public import SphereSixComplex.Paper.Topology.PaperActualEllipticFillingDeckTransport
public import SphereSixComplex.Paper.Topology.PaperCuspBoundaryUniversalCover
public import SphereSixComplex.Paper.Topology.PaperActualEllipticCanonicalFiniteMarking
public import Mathlib.Algebra.Group.Opposite
public import Mathlib.Algebra.Group.Equiv.Basic
public import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
public import Mathlib.Topology.Homotopy.Lifting
public import SphereSixComplex.Paper.Topology.PaperActualEllipticRelatorNormalClosureTypes
public import SphereSixComplex.Paper.Topology.PaperSectionSevenSmallMarkedDiscWitness
public import SphereSixComplex.Paper.Topology.PaperSectionSevenAffineRegularLiftCompletionAssembly
public import SphereSixComplex.Paper.Topology.PaperSectionSevenAffineOverlapInterleaving
public import SphereSixComplex.Paper.Periods.FuchsianModularLift.Ramification
public import SphereSixComplex.Prerequisites.Topology.FreeLoopProductHomotopy
public import Mathlib.Topology.Subpath
public import Mathlib.Topology.Homotopy.Path
public import Mathlib.Topology.ContinuousMap.Interval
public import Mathlib.Topology.ContinuousMap.Ordered
public import SphereSixComplex.Paper.TriangleGroup.Representation
public import SphereSixComplex.Paper.Geometry.GlobalTorusFiberFundamentalGroup
public import SphereSixComplex.Prerequisites.Topology.FreeLoopHomology
public import SphereSixComplex.Paper.Topology.ActualEllipticFourthInteriorTranslation
public import SphereSixComplex.Prerequisites.Topology.NormalizedCircleProductCross

@[expose] public section
noncomputable section
open AlgebraicTopology
namespace SphereSixComplex.Geometry.AnalyticData
open SphereSixComplex.Topology CircleProductIdentityMappingTorus Hurewicz.Chains

public def ellipticFourthHomologySweep (A : AnalyticData) :
    IntegralSingularHomology 1 A.ellipticInterior →+
      IntegralSingularHomology 2 A.ellipticInterior :=
  (integralSingularHomologyMap 2 A.ellipticFourthTranslation).comp (normalizedCircleCross 1)

end SphereSixComplex.Geometry.AnalyticData
