module

public import SphereSixComplex.Paper.Topology.LatticeWangAlgebra
public import SphereSixComplex.Paper.Topology.PaperEllipticTorusHomologyBasis

/-!
# Integral cusp-monodromy algebra in exterior degrees two and three

This module proves the lattice calculations used in Proposition 7.12.  It constructs the
coinvariant quotients of the actual cusp monodromy in exterior degrees two and three, but makes no
identification with the homology of the central fibre `W`.
-/

@[expose] public section

noncomputable section

open Matrix

namespace SphereSixComplex.CuspMonodromyCoinvariants

open LatticeData
open SphereSixComplex.LatticeWangAlgebra

public abbrev ExteriorTwoLattice := Fin 6 → ℤ

/-- The second exterior-power action of the cusp monodromy. -/
public def mZeroExteriorTwoMatrix : Matrix (Fin 6) (Fin 6) ℤ :=
  secondCompoundMatrix M₀

public theorem mZeroExteriorTwoMatrix_eq :
    mZeroExteriorTwoMatrix =
      !![1, 0, 0, 0, 0, 0;
         1, 1, 0, 0, 0, 0;
         0, 0, 1, 0, 0, 0;
         0, 0, 0, 1, 0, 0;
         1, 0, 0, 0, 1, 0;
         1, 1, 0, 0, 1, 1] := by
  rw [mZeroExteriorTwoMatrix, SphereSixComplex.Periods.M₀_eq_explicit]
  decide

/-- The algebraic differential `exteriorSquare(M₀) - I`. -/
public def mZeroExteriorTwoDifference : ExteriorTwoLattice →ₗ[ℤ] ExteriorTwoLattice :=
  mZeroExteriorTwoMatrix.mulVecLin - LinearMap.id

public theorem mZeroExteriorTwoDifference_apply (x : ExteriorTwoLattice) :
    mZeroExteriorTwoDifference x =
      ![0, x 0, 0, 0, x 0, x 0 + x 1 + x 4] := by
  funext i
  fin_cases i <;>
    simp [mZeroExteriorTwoDifference, mZeroExteriorTwoMatrix_eq, dotProduct,
      Fin.sum_univ_succ] ; ring

/-- The image in exterior degree two is generated by `w delta` and `gamma w + u delta`. -/
public def mZeroExteriorTwoRelationSubmodule : Submodule ℤ ExteriorTwoLattice where
  carrier := {x | x 0 = 0 ∧ x 2 = 0 ∧ x 3 = 0 ∧ x 1 = x 4}
  zero_mem' := by simp
  add_mem' := by
    rintro x y ⟨hx0, hx2, hx3, hx14⟩ ⟨hy0, hy2, hy3, hy14⟩
    simp [hx0, hx2, hx3, hx14, hy0, hy2, hy3, hy14]
  smul_mem' := by
    rintro n x ⟨hx0, hx2, hx3, hx14⟩
    simp [hx0, hx2, hx3, hx14]

public theorem range_mZeroExteriorTwoDifference :
    LinearMap.range mZeroExteriorTwoDifference = mZeroExteriorTwoRelationSubmodule := by
  ext x
  constructor
  · rintro ⟨y, rfl⟩
    simp [mZeroExteriorTwoDifference_apply, mZeroExteriorTwoRelationSubmodule]
  · rintro ⟨h0, h2, h3, h14⟩
    refine ⟨![x 1, x 5 - x 1, 0, 0, 0, 0], ?_⟩
    rw [mZeroExteriorTwoDifference_apply]
    funext i
    fin_cases i <;> simp [h0, h2, h3, h14]


/-- Coordinates `(gamma u, gamma delta, u w, gamma w - u delta)` on the degree-two
coinvariants. -/
public def mZeroExteriorTwoProjection : ExteriorTwoLattice →ₗ[ℤ] (Fin 4 → ℤ) where
  toFun x := ![x 0, x 2, x 3, x 1 - x 4]
  map_add' x y := by
    funext i
    fin_cases i <;> simp
    ring
  map_smul' n x := by
    funext i
    fin_cases i <;> simp
    ring

public theorem ker_mZeroExteriorTwoProjection :
    LinearMap.ker mZeroExteriorTwoProjection = mZeroExteriorTwoRelationSubmodule := by
  ext x
  constructor
  · intro hx
    have h := LinearMap.mem_ker.mp hx
    have h0 := congrFun h (0 : Fin 4)
    have h1 := congrFun h (1 : Fin 4)
    have h2 := congrFun h (2 : Fin 4)
    have h3 := congrFun h (3 : Fin 4)
    simp [mZeroExteriorTwoProjection] at h0 h1 h2 h3
    exact ⟨h0, h1, h2, by omega⟩
  · rintro ⟨h0, h2, h3, h14⟩
    apply LinearMap.mem_ker.mpr
    funext i
    fin_cases i <;> simp [mZeroExteriorTwoProjection, h0, h2, h3, h14]

public theorem mZeroExteriorTwoProjection_surjective :
    Function.Surjective mZeroExteriorTwoProjection := by
  intro y
  refine ⟨![y 0, y 3, y 1, y 2, 0, 0], ?_⟩
  funext i
  fin_cases i <;> simp [mZeroExteriorTwoProjection]

public abbrev MZeroExteriorTwoCoinvariants :=
  ExteriorTwoLattice ⧸ LinearMap.range mZeroExteriorTwoDifference




/-- The second exterior-power coinvariants are free of rank four. -/
public noncomputable def mZeroExteriorTwoCoinvariantsEquivIntFourth :
    MZeroExteriorTwoCoinvariants ≃ₗ[ℤ] (Fin 4 → ℤ) :=
  (Submodule.quotEquivOfEq _ _
      (range_mZeroExteriorTwoDifference.trans ker_mZeroExteriorTwoProjection.symm)).trans
    (mZeroExteriorTwoProjection.quotKerEquivOfSurjective
      mZeroExteriorTwoProjection_surjective)

@[simp]
public theorem mZeroExteriorTwoCoinvariantsEquivIntFourth_mk (x : ExteriorTwoLattice) :
    mZeroExteriorTwoCoinvariantsEquivIntFourth (Submodule.Quotient.mk x) =
      mZeroExteriorTwoProjection x := by
  rfl













end SphereSixComplex.CuspMonodromyCoinvariants
