module

public import SphereSixComplex.Paper.Topology.EstablishedMayerVietoris
public import SphereSixComplex.Paper.Topology.EstablishedSphereHomology
public import SphereSixComplex.Prerequisites.Topology.OpenCoverSmallification
public import SphereSixComplex.Prerequisites.Topology.SingularStandardSimplexCone

/-!
# Reduction of the Section 7 realization obligation

Section 7 of the paper computes the integral (co)homology of the glued space by two independent
routes: successive Mayer--Vietoris sequences and the integral Leray spectral sequence.  It does
not construct a direct chain equivalence between the finite Leray model and the full singular
chain complex.

This file isolates the chain-level content which is specific to the construction.  It is enough
to map the finite model to the subcomplex of singular chains small with respect to the four-piece
cover and prove that map is a quasi-isomorphism.  Passage from small chains to all singular chains
is supplied by the general open-cover subdivision theorem and its resulting chain-homotopy
equivalence, independently of the paper's construction.
-/

@[expose] public section

noncomputable section

open AlgebraicTopology CategoryTheory CategoryTheory.Limits Set

namespace SphereSixComplex

/-- The unresolved top boundary may be normalized to `-1`; the explicit pairings then satisfy
the required adjointness identity with positive orientation sign. -/
public def sectionSevenLerayAlgebraicDualityNegOne :
    SectionSevenLerayAlgebraicDuality (-1) where
  sign := 1
  sign_eq_one_or_neg_one := Or.inl rfl
  boundary_adjoint x y := by
    simp [sectionSevenOneFivePairing, sectionSevenTwoFourPairing,
      sectionSevenOneFivePairingMatrix, sectionSevenTwoFourPairingMatrix,
      sectionSevenLerayBoundaryTwo, sectionSevenLerayBoundaryFive,
      chosenLerayDifferential, twistObstruction, Matrix.mulVec, dotProduct,
      Fin.sum_univ_succ]

/-- The paper-specific chain comparison after separating off general open-cover excision.  The
target is the subcomplex generated by simplices contained in one of the four specified pieces.
No comparison with the standard sphere and no product trivialization of the pieces is assumed. -/
public structure SectionSevenFourPieceSmallChainComparison
    (X : Type) [TopologicalSpace X] (C : FourPieceOpenCover X) where
  /-- The chain map encoding the collapse/specialization or Leray calculation of Section 7. -/
  comparison : sectionSevenLerayChainModel (-1) ⟶
    coverSmallIntegralSingularChainComplex (TopCat.of X) C.piece
  /-- The paper-specific finite calculation proves this map is a quasi-isomorphism. -/
  quasiIso : QuasiIso comparison

namespace SectionSevenFourPieceSmallChainComparison

variable {X : Type} [TopologicalSpace X] {C : FourPieceOpenCover X}

/-- A chain homotopy equivalence gives a quasi-isomorphism to the small-chain complex. -/
public noncomputable def ofHomotopyEquiv
    (h : HomotopyEquiv (sectionSevenLerayChainModel (-1))
      (coverSmallIntegralSingularChainComplex (TopCat.of X) C.piece)) :
    SectionSevenFourPieceSmallChainComparison X C where
  comparison := h.hom
  quasiIso := by
    rw [quasiIso_iff]
    intro k
    rw [quasiIsoAt_iff_isIso_homologyMap]
    change IsIso ((h.toHomologyIso k).hom)
    infer_instance

/-- Compose the paper-specific small-chain comparison with an explicit general smallification
homotopy equivalence to obtain the former coherent-realization contract. -/
public noncomputable def toCoherentRealizationOfRetraction
    (h : SectionSevenFourPieceSmallChainComparison X C)
    (d : CoverSmallChainRetractionData (TopCat.of X) C.piece) :
    SectionSevenLerayCoherentRealization X where
  top := -1
  duality := sectionSevenLerayAlgebraicDualityNegOne
  comparison := h.comparison ≫
    coverSmallIntegralSingularChainInclusion (TopCat.of X) C.piece
  homologyMap_isIso k := by
    let _ : QuasiIso h.comparison := h.quasiIso
    rw [HomologicalComplex.homologyMap_comp]
    refine IsIso.comp_isIso' inferInstance ?_
    change IsIso ((d.toHomotopyEquiv.toHomologyIso k).hom)
    infer_instance

/-- General open-cover smallification discharges the non-paper-specific part of coherent
realization. -/
public noncomputable def toCoherentRealization
    (h : SectionSevenFourPieceSmallChainComparison X C) :
    SectionSevenLerayCoherentRealization X :=
  h.toCoherentRealizationOfRetraction
    (coverSmallChainRetractionData C.piece C.isOpen_piece C.covers)

/-- The reduced comparison yields the degreewise Section 7 homology calculation. -/
public theorem sectionSevenHomologyRealization
    (h : SectionSevenFourPieceSmallChainComparison X C) :
    SectionSevenHomologyRealization X :=
  h.toCoherentRealization.sectionSevenHomologyRealization

/-- The reduced comparison, together with the established homology of the standard sphere, gives
the required integral homology-sphere statement. -/
public theorem hasIntegralHomologyOfSixSphere
    (h : SectionSevenFourPieceSmallChainComparison X C) :
    HasIntegralHomologyOfSixSphere X :=
  h.toCoherentRealization.hasIntegralHomologyOfSixSphere_established

/-- All generic topological consequences of the four-piece cover and the reduced chain
comparison: Mayer--Vietoris exactness is supplied by the established binary theorem, while the
paper-specific comparison supplies the homology calculation. -/
public theorem genericConsequences
    (h : SectionSevenFourPieceSmallChainComparison X C) :
    FourPieceMayerVietorisExactness C ∧ HasIntegralHomologyOfSixSphere X :=
  ⟨establishedFourPieceMayerVietorisExactness C, h.hasIntegralHomologyOfSixSphere⟩

end SectionSevenFourPieceSmallChainComparison

end SphereSixComplex
