module

public import SphereSixComplex.Prerequisites.Topology.CWComplex.Homology
public import Mathlib.Algebra.Category.Grp.Zero

/-!
# Cellular chains of a CW complex

The cellular chain complex, its basis of cells, and its comparison with singular chains.  This is
general CW topology with no dependence on the paper's construction, so it sits upstream of both the
`A₂` cellular bridge and the Section 7 finite-CW models.
-/

@[expose] public section

noncomputable section

open CategoryTheory CategoryTheory.Limits

namespace SphereSixComplex


variable (Y : Type) [TopologicalSpace Y] [Topology.CWComplex (Set.univ : Set Y)]

/-- The cellular chain group of a degree carrying no cells is a zero object. -/
public theorem isZero_cellularChain_of_isEmpty_cell
    (M : IntegralCWCellularHomologyModel Y) (n : ℕ)
    [IsEmpty (Topology.CWComplex.cell (Set.univ : Set Y) n)] :
    IsZero (M.chainComplex.X n) := by
  have : Subsingleton (M.chainComplex.X n) := (M.cellBasis n).symm.injective.subsingleton
  exact AddCommGrpCat.isZero_of_subsingleton _

/-- A finite-dimensional Hausdorff CW complex has no `n`-th integral singular homology once it has no `n`-cells. -/
public theorem subsingleton_integralSingularHomology_of_isEmpty_cell (n : ℕ) [T2Space Y]
    [Topology.CWComplex.FiniteDimensional (Set.univ : Set Y)]
    [IsEmpty (Topology.CWComplex.cell (Set.univ : Set Y) n)] :
    Subsingleton (IntegralSingularHomology n Y) := by
  obtain M := integralCWCellularHomologyModel Y
  have hcell : IsZero (M.chainComplex.homology n) :=
    (HomologicalComplex.ExactAt.of_isZero
      (isZero_cellularChain_of_isEmpty_cell Y M n)).isZero_homology
  have : IsZero (AddCommGrpCat.of (IntegralSingularHomology n Y)) :=
    hcell.of_iso (M.homologyEquiv n).toAddCommGrpIso.symm
  exact AddCommGrpCat.subsingleton_of_isZero this

/-- An isolated positive cellular degree has homology freely generated by its cells. -/
public def IntegralCWCellularHomologyModel.homologyEquivCells
    (M : IntegralCWCellularHomologyModel Y) (n : ℕ)
    [IsEmpty (Topology.CWComplex.cell (Set.univ : Set Y) n)]
    [IsEmpty (Topology.CWComplex.cell (Set.univ : Set Y) (n + 2))] :
    IntegralSingularHomology (n + 1) Y ≃+
      (Topology.CWComplex.cell (Set.univ : Set Y) (n + 1) →₀ ℤ) := by
  let K := M.chainComplex
  have hf : K.d (n + 2) (n + 1) = 0 :=
    (isZero_cellularChain_of_isEmpty_cell Y M (n + 2)).eq_zero_of_src _
  have hg : K.d (n + 1) n = 0 :=
    (isZero_cellularChain_of_isEmpty_cell Y M n).eq_zero_of_tgt _
  let e : K.homology (n + 1) ≅ K.X (n + 1) :=
    (K.homologyIsoSc' (n + 2) (n + 1) n
      ((ComplexShape.down ℕ).prev_eq' (ComplexShape.down_mk (n + 2) (n + 1) (by omega)))
      ((ComplexShape.down ℕ).next_eq' (ComplexShape.down_mk (n + 1) n (by omega)))).trans
        (ShortComplex.HomologyData.ofZeros (K.sc' (n + 2) (n + 1) n) hf hg).left.homologyIso
  exact (M.homologyEquiv (n + 1)).symm.trans
    (e.addCommGroupIsoToAddEquiv.trans (M.cellBasis (n + 1)).symm)


end SphereSixComplex

end

end
