module

public import SphereSixComplex.Prerequisites.Topology.Sphere.HomologySphere
public import Mathlib.Algebra.Category.ModuleCat.Colimits
public import Mathlib.Algebra.Category.Grp.ZModuleEquivalence
import Mathlib.Algebra.Category.Grp.AB
public import TauCeti.AlgebraicTopology.Cellular.Comparison
public import TauCeti.AlgebraicTopology.Singular.Empty

/-!
# Integral cellular homology

Finite-dimensional CW complexes have cellular chains freely generated by their cells, and
cellular homology agrees with singular homology. The comparison is supplied by Tau Ceti's
skeletal-relative construction.
-/

@[expose] public section

noncomputable section

open CategoryTheory CategoryTheory.Limits

/-- A coproduct of copies of an abelian group is its group of finitely supported functions. -/
public def AddCommGrpCat.finsuppIsoCoproduct (A : AddCommGrpCat.{u}) (ι : Type u) :
    AddCommGrpCat.of (ι →₀ A) ≅ ∐ fun _ : ι ↦ A := by
  let F := forget₂ (ModuleCat ℤ) AddCommGrpCat
  let h := isColimitOfPreserves F (ModuleCat.finsuppCoconeIsColimit ℤ A ι)
  exact h.coconePointUniqueUpToIso (colimit.isColimit _)

namespace SphereSixComplex

/-- The boundary sphere of the coordinate disk used by CW characteristic maps. -/
public abbrev CWCharacteristicBoundarySphere (n : ℕ) :=
  ↥(Metric.sphere (0 : Fin n → ℝ) 1)

/-- A cellular chain complex with its cell basis and singular homology comparison. -/
public structure IntegralCWCellularHomologyModel
    (Y : Type) [TopologicalSpace Y] [Topology.CWComplex (Set.univ : Set Y)] where
  chainComplex : ChainComplex AddCommGrpCat ℕ
  cellBasis : ∀ n,
    (Topology.CWComplex.cell (Set.univ : Set Y) n →₀ ℤ) ≃+ chainComplex.X n
  homologyEquiv : ∀ n,
    chainComplex.homology n ≃+ IntegralSingularHomology n Y

/-- Cellular chains compute integral singular homology of a finite-dimensional CW complex. -/
public def integralCWCellularHomologyModel (Y : Type) [TopologicalSpace Y] [T2Space Y]
    [Topology.CWComplex (Set.univ : Set Y)]
    [Topology.CWComplex.FiniteDimensional (Set.univ : Set Y)] :
    IntegralCWCellularHomologyModel Y where
  chainComplex := TauCeti.cellularChainComplex (Set.univ : Set Y) (AddCommGrpCat.of ℤ)
  cellBasis n := by
    rw [TauCeti.cellularChainComplex_X]
    exact (AddCommGrpCat.finsuppIsoCoproduct (AddCommGrpCat.of ℤ)
      (Topology.CWComplex.cell (Set.univ : Set Y) n) ≪≫
      (TauCeti.cellularChainGroupIso (Set.univ : Set Y) (AddCommGrpCat.of ℤ) n).symm).addCommGroupIsoToAddEquiv
  homologyEquiv n :=
    (TauCeti.cellularSingularHomologyIso (Set.univ : Set Y) (AddCommGrpCat.of ℤ) n ≪≫
      (asIso ((TauCeti.complexBasePair (Set.univ : Set Y)).singularHomologyπ
        (AddCommGrpCat.of ℤ) n)).symm).addCommGroupIsoToAddEquiv |>.trans
      (integralSingularHomologyEquiv n (Homeomorph.Set.univ Y))

end SphereSixComplex
